### ISSUE TITLE
TypeError: create() takes at least 5 arguments (5 given)

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#1002]
hi all,
I have created a sample frequency type rule and tried running the below command
" elastalert-test-rule myrules/myrule.yaml " . When executed the command gave the below error

  ```
INFO:elastalert:Starting up
INFO:elastalert:Found expired previous run for log Access monitor for login at 2017-04-10 08:30:53.777394+00:00
INFO:elastalert:Queried rule log Access monitor for login _ from 2017-04-10 16:27 CST to 2017-04-10 16:32 CST: 48 hits
INFO:elastalert:Sent email to ['mymail']
ERROR:root:Traceback (most recent call last):
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 913, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 1002, in send_alert
    res = self.writeback('elastalert', alert_body)
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 1033, in writeback
    doc_type=doc_type, body=body)
  File "/usr/lib64/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: create() takes at least 5 arguments (5 given)


ERROR:root:Uncaught exception running rule log Access monitor for login: create() takes at least 5 arguments (5 given)
ERROR:root:Traceback (most recent call last):
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 763, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 590, in run_rule
    self.alert([match], rule)
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 915, in alert
    self.handle_uncaught_exception(e, rule)
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 1292, in handle_uncaught_exception
    self.handle_error('Uncaught exception running rule %s: %s' % (rule['name'], exception), {'rule': rule['name']})
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 1287, in handle_error
    self.writeback('elastalert_error', body)
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 1033, in writeback
    doc_type=doc_type, body=body)
  File "/usr/lib64/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: create() takes at least 5 arguments (5 given)

ERROR:root:Uncaught exception running rule log Access monitor for login : create() takes at least 5 arguments (5 given)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 1408, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 1405, in main
    client.start()
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 726, in start
    self.run_all_rules()
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 767, in run_all_rules
    self.handle_uncaught_exception(e, rule)
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 1292, in handle_uncaught_exception
    self.handle_error('Uncaught exception running rule %s: %s' % (rule['name'], exception), {'rule': rule['name']})
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 1287, in handle_error
    self.writeback('elastalert_error', body)
  File "/usr/bin/elastalert/elastalert/elastalert.py", line 1033, in writeback
    doc_type=doc_type, body=body)
  File "/usr/lib64/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: create() takes at least 5 arguments (5 given)

```

Please help ,What am I doing wrong here??!
Thanks

**Comment by Qmando** [comment]
What version of elasticsearch are you using? If it's 2.X, you need to run ``pip install "elasticsearch<=3.0.0"``

**Comment by stefansaye** [comment]
I am retrieve and store remote elk server , why have to install elastsearch ?

**Comment by Qmando** [comment]
Type ``curl <es_host>:<es_port>`` to find the elasticsearch version.
