### ISSUE TITLE
ImportError: No module named base.exceptions upon calling elastalert-test-rule

### ISSUE THREAD

**Issue by jesaremi** [Yelp/elastalert#1041]
I ran create index with no issues. the next command to run was test rule and this is what i get:
```
D:\app\elastalert>elastalert-test-rule rules\frequency.yaml
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\elastalert-test-rule-script.py", line 11, in <module>
    load_entry_point('elastalert==0.1.11', 'console_scripts', 'elastalert-test-rule')()
  File "C:\ProgramData\Anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 565, in
load_entry_point
  File "C:\ProgramData\Anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2598, in
 load_entry_point
  File "C:\ProgramData\Anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2258, in
 load
  File "C:\ProgramData\Anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2264, in
 resolve
  File "d:\app\elastalert\lib\site-packages\elastalert-0.1.11-py2.7.egg\elastalert\test_rule.py", line 20, in <module>
    import elastalert.config
  File "d:\app\elastalert\lib\site-packages\elastalert-0.1.11-py2.7.egg\elastalert\config.py", line 8, in <module>
    import alerts
  File "d:\app\elastalert\lib\site-packages\elastalert-0.1.11-py2.7.egg\elastalert\alerts.py", line 26, in <module>
    from twilio.base.exceptions import TwilioRestException
ImportError: No module named base.exceptions
```

Here's a list of all packages that are installed during the installation process:
```
[.]                                      [..]
[argparse-1.3.0.dist-info]               argparse-1.4.0-py2.7.egg
argparse.py                              argparse.pyc
[aws_requests_auth]                      [aws_requests_auth-0.2.5.dist-info]
aws_requests_auth-0.3.0-py2.7.egg        [blist]
[blist-1.3.6-py2.7-win-amd64.egg]        [blist-1.3.6.dist-info]
[boto3]                                  [boto3-1.4.4-py2.7.egg]
[boto3-1.4.4.dist-info]                  [botocore]
[botocore-1.5.41-py2.7.egg]              [botocore-1.5.41.dist-info]
[configparser-3.5.0-py2.7.egg]           [croniter]
croniter-0.3.16-py2.7.egg                [croniter-0.3.8.dist-info]
[cryptography]                           [cryptography-1.4.dist-info]
[dateutil]                               [docutils-0.13.1-py2.7.egg]
easy-install.pth                         [elastalert-0.1.11-py2.7.egg]
[elasticsearch]                          elasticsearch-5.3.0-py2.7.egg
[elasticsearch-5.3.0.dist-info]          [exotel]
[exotel-0.1.1.dist-info]                 exotel-0.1.4-py2.7.egg
[funcsigs-1.0.2-py2.7.egg]               functools32-3.2.3.post2-py2.7.egg
[futures-3.1.1-py2.7.egg]                [httplib2-0.10.3-py2.7.egg]
[jira]                                   jira-0.32-py2.7.egg
[jira-0.32.dist-info]                    [jmespath]
jmespath-0.9.2-py2.7.egg                 [jmespath-0.9.2.dist-info]
[jsonschema]                             [jsonschema-2.2.0.dist-info]
[jsonschema-2.6.0-py2.7.egg]             [jwt]
[meld3]                                  [meld3-1.0.2.dist-info]
[mock-1.0.0.dist-info]                   [mock-2.0.0-py2.7.egg]
mock.py                                  mock.pyc
[oauthlib]                               [oauthlib-0.7.2.dist-info]
oauthlib-2.0.2-py2.7.egg                 [pbr-2.1.0-py2.7.egg]
[PyJWT-1.5.0.dist-info]                  pystaticconfiguration-0.10.3-py2.7.egg
[PyStaticConfiguration-0.9.0.dist-info]  [python_dateutil-2.4.0.dist-info]
python_dateutil-2.6.0-py2.7.egg          pytz-2017.2-py2.7.egg
[PyYAML-3.11.dist-info]                  PyYAML-3.12-py2.7-win-amd64.egg
[requests]                               [requests-2.13.0-py2.7.egg]
[requests-2.5.1.dist-info]               [requests_oauthlib]
[requests_oauthlib-0.4.2.dist-info]      [requests_oauthlib-0.8.0-py2.7.egg]
[s3transfer]                             s3transfer-0.1.10-py2.7.egg
[s3transfer-0.1.10.dist-info]            [simplejson]
[simplejson-3.10.0-py2.7-win-amd64.egg]  [simplejson-3.3.0.dist-info]
site.py                                  site.pyc
[six-1.10.0-py2.7.egg]                   [staticconf]
[stomp]                                  [stomp.py-4.1.15.dist-info]
stomp.py-4.1.17-py2.7.egg                [supervisor]
supervisor-3.1.2-py2.7-nspkg.pth         [supervisor-3.1.2.dist-info]
[tests]                                  [texttable-0.8.4.dist-info]
texttable-0.8.8-py2.7.egg                texttable.py
texttable.pyc                            [tlslite]
[tlslite-0.4.8.dist-info]                tlslite-0.4.9-py2.7.egg
[twilio]                                 [twilio-6.0.0.dist-info]
[twilio-6.3.dev0-py2.7.egg]              [unittest2]
[unittest2-0.8.0.dist-info]              [urllib3]
[urllib3-1.20-py2.7.egg]                 [urllib3-1.20.dist-info]
[urllib3-1.8.2.dist-info]                [yaml]
```

**Comment by Qmando** [comment]
run ``pip install twilio==6.0.0``.

You've installed the 6.3.dev0 version which is not compatible.

**Comment by jesaremi** [comment]
thank you. that solved my problem!
