### ISSUE TITLE
Unable to create a index

### ISSUE THREAD

**Issue by sadiesh** [Yelp/elastalert#1055]
# elastalert-create-index
Traceback (most recent call last):
  File "/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests==2.2.1

**Comment by Qmando** [comment]
You can either run ``python -m elastalert.create_index``.

Or, uninstall elastalert and reinstall via ``pip install elastalert``.

Or attempt to fix the dependencies, ``pip install requests==2.2.1``.

Sorry about that. I need to remove setuptools (python setup.py install) from the documentation..

**Comment by sadiesh** [comment]
Thanks Qmando
