### ISSUE TITLE
Use of elastalert with index optimized for time series

### ISSUE THREAD

**Issue by fabMrc** [Yelp/elastalert#1061]
Hi

I have my index optimized for time series 

`
{
  "template": "metrics*",
  "settings": {
    "index": {
      "refresh_interval": "5s"
    }
  },
  "mappings": {
    "_default_": {
      "dynamic_templates": [
        {
          "strings": {
            "match": "*",
            "match_mapping_type": "string",
            "mapping":   { "type": "string",  "doc_values": true, "index": "not_analyzed" }
          }
        }
      ],
      "_all":            { "enabled": false },
      "_source":         { "enabled": false },
      "properties": {
        "@timestamp":    { "type": "date",    "doc_values": true },
        "count":         { "type": "integer", "doc_values": true, "index": "no" },
        "m1_rate":       { "type": "float",   "doc_values": true, "index": "no" },
        "m5_rate":       { "type": "float",   "doc_values": true, "index": "no" },
        "m15_rate":      { "type": "float",   "doc_values": true, "index": "no" },
        "max":           { "type": "integer", "doc_values": true, "index": "no" },
        "mean":          { "type": "integer", "doc_values": true, "index": "no" },
        "mean_rate":     { "type": "float",   "doc_values": true, "index": "no" },
        "median":        { "type": "float",   "doc_values": true, "index": "no" },
        "min":           { "type": "float",   "doc_values": true, "index": "no" },
        "p25":           { "type": "float",   "doc_values": true, "index": "no" },
        "p50":           { "type": "float",   "doc_values": true, "index": "no" },
        "p75":           { "type": "float",   "doc_values": true, "index": "no" },
        "p95":           { "type": "float",   "doc_values": true, "index": "no" },
        "p98":           { "type": "float",   "doc_values": true, "index": "no" },
        "p99":           { "type": "float",   "doc_values": true, "index": "no" },
        "p999":          { "type": "float",   "doc_values": true, "index": "no" },
        "stddev":        { "type": "float",   "doc_values": true, "index": "no" },
        "value":         { "type": "float",   "doc_values": true, "index": "no" },
        "duration_units":{ "type": "string",   "doc_values": true, "index": "not_analyzed" },
        "rate_units":    { "type": "string",   "doc_values": true, "index": "not_analyzed" },
        "units":         { "type": "string",   "doc_values": true, "index": "not_analyzed" }
      }
    }
  }
}
`

Now I want to test an alert 

`
 Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
es_host: localhost

# (Optional)
# Elasticsearch port
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword

# (Required)
# Rule name, must be unique
name: Example frequency rule

_source_enabled: false

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: metrics-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 5

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  minutes: 10

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- term:
    name: "counter.status.200.health"

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "toto@mail.com"

`

I have the result below : 
`
elastalert-test-rule example_rules/example_frequency.yaml
Successfully loaded Example frequency rule

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
Traceback (most recent call last):
  File "/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.12', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.12-py2.7.egg/elastalert/test_rule.py", line 333, in main
    test_instance.run_rule_test()
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.12-py2.7.egg/elastalert/test_rule.py", line 320, in run_rule_test
    hits = self.test_file(copy.deepcopy(rule_yaml), args)
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.12-py2.7.egg/elastalert/test_rule.py", line 83, in test_file
    terms = res['hits']['hits'][0]['_source']
KeyError: '_source'

`

However I have _source_enabled : false so I do not understand

**Comment by Qmando** [comment]
I think elastalert-test-rule in particular has an issue with _source_enabled: false. Try running 
```
elastalert --debug --rule example_frequency.yaml
```
instead. 

Thanks for reporting this issue. Sorry about that.

**Comment by fabMrc** [comment]
```sh
root@elastic elastalert]# elastalert --debug --rule example_rules/example_frequency.yaml
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:elastalert:Starting up
INFO:elastalert:Queried rule Example frequency rule from 2017-05-03 09:30 UTC to 2017-05-03 09:45 UTC: 90 / 90 hits
ERROR:root:Error running rule Example frequency rule: Error: No timestamp was found for hit. '_source_enabled' is set to false, check your mappings for stored fields
INFO:elastalert:Skipping writing to ES: {'message': "Error running rule Example frequency rule: Error: No timestamp was found for hit. '_source_enabled' is set to false, check your mappings for stored fields", 'traceback': ['Tr
aceback (most recent call last):', '  File "/usr/lib/python2.7/site-packages/elastalert-0.1.12-py2.7.egg/elastalert/elastalert.py", line 916, in run_all_rules', '    num_matches = self.run_rule(rule, endtime, self.starttime)',
'  File "/usr/lib/python2.7/site-packages/elastalert-0.1.12-py2.7.egg/elastalert/elastalert.py", line 686, in run_rule', "    if not self.run_query(rule, rule['starttime'], endtime):", '  File "/usr/lib/python2.7/site-packages/
elastalert-0.1.12-py2.7.egg/elastalert/elastalert.py", line 478, in run_query', '    data = self.get_hits(rule, start, end, index, scroll)', '  File "/usr/lib/python2.7/site-packages/elastalert-0.1.12-py2.7.egg/elastalert/elast
alert.py", line 332, in get_hits', '    hits = self.process_hits(rule, hits)', '  File "/usr/lib/python2.7/site-packages/elastalert-0.1.12-py2.7.egg/elastalert/elastalert.py", line 267, in process_hits', '    raise EAException(
"Error: No timestamp was found for hit. \'_source_enabled\' is set to false, check your mappings for stored fields")', "EAException: Error: No timestamp was found for hit. '_source_enabled' is set to false, check your mappings
for stored fields"], 'data': {'rule': 'Example frequency rule'}}
INFO:elastalert:Sleeping for 59.948246 seconds
```

Speaks about missing field timestamp but is present (check my mapping above)

**Comment by fabMrc** [comment]
Ok 

Doc_value with _source disabled and index no allow only aggregation/sort/script query 

for exemple : 

```
{
    "aggs" : {
        "gauge" : {
            "filter" : { "term": { "name": "mem.physical.free" } },
            "aggs" : {
                "avg_mem_physical_free" : { "avg" : { "field" : "value" } }
            }
        }
    }
}
```

return 
```
aggregations": {
        "gauge": {
            "doc_count": 55,
            "avg_mem_physical_free": {
                "value": 7886897226.472727
            }
        }
    }
```

Maybe it need to involves elastalert for ES time series optimized ?

**Comment by fabMrc** [comment]
Ok nice 
With my specific mapping the metric_aggregation rule must be use

and the ES generated request body is with debug enabled : 

```
{
 "aggs": {
    "filtered": {
      "aggs": {
        "interval_aggs": {
          "aggs": {
            "value_avg": {
              "avg": {
                "field": "value"
              }
            }
          },
          "date_histogram": {
            "field": "@timestamp",
            "interval": "10m"
          }
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2017-05-04T15:50:00.278240Z",
                  "lte": "2017-05-04T16:00:00.278240Z"
                }
              }
            },
           {
              "term": {
                "name": "mem.physical.free"
              }
            }
          ]
        }
      }
    }
  }
}
```

**Comment by Qmando** [comment]
Maybe you need to add
```
include: ["@timestamp"]
```
?

I have no experience with _source disabled or ES 5 so I'm not really sure what the issue is, sorry.

**Comment by fabMrc** [comment]
No it works as I said, no need to use include (* by default)
Now I am trying to use script in filter to improve the generated aggregated query
