### ISSUE TITLE
ImportError: No module named base.exceptions

### ISSUE THREAD

**Issue by Carole89** [Yelp/elastalert#1062]
Hi,

Please I need help, I am a beginner in the use of elaticsearch and elastalert. For running elastalert i used this tutorial.   [http://elastalert.readthedocs.io/en/latest/running_elastalert.html#testing-your-rule](url)

When I execute this  ` elastalert-test-rule example_rules/example_frequency.yaml` to test the rule I have the following error

 ```
elastalert-test-rule example_rules/example_frequency.yaml
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.1.12', 'console_scripts', 'elastalert-test-rule')()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/test_rule.py", line 20, in <module>
    import elastalert.config
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/config.py", line 8, in <module>
    import alerts
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.12-py2.7.egg/elastalert/alerts.py", line 26, in <module>
    from twilio.base.exceptions import TwilioRestException
ImportError: No module named base.exceptions

```

Also when I test this command to run elastalert `python elastalert/elastalert.py --config config.yaml --rule ./example_rules/example_frequency.yaml` i have the following error

```
Traceback (most recent call last):
  File "elastalert/elastalert.py", line 20, in <module>  from alerts import DebugAlerter
  File "/home/ubuntu/elastalert/elastalert/alerts.py", line 26, in <module>  
 from twilio.base.exceptions import TwilioRestException
ImportError: No module named base.exceptions
```

The config.yaml file I have is

> rules_folder: example_rules
> 
> run_every:
>   minutes: 1
> 
> buffer_time:
>   minutes: 15
> 
> es_host: localhost
> 
> es_port: 9200
> 
> highlight=send_get_body_as#transport
> 
> writeback_index: elastalert_status
> 
> alert_time_limit:
>   days: 2

The example_frequency.yaml file I have is

>  es_host: localhost
> 
> 
>  es_port: 9200
> 
> 
> name: Example frequency rule
> 
> 
> type: frequency
> 
> 
> index: logstash-*
> 
> 
> num_events: 50
> 
> 
> timeframe:
>   hours: 4
> 
> 
> filter:
> - term:
>     some_field: "some_value"
> 
> 
> alert:
> - "email"
> 
> email:
> - "carole.dubeau@hotmail.fr"
> 

Can you please help me ?

Thanks

**Comment by Qmando** [comment]
run ``pip install twilio==6.0.0``

**Comment by Carole89** [comment]
thank you for your reply.

I still have the same error

**Comment by Qmando** [comment]
Did the command succeed?

**Comment by Carole89** [comment]
Yes!

```
pip install twilio==6.0.0Collecting twilio==6.0.0
Collecting six (from twilio==6.0.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting requests>=2.0.0 (from twilio==6.0.0)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting idna>=2.0.0 (from twilio==6.0.0)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting pytz (from twilio==6.0.0)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting pyOpenSSL>=0.14 (from twilio==6.0.0)
  Using cached pyOpenSSL-17.0.0-py2.py3-none-any.whl
Collecting PyJWT>=1.4.2 (from twilio==6.0.0)
  Using cached PyJWT-1.5.0-py2.py3-none-any.whl
Collecting cryptography>=1.3.4 (from twilio==6.0.0)
Collecting setuptools>=11.3 (from cryptography>=1.3.4->twilio==6.0.0)
  Using cached setuptools-35.0.2-py2.py3-none-any.whl
Collecting ipaddress (from cryptography>=1.3.4->twilio==6.0.0)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4->twilio==6.0.0)
  Using cached asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=1.3.4->twilio==6.0.0)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.3.4->twilio==6.0.0)
  Using cached cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting packaging (from cryptography>=1.3.4->twilio==6.0.0)
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools>=11.3->cryptography>=1.3.4->twilio==6.0.0)
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.3.4->twilio==6.0.0)
Collecting pyparsing (from packaging->cryptography>=1.3.4->twilio==6.0.0)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Installing collected packages: six, requests, idna, pytz, appdirs, pyparsing, packaging, setuptools, ipaddress, asn1crypto, enum34, pycparser, cffi, cryptography, pyOpenSSL, PyJWT, twilio
Successfully installed PyJWT-1.5.0 appdirs-1.4.3 asn1crypto-0.22.0 cffi-1.10.0 cryptography-1.8.1 enum34-1.1.6 idna-2.5 ipaddress-1.0.18 packaging-16.8 pyOpenSSL-17.0.0 pycparser-2.17 pyparsing-2.2.0 pytz-2017.2 requests-2.13.0 setuptools-35.0.1 six-1.10.0 twilio-6.3.dev0
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by Qmando** [comment]
Can you run ``python -c "import twilio;print twilio.__file__"``??

**Comment by Carole89** [comment]
When I execute this command `python -c "import twilio;print twilio.__file__"` I have the following result

```
 python -c "import twilio;print twilio.__file__"
/usr/local/lib/python2.7/dist-packages/twilio-6.3.dev0-py2.7.egg/twilio/__init__.pyc

```

**Comment by Qmando** [comment]
Ok, it seems that pip is not installing to the correct directory. This usually happens if you have more than one Python installed. What operating system are you on? I think I've seen this on OSX before.

One solution is to use virtualenvs. https://virtualenv.pypa.io/en/stable/

Another is to fix pip, though I don't know exactly what you need to do for that.

A third is to open setup.py in elastalert and edit ``'twilio'`` to ``'twilio==6.0.0'``. The "latest" version that you downloaded (6.3.0) seems to be a beta version, and they made breaking changes. :(

**Comment by Carole89** [comment]
Yes I have two versions of python installed on my machine. :( (I work with linux kernel ubuntu) 
To solve this problem I have uninstalled all versions of python and its dependencies and reinstall the project again.

Now when I execute this command `python -c "import twilio;print twilio.__file__"` I have the following result

`/usr/local/lib/python2.7/dist-packages/twilio-6.0.0-py2.7.egg/twilio/__init__.pyc`

But when I run   `python elastalert/elastalert.py --config config.yaml --rule ./example_rules/example_frequency.yaml` i have the following message

```
Traceback (most recent call last):
  File "elastalert/elastalert.py", line 1597, in <module>
    sys.exit(main(sys.argv[1:]))
  File "elastalert/elastalert.py", line 1592, in main
    client = ElastAlerter(args)
  File "elastalert/elastalert.py", line 95, in __init__
    self.conf = load_rules(self.args)
  File "/home/ubuntu2/elastalert/elastalert/config.py", line 432, in load_rules
    rule = load_configuration(rule_file, conf, args)
  File "/home/ubuntu2/elastalert/elastalert/config.py", line 105, in load_configuration
    rule = load_rule_yaml(filename)
  File "/home/ubuntu2/elastalert/elastalert/config.py", line 118, in load_rule_yaml
    loaded = yaml_loader(filename)
  File "build/bdist.linux-x86_64/egg/staticconf/loader.py", line 168, in yaml_loader
  File "build/bdist.linux-x86_64/egg/yaml/__init__.py", line 71, in load
    
  File "build/bdist.linux-x86_64/egg/yaml/constructor.py", line 37, in get_single_data
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 39, in get_single_node
  File "build/bdist.linux-x86_64/egg/yaml/parser.py", line 98, in check_event
  File "build/bdist.linux-x86_64/egg/yaml/parser.py", line 174, in parse_document_start
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "./example_rules/example_frequency.yaml", line 20, column 1
```

**Comment by Qmando** [comment]
What is this in your rule config? It's not YAML.
``highlight=send_get_body_as#transport``
http://www.yaml.org/start.html

**Comment by Carole89** [comment]
Currently I have this configuration, but the same error :(
 
example_frequency.yaml

```
es_host: localhost
 es_port: 9200
name: Example frequency rule
type: frequency
index: logstash-*
num_events: 50
timeframe:
  hours: 4
filter:
- term:
    some_field: "some_value"
alert:
- "email"
email:
- "carole.dubeau@hotmail.fr"
```

in Config.yaml

```
rules_folder: example_rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: localhost
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2
```

**Comment by Qmando** [comment]
You've got a space before es_port, you can't have that.

**Comment by Carole89** [comment]
Many thanks Qmando it works.

![alert](https://cloud.githubusercontent.com/assets/28110780/25543136/48bf97f0-2c23-11e7-9478-81624a8f7b70.JPG)
 

Just a last question I need to add this example of configuration in frequency.yaml to identify my server? 
Or just i indicate my email address.

```
profile: outlook
        smtp:
            auth: true
            starttls.enable: true
            host: smtp-mail.outlook.com
            port: 587
            user: <username>
            password: <password>
```
			
Thanks

**Comment by Qmando** [comment]
http://elastalert.readthedocs.io/en/latest/ruletypes.html#email

You need an SMTP server. Outlook should work fine.

```
smtp_host: smtp-mail.outlook.com
smtp_auth_file: /path/to/file
from_addr: carole89@outlook.com
```

and within the auth file
```
user: carole
password: abcd123
```

**Comment by Carole89** [comment]
I add this configuration after email: - "carole.dubeau@hotmail.fr" ?

```
es_host: localhost
es_port: 9200
name: Example frequency rule
type: frequency
index: logstash-*
num_events: 50
timeframe:
  hours: 4
filter:
- term:
    some_field: "some_value"
alert:
- "email"
email:
- "carole.dubeau@hotmail.fr"
smtp_host: smtp-mail.outlook.com
smtp_auth_file: /path/to/file
from_addr: carole89@outlook.com

```

**Comment by Qmando** [comment]
yes, you also need ``email``, which is the recipient.

**Comment by Carole89** [comment]
Just I add `email` before - "carole.dubeau@hotmail.fr"  because it's my recipient. My new configuration is:

```
....
- term:
    some_field: "some_value"
alert:
- "email"
email: "carole.dubeau@hotmail.fr"
smtp_host: smtp-mail.outlook.com
smtp_auth_file: /path/to/file
from_addr: carole89@outlook.com
```

**Comment by Qmando** [comment]
Ok. You need to replace ``carole89@outlook.com`` with ``carole.dubeau@hotmail.fr``. And I'll just assume you kept ``/path/to/file`` but in the real config you have an actual file.

**Comment by Carole89** [comment]
Thank you very much Qmando!
