### ISSUE TITLE
Percentage match problem

### ISSUE THREAD

**Issue by you-think-you-are-special** [Yelp/elastalert#1068]
Trying this example https://github.com/Yelp/elastalert/blob/master/example_rules/example_percentage_match.yaml 
But have  raise EAException

```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert', 'console_scripts', 'elastalert')()
  File "/usr/src/elastalert-0.1.8/elastalert/elastalert.py", line 1458, in main
    client = ElastAlerter(args)
  File "/usr/src/elastalert-0.1.8/elastalert/elastalert.py", line 93, in __init__
    self.conf = load_rules(self.args)
  File "/usr/src/elastalert-0.1.8/elastalert/config.py", line 398, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file /opt/rules/seo200.yaml: Invalid Rule: Example Percentage Match
{'index': 'logstash-http-request-*', 'name': 'Example Percentage Match', 'query_key': 'Hostname.keyword', 'alert': ['debug'], 'filter': [{'term': {'_type': 'http_request'}}], 'buffer_time': {'minutes': 5},
 'doc_type': 'http_request', 'rule_file': '/opt/rules/seo200.yaml', 'match_bucket_filter': [{'terms': {'ResponseStatus': [200]}}], 'type': 'percentage_match', 'min_percentage': 95, 'description': '95% of a
ll http requests should be successful'} is not valid under any of the given schemas
```

![ba6af6f676](https://cloud.githubusercontent.com/assets/2720927/25620523/654dcd38-2f57-11e7-9db0-850b3c10bc0a.png)

**Comment by Qmando** [comment]
You've got an old version of elastalert. Percentage_match was added recently.
