### ISSUE TITLE
Unable to do ALERT using the term and match in logs

### ISSUE THREAD

**Issue by sadiesh** [Yelp/elastalert#1071]
ERROR:root:Error finding recent pending alerts: TransportError(400, u'search_phase_execution_exception', u'No mapping fo
und for [alert_time] in order to sort on') {'filter': {'range': {'alert_time': {'to': '2017-05-03T07:35:34.451Z', 'from'
: '2017-05-01T07:35:34.451Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 's
ort': {'alert_time': {'order': 'asc'}}}
Traceback (most recent call last):
  File "C:\Users\local\Desktop\project\elastalert\elastalert\elastalert.py", line 1214, in find_recent_pending_alerts

    size=100)
  File "C:\Python27\lib\site-packages\elasticsearch\client\utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\elasticsearch\client\__init__.py", line 625, in search
    doc_type, '_search'), params=params, body=body)
  File "C:\Python27\lib\site-packages\elasticsearch\transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "C:\Python27\lib\site-packages\elasticsearch\connection\http_requests.py", line 89, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "C:\Python27\lib\site-packages\elasticsearch\connection\base.py", line 124, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to s
ort on')
INFO:elastalert:Queried rule Local test rule from 2017-05-03 12:59 India Standard Time to 2017-05-03 13:05 India Standar
d Time: 0 / 0 hits
INFO:elastalert:Ran Local test rule from 2017-05-03 12:59 India Standard Time to 2017-05-03 13:05 India Standard Time: 0
 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 58.189 seconds

**Comment by kureus** [comment]
What is the output of 
`curl -XGET 'http://elasticsearch.example.com:14900/elastalert_status/_mapping/`

I would suspect you are hitting something like #207, where the elastalert index isn't being created properly for some reason
