### ISSUE TITLE
where did requirement.txt go?

### ISSUE THREAD

**Issue by prayagupd** [Yelp/elastalert#1073]
With latest changes, seems `requirements.txt` is gone, not a python guy but that file seems a package manager to python.
So, it can not find some modules while running `elastalert`, 

```bash
python -m elastalert.elastalert --verbose --config /usr/local/elastalert/stream-logevents.yaml
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/elastalert/elastalert/elastalert.py", line 20, in <module>
    from alerts import DebugAlerter
  File "elastalert/alerts.py", line 26, in <module>
    from twilio.base.exceptions import TwilioRestException
ImportError: No module named base.exceptions
```

What I did?
--

```bash
git clone git@github.com:Yelp/elastalert.git
apt-get -y install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev

apt-get -y install python-setuptools

sudo python setup.py install

#pip install -r requirements.txt # not requirements.txt exists
```

```
pip list
appdirs (1.4.3)
aws-requests-auth (0.3.0)
blist (1.3.6)
boto3 (1.4.4)
botocore (1.5.45)
configparser (3.5.0)
croniter (0.3.16)
defusedxml (0.5.0)
docutils (0.13.1)
elastalert (0.1.12)
elasticsearch (5.3.0)
exotel (0.1.4)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.1.1)
httplib2 (0.10.3)
jira (1.0.10)
jmespath (0.9.2)
jsonschema (2.6.0)
mock (2.0.0)
oauthlib (2.0.2)
ordereddict (1.1)
packaging (16.8)
pbr (3.0.0)
Pillow (3.1.2)
pip (8.1.1)
PyOpenGL (3.0.2)
pyparsing (2.2.0)
Pyrex (0.9.8.5)
PyStaticConfiguration (0.10.3)
python-dateutil (2.6.0)
pytz (2017.2)
PyYAML (3.12)
requests (2.13.0)
requests-oauthlib (0.8.0)
requests-toolbelt (0.7.1)
s3transfer (0.1.10)
setuptools (35.0.2)
simplejson (3.10.0)
six (1.10.0)
stomp.py (4.1.17)
texttable (0.8.8)
twilio (6.3.dev0)
urllib3 (1.21.1)
wheel (0.29.0)
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by prayagupd** [comment]
NVM 

pip installing `6.0.0` fixes it. Its already posted as issues [somewhere](https://github.com/Yelp/elastalert/issues/1041).

```bash
apt-get install build-essential libssl-dev libffi-dev python-dev
pip install cryptography
pip install twilio==6.0.0
```

**Comment by Qmando** [comment]
I'm going to add requirements.txt back, but have it match setup.py

**Comment by prayagupd** [comment]
@Qmando Thanks. I am not sure why do I need both `setup.py` and `requirement.txt` though? It worked for me without `requirement.txt` too, but had to manually `pip install twilio=6.0.0` instead of `twilio-6.3-dev`.
