### ISSUE TITLE
Elastalert crashes when checking for the ES version

### ISSUE THREAD

**Issue by nicorevin** [Yelp/elastalert#1097]
```
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
  "__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
  exec code in run_globals
File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1722, in <module>
  sys.exit(main(sys.argv[1:]))
File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1716, in main
  client = ElastAlerter(args)
File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 139, in __init__
  self.modify_rule_for_ES5(rule)
File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 877, in modify_rule_for_ES5
  if rule_es.info()['version']['number'].startswith('5'):
File "/root/.local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
  return func(*args, params=params, **kwargs)
File "/root/.local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 220, in info
  return self.transport.perform_request('GET', '/', params=params)
File "/root/.local/lib/python2.7/site-packages/elasticsearch/transport.py", line 327, in perform_request
  status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
File "/root/.local/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
  self._raise_error(response.status_code, raw_data)
File "/root/.local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 114, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(504, '...some html code here')
```

Elastalert version: **0.1.14**

**Comment by Qmando** [comment]
504 means gateway timeout, so perhaps something is wrong with your Elasticsearch cluster.

Can you curl it directly?
``$ curl localhost:9200``

**Comment by nicorevin** [comment]
Actually the problem is with proxy server. But still I would expect it to throw a warning/error and continue with other rules.

**Comment by nicorevin** [comment]
Fixed in https://github.com/Yelp/elastalert/commit/d518f1a0379aa579a812a6170103ad3e6ad75315
