### ISSUE TITLE
cannot import name load_rule_yaml

### ISSUE THREAD

**Issue by thanh3d** [Yelp/elastalert#1111]
> Traceback (most recent call last):
  File "/usr/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.14', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/test_rule.py", line 23, in <module>
    from elastalert.config import load_rule_yaml
ImportError: cannot import name load_rule_yaml

**Comment by thanh3d** [comment]
I have installed `PyYAML-3.12` successfully.

**Comment by Qmando** [comment]
This is very odd.
Does running ``$ python -c "import elastalert.config"`` throw an error?

**Comment by thanh3d** [comment]
No any error for `$ python -c "import elastalert.config"`
