### ISSUE TITLE
Elastalert returning error on Windows

### ISSUE THREAD

**Issue by blarrkan** [Yelp/elastalert#1123]
Hi,
I installed python 2.7 and pip, installed elastalert, created the index in elasticsearch.
Now when I try to run 
`elastalert-test-rule example_frequenzy.yaml`

I get the error message
'C:\elastalert\elastalert>elastalert-test-rule example_frequency.yaml
Traceback (most recent call last):
  File "C:\Python27\Scripts\elastalert-test-rule-script.py", line 11, in <module>
    load_entry_point('elastalert==0.1.14', 'console_scripts', 'elastalert-test-rule')()
  File "C:\Python27\lib\site-packages\elastalert-0.1.14-py2.7.egg\elastalert\test_rule.py", line 358, in main
    test_instance.run_rule_test()
  File "C:\Python27\lib\site-packages\elastalert-0.1.14-py2.7.egg\elastalert\test_rule.py", line 339, in run_rule_test
    conf = self.load_conf(rule_yaml, args)
  File "C:\Python27\lib\site-packages\elastalert-0.1.14-py2.7.egg\elastalert\test_rule.py", line 301, in load_conf
    load_options(rules, conf, args.file)
  File "C:\Python27\lib\site-packages\elastalert-0.1.14-py2.7.egg\elastalert\config.py", line 243, in load_options
    rule['compound_compare_key'] = [rule['compare_key']]
KeyError: 'compare_key''

Do anyone have any ideas what is wrong? I have of course edited both config.yaml and example_frequency.yaml with my elasticsearch server and search criteria.

**Comment by imagiro69** [comment]
Looks like the latest change for compound key support has broken the config.py

As a workaround, you can change config.py, line 242 from
`else:`
to
`elif 'compare_key' in rule:`

Not sure if this is correct solution, but it seems to work for now.

**Comment by Qmando** [comment]
Sorry about that. I'm always too eager to merge pull requests. It's fixed in master now.
