### ISSUE TITLE
Example does not work, KeyError: ('compare_key')

### ISSUE THREAD

**Issue by yuanxu-li** [Yelp/elastalert#1124]
I was going over the documentation and running the first example:
```bash
python -m elastalert.elastalert --verbose --rule example_frequency.yaml
```
It gives me the following error:
```
Traceback (most recent call last):
  File "/home/justin/.pyenv/versions/2.7.12/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/justin/.pyenv/versions/2.7.12/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/justin/dev_projects/elastalert/elastalert/elastalert.py", line 1730, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/justin/dev_projects/elastalert/elastalert/elastalert.py", line 1724, in main
    client = ElastAlerter(args)
  File "/home/justin/dev_projects/elastalert/elastalert/elastalert.py", line 111, in __init__
    self.conf = load_rules(self.args)
  File "elastalert/config.py", line 440, in load_rules
    rule = load_configuration(rule_file, conf, args)
  File "elastalert/config.py", line 107, in load_configuration
    load_options(rule, conf, filename, args)
  File "elastalert/config.py", line 243, in load_options
    rule['compound_compare_key'] = [rule['compare_key']]
KeyError: 'compare_key'
```

The error traces back to [here](https://github.com/Yelp/elastalert/blob/master/elastalert/config.py#L243).

This part of code does not make sense to me. In this `if-else` condition, `rule['compare_key']` is going to be accessed either way. If `compare_key` is not a key, then it will always render `KeyError`. And in the example, `compare_key` is not specified (not necessarily) in `example_frequency.yaml`.

Do I get something wrong?

**Comment by Qmando** [comment]
This was broken in master yesterday and fixed earlier today. Pull master again.
