### ISSUE TITLE
ElastAlert + Search Guard

### ISSUE THREAD

**Issue by otisonoza** [Yelp/elastalert#1129]
I'm trying to set up ElastAlert to work with my Search Guard secured ELK installation.

I'm following the guide here: http://elastalert.readthedocs.io/en/latest/running_elastalert.html

Since Search Guard requires TLS on the transport layer, I have this configured in config.yaml of ElastAlert:
```
# Connect with TLS to Elasticsearch
use_ssl: True

# Verify TLS certificates
verify_certs: False
```

When running the elastalert-create-index script it gives me the following error:
```
elastalert-create-index --config config.yaml
/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py:62: UserWarning: Connecting to https://localhost:9300 using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % self.base_url)                                                                                           
New index name? (Default elastalert_status)                                                                                                                                    
Name of existing index to copy? (Default None)                                                                                                                                 
Traceback (most recent call last):                                                                                                                                             
  File "/usr/bin/elastalert-create-index", line 11, in <module>                                                                                                                
    load_entry_point('elastalert==0.1.14', 'console_scripts', 'elastalert-create-index')()                                                                                     
  File "/usr/lib/python2.7/site-packages/elastalert/create_index.py", line 131, in main                                                                                        
    if es_index.exists(index):                                                                                                                                                 
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped                                                                                  
    return func(*args, params=params, **kwargs)                                                                                                                                
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 224, in exists                                                                                 
    params=params)                                                                                                                                                             
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request                                                                             
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)                                                              
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 82, in perform_request                                                               
    raise SSLError('N/A', str(e), e)                                                                                                                                           
elasticsearch.exceptions.SSLError: ConnectionError([SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:579)) caused by: SSLError([SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:579))
```

In the Elasticsearch logs I see the following:
```
[2017-05-26T21:28:29,772][ERROR][c.f.s.s.t.SearchGuardSSLNettyTransport] [sHQzypY] SSL Problem null cert chain
javax.net.ssl.SSLHandshakeException: null cert chain
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:?]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_92]
        at io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:218) ~[netty-handler-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1028) ~[netty-handler-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:950) ~[netty-handler-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:527) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:481) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.7.Final.jar:4.1.7.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: javax.net.ssl.SSLHandshakeException: null cert chain
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:?]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304) ~[?:?]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:292) ~[?:?]
        at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1865) ~[?:?]
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:230) ~[?:?]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) ~[?:?]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_92]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) ~[?:?]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1167) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1080) ~[?:?]
        ... 17 more
```

It looks no cert is sent.

**My question is, how do I configure which certificates are used for SSL?**

In case I disable SSL in ElastAlert, I have this error in Elasticsearch:
```
[2017-05-26T21:27:35,471][WARN ][c.f.s.s.t.SearchGuardSSLNettyTransport] [sHQzypY] exception caught on transport layer [[id: 0x8fd94dfe, L:0.0.0.0/0.0.0.0:9300 ! R:/0:0:0:0:0:0:0:1:37398]], closing connection
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 48454144202f656c617374616c6572745f73746174757320485454502f312e310d0a486f73743a206c6f63616c686f73743a393330300d0a4163636570742d456e636f64696e673a206964656e746974790d0a636f6e74656e742d747970653a206170706c69636174696f6e2f6a736f6e0d0a417574686f72697a6174696f6e3a204261736963205a57786863335268624756796444706c6247467a644746735a584a300d0a0d0a
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:968) [netty-handler-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:527) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:481) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.7.Final.jar:4.1.7.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```
So disabling it is not an option for me.

**Comment by floragunncom** [comment]
I think you confused transport with HTTP layer. As far as i know elastalert connect to ES via HTTP(S). So it is possible to disable SSL for HTTP (albeit we do not recommend it). SSL is only mandatory in Search Guard for the transport layer (not the HTTP layer). 

To get python based things running pls also [look here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/search-guard/Sr5BTLVrd-U/8Ec3Wj7XBQAJ)

**Comment by otisonoza** [comment]
I have SSL disabled on the HTTP layer, since I have this in my configuration:
`searchguard.ssl.http.enabled: false`

Plus, since I see this in the error logs:
`[2017-05-26T21:27:35,471][WARN ][c.f.s.s.t.SearchGuardSSLNettyTransport]`
I'm pretty sure it's the transport layer which complains.

I'll take a look at your link, maybe I find something to configure this Python based tool.

**Comment by otisonoza** [comment]
Also, could you please help me to understand the difference between transport layer and REST layer?

[Here](https://github.com/floragunncom/search-guard-docs/blob/master/tls_configuration.md) you write:

> For the REST layer, TLS is optional, while you cannot switch it off for the transport layer.

Here's how I understand it:
REST uses HTTP(S), so it can use HTTP over TLS.
TLS => **Transport** Layer Security

The transport what you mention is used when transferring the logs (?).
For example from Logstash to Elasticsearch.

So essentially they are the same, but you can configure it separately for these purposes.

Then I guess ElastAlert doesn't use the REST layer, but communicates directly with ES somehow.

**Comment by jochenkressin** [comment]
Admittedly it's a bit confusing since Elasticsearch uses the wording "transport layer" as well, independently from TLS.

REST layer in ES terminology means accessing your cluster via HTTP(S) and the REST API.

Transport layer means Elastics own wire protocol, which the nodes use to talk to each other. It's also used if you use a Transport Client to talk to the cluster. So, transport layer here means "inter-node communication".

If you switch on TLS for the REST layer, it means you can only communicate with your cluster via HTTPS. Plain HTTP is not allowed anymore. If you switch it off (not recommended for production) yu can still use plain, unencrypted HTTP.

Switching off TLS for the transport layer is not possible because it would allow for a couple of attack scenarios.

**Comment by otisonoza** [comment]
OK guys, seems like I'm an idiot.
I was trying to connect to port 9300 instead of 9200.

If I connect to 9200 without SSL I get this:
```
elastalert-create-index --config config.yaml
New index name? (Default elastalert_status)
Name of existing index to copy? (Default None)
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.1.14', 'console_scripts', 'elastalert-create-index')()
  File "/usr/lib/python2.7/site-packages/elastalert/create_index.py", line 131, in main
    if es_index.exists(index):
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 224, in exists
    params=params)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthenticationException: TransportError(401, u'')
```

I guess I just have to authenticate the plain HTTP request and it'll be OK.
I'll modify the python code to put a BasicAuth header for me.

I'll let you know how it will work.

**Comment by otisonoza** [comment]
Embarrassing .. my internal user DB was wrong in Search Guard.
Using a different user it works.
