### ISSUE TITLE
No rule works form me 

### ISSUE THREAD

**Issue by tnanga** [Yelp/elastalert#1131]
Hello, 
I'm trying to test a rules in Elastalert but the result is always : hits': 0, 'matches': 0,

I created my index and mapping with a php library called elasticsearch-php. This is my mapping :

$params = [
     'index' => 'blog',
     'body' => [
         'settings' => [
             'number_of_shards' => 1,
             'number_of_replicas' => 0
         ],
         'mappings' => [
             'article' => [
                 '_source' => [
                     'enabled' => true
                 ],
                 'properties' => [
                     'title' => [
                         'type' => 'string'
                     ],
                     'desc' => [
                         'type' => 'text'
                     ],
                     '@timestamp' => [
                         'format' => 'dateOptionalTime',
                         'type' => 'date'
                     ],
                     'alert_time' => [
                         'type' => 'date'
                     ],
                     'viewers' => [
                         'type' => 'integer'
                     ]
                 ]
             ]
         ]
     ]
 ];

I want to match with two differents rules. The first is : "alert when two documents have the same title but differents viewers (a number). The second is : "aler when any document has a word in his desc property. 

This is my yaml file for the second rule : 

name: My frequency rule
type: frequency
index: blog
num_events: 1
timeframe:
    minutes: 10
realert:
    minutes: 0
filter:
- query:
    query_string:
      query: "text:Elasticsearch"
alert:
 - "email"
email:
 - "elastalert@qbox.com"

The result is always :  INFO:elastalert:Queried rule Twitter frequency rule from 2017-05-29 15:33 CEST to 2017-05-29 15:48 CEST: 0 / 0 hits

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2017, 5, 29, 13, 48, 43, 478624, tzinfo=tzutc()), 'rule_name': 'Twitter frequency rule', 'starttime': datetime.datetime(2017, 5, 28, 13, 48, 43, 292388, tzinfo=tzutc()), 'endtime': datetime.datetime(2017, 5, 29, 13, 48, 43, 292388, tzinfo=tzutc()), 'time_taken': 0.18145084381103516}

**Comment by Qmando** [comment]
Can you show the full JSON source of a document you expect to match.

**Comment by anjan-cele** [comment]
Hi @Qmando 

I am getting following error: 

WARNING:elasticsearch:GET http://watchmandev:9200/jobcompletion-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.053s]
ERROR:root:Error running query: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')
WARNING:elasticsearch:POST http://watchmandev:9200/elastalert_status/elastalert_error [status:400 request:0.003s]
ERROR:root:Error writing alert info to Elasticsearch: TransportError(400, u'mapper_parsing_exception', u'failed to parse [data.query.query.bool.filter.bool.must.term]')
Traceback (most recent call last):
  File "/home/watchman/elastalert/elastalert/elastalert.py", line 1299, in writeback
    doc_type=doc_type, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 300, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 89, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 124, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse [data.query.query.bool.filter.bool.must.term]')


My rule is like :

name: Example NRG Success frequency rule

type: frequency

index: jobcompletion-*

num_events: 2

timeframe:
  days: 30

filter:
- term:
	jobname:"NRG Fact Summary"

- term: 
        resulttext:"Succeeded"

alert:
- "email"

email:

- "anjan.sinha@yahoo.com"


Can we use Jobcompletion instead of logstash, if jobcompletion is working fine in Kibana UI?

Thanks

**Comment by Qmando** [comment]
It's attempting to use ``@timestamp``, the default timepicker field, but you are using something else. You need to set ``timestamp_field: time-field`` where time-field is the name of the timestamp field.

The second error indicates that it doesn't have the correct mapping for ``elastalert_status`` index. You might also need to run ``elastalert-create-index`` if you haven't already. If you already did, can you paste the index mapping so I can verify it's correct?

Thirdly, you may want to switch term to query_string, if your fields are analyzed. Like
```
filter:
- query_string:
     query: "jobname: \"NRG Fact Summary\""
```

**Comment by anjan-cele** [comment]
Hi @Qmando 

Where I need to set timestamp_field: time-field ?

If I am using jobcompletion-* instead of logstash-*, there is a field called startdt (i.e startdt:May 24th 2017, 14:06:00.000 ...format).

So what kind of format I can use because @timestamp field is not present in logstash-*.

2nd point - I think I already created index. Though is the following command is correct to check the index :

curl -XGET 'http://amdc2webl17:9200/elastalert_status/_mapping/

If I am running this then the next line is asking for some additional command.
like
>
>

Thanks
