### ISSUE TITLE
Elastalert works for every rule type except new_term rule when running as daemon

### ISSUE THREAD

**Issue by monitoringit** [Yelp/elastalert#1136]
Elastalert 0.1.12 / 0.1.14 (these versions i have tried) when running against ES 5.2.1( we are testing against this)  in daemon mode fails to load new_term rule (rules/nt.yaml) at service startup and crashes with following message:

Traceback (most recent call last):
  File "/opt/elastalert/bin/elastalert", line 11, in <module>
    sys.exit(main())
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1716, in main

2017-05-31 18:19:30,621 DEBG 'elastalert' stderr output:
    client = ElastAlerter(args)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 110, in __init__
    self.conf = load_rules(self.args)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/config.py", line 437, in load_rules

2017-05-31 18:19:30,621 DEBG 'elastalert' stderr output:
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file rules/nt.yaml: Error initializing rule ELK new user found: Error searching for existing terms: ValueError(u'Unknown string format',)

Interestingly if you drop this rule (nt.yaml) in rules folder when daemon is already running it loads fine without an issue and generates alert. Its only when rule is already present in rules folder and you try to start the service elastalert process crashes on trying to load configuration.

Also if you run elastalert NOT in daemon mode, everything works fine.
My new term rule looks like this:
(elastalert) [root@ip-10-93-73-40 rules]# cat nt.yaml
name: ELK new user found
type: new_term
index: elk_mgmt_logs-*
terms_window_size:
  minutes: 5
fields:
  - remote_user
filter:
- term:
   _type: "elk_mgmt_logs"
alert:
- sns
alert_on_missing_field: false
sns_topic_arn: "arn:aws:sns:us-east-1:xxxxxxxxxxxxx:somestring"

My config.yaml ==>
rules_folder: rules
run_every:
  minutes: 2
buffer_time:
  minutes: 3
es_host: elasticsearch.xyz.com
es_port: 443
use_ssl: True
verify_certs: True
writeback_index: elastalert_status
alert_time_limit:
  hours: 1
smtp_host: xyz.com
from_addr: abc@xyz.com

Startup script used ==>
#!/bin/bash
# elastalert   startup script for elastalert
# pidfile:           /var/run/elastalert.pid
# chkconfig: 2345 99 01

NAME=elastalert
ELASTALERT_DIR=/opt/elastalert
PIDFILE=/var/run/$NAME.pid
#ELASTALERT_USER=elastalert
ELASTALERT_USER=root
ELASTALERT_GROUP=root
CONFIG_FILE=$ELASTALERT_DIR/config.yaml
ELASTALERT=$ELASTALERT_DIR/bin/$NAME
LOGFILE=/var/log/elastalert/elastalert.log

DEFAULT=/etc/default/elastalert

if [ -r $DEFAULT ]; then
    source $DEFAULT
fi

. /etc/rc.d/init.d/functions

case $1 in
   start)
      echo -n $"Starting $NAME: "
      $ELASTALERT_DIR/bin/python $ELASTALERT_DIR/bin/elastalert-create-index --config $ELASTALERT_DIR/config.yaml --index elastalert_status --old-index NONE
      daemon --user="$ELASTALERT_USER" --pidfile="$PIDFILE" "$ELASTALERT_DIR/bin/python $ELASTALERT --config $CONFIG_FILE --start NOW --verbose>> $LOGFILE 2>&1 &"
      RETVAL=$?
      pid=`ps -ef | grep python | grep elastalert | awk '{print $2}'`
      if [ -n "$pid" ]; then
        echo $pid > "$PIDFILE"
      fi
   ;;
...
...

**Comment by Qmando** [comment]
Can you add this patch, try again, and post the new traceback?
```
diff --git a/elastalert/config.py b/elastalert/config.py
index 2b7d3c3..7234dcc 100644
--- a/elastalert/config.py
+++ b/elastalert/config.py
@@ -441,7 +441,7 @@ def load_rules(args):
             if rule['name'] in names:
                 raise EAException('Duplicate rule named %s' % (rule['name']))
         except EAException as e:
-            raise EAException('Error loading file %s: %s' % (rule_file, e))
+            raise EAException('Error loading file %s: %s' % (rule_file, e)), None, sys.exc_info()[2]
```

**Comment by monitoringit** [comment]
Here it is:
Traceback (most recent call last):
  File "/opt/elastalert/bin/elastalert", line 11, in <module>
    sys.exit(main())
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1716, in main
    client = ElastAlerter(args)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 110, in __init__
    self.conf = load_rules(self.args)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/config.py", line 433, in load_rules
    rule = load_configuration(rule_file, conf, args)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/config.py", line 108, in load_configuration
    load_modules(rule, args)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/config.py", line 315, in load_modules
    rule['type'] = rule['type'](rule, args)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/ruletypes.py", line 574, in __init__
    self.get_all_terms(args)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/ruletypes.py", line 586, in get_all_terms
    end = ts_to_dt(args.start)
  File "/opt/elastalert/local/lib/python2.7/site-packages/elastalert/util.py", line 110, in ts_to_dt
    dt = dateutil.parser.parse(timestamp)
  File "/opt/elastalert/local/lib/python2.7/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/opt/elastalert/local/lib/python2.7/site-packages/dateutil/parser.py", line 559, in parse
    raise ValueError("Unknown string format")
elastalert.util.EAException: Error loading file /opt/elastalert/rules/nt.yaml: Error initializing rule ELK new user found 0.1.14: Error searching for existing terms: ValueError(u'Unknown string format',)

**Comment by Qmando** [comment]
Ah! I missed this. new_term rule is incompatible with ``--start NOW``. Sorry about that.

An alternative, before I make a proper fix:
Instead of NOW, use `date -u +"%Y-%m-%dT%H:%M:%SZ"`

```
$ date -u +"%Y-%m-%dT%H:%M:%SZ"
2017-05-31T19:03:15Z
```

**Comment by monitoringit** [comment]
This makes sense..!! I have updated the code and it is working now...I wish we can have it documented somewhere..will save time for others. Appreciate your quick help on this!!!!!

On a separate note: Is there any regression testing down on elastalert clients from its capacity perspective? Is it recommended to have a centralized elastalert in your environment or can we deploy it on 100s of clients which will query against same ES?

**Comment by dengyun19900722** [comment]
@Qmando 
where to set the args --start `date -u +"%Y-%m-%dT%H:%M:%SZ"`

**Comment by Qmando** [comment]
The same place you'd add `--start NOW`, as a command line argument.

```
$ elastalert --verbose --start $(date -u +"%Y-%m-%dT%H:%M:%SZ")
```
