### ISSUE TITLE
UnicodeDecodeError when formatting timestamp on a French Windows system with Python 2.7

### ISSUE THREAD

**Issue by AndreLouisCaron** [Yelp/elastalert#1141]
Hi there,

I ran into this exception:

```
$ elastalert-test-rule logging\alerting\rules\errors.yaml
Successfully loaded Error logs

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
Traceback (most recent call last):
  File "...\python\2.7.8-x86\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "...\python\2.7.8-x86\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "...\Scripts\elastalert-test-rule.exe\__main__.py", line 9, in <module>
  File "...\lib\site-packages\elastalert\test_rule.py", line 322, in main
    test_instance.run_rule_test()
  File "...\lib\site-packages\elastalert\test_rule.py", line 317, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "...\lib\site-packages\elastalert\test_rule.py", line 236, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "...\lib\site-packages\elastalert\elastalert.py", line 530, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "...\lib\site-packages\elastalert\elastalert.py", line 382, in run_query
    data = self.get_hits(rule, start, end, index, scroll)
  File "...\lib\site-packages\elastalert\elastalert.py", line 266, in get_hits
    status_log = "Queried rule %s from %s to %s: %s / %s hits" % (rule['name'],
pretty_ts(starttime, lt), pretty_ts(endtime, lt), self.num_hits, len(hits))
  File "...\lib\site-packages\elastalert\util.py", line 169, in pretty_ts
    return dt.strftime('%Y-%m-%d %H:%M %Z')
  File "...\lib\site-packages\dateutil\tz\_common.py", line 21, in adjust_encoding
    name = name.encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 12: ordinal not in range(128)
```

This error occurs because `time.tzname` returns "Est (heure d'été)" which is not ASCII and this breaks the `%Z` format string.

I believe this string is correctly returned as Unicode on Python 3, so this possibly impacts only Python 2.

Obviously, I can work around this issue by providing my own format string in the configuration file.  However, one way to make it work everywhere is to use `.decode(locale.getpreferredencoding()` on the time zone name.

**Comment by nouarf** [comment]
I have the same problem. How did you resolve it ?

**Comment by AndreLouisCaron** [comment]
@nouarf I set [use_local_time](https://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=utc#use-local-time) to `false` so that I always send UTC timestamps and no time zone name is included in that format.

I happened to do this for other reasons (easier to correlate with other events in centralized logs), but it hides this issue as well.
