### ISSUE TITLE
TypeError: dist must be a Distribution instance

### ISSUE THREAD

**Issue by Dmitry1987** [Yelp/elastalert#1160]
Hi, I got an error by just following the installation procedure.
Installed the deps (using "pip install -r requirements-dev.txt") then ran: 

python setup.py build
python setup.py install

and got this:
**TypeError: dist must be a Distribution instance
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-sMqog_/jira-1.0.10/setup.cfg: TypeError: dist must be a Distribution instance**

full log:
```
Installed /usr/local/lib/python2.7/site-packages/jsonschema-2.6.0-py2.7.egg
Searching for jira>=1.0.10
Reading https://pypi.python.org/simple/jira/
Downloading https://pypi.python.org/packages/f5/d3/2301c6ada2360119b8e99187979f488e3a5b203c122dd168c9fdb2e33394/jira-1.0.10.tar.gz#md5=22c0808a1409091b08f0d13229ccec50
Best match: jira 1.0.10
Processing jira-1.0.10.tar.gz
Writing /tmp/easy_install-sMqog_/jira-1.0.10/setup.cfg
Running jira-1.0.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-sMqog_/jira-1.0.10/egg-dist-tmp-TKAZWA
zip_safe flag not set; analyzing archive contents...

Installed /tmp/easy_install-sMqog_/jira-1.0.10/.eggs/pytest_runner-2.11.1-py2.7.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/local/lib/python2.7/site-packages/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/usr/local/lib/python2.7/site-packages/pbr/util.py", line 382, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 127, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-sMqog_/jira-1.0.10/setup.cfg: TypeError: dist must be a Distribution instance

```

any idea what did I do wrong? (missing steps?)

thanks :)

**Comment by Dmitry1987** [comment]
Then tried the "pip install -r requirements.txt" (realized i might not need the '-dev' deps)
and got 
```
Installed /usr/local/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg
Processing dependencies for elastalert==0.1.14
error: cryptography 1.5.3 is installed but cryptography>=1.7 is required by set(['pyOpenSSL'])
```
what's wrong with that pip, it gets confused by itself lol... can't it resolve the correct versions for all stuff? .. silly pip...  :1st_place_medal:
