### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sLuvpreet33** [Yelp/elastalert#1195]
I have tried installing it both by git cloning and by pip.

I get the same error when installing,

This is via pip,

        creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
        build/temp.linux-x86_64-2.7/_openssl.c:434:30: fatal error: openssl/opensslv.h: No such file or directory
        compilation terminated.
        error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
        ----------------------------------------
    Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-CJ6hJi/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-M4tNRh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-CJ6hJi/cryptography/

Also, I get this error during installing requirements, 

      ----------------------------------------
      Failed building wheel for cryptography

This is via git, 

    Writing /tmp/easy_install-7OBT3N/cryptography-1.9/setup.cfg
    Running cryptography-1.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7OBT3N/cryptography-1.9/egg-dist-tmp-WdrWjU
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    build/temp.linux-x86_64-2.7/_openssl.c:434:30: fatal error: openssl/opensslv.h: No such file or directory
    compilation terminated.
    error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by Qmando** [comment]
``apt-get install libssl-dev`` or equivalent

**Comment by sLuvpreet33** [comment]
Cool ! This solved the problem.

I installed it through pip, now, where should I write rules and alerts ?

**Comment by Qmando** [comment]
Anywhere you want. You just need just a config file (https://github.com/Yelp/elastalert/blob/master/config.yaml.example) and a folder for the rules.

**Comment by sLuvpreet33** [comment]
Where do I need to copy this file ?

OR 

I have to copy this content in the /etc/elasticsearch/elasticsearch.yml file ?

**Comment by sLuvpreet33** [comment]
monitoring-server@monitoring-server:/etc/elasticsearch$ elastalert-create-index
    Traceback (most recent call last):
      File "/usr/local/bin/elastalert-create-index", line 6, in <module>
        from pkg_resources import load_entry_point
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3037, in <module>
        @_call_aside
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3021, in _call_aside
        f(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 969, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 855, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'cryptography>=1.3.4' distribution was not found and is required by twilio

**Comment by sLuvpreet33** [comment]
monitoring-server@monitoring-server:/etc/elasticsearch$ elastalert-test-rule  python -m elastalert.elastalert --verbose --rule example_rule.yaml
    Traceback (most recent call last):
      File "/usr/local/bin/elastalert-test-rule", line 6, in <module>
        from pkg_resources import load_entry_point
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3037, in <module>
        @_call_aside
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3021, in _call_aside
        f(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
        ws.require(__requires__)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 969, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 855, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'cryptography>=1.3.4' distribution was not found and is required by twilio

**Comment by sLuvpreet33** [comment]
The cryptography package was not installed properly.

Then I did 

   $ sudo apt-get install build-essential libssl-dev libffi-dev python-dev

Then installed cryptography, 

    $ sudo -H pip install cryptography

Now, the index has been created.

But still I am confused where to put that config.yaml file ?

**Comment by prayagupd** [comment]
Pretty old post, maybe it could be helpful for non python devs including myself

```
$ sudo yum -y install build-essential libssl-dev libffi-dev python-dev openssl-devel
$ sudo pip install cryptography==2.3 ## I am using 2.3 for the error was complaining required >=2.3
```
