### ISSUE TITLE
Centos Elasalert not working 

### ISSUE THREAD

**Issue by sathishdsgithub** [Yelp/elastalert#1209]
I have installed elastalert on Centos version and I get below alert while running the rule. Am i missing something ?

```
[root@elastalert]# python -m elastalert.elastalert --verbose --rule Srx_port_scan.yaml
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.10.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/elastalert/elastalert/elastalert.py", line 18, in <module>
    import kibana
  File "elastalert/kibana.py", line 4, in <module>
    from util import EAException
  File "elastalert/util.py", line 8, in <module>
    from auth import Auth
  File "elastalert/auth.py", line 4, in <module>
    from aws_requests_auth.aws_auth import AWSRequestsAuth
  File "build/bdist.linux-x86_64/egg/aws_requests_auth/aws_auth.py", line 13, in <module>
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 90, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
```

**Comment by Qmando** [comment]
Can you report what ``pip freeze | grep urllib3`` says?

You can fix this by upgrading (or downgrading maybe?) urllib3. Here's a version I know works:
``pip install "urllib3==1.7.1"``

**Comment by sathishdsgithub** [comment]
The issue got resolved after applying the below command . Thanks

`pip install --upgrade urllib3`
