### ISSUE TITLE
429 error while writing alert info to Elastic

### ISSUE THREAD

**Issue by wittyameta** [Yelp/elastalert#1228]
```
ERROR:root:Error writing alert info to Elasticsearch: TransportError(429, u'es_rejected_execution_exception', u'rejected execution of org.elasticsearch.transport.TransportService$7@45aee1f0 on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@1c160c25[Running, pool size = 8, active threads = 8, queued tasks = 490, completed tasks = 490248830]]')
Traceback (most recent call last):
  File "/home/elastalert/elastalert/elastalert/elastalert.py", line 1299, in writeback
    doc_type=doc_type, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 298, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
TransportError: TransportError(429, u'es_rejected_execution_exception', u'rejected execution of org.elasticsearch.transport.TransportService$7@45aee1f0 on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@1c160c25[Running, pool size = 8, active threads = 8, queued tasks = 490, completed tasks = 490248830]]')
```

**Comment by liketic** [comment]
@Qmando Can I contribute to this? and this repo? Thanks in advance. 😃

**Comment by Qmando** [comment]
@liketic Of course
