### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'blist>=1.3.6' distribution was not found and is required by elastalert

### ISSUE THREAD

**Issue by anjan-cele** [Yelp/elastalert#1233]
Hi @Qmando 

Whenever I am running my test example i.e example_frequency. I am getting following error :

Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'blist>=1.3.6' distribution was not found and is required by elastalert

However

When I check for 'blist>=1.3.6' installation. It is telling as : 

Requirement already satisfied: blist>=1.3.6 in /usr/local/lib/python3.5/dist-packages

What could be the problem?

**Comment by Qmando** [comment]
``Requirement already satisfied: blist>=1.3.6 in /usr/local/lib/python3.5/dist-packages``
python3.5

```
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 829, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'blist>=1.3.6' distribution was not found and is required by elastalert
```
python2.7

You need to install blist for python2.7. Try ``pip2 install blist==1.3.6``

**Comment by ashishkaransingh** [comment]
Hi,

Can anyone help me on this.
I have python 3 installed.

**Comment by nsano-rururu** [comment]
@ashishkaransingh 

1. Have the following items been installed?

Packages on Ubuntu 18.x: build-essential python3-pip python3.6 python3.6-dev libffi-dev libssl-dev
Packages on Ubuntu 20.x: build-essential python3-pip python3.6 python3.6-dev libffi-dev libssl-dev
Packages on CentOS 7.x: 'Development Tools' python3-pip python36 python3-devel python3-libs python3-setuptools libffi-devel openssl-devel
Packages on CentOS 8.x: 'Development Tools' python3-pip python36 python3-devel python3-setuptools python3-libs libffi-devel openssl-devel

2. install

```
# Python3 Create virtual environment
python3 -m venv ~/elastalertvenv/

# Python3 Virtual environment switching
source ~/elastalertvenv/bin/activate
```
https://github.com/Yelp/elastalert#running-elastalert
>Running ElastAlert
>You can either install the latest released version of ElastAlert using pip:
>
>pip install elastalert
>
>or you can clone the ElastAlert repository for the most recent changes:
>
>git clone https://github.com/Yelp/elastalert.git
>
>Install the module:
>
>pip install "setuptools>=11.3"
>
>python setup.py install
