### ISSUE TITLE
Could not import module %s: %s" % (module_name, e)

### ISSUE THREAD

**Issue by anjan-cele** [Yelp/elastalert#1242]
Hi @Qmando 

I am getting following error when I ran the rule i.e elastalert-test-rule example_rules/example_frequency.yaml

Can you please help me.
Thanks

Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.18', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/elastalert-0.1.18-py3.5.egg/elastalert/test_rule.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/elastalert-0.1.18-py3.5.egg/elastalert/config.py", line 96
    raise EAException("Could not import module %s: %s" % (module_name, e)), None, sys.exc_info()[2]
                                                                          ^
SyntaxError: invalid syntax

**Comment by Qmando** [comment]
Don't use Python 3
