### ISSUE TITLE
HTTP POST Alerter: elastalert.util.EAException: Error initiating alert post: Could not import module post: need more than 1 value to unpack

### ISSUE THREAD

**Issue by av3ri** [Yelp/elastalert#1257]
Hi Guys,
Just want to start by saying thanks for this awesome tool.
I have been trying to setup a HTTP Post Alerter and keep getting a similar error to this  #1246. 
The alert rule below, I am trying to setup works fine with the alert type email just for context.

The webhook http://myendpoint.com/hook is just a basic endpoint that accepts a JSON payload.

````
name: Heartbeat
type: frequency
index: beat*

num_events: 4
timeframe:
  minutes: 5

query_key: metadata.hostname

filter:
  - query:
       query_string:
         query: "ping.value: 0"

realert:
  minutes: 10

alert: "post"
http_post_url: "http://myendpoint.com/hook"
````
I get the following output when I try to test the rule using elastalert-test-rule

`(venv) [root@alert elastalert]# elastalert-test-rule alert_rules/heartbeat.yaml`

```
Traceback (most recent call last):
  File "/opt/elastalert/venv/bin/elastalert-test-rule", line 11, in <module>
    sys.exit(main())
  File "/opt/elastalert/venv/lib/python2.7/site-packages/elastalert/test_rule.py", line 374, in main
    test_instance.run_rule_test()
  File "/opt/elastalert/venv/lib/python2.7/site-packages/elastalert/test_rule.py", line 369, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/opt/elastalert/venv/lib/python2.7/site-packages/elastalert/test_rule.py", line 207, in run_elastalert
    load_modules(rule)
  File "/opt/elastalert/venv/lib/python2.7/site-packages/elastalert/config.py", line 335, in load_modules
    rule['alert'] = load_alerts(rule, alert_field=rule['alert'])
  File "/opt/elastalert/venv/lib/python2.7/site-packages/elastalert/config.py", line 393, in load_alerts
    alert_field = [create_alert(a, b) for a, b in alert_field]
  File "/opt/elastalert/venv/lib/python2.7/site-packages/elastalert/config.py", line 378, in create_alert
    alert_class = alerts_mapping.get(alert) or get_module(alert)
  File "/opt/elastalert/venv/lib/python2.7/site-packages/elastalert/config.py", line 92, in get_module
    module_path, module_class = module_name.rsplit('.', 1)
elastalert.util.EAException: Error initiating alert post: Could not import module post: need more than 1 value to unpack
```

Any assistance on the above would be greatly appreciated. If there is a mistake in the way I am setting up the alert rule please let me know. I was following the basic directions from the DOC.

Thanks.

**Comment by Qmando** [comment]
You'll need the most recent version of elastalert to use the post alerter. v0.1.18

**Comment by av3ri** [comment]
@Qmando oh gosh I feel silly! Yes this definitely was the issue. It started working when I used "simple" instead of "post" as the alert method. Do you know if there is a -version command that I can use to quickly check the version for future?
