### ISSUE TITLE
remove_old_events not working with custom timestamp

### ISSUE THREAD

**Issue by mza97** [Yelp/elastalert#1258]
I have a rule with a custom timestamp format:
```
timestamp_type: custom
timestamp_format: '%Y-%m-%dT%H:%M:%S.000Z'
```

and I get this:

```
ERROR:root:Uncaught exception running rule ruletest : unsupported operand type(s) for -: 'unicode' and 'unicode'
INFO:elastalert:Rule ruletest disabled
Traceback (most recent call last):
  File "/usr/bin/elastalert", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 1777, in main
    client.start()
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 997, in start
    self.run_all_rules()
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 1088, in run_all_rules
    self.remove_old_events(rule)
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 547, in remove_old_events
    if now - timestamp > buffer_time:
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'unicode'
```

**Comment by mza97** [comment]
I added this and it's working
```
            if isinstance(timestamp, unicode):
                timestamp = parser.parse(timestamp)
```

**Comment by Qmando** [comment]
To which line? In ``remove_old_events``?

I haven't seen this bug before. Does your ``timestamp_field`` contain dots?

These two lines are supposed to convert everything in ``processed_hits`` to have a datetime object rather than a string timestamp.
https://github.com/Yelp/elastalert/blob/5ff411d8a48124185ff3e1d3300b571b05fb142b/elastalert/elastalert.py#L306

**Comment by mza97** [comment]
Sorry for the late response; yes it contains dot  ``` "@timestamp": "2017-08-01T00:00:00.000Z" ```

I implemented a rule type that can compare three events by a field (which have the same timestamp) based on the frequency one, and I had the same problem too in the add_data function:

```
    def add_data(self, data):
        if 'query_key' in self.rules:
            qk = self.rules['query_key']
        else:
            qk = None

        for event in data:
            if qk:
                key = hashable(lookup_es_key(event, qk))
            else:
                # If no query_key, we use the key 'all' for all events
                key = 'all'

            # Store the timestamps of recent occurrences, per key
            if isinstance(event['@timestamp'], unicode):
                event['@timestamp'] = parser.parse(event['@timestamp'])
            self.occurrences.setdefault(key, EventWindow(self.rules['timeframe'], getTimestamp=self.get_ts)).append((event, 1))
            self.check_for_match(key, end=False)
```

I think it's my timestamp format config that is not good
