### ISSUE TITLE
Can't create index

### ISSUE THREAD

**Issue by michaelcoll** [Yelp/elastalert#1325]
Hi,

I've just installed elastalert with pip.

After installation I've launch the initial index creation with the `elastalert-create-index` command and I got the exception :

```
Traceback (most recent call last):                                                                                       
  File "/usr/local/bin/elastalert-create-index", line 9, in <module>                                                     
    load_entry_point('elastalert==0.1.20', 'console_scripts', 'elastalert-create-index')()                               
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.20-py2.7.egg/elastalert/create_index.py", line 77, in main 
    username = args.username if args.username else data.get('es_username')                                               
UnboundLocalError: local variable 'data' referenced before assignment
```

My elastic search node is on localhost with port 9200.

BTW I've tried with the 0.1.20 release too.

**Comment by michaelcoll** [comment]
I've find out, while editing the file `create_index.py`, that the script NEEDS the config.yaml file and without that it can't initialize the `data` value.

So I've _fixed_ the problem by renaming the provided `config.yaml.example` to `config.yaml`, edit it and adapt the parameters to my needs.

So it was my fault :) but maybe a clearer error message could have help a bit :)

Bye

**Comment by garthompson** [comment]
I've just hit this issue also, and resolved it by using the `--config` parameter. It would be useful if the documentation mentioned it to avoid having to dig through the code.
