### ISSUE TITLE
change type rule  error

### ISSUE THREAD

**Issue by rubenrodr-versia** [Yelp/elastalert#1337]
Hi,

I have the following rule to search for field "name" with value "fichero_hosts_sha256_system32" and alert everytime the field "columns.sha256" changes:

`es_host: X.X.X.X`
`es_port: 9200`
`name: Regla - Modificacion fichero hosts`
`type: change`
`index: osquery-*`
`filter:`
` - term:`
`    name: fichero_hosts_sha256_system32`
`query_key: columns.path`
`compare_key: columns.sha256`
`realert:`
` minutes: 0`
`timeframe:`
`  hours: 24`
`alert:`
`- "email"`

An running the rule in debug mode:

`# python /opt/elastalert/elastalert/elastalert.py --config /opt/elastalert/config.yaml --verbose --rule /opt/elastalert/reglas/test.yaml`

i get the error:

`INFO:elastalert:Starting up`
`INFO:elastalert:Queried rule Regla - Modificacion fichero hosts from 2017-09-15 11:22 CEST to 2017-09-15 11:37 CEST: 1 / 1 hits`
`ERROR:root:Traceback (most recent call last):`
`  File "/opt/elastalert/elastalert/elastalert.py", line 1245, in alert`
`    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)`
`  File "/opt/elastalert/elastalert/elastalert.py", line 1325, in send_alert`
`    alert.alert(matches)`
`  File "/opt/elastalert/elastalert/alerts.py", line 412, in alert`
`    email_msg['Subject'] = self.create_title(matches)`
`  File "/opt/elastalert/elastalert/alerts.py", line 214, in create_title`
`    return self.create_custom_title(matches)`
`  File "/opt/elastalert/elastalert/alerts.py", line 235, in create_custom_title`
`    return alert_subject.format(*alert_subject_values)`
`IndexError: tuple index out of range`

Thanks.

**Comment by rubenrodr-versia** [comment]
Solved using query instead of term

`es_host: X.X.X.X`
`es_port: 9200`

`name: Regla - Modificacion ficheros en carpeta /etc/apt`
`type: change`
`realert:`
` minutes: 0`
`index: osquery-*`
`compare_key: columns.sha256`
`ignore_null: true`
`query_key: columns.path,host`
`timeframe:`
`  days: 10`
`filter:`
`- query:`
`    query_string:`
`      query: "name: Modificacion_ficheros_directorio_etc_apt_LINUX"`
