### ISSUE TITLE
my enhancements no module found

### ISSUE THREAD

**Issue by Mokatsu** [Yelp/elastalert#1344]
This is the error i get when i run elastalert-test-rule with "match_enhancements"
`Traceback (most recent call last):
  File "/etc/elastalert/elastalertenv/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.14', 'console_scripts', 'elastalert-test-rule')()
  File "/etc/elastalert/elastalertenv/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/test_rule.py", line 358, in main
    test_instance.run_rule_test()
  File "/etc/elastalert/elastalertenv/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/test_rule.py", line 353, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/etc/elastalert/elastalertenv/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/test_rule.py", line 199, in run_elastalert
    load_modules(rule)
  File "/etc/elastalert/elastalertenv/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/config.py", line 294, in load_modules
    enhancement = get_module(enhancement_name)
  File "/etc/elastalert/elastalertenv/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/config.py", line 92, in get_module
    base_module = __import__(module_path, globals(), locals(), [module_class])
elastalert.util.EAException: Could not import module elastalert_modules.my_enhancements.WeekdayAlertOnly: No module named elastalert_modules.my_enhancements`

the yaml file contains the flag : 
match_enhancements:
- "elastalert_modules.my_enhancements.WeekdayAlertOnly"

within the elastalert_modues i have an __init__.py file and my_enhancements.py file with the code taken from the guide (slightly edited)

**Comment by shweta1202** [comment]
@Mokatsu: even I'm facing the same issue, can you help on how you solved it?
