### ISSUE TITLE
enhancement not found when using match_enhancement in yaml file

### ISSUE THREAD

**Issue by Mokatsu** [Yelp/elastalert#1356]
Hi, when i use the match_enhancement flag with in a rule, I get this after following the guide within the elastalert docs:

This is the error i get when i run elastalert-test-rule with "match_enhancements"
Traceback (most recent call last): File "/etc/elastalert/elastalertenv/bin/elastalert-test-rule", line 11, in <module> load_entry_point('elastalert==0.1.14', 'console_scripts', 'elastalert-test-rule')() File "/etc/elastalert/elastalertenv/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/test_rule.py", line 358, in main test_instance.run_rule_test() File "/etc/elastalert/elastalertenv/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/test_rule.py", line 353, in run_rule_test self.run_elastalert(rule_yaml, conf, args) File "/etc/elastalert/elastalertenv/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/test_rule.py", line 199, in run_elastalert load_modules(rule) File "/etc/elastalert/elastalertenv/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/config.py", line 294, in load_modules enhancement = get_module(enhancement_name) File "/etc/elastalert/elastalertenv/lib/python2.7/site-packages/elastalert-0.1.14-py2.7.egg/elastalert/config.py", line 92, in get_module base_module = __import__(module_path, globals(), locals(), [module_class]) elastalert.util.EAException: Could not import module elastalert_modules.my_enhancements.WeekdayAlertOnly: No module named elastalert_modules.my_enhancements

the yaml file contains the flag :
match_enhancements:

    "elastalert_modules.my_enhancements.WeekdayAlertOnly"

within the elastalert_modues i have an init.py file and my_enhancements.py file with the code taken from the guide (slightly edited)

**Comment by Qmando** [comment]
Make sure that you are running elastalert from the directory with elastalert_modules folder. You can then try setting your PYTHONPATH variable.
```
$ PYTHONPATH=`pwd`:$PYTHONPATH
```

You should be able to run python and run ```from elastalert_modules.my_enhancements import WeekdayAlertOnly``` without any errors.

**Comment by Mokatsu** [comment]
So will the elastalert-test-rule script not work when using enhancements?

**Comment by Qmando** [comment]
It should still work. There might be some difference in terms of PYTHONPATH whether you run ``$ elastalert-test-rule`` versus ``$ python -m elastalert.test_rule``, I would try both because I can't remember what the exact nuances of importing, entrypoints and cwd are. In either case, the PYTHONPATH variable should allow you to run it from whatever directory you want.

**Comment by Qmando** [comment]
The modules folder needs to be in the current directory, not in elastalert. 

CWD
-> elastalert
     -> elastalert.py
     ...
-> elastalert_modules
     -> my_enhancements.py

NOT
CWD
-> elastalert
     -> elastalert.py
     -> elastalert_modules
          -> my_enhancements.py

bearing in mind that if you cloned versus pip installed elastalert, there's two folders in a row named "elastalert", it just shouldn't be in the one with the .py files.

**Comment by DravenJohnson** [comment]
Is this changed recently? I can `python -c "from elastalert_modules.my_enhancements import WeekdayAlertOnly"` and the `elastalert_modules` is in the current directory.

However, `python elastalert/elastalert.py --verbose --config config.yaml` shows `No module named elastalert_modules.my_enhancements` error.

**Comment by Qmando** [comment]
Try ``python -m elastalert.elastalert --verbose --config config.yaml``
