### ISSUE TITLE
Issue starting the elastalert

### ISSUE THREAD

**Issue by hsafe** [Yelp/elastalert#1383]
Hi,
I have  followed the online doc section to install elastalert through the python-pip method in an already set up elk stack Centos7. The issues I faced: a. there is no directory with the common script/configs
b. When I git clone the source and modified the config file and sample example_frequency.yaml file I face with the below issue:

> Traceback (most recent call last):
  File "/usr/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert==0.1.21', 'console_scripts', 'elastalert')()
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 1803, in main
    client = ElastAlerter(args)
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 129, in __init__
    self.conf = load_rules(self.args)
  File "/usr/lib/python2.7/site-packages/elastalert/config.py", line 461, in load_rules
    rule = load_configuration(rule_file, conf, args)
  File "/usr/lib/python2.7/site-packages/elastalert/config.py", line 110, in load_configuration
    rule = load_rule_yaml(filename)
  File "/usr/lib/python2.7/site-packages/elastalert/config.py", line 123, in load_rule_yaml
    loaded = yaml_loader(filename)
  File "/usr/lib/python2.7/site-packages/staticconf/loader.py", line 168, in yaml_loader
    return yaml.load(fh, Loader=SafeLoader) or {}
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "/tmp/elastalert/example_rules/example_frequency.yaml", line 15, column 1

> 
I wonder what went wrong. Your help is appreciated...

**Comment by Qmando** [comment]
You have invalid YAML on line 15 of example_frequency.yaml
