### ISSUE TITLE
displaying custom timezone in alert text got error

### ISSUE THREAD

**Issue by khejing** [Yelp/elastalert#1385]
I've already done #861, but there still problems. After using time enhancement, I can receive right time in alert text, but elastalert print error:
ERROR:root:Error writing alert info to Elasticsearch: TransportError(400, u'mapper_parsing_exception', u'failed to parse [match_time]')
Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 1385, in writeback
    doc_type=doc_type, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch-5.4.0-py2.7.egg/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch-5.4.0-py2.7.egg/elasticsearch/client/__init__.py", line 298, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch-5.4.0-py2.7.egg/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch-5.4.0-py2.7.egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch-5.4.0-py2.7.egg/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse [match_time]')

**Comment by keyolk** [comment]
I have same issue,

```
ERROR:root:Error writing alert info to Elasticsearch: TransportError(400, u'mapper_parsing_exception', u'failed to parse [match_time]')
Traceback (most recent call last):
  File "/home1/irteam/naver/profile/keyolk/.local/lib64/python2.7/site-packages/elastalert/elastalert.py", line 1385, in writeback
    doc_type=doc_type, body=body)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elasticsearch/client/__init__.py", line 298, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse [match_time]')
WARNING:elasticsearch:POST http://staging.logiss.navercorp.com:29200/elastalert_status/elastalert [status:400 request:0.009s]
ERROR:root:Error writing alert info to Elasticsearch: TransportError(400, u'mapper_parsing_exception', u'failed to parse [match_time]')
Traceback (most recent call last):
  File "/home1/irteam/naver/profile/keyolk/.local/lib64/python2.7/site-packages/elastalert/elastalert.py", line 1385, in writeback
    doc_type=doc_type, body=body)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elasticsearch/client/__init__.py", line 298, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse [match_time]')
```
and more ...
```
INFO:elastalert:Sleeping for 9.943924 seconds
ERROR:root:Traceback (most recent call last):
  File "/home1/irteam/naver/profile/keyolk/.local/lib64/python2.7/site-packages/elastalert/elastalert.py", line 1245, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/home1/irteam/naver/profile/keyolk/.local/lib64/python2.7/site-packages/elastalert/elastalert.py", line 1325, in send_alert
    alert.alert(matches)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elastalert/alerts.py", line 392, in alert
    body = self.create_alert_body(matches)
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elastalert/alerts.py", line 242, in create_alert_body
    body += unicode(BasicMatchString(self.rule, match))
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elastalert/alerts.py", line 135, in __str__
    self._add_custom_alert_text()
  File "/home1/irteam/profile/keyolk/.local/lib64/python2.7/site-packages/elastalert/alerts.py", line 72, in _add_custom_alert_text
    alert_text = alert_text.format(*alert_text_values)
IndexError: tuple index out of range
```

**Comment by Qmando** [comment]
For the first error, change the name of the new field from ``@timestamp`` to ``local-timestamp`` or something, and use that in the ``alert_text`` instead.

The second error posted is because the number of alert_text_values doesn't match the number of {}'s in alert_text.

**Comment by khejing** [comment]
@Qmando It works! Thank you so much!

**Comment by VolodymyrPerlovskiy** [comment]
Hello,
    How the rule extension look like in first case: 
"For the first error, change the name of the new field from @timestamp to local-timestamp or something, and use that in the alert_text instead."
In other words, how store timestamp in new field ES?
In Python ...

Tell me Please!

**Comment by Qmando** [comment]
Assuming your enhancement code is 
```
from elastalert.util import pretty_ts
from elastalert.enhancements import BaseEnhancement


class TimeEnhancement(BaseEnhancement):
    def process(self, match):
        for k, v in match.items():
            if isinstance(v, basestring) and v.endswith('Z'):
                try:
                    match[k] = pretty_ts(v)
                except:
                    pass
```


Change the line

```
                    match[k] = pretty_ts(v)
```
to
```
                    match['local-timestamp'] = pretty_ts(v)
```

then add that to alert text
```
alert_text: "The alert occured at {}"
alert_text_args: [local-timestamp]
```

**Comment by VolodymyrPerlovskiy** [comment]
Thank you very much )
