### ISSUE TITLE
Elastalert query issues

### ISSUE THREAD

**Issue by zozo6015** [Yelp/elastalert#1398]
Hello,

I have created a frequency alert using the example which looks like this:

    es_host: 172.16.99.5
    es_port: 9200
    index: heartbeat-*
    type: frequency
    timeframe:
      minutes: 1
    num_events: 1
    filter:
    - term:
        monitor.status: "down"
    - term:
        NOT http.response.status: "200"
    alert:
    - "email"
    email:
    - "email@example.com

when I run the rule in  elastalert-test-rule I get the following output: 

    WARNING:elasticsearch:GET http://172.16.99.5:9200/heartbeat-*/_search?ignore_unavailable=true&size=1 [status:400 request:0.001s]
    Error running your filter:
    RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [filtered]', u'type': u'parsing_exception', u'line': 1, u'col': 68}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [filtered]', u'col': 68}})
    INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
    WARNING:elasticsearch:GET http://172.16.99.5:9200/heartbeat-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.001s]
    ERROR:root:Error running query: TransportError(400, u'parsing_exception', u'no [query] registered for [filtered]')

    Would have written the following documents to writeback index (default is elastalert_status):

    elastalert_error - {'message': "Error running query: TransportError(400, u'parsing_exception', u'no [query] registered for [filtered]')", 'traceback': ['Traceback (most recent call last):', '  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/elastalert.py", line 369, in get_hits', '    **extra_args', '  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 623, in search', "    doc_type, '_search'), params=params, body=body)", '  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request', '    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: TransportError(400, u'parsing_exception', u'no [query] registered for [filtered]')"], 'data': {'query': {'sort': [{'@timestamp': {'order': 'asc'}}], 'query': {'filtered': {'filter': {'bool': {'must': [{'range': {'@timestamp': {'gt': '2017-10-23T21:03:22.085510Z', 'lte': '2017-10-23T21:18:22.085510Z'}}}, {'term': {'monitor.status': 'down'}}, {'term': {'NOT http.response.status': '200'}}]}}}}}, 'rule': 'rules/test'}}

Please help me figure out where the problem is so that I can have it up and running and continue my testing.

Thanks in advance

**Comment by GRomR1** [comment]
I've the same error

**Comment by piercarlomacca** [comment]
Same here with Elastic 6.1.1 and Elastalert 0.1.26 with the same alert

**Comment by Swashy** [comment]
Same:
`RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [filtered]', u'type': u'parsing_exception', u'line': 1, u'col': 62}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [filtered]', u'col': 62}})
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
^CTraceback (most recent call last):
  File "/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.27', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.7/site-packages/elastalert/test_rule.py", line 378, in main
    test_instance.run_rule_test()
  File "/usr/lib/python2.7/site-packages/elastalert/test_rule.py", line 373, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/lib/python2.7/site-packages/elastalert/test_rule.py", line 269, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 806, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 599, in run_query
    data = self.get_hits_terms(rule, start, end, index, rule['query_key'])
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 495, in get_hits_terms
    res = self.current_es.search(index=index, doc_type=rule['doc_type'], body=query, size=0, ignore_unavailable=True)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 636, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 76, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)`

**Comment by Stono** [comment]
Ditto, also getting this problem.

**Comment by samiujan** [comment]
same here - ES 6.1.2

**Comment by BoyCook** [comment]
Same here ES 6.2.2 EA 0.1.29
@yelp any update on this please?

**Comment by sqanto** [comment]
Same

 ProcessController:  ERROR:root:Error writing alert info to Elasticsearch: TransportError(400, u'illegal_argument_exception', u'Rejecting mapping update to [elastalert_status] as the final mapping would have more than 1 type: [elastalert_error, elastalert_status]')
