### ISSUE TITLE
Problem when running elastalert-create-index

### ISSUE THREAD

**Issue by Demantel2016** [Yelp/elastalert#1425]
I am using windows 10 powershell to run it.
When i run code i got error as below. Please help.

PS C:\Users\smiforce-2ndPC\Downloads\Compressed\elastalert-master\elastalert-master> elastalert-create-index
Traceback (most recent call last):
  File "C:\Users\smiforce-2ndPC\AppData\Local\Programs\Python\Python36-32\Scripts\elastalert-create-index-script.py", line 11, in <module>
    load_entry_point('elastalert==0.1.21', 'console_scripts', 'elastalert-create-index')()
  File "c:\users\smiforce-2ndpc\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\smiforce-2ndpc\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2769, in load_entry_point
    return ep.load()
  File "c:\users\smiforce-2ndpc\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2422, in load
    return self.resolve()
  File "c:\users\smiforce-2ndpc\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2428, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\smiforce-2ndpc\appdata\local\programs\python\python36-32\lib\site-packages\elastalert\create_index.py", line 12, in <module>
    from auth import Auth
ModuleNotFoundError: No module named 'auth'
PS C:\Users\smiforce-2ndPC\Downloads\Compressed\elastalert-master\elastalert-master> python -m elastalert.elastalert --verbose --config config.yaml
Traceback (most recent call last):
  File "C:\Users\smiforce-2ndPC\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\smiforce-2ndPC\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\smiforce-2ndPC\Downloads\Compressed\elastalert-master\elastalert-master\elastalert\elastalert.py", line 1210
    raise EAException("Error querying for dashboard: %s" % (e)), None, sys.exc_info()[2]
                                                               ^
SyntaxError: invalid syntax

**Comment by Qmando** [comment]
Use python 2 not 3

**Comment by Demantel2016** [comment]
Why ? Isn't it possible to run Elasalert on Python 3 ?

**Comment by Demantel2016** [comment]
I installed python 2. Now i created index.
when i ran the test rule i got another error

PS C:\Users\smiforce-2ndPC\Downloads\Compressed\elastalert-master\elastalert-master> elastalert-test-rule alert_rules/frequency.yaml
Traceback (most recent call last):
  File "C:\Python27\Scripts\elastalert-test-rule-script.py", line 11, in <module>
    load_entry_point('elastalert==0.1.21', 'console_scripts', 'elastalert-test-rule')()
  File "c:\python27\lib\site-packages\elastalert\test_rule.py", line 374, in main
    test_instance.run_rule_test()
  File "c:\python27\lib\site-packages\elastalert\test_rule.py", line 353, in run_rule_test
    rule_yaml = load_rule_yaml(args.file)
  File "c:\python27\lib\site-packages\elastalert\config.py", line 123, in load_rule_yaml
    loaded = yaml_loader(filename)
  File "c:\python27\lib\site-packages\staticconf\loader.py", line 168, in yaml_loader
    return yaml.load(fh, Loader=SafeLoader) or {}
  File "c:\python27\lib\site-packages\yaml\__init__.py", line 71, in load
    return loader.get_single_data()
  File "c:\python27\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "ext\_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext\_yaml.c:9666)
  File "ext\_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext\_yaml.c:9973)
  File "ext\_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext\_yaml.c:10862)
  File "ext\_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node (ext\_yaml.c:12678)
  File "ext\_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext\_yaml.c:12854)
yaml.parser.ParserError: while parsing a block mapping
  in "alert_rules/frequency.yaml", line 20, column 1
did not find expected key
  in "alert_rules/frequency.yaml", line 58, column 3
