### ISSUE TITLE
Email sending error in elastalert

### ISSUE THREAD

**Issue by Demantel2016** [Yelp/elastalert#1430]
i got gmail authentication error. my config and error message as below
I already allowed less secure apps in gmail.

email:
"to_address@gmail.com"

smtp_host: "smtp.gmail.com"
smtp_port: "465"
smtp_ssl: true
from_addr: "from_address@gmail.com"

user: "from_address@gmail.com"
password: "password"

PS C:\Users\smiforce-2ndPC\Downloads\Compressed\elastalert-master\elastalert-master> python -m elastalert.elastalert --verbose --config ./config.yaml --rule ./alert_rules/frequency4.yaml
INFO:elastalert:Starting up
INFO:elastalert:Queried rule frequency_rule4 from 2017-11-20 09:48 Central Standard Time to 2017-11-21 09:48 Central Standard Time: 24 / 24 hits
ERROR:root:Traceback (most recent call last):
File "C:\Users\smiforce-2ndPC\Downloads\Compressed\elastalert-master\elastalert-master\elastalert\elastalert.py", line 1246, in alert
return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
File "C:\Users\smiforce-2ndPC\Downloads\Compressed\elastalert-master\elastalert-master\elastalert\elastalert.py", line 1326, in send_alert
alert.alert(matches)
File "elastalert\alerts.py", line 451, in alert
self.smtp.sendmail(self.from_addr, to_addr, email_msg.as_string())
File "C:\Python27\lib\smtplib.py", line 737, in sendmail
raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1 https://support.google.com/mail/?p=WantAuthError l4sm636961ioc.69 - gsmtp', 'test@gmail.com')

ERROR:root:Uncaught exception running rule frequency_rule4: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1 https://support.google.com/mail/?p=WantAuthError l4sm636961ioc.69 - gsmt

**Comment by nsano-rururu** [comment]
Launch a web browser on the terminal running ElastAlert, access the Google settings screen, go to the Google account → App that can access the account → Allow less secure apps: Disable → Change to enable. When I specified the Gmail address with from_addr and confirmed the operation, it worked normally.

![1](https://user-images.githubusercontent.com/22293449/99170784-c3bdef80-274a-11eb-81c9-3fa2f85399c2.PNG)
![2](https://user-images.githubusercontent.com/22293449/99170826-c6b8e000-274a-11eb-8da4-caf08992cf85.PNG)
![キャプチャ](https://user-images.githubusercontent.com/22293449/99170853-c882a380-274a-11eb-9212-14fc09e82e45.PNG)

**smtp_port: 465**

```yaml
smtp_host: "smtp.gmail.com" 
smtp_port: 465 
smtp_ssl: true
smtp_auth_file: '/opt/elastalert/smtp/smtp_auth_user.yaml"
```

smtp_auth_user.yaml

```yaml
user: xxx@gmail
password: xxx
```
