### ISSUE TITLE
Error on Testing New aggregation Rule

### ISSUE THREAD

**Issue by Chadders13** [Yelp/elastalert#1431]
Try to create an aggregation rule to show a heartbeat and keep getting an error on testing the rule. I'm hoping its something simple that I have missed.

Below is the error i'm getting:

```Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.21', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/test_rule.py", line 378, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/test_rule.py", line 373, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/test_rule.py", line 269, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/elastalert.py", line 839, in run_rule
    self.add_aggregated_alert(match, rule)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/elastalert.py", line 1595, in add_aggregated_alert
    alert_body = self.get_alert_body(match, rule, False, alert_time)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/elastalert.py", line 1351, in get_alert_body
    'alert_info': rule['alert'][0].get_info(),
AttributeError: 'str' object has no attribute 'get_info'
```
I am running this command 

` elastalert-test-rule /home/*******/elastalert/elastalert/my-rule-set/heartbeat.yaml`

This is my rules code (Currently i'm just doing a count of selected users over an hour to test it):

``` 
import dateutil.parser

from elastalert.ruletypes import RuleType

from elastalert.util import ts_to_dt

class HeartBeatRule(RuleType):

    required_options = set(['usernames'])

    def add_data(self, data):
        count = 0
        matchItem = {}

        for username in self.rules['usernames']:
            matchItem[username] = 0

        for document in data:
            matchUsername = document['username']
            if matchUsername in self.rules['usernames']:
                loginTime = document['errorTime'].time()
                matchItem[matchUsername] = matchItem[matchUsername] + 1

        for key in matchItem.keys():
            item = {"username":key,"count":matchItem[key]}
            self.add_match(item)

    def get_match_str(self,match):
        #return "%s they are very trying(%s) back again " % (match['username'],match['count'])
        return "Yo it's here"

    def garbage_collect(self, timestamp):
        pass

```

and finally this is my config :

```
name: "Heart beat"

type: "elastalert_modules.heartbeatRules.HeartBeatRule"

index: error-*

timestamp_field : errorTime

usernames:
- hacker101
- cat1997
- dog1665

inculde:
- username

aggregation:
  schedule: '00 0/1 * * MON-FRI'

aggregate_by_match_time: True

aggregation_key: 'username'

summary_table_fields:
- count
- username

alert:
- "slack"

slack_webhook_url : "**************************"
slack_msg_color : good

```
#### not induced the sensitive web hook information for obvious reasons 🙈

**Comment by mrbobcode** [comment]
I had this same issue, mine only had an error when running it with --debug flag

**Comment by Qmando** [comment]
This bug was introduced by #1413. I'll try have a fix up shortly.

**Comment by bcbeck** [comment]
Any news on the fix for this?  I sorely miss being able to use debug mode.

**Comment by Qmando** [comment]
@bcbeck 

Just added the fix. Sorry about that.

**Comment by bcbeck** [comment]
@Qmando - Wow!  I couldn't get a patch from someone on my own team as fast as you did that.  Problem solved.  Thanks.
