### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get_info'

### ISSUE THREAD

**Issue by mrbobcode** [Yelp/elastalert#1432]
Hi,

I am using the latest revision from the GIT repo, I have tested it with the aggregation option but am receiving the error below. I have tried a few different rule types and default alerting or custom alerting. I can't work out what it is, I removed the get_info() function off the 'rule['alert'][0]' and it works without an error. But this doesn't fix the bug, it also does not appear to be an issue when not using aggregation.

 customer `ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/elastalert.py", line 1079, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/elastalert.py", line 839, in run_rule
    self.add_aggregated_alert(match, rule)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/elastalert.py", line 1594, in add_aggregated_alert
    alert_body = self.get_alert_body(match, rule, False, alert_time)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.21-py2.7.egg/elastalert/elastalert.py", line 1350, in get_alert_body
    'alert_info': rule['alert'][0].get_info(),
AttributeError: 'str' object has no attribute 'get_info'`

Many thanks in advanced

**Comment by mrbobcode** [comment]
Looks like it only does it when running --debug
