### ISSUE TITLE
AttributeError: 'module' object has no attribute 'StrideAlerter'

### ISSUE THREAD

**Issue by sathishdsgithub** [Yelp/elastalert#1438]
I get error when I start elastalert

```
[root@ elastalert]# python -m elastalert.elastalert --start NOW --verbose --config config.yaml
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/elastalert/elastalert/elastalert.py", line 22, in <module>
    from config import get_rule_hashes
  File "elastalert/config.py", line 69, in <module>
    'stride': alerts.StrideAlerter,
```
**AttributeError: 'module' object has no attribute 'StrideAlerter'**

**Comment by jness** [comment]
It seems like you may not have a fully upgraded elastalert, how was elastalert installed in your environment? 

Your elastalert/config.py is mapping to the alerts.StrideAlerter class:
https://github.com/Yelp/elastalert/blob/master/elastalert/config.py#L69 

The alerts.StrideAlerter class can be found in your elastalert/alerts.py:
https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L1458

The exception above makes it sound like your elastalert/config.py is newer than your elastalert/alerts.py.

I would start by checking elastalert/alerts.py for a StrideAlerter class.
