### ISSUE TITLE
SMTP email alert Error

### ISSUE THREAD

**Issue by sathishdsgithub** [Yelp/elastalert#1447]
@Qmando 
I get the below error when the elastalert tries to send email 

```
ERROR:root:Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 1231, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
  File "/opt/elastalert/elastalert/elastalert.py", line 1308, in send_alert
    alert.alert(matches)
  File "elastalert/alerts.py", line 481, in alert
    self.smtp.sendmail(self.from_addr, to_addr, email_msg.as_string())
  File "/usr/lib64/python2.7/smtplib.py", line 734, in sendmail
    self.rset()
  File "/usr/lib64/python2.7/smtplib.py", line 468, in rset
    return self.docmd("rset")
  File "/usr/lib64/python2.7/smtplib.py", line 393, in docmd
    return self.getreply()
  File "/usr/lib64/python2.7/smtplib.py", line 367, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
SMTPServerDisconnected: Connection unexpectedly closed

```

![image](https://user-images.githubusercontent.com/19161126/33548836-9289298a-d90e-11e7-98a2-8112e3735c92.png)

**Comment by Qmando** [comment]
Do you own the smtp server?
Did it used to work and stopped working? 
Are you using a TLS endpoint or have you tried it?
