### ISSUE TITLE
SMTPSenderRefused: (501, : sender address must contain a domain

### ISSUE THREAD

**Issue by leeningli** [Yelp/elastalert#1448]
ERROR:root:Traceback (most recent call last):
  File "/wls/wls81/elastalert-master/elastalert/elastalert.py", line 1246, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/wls/wls81/elastalert-master/elastalert/elastalert.py", line 1326, in send_alert
    alert.alert(matches)
  File "elastalert/alerts.py", line 451, in alert
    self.smtp.sendmail(self.from_addr, to_addr, email_msg.as_string())
  File "/wls/wls81/python2.7.14/lib/python2.7/smtplib.py", line 737, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (501, '<ElastAlert>: sender address must contain a domain', 'ElastAlert')

**Comment by leeningli** [comment]
Close....
