### ISSUE TITLE
failed validating 'type' in schema

### ISSUE THREAD

**Issue by stcoyleNJDGE** [Yelp/elastalert#1459]
I tried to make a new rule to send an alert when a term is in a field for elasticsearch. when i test the rule i am getting: 

`Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.25', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.25-py2.7.egg/elastalert/test_rule.py", line 378, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.25-py2.7.egg/elastalert/test_rule.py", line 359, in run_rule_test
    conf = self.load_conf(rule_yaml, args)
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.25-py2.7.egg/elastalert/test_rule.py", line 320, in load_conf
    load_options(rules, conf, args.file)
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.25-py2.7.egg/elastalert/config.py", line 158, in load_options
    raise EAException("Invalid Rule file: %s\n%s" % (filename, e))
elastalert.util.EAException: Invalid Rule file: /root/elastalert/example_rules/elastalert-ossec.yaml
None is not of type 'array', 'object'

Failed validating 'type' in schema['properties']['filter']:
    {'additionalProperties': False,
     'items': {},
     'properties': {'download_dashboard': {'type': 'string'}},
     'type': ['array', 'object']}

On instance['filter']:
    None
`

here is my rule yaml file:
`es_host: 192.168.137.129

es_port: 9200

name: OSSEC-Alerts

type: any

index: ossec-*

num_events: 1

timeframe:
  hours: 1

filter:
-term:
    Description: "Integrity checksum changed"

alert_subject: "OSSEC Alert"

alert:
- "email"
email:
<removed>

email_from_field: "File Change"
smtp_host: <removed>
smtp_auth_file: <removed>
`

i am running ES 6.0.0. i did the quick and dirty fix i found on here and it seemed to be working i was able to create the indexes and everything. but i dont seem to be able to create a rule. even the example rules fail??  

any help would be appreciated. thanks.

**Comment by Qmando** [comment]
The issue here is that there is no space in ``-term`` after filter. this becomes something separate in YAML.
It should be 
```
filter:
- term
```

```
>>> yaml.load('filter:\n-term:\n    test: hi')
{'filter': None, '-term': {'test': 'hi'}}
>>> yaml.load('filter:\n- term:\n    test: hi')
{'filter': [{'term': {'test': 'hi'}}]}
```

**Comment by stcoyleNJDGE** [comment]
@Qmando  thanks! i made that change and now im getting a whole new error about it not matching and schema? 

```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.25', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.25-py2.7.egg/elastalert/test_rule.py", line 378, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.25-py2.7.egg/elastalert/test_rule.py", line 359, in run_rule_test
    conf = self.load_conf(rule_yaml, args)
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.25-py2.7.egg/elastalert/test_rule.py", line 320, in load_conf
    load_options(rules, conf, args.file)
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.25-py2.7.egg/elastalert/config.py", line 158, in load_options
    raise EAException("Invalid Rule file: %s\n%s" % (filename, e))
elastalert.util.EAException: Invalid Rule file: /root/elastalert/example_rules/File_Change_Alert.yaml
{'es_port': 9200, 'name': 'OSSEC-Alerts', 'index': 'ossec-*', 'smtp_host': 'smtp.gmail.com', 'rule_file': '/root/elastalert/example_rules/File_Change_Alert.yaml', 'smtp_auth_file': '/root/elastalert/example_rules/email.yaml', 'num_events': 1, 'alert': ['email'], 'filter': [{'term': 'Description:"Integrity checksum changed"'}], 'es_host': '192.168.137.129', 'alert_subject': 'OSSEC Alert', 'timeframe': {'hours': 48}, 'type': 'Any', 'email': ['emails removed'], 'email_from_field': 'File Change'} is not valid under any of the given schemas

Failed validating 'oneOf' in schema:
    {'$schema': 'http://json-schema.org/draft-04/schema#',
     'definitions': {'arrayOfStrings': {'items': {'type': 'string'},
                                        'type': ['string', 'array']},
                     'arrayOfStringsOrOtherArrays': {'items': {'type': ['string',
                                                                        'array']},
                                                     'type': ['string',
                                                              'array']},
                     'filter': {},
                     'timeFrame': {'additionalProperties': False,
                                   'properties': {'days': {'type': 'number'},
                                                  'hours': {'type': 'number'},
                                                  'milliseconds': {'type': 'number'},
                                                  'minutes': {'type': 'number'},
                                                  'schedule': {'type': 'string'},
                                                  'seconds': {'type': 'number'},
                                                  'weeks': {'type': 'number'}},
                                   'type': 'object'}},
     'oneOf': [{'properties': {'type': {'enum': ['any']}},
                'title': 'Any'},
               {'properties': {'blacklist': {'items': {'type': 'string'},
                                             'type': 'array'},
                               'compare_key': {'items': {'type': 'string'},
                                               'type': ['string',
                                                        'array']},
                               'type': {'enum': ['blacklist']}},
                'required': ['blacklist', 'compare_key'],
                'title': 'Blacklist'},
               {'properties': {'compare_key': {'items': {'type': 'string'},
                                               'type': ['string',
                                                        'array']},
                               'ignore_null': {'type': 'boolean'},
                               'type': {'enum': ['whitelist']},
                               'whitelist': {'items': {'type': 'string'},
                                             'type': 'array'}},
                'required': ['whitelist', 'compare_key', 'ignore_null'],
                'title': 'Whitelist'},
               {'properties': {'compare_key': {'items': {'type': 'string'},
                                               'type': ['string',
                                                        'array']},
                               'ignore_null': {'type': 'boolean'},
                               'timeframe': {'additionalProperties': False,
                                             'properties': {'days': {'type': 'number'},
                                                            'hours': {'type': 'number'},
                                                            'milliseconds': {'type': 'number'},
                                                            'minutes': {'type': 'number'},
                                                            'schedule': {'type': 'string'},
                                                            'seconds': {'type': 'number'},
                                                            'weeks': {'type': 'number'}},
                                             'type': 'object'},
                               'type': {'enum': ['change']}},
                'required': ['query_key', 'compare_key', 'ignore_null'],
                'title': 'Change'},
               {'properties': {'attach_related': {'type': 'boolean'},
                               'doc_type': {'type': 'string'},
                               'num_events': {'type': 'integer'},
                               'terms_size': {'type': 'integer'},
                               'timeframe': {'additionalProperties': False,
                                             'properties': {'days': {'type': 'number'},
                                                            'hours': {'type': 'number'},
                                                            'milliseconds': {'type': 'number'},
                                                            'minutes': {'type': 'number'},
                                                            'schedule': {'type': 'string'},
                                                            'seconds': {'type': 'number'},
                                                            'weeks': {'type': 'number'}},
                                             'type': 'object'},
                               'type': {'enum': ['frequency']},
                               'use_count_query': {'type': 'boolean'},
                               'use_terms_query': {'type': 'boolean'}},
                'required': ['num_events', 'timeframe'],
                'title': 'Frequency'},
               {'properties': {'alert_on_new_data': {'type': 'boolean'},
                               'doc_type': {'type': 'string'},
                               'spike_height': {'type': 'number'},
                               'spike_type': {'enum': ['up',
                                                       'down',
                                                       'both']},
                               'terms_size': {'type': 'integer'},
                               'threshold_cur': {'type': 'integer'},
                               'threshold_ref': {'type': 'integer'},
                               'timeframe': {'additionalProperties': False,
                                             'properties': {'days': {'type': 'number'},
                                                            'hours': {'type': 'number'},
                                                            'milliseconds': {'type': 'number'},
                                                            'minutes': {'type': 'number'},
                                                            'schedule': {'type': 'string'},
                                                            'seconds': {'type': 'number'},
                                                            'weeks': {'type': 'number'}},
                                             'type': 'object'},
                               'type': {'enum': ['spike']},
                               'use_count_query': {'type': 'boolean'},
                               'use_terms_query': {'type': 'boolean'}},
                'required': ['spike_height', 'spike_type', 'timeframe'],
                'title': 'Spike'},
               {'properties': {'doc_type': {'type': 'string'},
                               'threshold': {'type': 'integer'},
                               'timeframe': {'additionalProperties': False,
                                             'properties': {'days': {'type': 'number'},
                                                            'hours': {'type': 'number'},
                                                            'milliseconds': {'type': 'number'},
                                                            'minutes': {'type': 'number'},
                                                            'schedule': {'type': 'string'},
                                                            'seconds': {'type': 'number'},
                                                            'weeks': {'type': 'number'}},
                                             'type': 'object'},
                               'type': {'enum': ['flatline']},
                               'use_count_query': {'type': 'boolean'}},
                'required': ['threshold', 'timeframe'],
                'title': 'Flatline'},
               {'properties': {'alert_on_missing_field': {'type': 'boolean'},
                               'fields': {'items': {'type': ['string',
                                                             'array']},
                                          'type': ['string', 'array']},
                               'terms_size': {'type': 'integer'},
                               'terms_window_size': {'additionalProperties': False,
                                                     'properties': {'days': {'type': 'number'},
                                                                    'hours': {'type': 'number'},
                                                                    'milliseconds': {'type': 'number'},
                                                                    'minutes': {'type': 'number'},
                                                                    'schedule': {'type': 'string'},
                                                                    'seconds': {'type': 'number'},
                                                                    'weeks': {'type': 'number'}},
                                                     'type': 'object'},
                               'type': {'enum': ['new_term']},
                               'use_terms_query': {'type': 'boolean'}},
                'required': ['fields'],
                'title': 'New Term'},
               {'properties': {'cardinality_field': {'type': 'string'},
                               'max_cardinality': {'type': 'integer'},
                               'min_cardinality': {'type': 'integer'},
                               'timeframe': {'additionalProperties': False,
                                             'properties': {'days': {'type': 'number'},
                                                            'hours': {'type': 'number'},
                                                            'milliseconds': {'type': 'number'},
                                                            'minutes': {'type': 'number'},
                                                            'schedule': {'type': 'string'},
                                                            'seconds': {'type': 'number'},
                                                            'weeks': {'type': 'number'}},
                                             'type': 'object'},
                               'type': {'enum': ['cardinality']}},
                'required': ['cardinality_field', 'timeframe'],
                'title': 'Cardinality'},
               {'properties': {'metric_agg_type': {'enum': ['min',
                                                            'max',
                                                            'avg',
                                                            'sum',
                                                            'cardinality',
                                                            'value_count']},
                               'type': {'enum': ['metric_aggregation']}},
                'required': ['metric_agg_key', 'metric_agg_type'],
                'title': 'Metric Aggregation'},
               {'properties': {'type': {'enum': ['percentage_match']}},
                'required': ['match_bucket_filter'],
                'title': 'Percentage Match'},
               {'properties': {'type': {'pattern': '[.]'}},
                'title': 'Custom Rule from Module'}],
     'properties': {'aggregation': {'additionalProperties': False,
                                    'properties': {'days': {'type': 'number'},
                                                   'hours': {'type': 'number'},
                                                   'milliseconds': {'type': 'number'},
                                                   'minutes': {'type': 'number'},
                                                   'schedule': {'type': 'string'},
                                                   'seconds': {'type': 'number'},
                                                   'weeks': {'type': 'number'}},
                                    'type': 'object'},
                    'alert_text': {'type': 'string'},
                    'alert_text_args': {'items': {'type': 'string'},
                                        'type': 'array'},
                    'alert_text_kw': {'type': 'object'},
                    'alert_text_type': {'enum': ['alert_text_only',
                                                 'exclude_fields']},
                    'buffer_time': {'additionalProperties': False,
                                    'properties': {'days': {'type': 'number'},
                                                   'hours': {'type': 'number'},
                                                   'milliseconds': {'type': 'number'},
                                                   'minutes': {'type': 'number'},
                                                   'schedule': {'type': 'string'},
                                                   'seconds': {'type': 'number'},
                                                   'weeks': {'type': 'number'}},
                                    'type': 'object'},
                    'command': {'items': {'type': 'string'},
                                'type': ['string', 'array']},
                    'email': {'items': {'type': 'string'},
                              'type': ['string', 'array']},
                    'email_reply_to': {'type': 'string'},
                    'es_host': {'type': 'string'},
                    'es_password': {'type': 'string'},
                    'es_port': {'type': 'integer'},
                    'es_username': {'type': 'string'},
                    'exotel_account_sid': {'type': 'string'},
                    'exotel_auth_token': {'type': 'string'},
                    'exotel_from_number': {'type': 'string'},
                    'exotel_to_number': {'type': 'string'},
                    'exponential_realert': {'additionalProperties': False,
                                            'properties': {'days': {'type': 'number'},
                                                           'hours': {'type': 'number'},
                                                           'milliseconds': {'type': 'number'},
                                                           'minutes': {'type': 'number'},
                                                           'schedule': {'type': 'string'},
                                                           'seconds': {'type': 'number'},
                                                           'weeks': {'type': 'number'}},
                                            'type': 'object'},
                    'fail_on_non_zero_exit': {'type': 'boolean'},
                    'field': {},
                    'filter': {'additionalProperties': False,
                               'items': {},
                               'properties': {'download_dashboard': {'type': 'string'}},
                               'type': ['array', 'object']},
                    'from_addr': {'type': 'string'},
                    'generate_kibana_link': {'type': 'boolean'},
                    'gitter_msg_level': {'enum': ['info', 'error']},
                    'gitter_proxy': {'type': 'string'},
                    'gitter_webhook_url': {'type': 'string'},
                    'hipchat_auth_token': {'type': 'string'},
                    'hipchat_domain': {'type': 'string'},
                    'hipchat_from': {'type': 'string'},
                    'hipchat_ignore_ssl_errors': {'type': 'boolean'},
                    'hipchat_notify': {'type': 'boolean'},
                    'hipchat_room_id': {'type': ['string', 'integer']},
                    'import': {'type': 'string'},
                    'include': {'items': {'type': 'string'},
                                'type': 'array'},
                    'index': {'type': 'string'},
                    'jira_account_file': {'type': 'string'},
                    'jira_assignee': {'type': 'string'},
                    'jira_bump_in_statuses': {'items': {'type': 'string'},
                                              'type': ['string',
                                                       'array']},
                    'jira_bump_not_in_statuses': {'items': {'type': 'string'},
                                                  'type': ['string',
                                                           'array']},
                    'jira_bump_tickets': {'type': 'boolean'},
                    'jira_component': {'items': {'type': 'string'},
                                       'type': ['string', 'array']},
                    'jira_components': {'items': {'type': 'string'},
                                        'type': ['string', 'array']},
                    'jira_issuetype': {'type': 'string'},
                    'jira_label': {'items': {'type': 'string'},
                                   'type': ['string', 'array']},
                    'jira_labels': {'items': {'type': 'string'},
                                    'type': ['string', 'array']},
                    'jira_max_age': {'type': 'number'},
                    'jira_project': {'type': 'string'},
                    'jira_server': {'type': 'string'},
                    'jira_watchers': {'items': {'type': 'string'},
                                      'type': ['string', 'array']},
                    'kibana_dashboard': {'type': 'string'},
                    'match_enhancements': {'items': {'type': 'string'},
                                           'type': 'array'},
                    'max_query_size': {'type': 'integer'},
                    'name': {'type': 'string'},
                    'notify_email': {'items': {'type': 'string'},
                                     'type': ['string', 'array']},
                    'owner': {'type': 'string'},
                    'pagerduty_client_name': {'type': 'string'},
                    'pagerduty_event_type': {'enum': ['none',
                                                      'trigger',
                                                      'resolve',
                                                      'acknowledge']},
                    'pagerduty_service_key': {'type': 'string'},
                    'pipe_match_json': {'type': 'boolean'},
                    'priority': {'type': 'integer'},
                    'query_delay': {'additionalProperties': False,
                                    'properties': {'days': {'type': 'number'},
                                                   'hours': {'type': 'number'},
                                                   'milliseconds': {'type': 'number'},
                                                   'minutes': {'type': 'number'},
                                                   'schedule': {'type': 'string'},
                                                   'seconds': {'type': 'number'},
                                                   'weeks': {'type': 'number'}},
                                    'type': 'object'},
                    'query_key': {'items': {'type': 'string'},
                                  'type': ['string', 'array']},
                    'raw_count_keys': {'type': 'boolean'},
                    'realert': {'additionalProperties': False,
                                'properties': {'days': {'type': 'number'},
                                               'hours': {'type': 'number'},
                                               'milliseconds': {'type': 'number'},
                                               'minutes': {'type': 'number'},
                                               'schedule': {'type': 'string'},
                                               'seconds': {'type': 'number'},
                                               'weeks': {'type': 'number'}},
                                'type': 'object'},
                    'replace_dots_in_field_names': {'type': 'boolean'},
                    'simple_proxy': {'type': 'string'},
                    'simple_webhook_url': {'items': {'type': 'string'},
                                           'type': ['string', 'array']},
                    'slack_emoji_override': {'type': 'string'},
                    'slack_icon_url_override': {'type': 'string'},
                    'slack_msg_color': {'enum': ['good',
                                                 'warning',
                                                 'danger']},
                    'slack_parse_override': {'enum': ['none', 'full']},
                    'slack_text_string': {'type': 'string'},
                    'slack_username_override': {'type': 'string'},
                    'slack_webhook_url': {'items': {'type': 'string'},
                                          'type': ['string', 'array']},
                    'smtp_host': {'type': 'string'},
                    'stride_access_token': {'type': 'string'},
                    'stride_cloud_id': {'type': 'string'},
                    'stride_converstation_id': {'type': 'string'},
                    'stride_ignore_ssl_errors': {'type': 'boolean'},
                    'telegram_api_url': {'type': 'string'},
                    'telegram_bot_token': {'type': 'string'},
                    'telegram_room_id': {'type': 'string'},
                    'timestamp_field': {'type': 'string'},
                    'top_count_keys': {'items': {'type': 'string'},
                                       'type': 'array'},
                    'top_count_number': {'type': 'integer'},
                    'twilio_account_sid': {'type': 'string'},
                    'twilio_auth_token': {'type': 'string'},
                    'twilio_from_number': {'type': 'string'},
                    'twilio_to_number': {'type': 'string'},
                    'use_kibana_dashboard': {'type': 'string'},
                    'use_local_time': {'type': 'boolean'},
                    'use_ssl': {'type': 'boolean'},
                    'use_strftime_index': {'type': 'boolean'},
                    'verify_certs': {'type': 'boolean'},
                    'victorops_api_key': {'type': 'string'},
                    'victorops_entity_display_name': {'type': 'string'},
                    'victorops_message_type': {'enum': ['INFO',
                                                        'WARNING',
                                                        'ACKNOWLEDGEMENT',
                                                        'CRITICAL',
                                                        'RECOVERY']},
                    'victorops_routing_key': {'type': 'string'}},
     'required': ['type', 'index', 'alert'],
     'type': 'object'}

On instance:
    {'alert': ['email'],
     'alert_subject': 'OSSEC Alert',
     'email': ['removed'],
     'email_from_field': 'File Change',
     'es_host': '192.168.137.129',
     'es_port': 9200,
     'filter': [{'term': 'Description:"Integrity checksum changed"'}],
     'index': 'ossec-*',
     'name': 'OSSEC-Alerts',
     'num_events': 1,
     'rule_file': '/root/elastalert/example_rules/File_Change_Alert.yaml',
     'smtp_auth_file': '/root/elastalert/example_rules/email.yaml',
     'smtp_host': 'removed',
     'timeframe': {'hours': 48},
     'type': 'Any'}
```
