### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by lynnic26** [Yelp/elastalert#1469]
- ES 5.5.2
- PYTHON 2.7
```
INFO:elastalert:Starting up
ERROR:root:Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\elastalert-0.1.25-py2.7.egg\elastalert\elastalert.py", line 1084, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "C:\Python27\lib\site-packages\elastalert-0.1.25-py2.7.egg\elastalert\elastalert.py", line 797, in run_rule
    if not self.run_query(rule, rule['starttime'], endtime):
  File "C:\Python27\lib\site-packages\elastalert-0.1.25-py2.7.egg\elastalert\elastalert.py", line 585, in run_query
    data = self.get_hits(rule, start, end, index, scroll)
  File "C:\Python27\lib\site-packages\elastalert-0.1.25-py2.7.egg\elastalert\elastalert.py", line 388, in get_hits
    pretty_ts(starttime, lt),
  File "C:\Python27\lib\site-packages\elastalert-0.1.25-py2.7.egg\elastalert\util.py", line 170, in pretty_ts
    return dt.strftime('%Y-%m-%d %H:%M %Z')
  File "build\bdist.win32\egg\dateutil\tz\_common.py", line 22, in adjust_encoding
    name = name.encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 0: ordinal not in range(128)

ERROR:root:Uncaught exception running rule Example frequency rule: 'ascii' codec can't decode byte 0xd6 in position 0: ordinal not in range(128)
```
Does I need to downgrade the dateutil?
Or manully hotfix like this [#471](https://github.com/Yelp/elastalert/issues/471#issuecomment-209657248)

**Comment by arypurnomoz** [comment]
i got the same error

**Comment by ahaii** [comment]
i got the same error
