### ISSUE TITLE
Issue when running on ElasticSearch 6.x.x

### ISSUE THREAD

**Issue by alexraileanu** [Yelp/elastalert#1479]
Hi.

I am trying to set up elastalert on a newly created ElasticSearch instance version 6.1.1. I saw the PR #1472 and from my understanding it should work. I noticed it does create all the necessary indices:

```
root@host:~/elastalert# curl -X GET elastic:9200/_cat/indices
yellow open elastalert_status_past      UN6_P71dSqup5c_xthAdqw 5 1      0 0   1.1kb   1.1kb
yellow open elastalert_status_error     zNGjtTiHQXaMXiscW5acSw 5 1      0 0   1.1kb   1.1kb
yellow open elastalert_status_silence   nSPXnsXGQECcVSAx-f96_Q 5 1      0 0   1.1kb   1.1kb
yellow open elastalert_status_status    4y3-UfjjTU6j32TagSQmLA 5 1      0 0   1.1kb   1.1kb
yellow open elastalert_status           2fx5Ld4MS6qNI5wbCva87g 5 1      1 0   4.4kb   4.4kb
```

However, when running elastalert I get the following output:

```
root@host:~/elastalert# elastalert --verbose --rule rules.yml
INFO:elastalert:Starting up
INFO:elastalert:Queried rule Test rule from 2018-01-08 10:15 UTC to 2018-01-08 10:30 UTC: 0 / 0 hits
{'hits': 0, 'matches': 0, '@timestamp': '2018-01-08T10:30:46.174458Z', 'rule_name': 'Test rule', 'starttime': '2018-01-08T10:15:46.165293Z', 'endtime': '2018-01-08T10:30:46.165293Z', 'time_taken': 0.00915384292602539}
WARNING:elasticsearch:POST http://elastic:9200/elastalert_status/elastalert_status [status:400 request:0.015s]
ERROR:root:Error writing alert info to Elasticsearch: TransportError(400, u'illegal_argument_exception', u'Rejecting mapping update to [elastalert_status] as the final mapping would have more than 1 type: [elastalert, elastalert_status]')
Traceback (most recent call last):
  File "/root/venv/local/lib/python2.7/site-packages/elastalert-0.1.26-py2.7.egg/elastalert/elastalert.py", line 1417, in writeback
    doc_type=doc_type, body=body)
  File "/root/venv/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/root/venv/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 300, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/root/venv/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/root/venv/local/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/root/venv/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'illegal_argument_exception', u'Rejecting mapping update to [elastalert_status] as the final mapping would have more than 1 type: [elastalert, elastalert_status]')
INFO:elastalert:Ran Test rule from 2018-01-08 10:15 UTC to 2018-01-08 10:30 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59.965396 seconds
```

My config file looks like this:

```
rules_folder: .
buffer_time:
    minutes: 15
run_every:
    minutes: 1
es_host: elastic
es_port: 9200
use_ssl: False
writeback_index: elastalert_status
alert_time_limit:
    days: 2
```

My rules file looks like this:

```
name: Test rule
type: frequency
index: filebeat-*
num_events: 50
timeframe:
    minutes: 5
filter:
    - term:
        fields.env: "test"
    - term:
        filename: "test"
alert:
    - "email"
email:
    - "email@address.com"
```

Any help would be appreciated.

**Comment by hollowimage** [comment]
+1 here as well running latest master against ES6.1.1

**Comment by fkgre** [comment]
+1

**Comment by Qmando** [comment]
Try changing your ``writeback_index`` setting from ``elastalert_status`` to just ``elastalert``, recreate the indexes, and then try again.

I'll get a proper fix for this shortly.

**Comment by alexraileanu** [comment]
Awesome. @Qmando that seems to have done the trick! Many thanks and looking forward to your fix :).

**Comment by CodingSpiderFox** [comment]
Please publish the fix as soon as possible.

**Comment by zffocussss** [comment]
> Try changing your `writeback_index` setting from `elastalert_status` to just `elastalert`, recreate the indexes, and then try again.
> 
> I'll get a proper fix for this shortly. Sorry for the inconvenience!

is it updated?

**Comment by zffocussss** [comment]
> Try changing your `writeback_index` setting from `elastalert_status` to just `elastalert`, recreate the indexes, and then try again.
> 
> I'll get a proper fix for this shortly. Sorry for the inconvenience!

there are multiple writeback_index: elastalert_status in config.json and elastalert.yaml.which one should I change?

**Comment by CodingSpiderFox** [comment]
I don't remember exactly but I think all 4 of them had to be changed
