### ISSUE TITLE
All shards failed for phase: [query]

### ISSUE THREAD

**Issue by xiaobao2** [Yelp/elastalert#1553]
[2018-02-13T09:35:50,753][DEBUG][o.e.a.s.TransportSearchAction] [node-1] All shards failed for phase: [query]
[2018-02-13T09:35:50,753][WARN ][r.suppressed             ] path: /elastalert_status/elastalert/_search, params: {size=1000, index=elastalert_status, type=elastalert}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:274) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:132) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:243) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:107) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:205) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.search.InitialSearchPhase$1.doRun(InitialSearchPhase.java:184) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.1.0.jar:6.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by ninadvps** [comment]
how come no one has commented on this? Im getting the same issue

**Comment by RamjiVE** [comment]
Reindex from old kibana index into the newly created one
```
curl -XPOST -s -uelastic:changeme 'https://localhost:9200/_reindex' -d'
{
  "source": {
    "index": ".kibana"
  },
  "dest": {
    "index": ".kibana-5.6.0"
  }
}'
```
edit kibana.yml to use the new index
Just change kibana.index: ".kibana to kibana.index: ".kibana-5.6.0" and restart kibana.

Note: Rather than re configuring kibana.index: one could also DELETE the old .kibana index and create an alias with that name pointing to the new index name.
