### ISSUE TITLE
<MISSING VALUE> for command alert

### ISSUE THREAD

**Issue by bennneuh** [Yelp/elastalert#1593]
I don't have the value "MISSING VALUE" from "command" alert. The value seems empty.

So i have an error when the value is missing (but in parallel the alert on slack works fine)

Error during test:
```
ERROR:root:Error while running alert command: Error formatting command: 'web_test_name'

elastalert_error - {'message': "Error while running alert command: Error formatting command: 'web_test_name'", 'traceback': ['Traceback (most recent call last):', '  File "/opt/elastalert/elastalert/elastalert.py", line 1363, in send_alert', '    alert.alert(matches)', '  File "/opt/elastalert/elastalert/alerts.py", line 866, in alert', '    raise EAException("Error formatting command: %s" % (e))', "EAException: Error formatting command: 'web_test_name'"], 'data': {'rule': '04-ML'}}
```
I suspect that the command alert don't manage missing value ?

**Comment by bennneuh** [comment]
Hello,
No ideas about this potential issue ?

Thanks,

**Comment by Qmando** [comment]
This was fixed. Sorry for slow response.
