### ISSUE TITLE
create a new bugfix release

### ISSUE THREAD

**Issue by CodingSpiderFox** [Yelp/elastalert#1635]
I can't build my docker image anymore because of the broken dependency (this was fixed with commit bd10b81757b7765fd32b886153754f252dff4a2e)

Can you please release a new version?

Will the project change to semantic versioning in the future?

**Comment by amoskyler** [comment]
In the meantime, you can fix your Dockerfile by doing something like this:

```# Install Elastalert.
RUN pip install 'python-dateutil>=2.6.0,<2.7.0' && \
    python setup.py install && \
    pip install -e .
```

This works for me in the interim.

**Comment by CodingSpiderFox** [comment]
Works! Thank you very much!

**Comment by CodingSpiderFox** [comment]
Now it's broken again on install

```
Running exotel-0.1.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-B2TbVR/exotel-0.1.5/egg-dist-tmp-48zSEr
[91mTraceback (most recent call last):
  File "setup.py", line 48, in <module>
    'twilio>=6.0.0,<6.1',
[0m[91m  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
[0m[91m    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
[0m[91m    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
[0m[91m    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
[0m[91m    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 411, in run
[0m[91m    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in easy_install
[0m[91m    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 702, in install_item
[0m[91m    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 747, in process_distribution
[0m[91m    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
[0m[91m    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1118, in best_match
[0m[91m    return self.obtain(req, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1130, in obtain
[0m[91m    return installer(requirement)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
[0m[91m    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 700, in install_item
[0m[91m    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
[0m[91m    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
[0m[91m    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
[0m[91m    run_setup(setup_script, args)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in run_setup
[0m[91m    with setup_context(setup_dir):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
[0m[91m    return self.gen.next()
[0m[91m  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
[0m[91m    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
[0m[91m    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
[0m[91m    saved_exc.resume()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 144, in resume
[0m[91m    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
[0m[91m    yield saved
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 197, in setup_context
[0m[91m    __import__('setuptools')
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, map
  File "/usr/lib/python2.7/site-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 74, in <module>
[0m[91m    __import__('pkg_resources.extern.packaging.requirements')
  File "/usr/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
[0m[91m    __import__(extant)
  File "/usr/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "/usr/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
[0m[91m    __import__(extant)
  File "/usr/lib/python2.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 943, in <module>
[0m[91m    collections.MutableMapping.register(ParseResults)
  File "/usr/lib/python2.7/abc.py", line 109, in register
    if issubclass(subclass, cls):
  File "/usr/lib/python2.7/abc.py", line 180, in __subclasscheck__
[0m[91m    if issubclass(subclass, scls):
  File "build/bdist.linux-x86_64/egg/typing.py", line 1249, in __subclasscheck__
[0m[91mTypeError: super() argument 1 must be type, not None
[0mThe command '/bin/sh -c pip install 'python-dateutil>=2.6.0,<2.7.0' &&     python setup.py install &&     pip install -e . &&     pip uninstall twilio --yes &&     pip install twilio==6.0.0 &&     easy_install supervisor &&     mkdir -p "${CONFIG_DIR}" &&     mkdir -p "${RULES_DIRECTORY}" &&     mkdir -p "${LOG_DIR}" &&     mkdir -p /var/empty &&     apk del python2-dev &&     apk del musl-dev &&     apk del gcc &&     apk del openssl-dev &&     apk del libffi-dev &&     rm -rf /var/cache/apk/*' returned a non-zero code: 1
```
