### ISSUE TITLE
error running elastalert

### ISSUE THREAD

**Issue by bitsofinfo** [Yelp/elastalert#1650]
```
bash-4.4$ elastalert
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert==0.1.29', 'console_scripts', 'elastalert')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.1.29-py3.6.egg/elastalert/elastalert.py", line 1246
    raise EAException("Error querying for dashboard: %s" % (e)), None, sys.exc_info()[2]
                                                               ^
SyntaxError: invalid syntax
```

**Comment by sergekir** [comment]
#1210

**Comment by boddumanohar** [comment]
I see on v.0.2.1
