### ISSUE TITLE
ParseException: Cannot parse 'aggregate_id:-GENERATED_ID'

### ISSUE THREAD

**Issue by XizzoR** [Yelp/elastalert#1656]
Hello!

We are using Elasticsearch (6.2.3) with SearchGuard and ElastAlert (0.1.29) - all those three as a containers in Docker.
Everything is working fine until we put some valid rules in ElastAlert. Then ElastAlert "crashes" our Elasticsearch instance (if in production mode). We believe that parsing fails because ElastAlert is turning document "_id" into "aggregate_id" with some anomalies (i.e. prefixing it with dash symbol "-"). Interesting thing is that this happens about 10-15 minutes after the ElastAlert is up and running. There is an error output (debug, if in development mode):

```
[DEBUG][o.e.a.s.TransportSearchAction] [elasticsearch-node0] [elastalert][2], node[WgxqbLwwSyCb-3AwCSytUw], [P], s[STARTED], a[id=5B20gkFuQlmw4AmT5FfBPg]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[elastalert], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[elastalert], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=128, source={"size":10000,"query":{"query_string":{"query":"aggregate_id:-GjO72IBACQhkrW2Q0b8","fields":[],"type":"best_fields","default_operator":"or","max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"auto_generate_synonyms_phrase_query":true,"fuzzy_transpositions":true,"boost":1.0}},"sort":[{"@timestamp":{"order":"asc"}}]}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [elasticsearch-node0][10.0.0.17:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: Failed to parse query [aggregate_id:-GjO72IBACQhkrW2Q0b8]
```
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1024) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:707) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:558) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:534) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:330) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) [elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) [elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) [elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) [elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.3.jar:6.2.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'aggregate_id:-GjO72IBACQhkrW2Q0b8': Encountered " "-" "- "" at line 1, column 13.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    \<QUOTED\> ...
    \<TERM\> ...
    \<PREFIXTERM\> ...
    \<WILDTERM\> ...
    \<REGEXPTERM\> ...
    "[" ...
    "{" ...
    \<NUMBER\> ...
```

        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:114) ~[lucene-queryparser-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:49:34]
        at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:777) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1022) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:707) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:558) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:534) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:330) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) [elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.3.jar:6.2.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_162]
```
Caused by: org.apache.lucene.queryparser.classic.ParseException: Encountered " "-" "- "" at line 1, column 13.
Was expecting one of:
    \<BAREOPER\> ...
    "(" ...
    "*" ...
    \<QUOTED\> ...
    \<TERM\> ...
    \<PREFIXTERM\> ...
    \<WILDTERM\> ...
    \<REGEXPTERM\> ...
    "[" ...
    "{" ...
    \<NUMBER\> ...
```

        at org.apache.lucene.queryparser.classic.QueryParser.generateParseException(QueryParser.java:931) ~[lucene-queryparser-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:49:34]
        at org.apache.lucene.queryparser.classic.QueryParser.jj_consume_token(QueryParser.java:813) ~[lucene-queryparser-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:49:34]
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:373) ~[lucene-queryparser-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:49:34]
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:244) ~[lucene-queryparser-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:49:34]
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215) ~[lucene-queryparser-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:49:34]
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109) ~[lucene-queryparser-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:49:34]
        at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:777) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1022) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:707) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:558) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:534) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:330) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.3.jar:6.2.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_162]

Any kind of help is appreciated.

**Comment by XizzoR** [comment]
Strange.
It looks that it can parse a string only if dash or any other special symbol (underscore etc.) are not a first character in it. Either way, while computing an "aggregate_id", surrounding it with quotation marks escapes such parse failure. We found that out while experimenting with Kibana - when you search for "_id:-j1298dn91H23..." it returns the same error, but when searching for "_id:"-j1298dn91H23..."", that produces a valid result.
Case closed.
