### ISSUE TITLE
Mapping contains more then one type (creating ElastAlert index)

### ISSUE THREAD

**Issue by XizzoR** [Yelp/elastalert#1657]
Hello!

I got following message when starting ElastAlert (from Docker):

Creating Elastalert index in Elasticsearch...
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.1.29', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.29-py2.7.egg/elastalert/create_index.py", line 175, in main
    es.indices.put_mapping(index=index+'_status', doc_type='elastalert_status', body=ess_mapping)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 271, in put_mapping
Elastic Version:6
Mapping used for string:{'type': 'keyword'}
    '_mapping', doc_type), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'Rejecting mapping update to [elastalert_status] as the final mapping would have more than 1 type: [search, elastalert_status]')
Starting Elastalert...

I tried to remove indices, but no luck, the message still persist while Im trying to start elastalert. However, indices (elastalert_status, elastalert_error, ...) are created and filled with some data.

**Comment by Qmando** [comment]
This has been fixed in the meantime
