### ISSUE TITLE
Install fails on Windows 2012

### ISSUE THREAD

**Issue by callahan22** [Yelp/elastalert#1665]
Hi,

I'm getting the following error when installing elastalert on Windows 2012 running the ELK stack.

```
Installed c:\program files (x86)\python36-32\lib\site-packages\elastalert-0.1.29-py3.6.egg
Processing dependencies for elastalert==0.1.29
Searching for blist>=1.3.6
Reading https://pypi.python.org/simple/blist/
Downloading https://files.pythonhosted.org/packages/6b/a8/dca5224abe81ccf8db81f8a2ca3d63e7a5fa7a86adc198d4e268c67ce884/blist-1.3.6.tar.gz#sha256=3a12c450b001bdf895b30ae818d4d6
d3f1552096b8c995f0fe0c74bef04d1fc3
Best match: blist 1.3.6
Processing blist-1.3.6.tar.gz
Writing C:\Users\_ADMNE~1.ARN\AppData\Local\Temp\easy_install-cliwa8zc\blist-1.3.6\setup.cfg
Running blist-1.3.6\setup.py -q bdist_egg --dist-dir C:\Users\_ADMNE~1.ARN\AppData\Local\Temp\easy_install-cliwa8zc\blist-1.3.6\egg-dist-tmp-bel17sg_
warning: no files found matching 'blist.rst'
_blist.c
blist/_blist.c(5994): error C2121: '#': invalid character: possibly the result of a macro expansion
blist/_blist.c(5994): error C2065: 'endif': undeclared identifier
blist/_blist.c(5994): warning C4047: 'function': 'Py_ssize_t *' differs in levels of indirection from 'Py_ssize_t'
blist/_blist.c(5994): warning C4024: 'PySlice_Unpack': different types for formal and actual parameter 2
blist/_blist.c(5994): warning C4024: 'PySlice_AdjustIndices': different types for formal and actual parameter 2
blist/_blist.c(6963): error C2121: '#': invalid character: possibly the result of a macro expansion
blist/_blist.c(6963): error C2065: 'endif': undeclared identifier
blist/_blist.c(6963): warning C4047: 'function': 'Py_ssize_t *' differs in levels of indirection from 'Py_ssize_t'
blist/_blist.c(6963): warning C4024: 'PySlice_Unpack': different types for formal and actual parameter 2
blist/_blist.c(6963): warning C4024: 'PySlice_AdjustIndices': different types for formal and actual parameter 2
blist/_blist.c(7743): fatal error C1070: mismatched #if/#endif pair in file 'c:\users\_adm.neil.arnold\appdata\local\temp\easy_install-cliwa8zc\blist-1.3.6\blist\_blist.c'
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
```

I have the follow components from Visual Studio installed:

- VC++ 2015.3 v140 toolset for desktop (x86,x64)
- VC++ 2017 v141 toolset (x86,x64)
- VC++ 2017 version 15.4 v14.11 toolset
- VC++ 2017 version 15.5 v14.12 toolset
- Visual C++ 2017 Redistributable Update
- Visual Studio C++ core features

Could someone tell me which specific components from VS 2017 I need to have installed to get this to install correctly or how to correct this specific issue?

Thanks.

**Comment by callahan22** [comment]
Installing

**Comment by callahan22** [comment]
Installing the latest version of Python seemed to resolve the install issues. However, I'm trying to run elastalert-create-index.exe as per the installtion steps and it's throwing an error below. There doesn't appear to be any step by step walkthroughs to get this running on Windows.

```
C:\Program Files (x86)\Python36-32\Scripts>elastalert-create-index.exe
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\Scripts\elastalert-create-index-script.py", line 11, in <module>
    load_entry_point('elastalert==0.1.29', 'console_scripts', 'elastalert-create-index')()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'elastalert'

```

**Comment by callahan22** [comment]
Trying to run elastalert on its own gives the following errors.

```
C:\Program Files (x86)\Python36-32>python -m elastalert.elastalert
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\elastalert\elastalert.py", line 1238
    raise EAException("Error querying for dashboard: %s" % (e)), None, sys.exc_info()[2]
                                                               ^
SyntaxError: invalid syntax
```
Running "elastalert" on it's own results in the same error.

Getting this installed and working is a lot more complex than I was expecting.

**Comment by ormam** [comment]
there are no scripts directory in the python directory

**Comment by srinivas946** [comment]
@callahan22 looking at the issue the problem with blist file better to download the appropriate wheel file from this link and run it. [blist_wheel](https://www.lfd.uci.edu/~gohlke/pythonlibs/#blist)
