### ISSUE TITLE
Can't create index.

### ISSUE THREAD

**Issue by sshaky2** [Yelp/elastalert#1671]
I got following error while running elastalert-create-index

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\elastalert-create-index-script.py", line 11, in <module>
    load_entry_point('elastalert==0.1.29', 'console_scripts', 'elastalert-create-index')()
  File "C:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "C:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "C:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\anaconda3\lib\site-packages\elastalert-0.1.29-py3.5.egg\elastalert\create_index.py", line 12, in <module>
ImportError: No module named 'auth'

**Comment by caleb15** [comment]
i also got `ImportError: No module named 'auth'` :(

**Comment by Qmando** [comment]
You need `aws-requests-auth` as shown in setup.py AND requirements.txt. Did you follow the installation instructions?

**Comment by caleb15** [comment]
yes, but I was using python 3. I found out that python 2 is required, switched to that, and now it's working. I was really surprised that elastalert still uses python 2 - it's going to be deprecated next year.

**Comment by Qmando** [comment]
I'll update it before https://pythonclock.org 🐌

**Comment by caleb15** [comment]
Thanks! That's great news.
