### ISSUE TITLE
elasticsearch.exceptions.NotFoundError when recreate index

### ISSUE THREAD

**Issue by ziru** [Yelp/elastalert#1675]
```
/opt/elastalert # elastalert-create-index --index elastalert_status --old-index "" --no-auth --recreat
e True
Elastic Version:6
Mapping used for string:{'type': 'keyword'}
Deleting index elastalert_status.
Deleting index elastalert_status_status.
Deleting index elastalert_status_silence.
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.1.30', 'console_scripts', 'elastalert-create-index')()
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.30-py2.7.egg/elastalert/create_index.py", line 242, in main
    es_index.delete(index_name)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 188, in delete
    params=params)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, u'index_not_found_exception', u'no such index')
```

**Comment by Qmando** [comment]
Delete the indices manually, anything starting with elastalert_, and then try to recreate this. 

Looks like if only half the indices get applied, you can't recreate it, because it tries to delete it. I'll fix this.

**Comment by rrana** [comment]
We ran into similar issue:

```/usr/local/bin/elastalert-create-index --host <elasticsearch-host-address> --port 80 --no-ssl --no-auth --url-prefix '' --index elastalert_status --recreate True```
```Name of existing index to copy? (Default None) 
Elastic Version:6
Mapping used for string:{'type': 'keyword'}
Deleting index elastalert_status.
Deleting index elastalert_status_status.
Deleting index elastalert_status_silence.
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 9, in <module>
    load_entry_point('elastalert==0.1.30', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert/create_index.py", line 242, in main
    es_index.delete(index_name)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 188, in delete
    params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, u'index_not_found_exception', u'no such index')
```

Deletion logic is not handling exception when the index doesn't exists or we used incorrect parameters in command?

To get a workaround we created all the required indexes before running the command:
```curl -XPUT http://<elasticsearch-host-address>/elastalert_status
curl -XPUT http://<elasticsearch-host-address>/elastalert_status_status
curl -XPUT http://<elasticsearch-host-address>/elastalert_status_error
curl -XPUT http://<elasticsearch-host-address>/elastalert_status_silence
curl -XPUT http://<elasticsearch-host-address>/elastalert_status_past
```

**Comment by Qmando** [comment]
How is this error even occurring??? at create_index.py", line 242
```
if es_index.exists(index_name):
    es_index.delete(index_name)
```
😠

**Comment by cseveer** [comment]
Thanks every one!, Here are the steps I followed to make it success!!

0. elastalert-create-index
1. curl -XPUT http://<elasticsearch-host-address>/elastalert_status_status
2. curl -XPUT http://<elasticsearch-host-address>/elastalert_status_error
3. curl -XPUT http://<elasticsearch-host-address>/elastalert_status_silence
4. curl -XPUT http://<elasticsearch-host-address>/elastalert_status_past

Once all 5 indices are created THEN follow below step:
curl -XPUT http://<elasticsearch-host-address>/elastalert-create-index --recreate True

With this you all have all the indices deleted and re-created with mapping, here is the output you get:
********************************
Elastic Version:6
Mapping used for string:{'type': 'keyword'}
Deleting index elastalert_status.
Deleting index elastalert_status_status.
Deleting index elastalert_status_silence.
Deleting index elastalert_status_error.
Deleting index elastalert_status_past.
New index elastalert_status created
Done!

**Comment by ziru** [comment]
@Qmando I believed 0.1.30 release contains this bug in `create_index.py`:

```
for index_name in index_names:
  if es_index.exists(index):
     print('Deleting index ' + index_name + '.')
     es_index.delete(index_name)
  es_index.create(index_name)
```

This bug got fixed later:
```
  if es_index.exists(index):
```         

=>

```
  if es_index.exists(index_name):
```

I think we just need a 0.1.31 release.

**Comment by Qmando** [comment]
Done

**Comment by stefk** [comment]
@Qmando, I can confirm the problem is gone in 0.1.31. Thanks :+1:
