### ISSUE TITLE
elastalert-test-rule with --data still tries to connect to the elasticsearch server

### ISSUE THREAD

**Issue by 0xdabbad00** [Yelp/elastalert#168]
When you run `elastalert-test-rule --data data.json myrule.yaml` it will still try to hit the elasticsearch instance defined in `myruyle.yaml`'s `es_host` setting, resulting in 

```
No handlers could be found for logger "elasticsearch"
Traceback (most recent call last):
...
File "elastalert/elastalert/config.py", line 235, in load_modules
    raise EAException('Error initializing rule %s: %s' % (rule['name'], e))
elastalert.util.EAException: Error initializing rule Osquery - new kext: Error searching for existing terms: ConnectionError(
('Connection failed.', gaierror(-2, 'Name or service not known'))) caused by: ConnectionError(('Connection failed.', gaierror
(-2, 'Name or service not known')))
```

The current work-around I'm using is to simply comment out the `es_host` in the rule file.  Instead, `elastalert-test-rule` should be smart enough to simply override bothering to connect to elasticsearch and just use the file data since it's not getting any data from elasticsearch anyway.

**Comment by christophetd** [comment]
Same behavior here:

```
bash-4.4# cat rule.yml                                                                                                                                          
index: my-index                                                                                                                                                 
name: Sample rule                                                                                                                                               
type: any                                                                                                                                                       
filter:                                                                                                                                                         
- term:                                                                                                                                                         
    foo: "bar"                                                                                                                                                  
alert:                                                                                                                                                          
- command                                                                                                                                                                                                                                                                                                             
command: [ "touch", "/tmp/alert" ]    
                                                                                                                          
bash-4.4# cat data.json
[
  {"foo": "bar", "_id": "hello", "@timestamp": "2018-11-13T10:00:00"}
]

bash-4.4# elastalert-test-rule --data data.json rule.yml
Successfully loaded Sample rule

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
WARNING:elasticsearch:GET http://localhost:14900/ [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 76, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=14900): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5adbbc0390>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

Does that mean that there's actually no way to run `elastalert-test-rule` without an actual connection to an ES cluster?

**Comment by christophetd** [comment]
Hello,

I'm still hitting the issue with Elastalert 0.1.39. What's more, it seems like the parameter passed to `--data` is simply ignored?

Any insights? This whole thing seems to totally defeat the whole purpose of elastalert-test-rule to me.
