### ISSUE TITLE
no mappping found for.....

### ISSUE THREAD

**Issue by stcoyleNJDGE** [Yelp/elastalert#1682]
when run elastalert with a rule i made (and after a successful test) i am getting this error:
```
ERROR:root:Error finding recent pending alerts: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on') {'sort': {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {$
Traceback (most recent call last):
  File "/root/elastalert/elastalert/elastalert.py", line 1461, in find_recent_pending_alerts
    size=1000)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 636, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on')
```

when i check the elastalert_status index for its mappings i return:
```
{
  "elastalert_status": {
    "mappings": {}
  }
}
```

would any one have the correct mappings so i can go ahead and use the PUT /elastalert_status/_mapping/elastalert_status to import the correct mappings?

i tried deleting and running elastalert-create-index a few times and still end up with no mappings 

thanks in advance.

**Comment by Qmando** [comment]
Hmm very odd.. The elastalert-create-index script should fail if Elasticsearch doesn't accept the mappings, but yet somehow this happens all the time.

You should be able to extract the mappings out of https://github.com/Yelp/elastalert/blob/master/elastalert/create_index.py. Hopefully it's somewhat obvious.

Let me know if this works for you.

**Comment by stcoyleNJDGE** [comment]
@Qmando ok i tried using these mappings :

```
PUT /elastalert_status/_mapping/elastalert_status
{
  "elastalert_status": {
    "mappings": {
      "silence": {
        "properties": {
          "rule_name": {
            "type": "string",
            "index": "not_analyzed"
          },
          "until": {
            "type": "date",
            "format": "dateOptionalTime"
          }
        }
      },
      "elastalert_status": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "rule_name": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      },
      "elastalert": {
        "properties": {
          "aggregate_id": {
            "type": "string",
            "index": "not_analyzed"
          },
          "match_body": {
            "type": "object",
            "enabled": false
          },
          "rule_name": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      },
      "elastalert_error": {
        "properties": {
          "data": {
            "type": "object",
            "enabled": false
          }
        }
      }
    }
  }
}
```

but then i got this error in return:
```

{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Root mapping definition has unsupported parameters:  [mappings : {silence={properties={rule_name={type=string, index=not_analyzed}, until={type=date, format=dateOptionalTime}}}, elastalert_status={properties={@timestamp={type=date, format=dateOptionalTime}, rule_name={type=string, index=not_analyzed}}}, elastalert={properties={aggregate_id={type=string, index=not_analyzed}, match_body={type=object, enabled=false}, rule_name={type=string, index=not_analyzed}}}, elastalert_error={properties={data={type=object, enabled=false}}}}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Root mapping definition has unsupported parameters:  [mappings : {silence={properties={rule_name={type=string, index=not_analyzed}, until={type=date, format=dateOptionalTime}}}, elastalert_status={properties={@timestamp={type=date, format=dateOptionalTime}, rule_name={type=string, index=not_analyzed}}}, elastalert={properties={aggregate_id={type=string, index=not_analyzed}, match_body={type=object, enabled=false}, rule_name={type=string, index=not_analyzed}}}, elastalert_error={properties={data={type=object, enabled=false}}}}]"
  },
  "status": 400
}
```


which is odd because I pulled them from that file you linked.

**Comment by Qmando** [comment]
What version of Elasticsearch are you using?

**Comment by stcoyleNJDGE** [comment]
@Qmando currently we are on 6.2.1
