### ISSUE TITLE
Unable to connect Elasticsearch using with SSL

### ISSUE THREAD

**Issue by ankit22550** [Yelp/elastalert#1684]
Hi Team,

Unable to connect Elasticsearch with SSL its show me below error if i enable SSL verfication True.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 76, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='node-1', port=9200): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",),))
WARNING:elasticsearch:GET https://node-1:9200/ [status:N/A request:0.043s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 76, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='node-1', port=9200): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",),))
WARNING:elasticsearch:GET https://node-1:9200/ [status:N/A request:0.039s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 76, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='node-1', port=9200): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",),))

**Comment by pedrofausto** [comment]
I'm having the same problem.
Setup:
ELK 6.2.x
Search-Guard Plugin installed.
Python 2.7.9
elastalert cloned from git

What is working:
ELk <-> Search Plugin OK

Whats is not working:
ELK <-> elastalert-create-index with argumento --no-verify-certs

command and arguments used:
python elastalert/create_index.py --no-verify-certs --config /opt/elastalert/config.yaml

Log:
---------------
/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py:63: UserWarning: Connecting to https://<elk-server>:9200 using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % self.base_url)
Traceback (most recent call last):
  File "elastalert/create_index.py", line 277, in <module>
    main()
  File "elastalert/create_index.py", line 129, in main
    esversion = es.info()["version"]["number"]
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 241, in info
    return self.transport.perform_request('GET', '/', params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    raise SSLError('N/A', str(e), e)
elasticsearch.exceptions.SSLError: ConnectionError(HTTPSConnectionPool(host='<elk-server>', port=9200): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",),))) caused by: SSLError(HTTPSConnectionPool(host='<elk-server>', port=9200): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",),)))

**Comment by Qmando** [comment]
Did you try setting ``ca_certs``? If the certificate is valid, it's likely that Python isn't connected to your sysyem's certificate store. You can also use ``verify_certs: false`` to ignore this.
