### ISSUE TITLE
ERROR:root:Error finding recent pending alerts: u'No mapping found for [alert_time] in order to sort on'

### ISSUE THREAD

**Issue by vitassecuriti** [Yelp/elastalert#1685]
In what the reason of a similar error in logs?
The index is created in case of start. I tried to delete completely the elastalert index, but everything repeats. Maybe someone faced already similar? there are ideas? 

>    elastalert version v.0.1.30 (from tag)

my elastalert.yml

>     es_host: elastalert
>     es_port: 9200
>     rules_folder: rules
>     run_every:
>          minutes: 1
>     buffer_time:
>          minutes: 1
>     writeback_index: elastalerttp
>     alert_time_limit:
>          days: 2

 my rule

>     name: Count events gt 500 per 5 minutes from nba191
>     type: frequency
>     index: logstash-*
>     query_delay:
>        minutes: 5
>     num_events: 500
>     timeframe:
>       minutes: 5
>     filter:
>     - query_string:
>           query: "logger_name: \"atc.stopwatch.ProfileExecutionAspect\" AND etime: [5000 TO *]"
>     alert:
>     - command
>     realert:
>       minutes: 5
>     exponential_realert:
>       hours: 3
>     command:
>     - "/opt/appuser/ElastAlert/monitor-appender/sendElastAlertEmail.sh"

after run elastaler a get log like:
```

    elastalert | WARNING:elasticsearch:GET 
    http://elastalert:9200/elastalerttp/elastalert/_search?size=1000 [status:400 request:0.019s]
    elastalert | ERROR:root:Error finding recent pending alerts: TransportError(400, 
    u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on') {'sort': 
    {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'alert_time': {'to': '2018-05- 
    08T15:38:22.999271Z', 'from': '2018-05-06T15:38:22.999225Z'}}}, 'must': {'query_string': {'query': 
    '!_exists_:aggregate_id AND alert_sent:false'}}}}}
    elastalert | Traceback (most recent call last):
    elastalert |   File "/opt/elastalert/elastalert.py", line 1461, in find_recent_pending_alerts
    elastalert |     size=1000)
    elastalert |   File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    elastalert |     return func(*args, params=params, **kwargs)
    elastalert |   File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 655, in search
    elastalert |     doc_type, '_search'), params=params, body=body)
    elastalert |   File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in 
    perform_request
    elastalert |     status, headers_response, data = connection.perform_request(method, url, params, body, 
    headers=headers, ignore=ignore, timeout=timeout)
    elastalert |   File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, 
    in perform_request
    elastalert |     self._raise_error(response.status_code, raw_data)
    elastalert |   File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in 
    _raise_error
    elastalert |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, 
    additional_info)
    elastalert | RequestError: TransportError(400, u'search_phase_execution_exception', u'No mapping 
    found for [alert_time] in order to sort on')
    elastalert | INFO:elastalert:Queried rule Count events gt 500 per 5 minutes from nba191 from 2018-05- 
    08 15:32 UTC to 2018-05-08 15:33 UTC: 0 / 0 hits
    elastalert | INFO:elastalert:Queried rule Count events gt 500 per 5 minutes from nba191 from 2018-05- 
    08 15:33 UTC to 2018-05-08 15:33 UTC: 0 / 0 hits
    elastalert | INFO:elastalert:Ran Count events gt 500 per 5 minutes from nba191 from 2018-05-08 15:32 
    UTC to 2018-05-08 15:33 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
    elastalert | INFO:elastalert:Sleeping for 59.952174 seconds
```

**Comment by Qmando** [comment]
Try recreating the index again.. This seems to happen all the time but I can't reproduce it on our cluster. Maybe it's time for me to actually [fix this TODO](https://github.com/Yelp/elastalert/blob/master/elastalert/create_index.py#L245) 🤣 

If this still doesn't work, you could try to apply the mappings manually. This is what it should end up looking like:
```
$ curl localhost:20778/elastalert_test/_mapping | jq .
{
  "elastalert_test": {
    "mappings": {
      "silence": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "rule_name": {
            "type": "string",
            "index": "not_analyzed"
          },
          "until": {
            "type": "date",
            "format": "dateOptionalTime"
          }
        }
      },
      "elastalert_status": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "rule_name": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      },
      "past_elastalert": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "aggregate_id": {
            "type": "string",
            "index": "not_analyzed"
          },
          "match_body": {
            "type": "object",
            "enabled": false
          },
          "rule_name": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      },
      "elastalert": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "aggregate_id": {
            "type": "string",
            "index": "not_analyzed"
          },
          "alert_time": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "match_body": {
            "type": "object",
            "enabled": false
          },
          "match_time": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "rule_name": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      },
      "elastalert_error": {
        "properties": {
          "@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
          },
          "data": {
            "type": "object",
            "enabled": false
          }
        }
      }
    }
  }
}
```

**Comment by vincenthuynh** [comment]
We hit this error as well on master. Tried recreating elastalert_status index but no luck.

**Comment by Qmando** [comment]
What version of elasticsearch are you guys using?

**Comment by vitassecuriti** [comment]
Elasticsearch version 6.2.4

**Comment by Qmando** [comment]
Please report the output of ``$ curl localhost:9200/elastalert_*/_mapping``

Also, the output of ``pip freeze | grep elasticsearch``

Also, the full output of running elastalert-create-index, after deleting the existing ones.

From your first error, ``http://elastalert:9200/elastalerttp/elastalert/_search`` URL is a Elasticsearch < 6.0 URL, because there is a separate type and index name.

**Comment by Qmando** [comment]
This is what it should look like after a fresh elasticsearch 6.2.4 install
```
$ curl localhost:14900
{
  "name" : "b3dJuEr",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "LbzSI_RfSpOZj5iYHeOZ9g",
  "version" : {
    "number" : "6.2.4",
    "build_hash" : "ccec39f",
    "build_date" : "2018-04-12T20:37:28.497551Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

curl localhost:14900/elastalert*/_mapping
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","index_uuid":"_na_","index":"elastalert*"}],"type":"index_not_found_exception","reason":"no such index","index_uuid":"_na_","index":"elastalert*"},"status":404}

$ elastalert-create-index
Enter Elasticsearch host: localhost
Enter Elasticsearch port: 14900
Use SSL? t/f:
Enter optional basic-auth username (or leave blank):
Enter optional basic-auth password (or leave blank):
Enter optional Elasticsearch URL prefix (prepends a string to the URL of every request):
New index name? (Default elastalert_status) elastalerttp
Name of existing index to copy? (Default None)
Elastic Version:6
Mapping used for string:{'type': 'keyword'}
New index elastalerttp created
Done!

$ curl localhost:14900/elastalert*/_mapping
{"elastalerttp":{"mappings":{"elastalert":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"aggregate_id":{"type":"keyword"},"alert_time":{"type":"date","format":"dateOptionalTime"},"match_body":{"type":"object","enabled":false},"match_time":{"type":"date","format":"dateOptionalTime"},"rule_name":{"type":"keyword"}}}}},"elastalerttp_error":{"mappings":{"elastalert_error":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"data":{"type":"object","enabled":false}}}}},"elastalerttp_status":{"mappings":{"elastalert_status":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"rule_name":{"type":"keyword"}}}}},"elastalerttp_past":{"mappings":{"past_elastalert":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"aggregate_id":{"type":"keyword"},"match_body":{"type":"object","enabled":false},"rule_name":{"type":"keyword"}}}}},"elastalerttp_silence":{"mappings":{"silence":{"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"rule_name":{"type":"keyword"},"until":{"type":"date","format":"dateOptionalTime"}}}}}}
```

**Comment by vitassecuriti** [comment]
The error was eliminated as soon as worked the rule trigger.the remaping did not pass
