### ISSUE TITLE
TypeError: execv() arg 2 must contain only strings. What can this error be connected to?

### ISSUE THREAD

**Issue by vitassecuriti** [Yelp/elastalert#1695]
docker version  Version:      17.06.2-ce
elastalert version v.0.1.30 (from tag)

my elastalert.yml

```
es_host: elastalert
es_port: 9200
rules_folder: rules
run_every:
     minutes: 1
buffer_time:
     minutes: 1
writeback_index: elastalerttp
alert_time_limit:
     days: 2

```
my rule

```
name: Count events gt 500 per 5 minutes
type: frequency
index: logstash-*

num_events: 500

timeframe:
  minutes: 5

filter:
- query_string:
      query: "HOSTNAME: \"NBD145\" AND logger_name: \"aProfileExecutionAspect\" AND CONTEXT_NAME: \"payments\" AND etime: [5000 TO *]"

alert:
- command

exponential_realert:
  hours: 3

command:
- "/opt/elastalert/monitor-appender/sendElastAlertEmail.sh"
- "Кличество полученных событий превышает 500 в 5 минут!"
- "http://kibana:5601/app/kibana#/discover/ee3bd7c0-52ce-11e8-b2a9-0744650f787c?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'{from}',mode:absolute,to:'{to}'))&_a=(columns:!(_source),filters:!(),index:'5e673610-4a33-11e8-b2a9-0744650f787c',interval:auto,query:(language:lucene,query:'HOSTNAME:\"NBD145\" AND logger_name: \"ProfileExecutionAspect\" AND CONTEXT_NAME:\"payments\" AND etime: [5000 TO *]'),sort:!('@timestamp',desc))"
- "0"
- "10"
- "email@mail.ru"
- "1"
- "23"
```

elasticsearch version 6.2.4

ElastAlert is launched, in logs is displayed

```
INFO:elastalert:Queried rule Count events gt 500 per 5 minutes from 2018-05-14 16:10 MSK to 2018-05-14 16:11 MSK: 0 / 0 hits
INFO:elastalert:Queried rule Count events gt 500 per 5 minutes from 2018-05-14 16:11 MSK to 2018-05-14 16:11 MSK: 0 / 0 hits
INFO:elastalert:Ran Count events gt 500 per 5 minutes from 2018-05-14 16:10 MSK to 2018-05-14 16:11 MSK: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59.926816 seconds
```

But when the trigger works, annunciator does not happen. in logs it is displayed

```

ERROR:root:Traceback (most recent call last):
  File "/opt/elastalert/elastalert.py", line 1282, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/opt/elastalert/elastalert.py", line 1371, in send_alert
    alert.alert(matches)
  File "alerts.py", line 902, in alert
    subp = subprocess.Popen(command, stdin=subprocess.PIPE, shell=self.shell)
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

ERROR:root:Uncaught exception running rule Count events gt 500 per 5 minutes from nba191: execv() arg 2 must contain only strings
INFO:elastalert:Rule Count events gt 500 per 5 minutes from nba191 disabled
```

What can this error be connected to?

**Comment by Qmando** [comment]
This is the error I would expect if you didn't have quotes around the numbers. I'm not sure why it's happening, because I copied your YAML exactly and it seemed to work. Maybe it would help to put a ``print command`` in alerts.py right before the subprocess.Popen command to see what exactly it's trying to use.

**Comment by danielpops** [comment]
Is it possible that the `&` in the url is being interpreted by bash?

**Comment by vitassecuriti** [comment]
> This is the error I would expect if you didn't have quotes around the numbers. I'm not sure why it's happening, because I copied your YAML exactly and it seemed to work. Maybe it would help to put a print command in alerts.py right before the subprocess.Popen command to see what exactly it's trying to use.

Sorry, I am poorly familiar with python. could not you specify, as where to insert to check your hypothesis?

**Comment by vitassecuriti** [comment]
@danielpops , If I correctly understood you, then hardly existence of the character "also" can be the cause.
The line URL is used as the parameter for a script which is caused when actuating the trigger (because of feature of our network, it is not possible to use the built-in functionality of annunciator). The error in a log appears at the time of actuating of the trigger, but before attempt to execute a notification command through a script.
Here the text of a script for notification

``` bash
#!/bin/bash
alertText="$1"
dateTo=$(date +%F"T"%T --date='now - '"$3"' minutes')
timeTo=$(date +%H --date='now - '"$3"' minutes')
dateFrom=$(date +%F"T"%T --date='now - '$[$3 + $4]' minutes')
KibanaDashboardUrl=$(echo "$2" | sed 's/{from}/'$dateFrom'/1;s/{to}/'$dateTo'/1')
alertBody="$KibanaDashboardUrl"

cd /opt/elastalert/monitor-appender
if [ "$timeTo" -ge "$6" ] && [ "$timeTo" -lt "$7" ]; then
   IFS=";"
   array=($(echo -e "$5"))
   for((i=0;i<${#array[@]};i++)); do
     export LC_ALL=ru_RU.UTF-8
     java -jar monitor-appender-1.0-SNAPSHOT.jar "${array[$i]}" "$alertText" "$alertBody" jdbc:h2:tcp://nba44.vimpelcom.ru/cm "cm" "cmroom" "ElastAlert" "NBA120" "ElastAlert"
   done
fi
```

**Comment by Qmando** [comment]
" put a ``print command`` in alerts.py right before the subprocess.Popen"

```
File "alerts.py", line 902, in alert
    subp = subprocess.Popen(command, stdin=subprocess.PIPE, shell=self.shell)
```

This should print out a list ``["/opt/elastalert/monitor-appender/sendElastAlertEmail.sh", "Кличество .... ", ....]``. Report back with what it outputs.

**Comment by vitassecuriti** [comment]
I added print output in  in alerts.py

```python
    print("This is error message ====================")
    print(command)
    print("This is error message end ===================")
```

In a log it is visible only

```
elastalert | INFO:elastalert:Queried rule TESTTTT from 2018-05-29 10:57 UTC to 2018-05-29 10:57 UTC: 0 / 0 hits
elastalert | INFO:elastalert:Ran TESTTTT from 2018-05-29 10:56 UTC to 2018-05-29 10:57 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
elastalert | INFO:elastalert:Sleeping for 59.97303 seconds
elastalert | INFO:elastalert:Queried rule TESTTTT from 2018-05-29 10:57 UTC to 2018-05-29 10:58 UTC: 12 / 12 hits
elastalert | INFO:elastalert:Queried rule TESTTTT from 2018-05-29 10:58 UTC to 2018-05-29 10:58 UTC: 12 / 0 hits
elastalert | ERROR:root:Traceback (most recent call last):
elastalert |   File "/opt/elastalert/elastalert.py", line 1282, in alert
elastalert |     return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
elastalert |   File "/opt/elastalert/elastalert.py", line 1371, in send_alert
elastalert |     alert.alert(matches)
elastalert |   File "alerts.py", line 902, in alert
elastalert |     print("This is error message ====================")
elastalert |   File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
elastalert |     errread, errwrite)
elastalert |   File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
elastalert |     raise child_exception
elastalert | TypeError: execv() arg 2 must contain only strings
elastalert |
elastalert | ERROR:root:Uncaught exception running rule TESTTTT: execv() arg 2 must contain only strings
elastalert | INFO:elastalert:Rule TESTTTT disabled
elastalert | INFO:elastalert:Ran TESTTTT from 2018-05-29 10:57 UTC to 2018-05-29 10:58 UTC: 12 query hits (0 already seen), 1 matches, 0 alerts sent
```

**Comment by vitassecuriti** [comment]
I deleted the files specified by you. I added command output. But nothing changed except that business did not reach a command output.

```
INFO:elastalert:Queried rule TESTTTT 12 from 2018-05-30 12:01 UTC to 2018-05-30 12:02 UTC: 30 / 30 hits
INFO:elastalert:Queried rule TESTTTT 12 from 2018-05-30 12:02 UTC to 2018-05-30 12:02 UTC: 30 / 0 hits
ERROR:root:Traceback (most recent call last):
  File "/opt/elastalert/elastalert.py", line 1282, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/opt/elastalert/elastalert.py", line 1371, in send_alert
    alert.alert(matches)
  File "alerts.py", line 905, in alert
    subp = subprocess.Popen(command, stdin=subprocess.PIPE, shell=self.shell)
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

ERROR:root:Uncaught exception running rule TESTTTT 12: execv() arg 2 must contain only strings
INFO:elastalert:Rule TESTTTT 12 disabled
```

**Comment by vitassecuriti** [comment]
I try to understand everything that not so.
I added outputs to the elastalert.py file before line 1285 **_return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)_**

```python
    print("elastalert alert 1285 ==============")
    print(self)
    print(matches)
    print(rule)
    print("elastalert alert 1285 ============== end")
```

and lines of an output before line 1371 **_alert.alert(matches)_**

```python
    print(" send_alert 1371 =============")
    print(matches)
    print(" send_alert 1371 ============= end")
```
Text of an output
```
elastalert | elastalert alert 1285 ==============
elastalert | <__main__.ElastAlerter instance at 0x7efd8eb7c5a8>
elastalert | [{u'thread_name': u'main', '_type': u'doc', '_index': u'logstash-2018.05.31', 'num_hits': 100, u'@timestamp': '2018-05-31T12:20:09.724Z', u'level': u'INFO', u'host': u'192.168.225.206', u'level_value': 20000, u'logger_name': u'STASH', 'num_matches': 10, u'CONTEXT_NAME': u'kibana-test', u'message': u'test', '_id': u'Bl0ktmMBVE_3FkStFYuJ', u'@version': 1}]
elastalert | {'es_port': 9200, 'scan_subdirectories': True, 'hipchat_from': '', 'timestamp_type': 'iso', 'aggregate_alert_time': {}, 'agg_matches': [], 'num_events': 10, 'original_starttime': datetime.datetime(2018, 5, 31, 12, 19, 20, 957256, tzinfo=tzutc()), 'buffer_time': datetime.timedelta(0, 60), 'previous_endtime': datetime.datetime(2018, 5, 31, 12, 19, 20, 957256, tzinfo=tzutc()), 'owner': '', '_source_enabled': True, 'max_query_size': 10000, 'hipchat_ignore_ssl_errors': False, 'index': 'logstash-*', 'ts_to_dt': <function ts_to_dt at 0x7efd8f0fee60>, 'current_aggregate_id': {}, 'writeback_index': 'elastalerttp', 'use_local_time': True, 'scroll_keepalive': '30s', 'match_enhancements': [], 'hipchat_notify': True, 'rule_file': 'rules/testtttt.yaml', 'timeframe': datetime.timedelta(0, 300), 'include': ['@timestamp', '*'], 'type': <ruletypes.FrequencyRule object at 0x7efd8e2b87d0>, 'description': '', 'query_delay': datetime.timedelta(0), 'aggregation': datetime.timedelta(0), 'alert': [<alerts.CommandAlerter object at 0x7efd904a45d0>], 'five': True, 'alert_time_limit': datetime.timedelta(2), 'run_every': datetime.timedelta(0, 60), 'old_query_limit': datetime.timedelta(7), 'doc_type': u'doc', 'hipchat_domain': 'api.hipchat.com', 'dt_to_ts': <function dt_to_ts at 0x7efd8f0feed8>, 'name': 'TESTTTT 12', 'hipchat_msg_color': 'red', 'realert': datetime.timedelta(0, 60), 'disable_rules_on_error': True, 'timestamp_field': '@timestamp', 'filter': [{'query_string': {'query': 'CONTEXT_NAME: "kibana-test"'}}], 'command': ['/opt/elastalert/monitor-appender/sendElastAlertEmail.sh', u'\u0414\u043b\u044f "trusted payments on NBA191" \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u043d\u044b\u0445 \u0441\u043e\u0431\u044b\u0442\u0438\u0439 \u043f\u0440\u0435\u0432\u044b\u0448\u0430\u0435\u0442 500 \u0432 5 \u043c\u0438\u043d\u0443\u0442!', 'TEST CHARACTERS', '0', '10', 'vitassecuriti@mail.ru;vitassecuriti@mail.ru', '1', '23'], 'timestamp_format': '%Y-%m-%dT%H:%M:%SZ', 'starttime': datetime.datetime(2018, 5, 31, 12, 20, 20, 957256, tzinfo=tzutc()), 'rules_folder': 'rules', 'processed_hits': {u'Dl4ktmMBVE_3FkStNUlU': datetime.datetime(2018, 5, 31, 12, 20, 17, 801000, tzinfo=tzutc()), u'B10ktmMBVE_3FkStFYuJ': datetime.datetime(2018, 5, 31, 12, 20, 9, 718000, tzinfo=tzutc()), u'W14ktmMBVE_3FkStNUyv': datetime.datetime(2018, 5, 31, 12, 20, 17, 800000, tzinfo=tzutc()), u'ol0ktmMBVE_3FkStJvMN': datetime.datetime(2018, 5, 31, 12, 20, 13, 754000, tzinfo=tzutc()), u'pV0ktmMBVE_3FkStJvMN': datetime.datetime(2018, 5, 31, 12, 20, 13, 759000, tzinfo=tzutc()), u'UF4ktmMBVE_3FkStLiJo': datetime.datetime(2018, 5, 31, 12, 20, 15, 777000, tzinfo=tzutc()), u'TF4ktmMBVE_3FkStNU6y': datetime.datetime(2018, 5, 31, 12, 20, 17, 804000, tzinfo=tzutc()), u'm10ktmMBVE_3FkStHcG5': datetime.datetime(2018, 5, 31, 12, 20, 11, 738000, tzinfo=tzutc()), u'nV0ktmMBVE_3FkStIdqH': datetime.datetime(2018, 5, 31, 12, 20, 12, 743000, tzinfo=tzutc()), u'GV0ktmMBVE_3FkStGqcj': datetime.datetime(2018, 5, 31, 12, 20, 10, 733000, tzinfo=tzutc()), u'_10ktmMBVE_3FkStFYqJ': datetime.datetime(2018, 5, 31, 12, 20, 9, 601000, tzinfo=tzutc()), u'nF0ktmMBVE_3FkStJvMM': datetime.datetime(2018, 5, 31, 12, 20, 13, 756000, tzinfo=tzutc()), u'n10ktmMBVE_3FkStHcG5': datetime.datetime(2018, 5, 31, 12, 20, 11, 739000, tzinfo=tzutc()), u'x14ktmMBVE_3FkStLiJo': datetime.datetime(2018, 5, 31, 12, 20, 15, 772000, tzinfo=tzutc()), u'pF0ktmMBVE_3FkStJvMN': datetime.datetime(2018, 5, 31, 12, 20, 13, 755000, tzinfo=tzutc()), u'F10ktmMBVE_3FkStGqcj': datetime.datetime(2018, 5, 31, 12, 20, 10, 733000, tzinfo=tzutc()), u'Bl0ktmMBVE_3FkStGqcj': datetime.datetime(2018, 5, 31, 12, 20, 10, 725000, tzinfo=tzutc()), u'EV0ktmMBVE_3FkStIdmF': datetime.datetime(2018, 5, 31, 12, 20, 12, 745000, tzinfo=tzutc()), u'yV4ktmMBVE_3FkStKQfe': datetime.datetime(2018, 5, 31, 12, 20, 14, 764000, tzinfo=tzutc()), u'tV4ktmMBVE_3FkStNVC2': datetime.datetime(2018, 5, 31, 12, 20, 17, 800000, tzinfo=tzutc()), u'Al0ktmMBVE_3FkStFYuJ': datetime.datetime(2018, 5, 31, 12, 20, 9, 721000, tzinfo=tzutc()), u'eV4ktmMBVE_3FkStOWMX': datetime.datetime(2018, 5, 31, 12, 20, 18, 807000, tzinfo=tzutc()), u'WV4ktmMBVE_3FkStNUyv': datetime.datetime(2018, 5, 31, 12, 20, 17, 803000, tzinfo=tzutc()), u'oV0ktmMBVE_3FkStJvMN': datetime.datetime(2018, 5, 31, 12, 20, 13, 758000, tzinfo=tzutc()), u'BV0ktmMBVE_3FkStFYuJ': datetime.datetime(2018, 5, 31, 12, 20, 9, 717000, tzinfo=tzutc()), u'RF4ktmMBVE_3FkStMTTg': datetime.datetime(2018, 5, 31, 12, 20, 16, 788000, tzinfo=tzutc()), u'nV0ktmMBVE_3FkStHcG5': datetime.datetime(2018, 5, 31, 12, 20, 11, 739000, tzinfo=tzutc()), u'JF4ktmMBVE_3FkStMTjt': datetime.datetime(2018, 5, 31, 12, 20, 16, 788000, tzinfo=tzutc()), u'n10ktmMBVE_3FkStJvMM': datetime.datetime(2018, 5, 31, 12, 20, 13, 759000, tzinfo=tzutc()), u'AV0ktmMBVE_3FkStFYuJ': datetime.datetime(2018, 5, 31, 12, 20, 9, 719000, tzinfo=tzutc()), u'hV4ktmMBVE_3FkStLiRs': datetime.datetime(2018, 5, 31, 12, 20, 15, 773000, tzinfo=tzutc()), u'cV4ktmMBVE_3FkStLiZv': datetime.datetime(2018, 5, 31, 12, 20, 15, 779000, tzinfo=tzutc()), u'iV0ktmMBVE_3FkStIdqH': datetime.datetime(2018, 5, 31, 12, 20, 12, 749000, tzinfo=tzutc()), u'914ktmMBVE_3FkStLiNr': datetime.datetime(2018, 5, 31, 12, 20, 15, 773000, tzinfo=tzutc()), u'fV4ktmMBVE_3FkStMTjt': datetime.datetime(2018, 5, 31, 12, 20, 16, 786000, tzinfo=tzutc()), u'yF0ktmMBVE_3FkStIdmG': datetime.datetime(2018, 5, 31, 12, 20, 12, 750000, tzinfo=tzutc()), u'Ll4ktmMBVE_3FkStKQzj': datetime.datetime(2018, 5, 31, 12, 20, 14, 769000, tzinfo=tzutc()), u'j14ktmMBVE_3FkStLiFn': datetime.datetime(2018, 5, 31, 12, 20, 15, 774000, tzinfo=tzutc()), u'cV4ktmMBVE_3FkStLiBm': datetime.datetime(2018, 5, 31, 12, 20, 15, 771000, tzinfo=tzutc()), u'wV4ktmMBVE_3FkStKQzl': datetime.datetime(2018, 5, 31, 12, 20, 14, 766000, tzinfo=tzutc()), u'nF0ktmMBVE_3FkStHcG5': datetime.datetime(2018, 5, 31, 12, 20, 11, 735000, tzinfo=tzutc()), u'oV0ktmMBVE_3FkStHcG5': datetime.datetime(2018, 5, 31, 12, 20, 11, 740000, tzinfo=tzutc()), u'zF4ktmMBVE_3FkStKQjg': datetime.datetime(2018, 5, 31, 12, 20, 14, 765000, tzinfo=tzutc()), u'mV0ktmMBVE_3FkStHcG5': datetime.datetime(2018, 5, 31, 12, 20, 11, 738000, tzinfo=tzutc()), u'I10ktmMBVE_3FkStGqcj': datetime.datetime(2018, 5, 31, 12, 20, 10, 728000, tzinfo=tzutc()), u'SV4ktmMBVE_3FkStOWEU': datetime.datetime(2018, 5, 31, 12, 20, 18, 807000, tzinfo=tzutc()), u'Xl4ktmMBVE_3FkStOWEV': datetime.datetime(2018, 5, 31, 12, 20, 18, 809000, tzinfo=tzutc()), u'oF0ktmMBVE_3FkStJvMN': datetime.datetime(2018, 5, 31, 12, 20, 13, 755000, tzinfo=tzutc()), u'D10ktmMBVE_3FkStGqcj': datetime.datetime(2018, 5, 31, 12, 20, 10, 731000, tzinfo=tzutc()), u'gF4ktmMBVE_3FkStOWEV': datetime.datetime(2018, 5, 31, 12, 20, 18, 805000, tzinfo=tzutc()), u'G10ktmMBVE_3FkStGqcj': datetime.datetime(2018, 5, 31, 12, 20, 10, 727000, tzinfo=tzutc()), u'h10ktmMBVE_3FkStIdqH': datetime.datetime(2018, 5, 31, 12, 20, 12, 749000, tzinfo=tzutc()), u'E10ktmMBVE_3FkStIdmF': datetime.datetime(2018, 5, 31, 12, 20, 12, 748000, tzinfo=tzutc()), u'iF0ktmMBVE_3FkStIdqH': datetime.datetime(2018, 5, 31, 12, 20, 12, 749000, tzinfo=tzutc()), u'xF4ktmMBVE_3FkStNVG4': datetime.datetime(2018, 5, 31, 12, 20, 17, 803000, tzinfo=tzutc()), u'Fl4ktmMBVE_3FkStMTvw': datetime.datetime(2018, 5, 31, 12, 20, 16, 783000, tzinfo=tzutc()), u'BF0ktmMBVE_3FkStFYuJ': datetime.datetime(2018, 5, 31, 12, 20, 9, 723000, tzinfo=tzutc()), u'nl0ktmMBVE_3FkStHcG5': datetime.datetime(2018, 5, 31, 12, 20, 11, 736000, tzinfo=tzutc()), u'hl0ktmMBVE_3FkStIdqH': datetime.datetime(2018, 5, 31, 12, 20, 12, 749000, tzinfo=tzutc()), u'1F4ktmMBVE_3FkStOWIW': datetime.datetime(2018, 5, 31, 12, 20, 18, 808000, tzinfo=tzutc()), u'2V4ktmMBVE_3FkStLiBm': datetime.datetime(2018, 5, 31, 12, 20, 15, 774000, tzinfo=tzutc()), u'CF0ktmMBVE_3FkStFYuJ': datetime.datetime(2018, 5, 31, 12, 20, 9, 718000, tzinfo=tzutc()), u'R14ktmMBVE_3FkStMTzx': datetime.datetime(2018, 5, 31, 12, 20, 16, 785000, tzinfo=tzutc()), u'0F4ktmMBVE_3FkStMTrw': datetime.datetime(2018, 5, 31, 12, 20, 16, 786000, tzinfo=tzutc()), u'814ktmMBVE_3FkStOWMY': datetime.datetime(2018, 5, 31, 12, 20, 18, 806000, tzinfo=tzutc()), u'814ktmMBVE_3FkStLiJp': datetime.datetime(2018, 5, 31, 12, 20, 15, 774000, tzinfo=tzutc()), u'AF0ktmMBVE_3FkStFYuJ': datetime.datetime(2018, 5, 31, 12, 20, 9, 714000, tzinfo=tzutc()), u'Gl4ktmMBVE_3FkStOWIW': datetime.datetime(2018, 5, 31, 12, 20, 18, 810000, tzinfo=tzutc()), u'El0ktmMBVE_3FkStIdmF': datetime.datetime(2018, 5, 31, 12, 20, 12, 747000, tzinfo=tzutc()), u'il0ktmMBVE_3FkStIdqH': datetime.datetime(2018, 5, 31, 12, 20, 12, 749000, tzinfo=tzutc()), u'cl4ktmMBVE_3FkStMTTj': datetime.datetime(2018, 5, 31, 12, 20, 16, 785000, tzinfo=tzutc()), u'mF0ktmMBVE_3FkStHcG5': datetime.datetime(2018, 5, 31, 12, 20, 11, 737000, tzinfo=tzutc()), u'cV4ktmMBVE_3FkStOWAT': datetime.datetime(2018, 5, 31, 12, 20, 18, 808000, tzinfo=tzutc()), u'JF4ktmMBVE_3FkStNUuu': datetime.datetime(2018, 5, 31, 12, 20, 17, 799000, tzinfo=tzutc()), u'fF4ktmMBVE_3FkStKQfe': datetime.datetime(2018, 5, 31, 12, 20, 14, 768000, tzinfo=tzutc()), u'ql4ktmMBVE_3FkStNU2x': datetime.datetime(2018, 5, 31, 12, 20, 17, 802000, tzinfo=tzutc()), u'TV4ktmMBVE_3FkStMTfr': datetime.datetime(2018, 5, 31, 12, 20, 16, 787000, tzinfo=tzutc()), u'Ql4ktmMBVE_3FkStMTTg': datetime.datetime(2018, 5, 31, 12, 20, 16, 787000, tzinfo=tzutc()), u'KF0ktmMBVE_3FkStGqcj': datetime.datetime(2018, 5, 31, 12, 20, 10, 730000, tzinfo=tzutc()), u'FF0ktmMBVE_3FkStGqcj': datetime.datetime(2018, 5, 31, 12, 20, 10, 732000, tzinfo=tzutc()), u'vl4ktmMBVE_3FkStMTfs': datetime.datetime(2018, 5, 31, 12, 20, 16, 787000, tzinfo=tzutc()), u'wl4ktmMBVE_3FkStKQvj': datetime.datetime(2018, 5, 31, 12, 20, 14, 770000, tzinfo=tzutc()), u'nl0ktmMBVE_3FkStJvMM': datetime.datetime(2018, 5, 31, 12, 20, 13, 757000, tzinfo=tzutc()), u'nV0ktmMBVE_3FkStJvMM': datetime.datetime(2018, 5, 31, 12, 20, 13, 758000, tzinfo=tzutc()), u'Cl4ktmMBVE_3FkStKQri': datetime.datetime(2018, 5, 31, 12, 20, 14, 767000, tzinfo=tzutc()), u'4l4ktmMBVE_3FkStLiZw': datetime.datetime(2018, 5, 31, 12, 20, 15, 774000, tzinfo=tzutc()), u'Il0ktmMBVE_3FkStGqcj': datetime.datetime(2018, 5, 31, 12, 20, 10, 729000, tzinfo=tzutc()), u'jF4ktmMBVE_3FkStKQjg': datetime.datetime(2018, 5, 31, 12, 20, 14, 767000, tzinfo=tzutc()), u'ml0ktmMBVE_3FkStHcG5': datetime.datetime(2018, 5, 31, 12, 20, 11, 735000, tzinfo=tzutc()), u'HF0ktmMBVE_3FkStGqcj': datetime.datetime(2018, 5, 31, 12, 20, 10, 729000, tzinfo=tzutc()), u'A10ktmMBVE_3FkStFYuJ': datetime.datetime(2018, 5, 31, 12, 20, 9, 720000, tzinfo=tzutc()), u'o10ktmMBVE_3FkStJvMN': datetime.datetime(2018, 5, 31, 12, 20, 13, 758000, tzinfo=tzutc()), u'7F4ktmMBVE_3FkStNVC2': datetime.datetime(2018, 5, 31, 12, 20, 17, 800000, tzinfo=tzutc()), u'Bl0ktmMBVE_3FkStFYuJ': datetime.datetime(2018, 5, 31, 12, 20, 9, 724000, tzinfo=tzutc()), u't14ktmMBVE_3FkStKQzl': datetime.datetime(2018, 5, 31, 12, 20, 14, 763000, tzinfo=tzutc()), u'MV4ktmMBVE_3FkStKQzj': datetime.datetime(2018, 5, 31, 12, 20, 14, 769000, tzinfo=tzutc()), u'Hl4ktmMBVE_3FkStOWUZ': datetime.datetime(2018, 5, 31, 12, 20, 18, 809000, tzinfo=tzutc()), u'oF0ktmMBVE_3FkStHcG5': datetime.datetime(2018, 5, 31, 12, 20, 11, 737000, tzinfo=tzutc()), u'eF4ktmMBVE_3FkStOWQY': datetime.datetime(2018, 5, 31, 12, 20, 18, 809000, tzinfo=tzutc()), u'GV4ktmMBVE_3FkStNVC2': datetime.datetime(2018, 5, 31, 12, 20, 17, 801000, tzinfo=tzutc())}, 'es_host': 'nba120.vimpelcom.ru', 'priority': '2'}
elastalert | elastalert alert 1285 ============== end
elastalert |  send_alert 1374 =============
elastalert | [{u'thread_name': u'main', '_type': u'doc', '_index': u'logstash-2018.05.31', 'num_hits': 100, u'@timestamp': '2018-05-31T12:20:09.724Z', u'level': u'INFO', u'host': u'192.168.225.206', u'level_value': 20000, u'logger_name': u'STASH', 'num_matches': 10, u'CONTEXT_NAME': u'kERROR:root:Traceback (most recent call last):
elastalert |   File "/opt/elastalert/elastalert.py", line 1290, in alert
elastalert |     return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
elastalert |   File "/opt/elastalert/elastalert.py", line 1382, in send_alert
elastalert |     alert.alert(matches)
elastalert |   File "alerts.py", line 906, in alert
elastalert |     subp = subprocess.Popen(command, stdin=subprocess.PIPE, shell=self.shell)
elastalert |   File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
elastalert |     errread, errwrite)
elastalert |   File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
elastalert |     raise child_exception
elastalert | TypeError: execv() arg 2 must contain only strings
elastalert |
elastalert | ERROR:root:Uncaught exception running rule TESTTTT 12: execv() arg 2 must contain only strings
elastalert | INFO:elastalert:Rule TESTTTT 12 disabled
```

**Comment by vitassecuriti** [comment]
What Python version shall stand on the machine?
