### ISSUE TITLE
OverflowError: signed integer is greater than maximum

### ISSUE THREAD

**Issue by quan0012** [Yelp/elastalert#1697]
I use metric_aggregation to monitor my service, my timestamp field format is unix_ms, and I set "timestamp_type: unix_ms" in my yml.
but I got this error when "rule_inst.add_aggregation_data(data)", the full stack is below, I think this is because the method_(ts_to_dt(timestamp))_ can not parse the unix_ms. 
Is this a bug? how can I fix it ?

ERROR:root:Traceback (most recent call last):
  File "/home/ark/app/elastalert/elastalert/elastalert.py", line 1126, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/home/ark/app/elastalert/elastalert/elastalert.py", line 816, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/home/ark/app/elastalert/elastalert/elastalert.py", line 620, in run_query
    rule_inst.add_aggregation_data(data)
  File "elastalert/ruletypes.py", line 930, in add_aggregation_data
    self.unwrap_term_buckets(timestamp, payload_data['bucket_aggs']['buckets'])
  File "elastalert/ruletypes.py", line 946, in unwrap_term_buckets
    self.unwrap_interval_buckets(timestamp, term_data['key'], term_data['interval_aggs']['buckets'])
  File "elastalert/ruletypes.py", line 938, in unwrap_interval_buckets
    elastalert_logger.info('ts: %s' % ts_to_dt(interval_data['key_as_string']))
  File "elastalert/util.py", line 112, in ts_to_dt
    dt = dateutil.parser.parse(timestamp)
  File "/usr/lib/python2.7/site-packages/python_dateutil-2.6.1-py2.7.egg/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/lib/python2.7/site-packages/python_dateutil-2.6.1-py2.7.egg/dateutil/parser.py", line 578, in parse
    if cday > monthrange(cyear, cmonth)[1]:
  File "/usr/lib64/python2.7/calendar.py", line 121, in monthrange
    day1 = weekday(year, month, 1)
  File "/usr/lib64/python2.7/calendar.py", line 113, in weekday
    return datetime.date(year, month, day).weekday()
OverflowError: signed integer is greater than maximum

**Comment by Qmando** [comment]
This looks like a bug. A funny one! The metric aggregation rule type is bypassing ``timestamp_format`` in this one line and using the default timestamp parser, which is using ISO8601 format. In ISO8601 format, the first number is the year, so it's trying to create an object for year ~ 1526507252784. 

The fix is to get the most recent version of elastalert, then apply this diff
```
--- a/elastalert/ruletypes.py
+++ b/elastalert/ruletypes.py
@@ -934,7 +934,7 @@ class BaseAggregationRule(RuleType):
     def unwrap_interval_buckets(self, timestamp, query_key, interval_buckets):
         for interval_data in interval_buckets:
             # Use bucket key here instead of start_time for more accurate match timestamp
-            self.check_matches(ts_to_dt(interval_data['key_as_string']), query_key, interval_data)
+            self.check_matches(self.rules['ts_to_dt'](interval_data['key_as_string']), query_key, interval_data)
```

I'll try to get this fixed in master ASAP, but it looks like there's a couple other places.

**Comment by quan0012** [comment]
ok, thank you
