### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'rules/jira.yaml'

### ISSUE THREAD

**Issue by stevegszabo** [Yelp/elastalert#1706]
https://github.com/Yelp/elastalert/commit/3e71527e410396f56ff57346b9f9af65f7d2ab0e

This change seems to break when we place a jira.yaml config one level above the rules directory. On startup elastalert fails to load the jira account config as it expects it to be under rules. If we place the config under rules it fails to load the config as it expects it to be rule.

```
INFO:elastalert:Found 7 unique values for oiqhash
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/elastalert/elastalert.py", line 1861, in main
    client = ElastAlerter(args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert/elastalert.py", line 130, in __init__
    self.conf = load_rules(self.args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert/config.py", line 477, in load_rules
    rule = load_configuration(rule_file, conf, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert/config.py", line 117, in load_configuration
    load_modules(rule, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert/config.py", line 362, in load_modules
    rule['alert'] = load_alerts(rule, alert_field=rule['alert'])
  File "/usr/local/lib/python2.7/dist-packages/elastalert/config.py", line 420, in load_alerts
    alert_field = [create_alert(a, b) for a, b in alert_field]
  File "/usr/local/lib/python2.7/dist-packages/elastalert/config.py", line 411, in create_alert
    return alert_class(alert_config)
  File "/usr/local/lib/python2.7/dist-packages/elastalert/alerts.py", line 539, in __init__
    self.get_account(self.rule['jira_account_file'])
  File "/usr/local/lib/python2.7/dist-packages/elastalert/alerts.py", line 301, in get_account
    account_conf = yaml_loader(account_file_path)
  File "/usr/local/lib/python2.7/dist-packages/staticconf/loader.py", line 167, in yaml_loader
    with open(filename) as fh:
IOError: [Errno 2] No such file or directory: 'rules/jira.yaml'
```

**Comment by stevegszabo** [comment]
If we place the account config above the rules directory we need to use:

jira_account_file: ../jira.yaml

This works
