### ISSUE TITLE
TransportError 411

### ISSUE THREAD

**Issue by lanzehao** [Yelp/elastalert#1720]
Hi, I have just installed elastalert, and I meet one error under. It seems that I used wrong query, but I can't find where my mistake is, plz help.

es version: 5.5.1
es-alert: clone the last version form github
and my rule file is like:
    type: frequency
    index: balance
    num_events: 2
    timeframe:
        minutes: 5
    filter:
    - query_string:
        query: "type: ex*"
    alert:
        - "email"

and the error is like:

``` 

WARNING:elasticsearch:GET http://10.62.12.59:9200/elastalert_status/elastalert/_search?size=1000 [status:411 request:0.007s]

WARNING:elasticsearch:Undecodable raw error response from server: No JSON object could be decoded

ERROR:root:Error finding recent pending alerts: TransportError(411, u'<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html><head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<title>ERROR: The requested URL could not be retrieved</title>\n<style type="text/css"><!-- \n /*\n Stylesheet for Squid Error pages\n Adapted from design by Free CSS Templates\n http://www.freecsstemplates.org\n Released for free under a Creative Commons Attribution 2.5 License\n*/\n\n/* Page basics */\n* {\n\tfont-family: verdana, sans-serif;\n}\n\nhtml body {\n\tmargin: 0;\n\tpadding: 0;\n\tbackground: #efefef;\n\tfont-size: 12px;\n\tcolor: #1e1e1e;\n}\n\n/* Page displayed title area */\n#titles {\n\tmargin-left: 15px;\n\tpadding: 10px;\n\tpadding-left: 100px;\n\tbackground: url(\'http://www.squid-cache.org/Artwork/SN.png\') no-repeat left;\n}\n\n/* initial title */\n#titles h1 {\n\tcolor: #000000;\n}\n#titles h2 {\n\tcolor: #000000;\n}\n\n/* special event: FTP success page titles */\n#titles ftpsuccess {\n\tbackground-color:#00ff00;\n\twidth:100%;\n}\n\n/* Page displayed body content area */\n#content {\n\tpadding: 10px;\n\tbackground: #ffffff;\n}\n\n/* General text */\np {\n}\n\n/* error brief description */\n#error p {\n}\n\n/* some data which may have caused the problem */\n#data {\n}\n\n/* the error message received from the system or other software */\n#sysmsg {\n}\n\npre {\n    font-family:sans-serif;\n}\n\n/* special event: FTP / Gopher directory listing */\n#dirmsg {\n    font-family: courier;\n    color: black;\n    font-size: 10pt;\n}\n#dirlisting {\n    margin-left: 2%;\n    margin-right: 2%;\n}\n#dirlisting tr.entry td.icon,td.filename,td.size,td.date {\n    border-bottom: groove;\n}\n#dirlisting td.size {\n    width: 50px;\n    text-align: right;\n    padding-right: 5px;\n}\n\n/* horizontal lines */\nhr {\n\tmargin: 0;\n}\n\n/* page displayed footer area */\n#footer {\n\tfont-size: 9px;\n\tpadding-left: 10px;\n}\n\n\nbody\n:lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; }\n:lang(he) { direction: rtl; }\n --></style>\n</head><body id=ERR_INVALID_REQ>\n<div id="titles">\n<h1>ERROR</h1>\n<h2>The requested URL could not be retrieved</h2>\n</div>\n<hr>\n\n<div id="content">\n<p><b>Invalid Request</b> error was encountered while trying to process the request:</p>\n\n<blockquote id="data">\n<pre>GET /elastalert_status/elastalert/_search?size=1000 HTTP/1.1\nHost: 10.62.12.59:9200\r\nAccept-Encoding: identity\r\nContent-Type: application/json\r\nContent-Length: 262\r\n</pre>\n</blockquote>\n\n<p>Some possible problems are:</p>\n<ul>\n<li id="missing-method"><p>Missing or unknown request method.</p></li>\n<li id="missing-url"><p>Missing URL.</p></li>\n<li id="missing-protocol"><p>Missing HTTP Identifier (HTTP/1.0).</p></li>\n<li><p>Request is too large.</p></li>\n<li><p>Content-Length missing for POST or PUT requests.</p></li>\n<li><p>Illegal character in hostname; underscores are not allowed.</p></li>\n<li><p>HTTP/1.1 <q>Expect:</q> feature is being asked from an HTTP/1.0 software.</p></li>\n</ul>\n\n<p>Your cache administrator is <a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_INVALID_REQ&amp;body=CacheHost%3A%20cnsz01vl00319%0D%0AErrPage%3A%20ERR_INVALID_REQ%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Wed,%2030%20May%202018%2001%3A41%3A50%20GMT%0D%0A%0D%0AClientIP%3A%2010.62.12.59%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2Felastalert_status%2Felastalert%2F_search%3Fsize%3D1000%20HTTP%2F1.1%0AHost%3A%2010.62.12.59%3A9200%0D%0AAccept-Encoding%3A%20identity%0D%0AContent-Type%3A%20application%2Fjson%0D%0AContent-Length%3A%20262%0D%0A%0D%0A%0D%0A">root</a>.</p>\n<br>\n</div>\n\n<script language="javascript">\nif (\'GET\' != \'[unknown method]\') document.getElementById(\'missing-method\').style.display = \'none\';\nif (\'http://10.62.12.59:9200/elastalert_status/elastalert/_search?size=1000\' != \'[no URL]\') document.getElementById(\'missing-url\').style.display = \'none\';\nif (\'HTTP\' != \'[unknown protocol]\') document.getElementById(\'missing-protocol\').style.display = \'none\';\n</script>\n\n<hr>\n<div id="footer">\n<p>Generated Wed, 30 May 2018 01:41:50 GMT by cnsz01vl00319 (squid/3.3.8)</p>\n<!-- ERR_INVALID_REQ -->\n</div>\n</body></html>\n') {'sort': {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'alert_time': {'to': '2018-05-30T01:41:50.862404Z', 'from': '2018-05-28T01:41:50.862146Z'}}}, 'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}}}}

Traceback (most recent call last):
  File "/opt/elasticsearch/es-alert/elastalert-email/elastalert/elastalert.py", line 1464, in find_recent_pending_alerts
    size=1000)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

TransportError: TransportError(411, u'<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html><head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<title>ERROR: The requested URL could not be retrieved</title>\n<style type="text/css"><!-- \n /*\n Stylesheet for Squid Error pages\n Adapted from design by Free CSS Templates\n http://www.freecsstemplates.org\n Released for free under a Creative Commons Attribution 2.5 License\n*/\n\n/* Page basics */\n* {\n\tfont-family: verdana, sans-serif;\n}\n\nhtml body {\n\tmargin: 0;\n\tpadding: 0;\n\tbackground: #efefef;\n\tfont-size: 12px;\n\tcolor: #1e1e1e;\n}\n\n/* Page displayed title area */\n#titles {\n\tmargin-left: 15px;\n\tpadding: 10px;\n\tpadding-left: 100px;\n\tbackground: url(\'http://www.squid-cache.org/Artwork/SN.png\') no-repeat left;\n}\n\n/* initial title */\n#titles h1 {\n\tcolor: #000000;\n}\n#titles h2 {\n\tcolor: #000000;\n}\n\n/* special event: FTP success page titles */\n#titles ftpsuccess {\n\tbackground-color:#00ff00;\n\twidth:100%;\n}\n\n/* Page displayed body content area */\n#content {\n\tpadding: 10px;\n\tbackground: #ffffff;\n}\n\n/* General text */\np {\n}\n\n/* error brief description */\n#error p {\n}\n\n/* some data which may have caused the problem */\n#data {\n}\n\n/* the error message received from the system or other software */\n#sysmsg {\n}\n\npre {\n    font-family:sans-serif;\n}\n\n/* special event: FTP / Gopher directory listing */\n#dirmsg {\n    font-family: courier;\n    color: black;\n    font-size: 10pt;\n}\n#dirlisting {\n    margin-left: 2%;\n    margin-right: 2%;\n}\n#dirlisting tr.entry td.icon,td.filename,td.size,td.date {\n    border-bottom: groove;\n}\n#dirlisting td.size {\n    width: 50px;\n    text-align: right;\n    padding-right: 5px;\n}\n\n/* horizontal lines */\nhr {\n\tmargin: 0;\n}\n\n/* page displayed footer area */\n#footer {\n\tfont-size: 9px;\n\tpadding-left: 10px;\n}\n\n\nbody\n:lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; }\n:lang(he) { direction: rtl; }\n --></style>\n</head><body id=ERR_INVALID_REQ>\n<div id="titles">\n<h1>ERROR</h1>\n<h2>The requested URL could not be retrieved</h2>\n</div>\n<hr>\n\n<div id="content">\n<p><b>Invalid Request</b> error was encountered while trying to process the request:</p>\n\n<blockquote id="data">\n<pre>GET /elastalert_status/elastalert/_search?size=1000 HTTP/1.1\nHost: 10.62.12.59:9200\r\nAccept-Encoding: identity\r\nContent-Type: application/json\r\nContent-Length: 262\r\n</pre>\n</blockquote>\n\n<p>Some possible problems are:</p>\n<ul>\n<li id="missing-method"><p>Missing or unknown request method.</p></li>\n<li id="missing-url"><p>Missing URL.</p></li>\n<li id="missing-protocol"><p>Missing HTTP Identifier (HTTP/1.0).</p></li>\n<li><p>Request is too large.</p></li>\n<li><p>Content-Length missing for POST or PUT requests.</p></li>\n<li><p>Illegal character in hostname; underscores are not allowed.</p></li>\n<li><p>HTTP/1.1 <q>Expect:</q> feature is being asked from an HTTP/1.0 software.</p></li>\n</ul>\n\n<p>Your cache administrator is <a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_INVALID_REQ&amp;body=CacheHost%3A%20cnsz01vl00319%0D%0AErrPage%3A%20ERR_INVALID_REQ%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Wed,%2030%20May%202018%2001%3A41%3A50%20GMT%0D%0A%0D%0AClientIP%3A%2010.62.12.59%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2Felastalert_status%2Felastalert%2F_search%3Fsize%3D1000%20HTTP%2F1.1%0AHost%3A%2010.62.12.59%3A9200%0D%0AAccept-Encoding%3A%20identity%0D%0AContent-Type%3A%20application%2Fjson%0D%0AContent-Length%3A%20262%0D%0A%0D%0A%0D%0A">root</a>.</p>\n<br>\n</div>\n\n<script language="javascript">\nif (\'GET\' != \'[unknown method]\') document.getElementById(\'missing-method\').style.display = \'none\';\nif (\'http://10.62.12.59:9200/elastalert_status/elastalert/_search?size=1000\' != \'[no URL]\') document.getElementById(\'missing-url\').style.display = \'none\';\nif (\'HTTP\' != \'[unknown protocol]\') document.getElementById(\'missing-protocol\').style.display = \'none\';\n</script>\n\n<hr>\n<div id="footer">\n<p>Generated Wed, 30 May 2018 01:41:50 GMT by cnsz01vl00319 (squid/3.3.8)</p>\n<!-- ERR_INVALID_REQ -->\n</div>\n</body></html>\n')

WARNING:elasticsearch:GET http://10.62.12.59:9200/balance/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:411 request:0.003s]

WARNING:elasticsearch:Undecodable raw error response from server: No JSON object could be decoded

ERROR:root:Error running query: TransportError(411, u'<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html><head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<title>ERROR: The requested URL could not be retrieved</title>\n<style type="text/css"><!-- \n /*\n Stylesheet for Squid Error pages\n Adapted from design by Free CSS Templates\n http://www.freecsstemplates.org\n Released for free under a Creative Commons Attribution 2.5 License\n*/\n\n/* Page basics */\n* {\n\tfont-family: verdana, sans-serif;\n}\n\nhtml body {\n\tmargin: 0;\n\tpadding: 0;\n\tbackground: #efefef;\n\tfont-size: 12px;\n\tcolor: #1e1e1e;\n}\n\n/* Page displayed title area */\n#titles {\n\tmargin-left: 15px;\n\tpadding: 10px;\n\tpadding-left: 100px;\n\tbackground: url(\'http://www.squid-cache.org/Artwork/SN.png\') no-repeat left;\n}\n\n/* initial title */\n#titles h1 {\n\tcolor: #000000;\n}\n#titles h2 {\n\tcolor: #000000;\n}\n\n/* special event: FTP success page titles */\n#titles ftpsuccess {\n\tback... (3452 characters removed)

INFO:elastalert:Ran Network Counter Issue Rule from 2018-05-30 09:31 CST to 2018-05-30 09:41 CST: 0 query hits (0 already seen), 0 matches, 0 alerts sent


```

**Comment by 1998729** [comment]
解决了吗？
