### ISSUE TITLE
Unable to Start Elastalert 

### ISSUE THREAD

**Issue by ankit22550** [Yelp/elastalert#1721]
Unable to start Elastalert service giveing me below error currently i am using E.S-6.2.3

09:36:08.665Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
09:36:08.667Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
09:36:08.675Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 28664)
09:36:08.678Z  INFO elastalert-server: Server:  Server listening on port 3030
09:36:08.679Z  INFO elastalert-server: Server:  Server started
09:36:12.414Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET https://node-1:9200/elastalerta_status/elastalert/_search?size=1000 [status:400 request:0.002s]

09:36:12.424Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-05-30T09:36:12.411021Z', 'from': '2018-05-28T09:36:12.410986Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
    Traceback (most recent call last):
      File "/images/ELK/elastalert/elastalert/elastalert/elastalert.py", line 1325, in find_recent_pending_alerts
        size=1000)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 655, in search
        doc_type, '_search'), params=params, body=body)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 314, in perform_request
        status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')

**Comment by Qmando** [comment]
Looks like you need to update elastalert to the latest version

**Comment by ankit22550** [comment]
@Qmando so  i need to check out with below GITHub Link using master brunch.

https://github.com/bitsensor/elastalert/tree/master

**Comment by ankit22550** [comment]
@Qmando after updating Elastalert  i am getting below error.

10:17:11.958Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
10:17:11.958Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
10:17:11.968Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 9793)
10:17:11.970Z  INFO elastalert-server: Server:  Server listening on port 3030
10:17:11.971Z  INFO elastalert-server: Server:  Server started
10:17:14.542Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET https://node-1:9200/elastalerta_status/elastalert/_search?size=1000 [status:400 request:0.106s]

10:17:14.545Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on') {'sort': {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'alert_time': {'to': '2018-05-31T10:17:14.364793Z', 'from': '2018-05-29T10:17:14.364758Z'}}}, 'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}}}}
    Traceback (most recent call last):
      File "/images/ELK/elastalert/elk/elastalert/elastalert/elastalert.py", line 1464, in find_recent_pending_alerts
        size=1000)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 655, in search
        doc_type, '_search'), params=params, body=body)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 314, in perform_request
        status, headers_res

**Comment by ankit22550** [comment]
10:27:53.237Z  INFO elastalert-server: Server:  Server listening on port 3030
10:27:53.238Z  INFO elastalert-server: Server:  Server started
10:28:00.421Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET https://node-1:9200/elastalerta_status/elastalert/_search?size=1000 [status:404 request:0.003s]

10:28:00.430Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(404, u'index_not_found_exception', u'no such index') {'sort': {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'alert_time': {'to': '2018-05-31T10:28:00.305646Z', 'from': '2018-05-29T10:28:00.305615Z'}}}, 'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}}}}
    Traceback (most recent call last):
      File "/images/ELK/elastalert/elk/elastalert/elastalert/elastalert.py", line 1464, in find_recent_pending_alerts
        size=1000)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 655, in search
        doc_type, '_search'), params=params, body=body)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 314, in perform_request
        status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    NotFoundError: TransportError(404, u'index_not_found_exception', u'no such index')

10:28:00.435Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET https://node-1:9200/elastalerta_status_status/elastalert_status/_search?_source_include=endtime%2Crule_name&size=1 [status:404 request:0.003s]

10:28:00.436Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error querying for last run: TransportError(404, u'index_not_found_exception', u'no such index')

**Comment by Qmando** [comment]
https://github.com/bitsensor/elastalert/tree/master is not elastalert. It's a third party integration. 

Please read http://elastalert.readthedocs.io/en/latest/running_elastalert.html. You've missed the index creation step.
