### ISSUE TITLE
AttributeError: 'TelegramAlerter' object has no attribute 'create_title'

### ISSUE THREAD

**Issue by yeastor** [Yelp/elastalert#1732]
ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 1274, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 1363, in send_alert
    alert.alert(matches)
  File "/usr/lib/python2.7/site-packages/elastalert/alerts.py", line 766, in alert
    body = u'⚠ %s ⚠ ```\n' % (self.create_title(matches))
AttributeError: 'TelegramAlerter' object has no attribute 'create_title'

**Comment by yeastor** [comment]
sorry old version
