### ISSUE TITLE
Unable to use elastalert with version 6.3.0

### ISSUE THREAD

**Issue by RichardLaing** [Yelp/elastalert#1771]
Hi there I have deployed a testing cluster with elastic stack 6.3.0 and I am unable to have elastalert connect to the http node, after installation I receive the following error, I have tested the connection with a manual curl and the node works correctly with the account and password to the same node this is being done with Ubuntu 16.04

```
Traceback (most recent call last):
  File "/opt/elastalert/elastalert/create_index.py", line 277, in <module>
    main()
  File "/opt/elastalert/elastalert/create_index.py", line 129, in main
    esversion = es.info()["version"]["number"]
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 241, in info
    return self.transport.perform_request('GET', '/', params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 85, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='es-g2.isolated', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb891a73710>: Failed to establish a new connection: [Errno -2] Name or service not known',))) caused by: ConnectionError(HTTPConnectionPool(host='es-g2.isolated', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb891a73710>: Failed to establish a new connection: [Errno -2] Name or service not known',)))
INFO:elastalert:Starting up
WARNING:elasticsearch:GET http://es-g2.isolated:9200/ [status:N/A request:0.006s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 76, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='es-g2.isolated', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3361de5350>: Failed to establish a new connection: [Errno -2] Name or service not known',))
WARNING:elasticsearch:GET http://es-g2.isolated:9200/ [status:N/A request:0.007s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 76, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='es-g2.isolated', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3361f2d510>: Failed to establish a new connection: [Errno -2] Name or service not known',))
WARNING:elasticsearch:GET http://es-g2.isolated:9200/ [status:N/A request:4.014s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 76, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='es-g2.isolated', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3361f2d490>: Failed to establish a new connection: [Errno -2] Name or service not known',))
WARNING:elasticsearch:GET http://es-g2.isolated:9200/ [status:N/A request:0.008s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 76, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='es-g2.isolated', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3361f2d4d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "elastalert/elastalert.py", line 1902, in <module>
    sys.exit(main(sys.argv[1:]))
  File "elastalert/elastalert.py", line 1898, in main
    client.start()
  File "elastalert/elastalert.py", line 1085, in start
    self.run_all_rules()
  File "elastalert/elastalert.py", line 1137, in run_all_rules
    self.send_pending_alerts()
  File "elastalert/elastalert.py", line 1507, in send_pending_alerts
    pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
  File "elastalert/elastalert.py", line 1490, in find_recent_pending_alerts
    if self.is_atleastfive():
  File "elastalert/elastalert.py", line 179, in is_atleastfive
    return int(self.es_version.split(".")[0]) >= 5
  File "elastalert/elastalert.py", line 175, in es_version
    self._es_version = self.get_version()
  File "elastalert/elastalert.py", line 169, in get_version
    info = self.writeback_es.info()
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 241, in info
    return self.transport.perform_request('GET', '/', params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 85, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='es-g2.isolated', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3361f2d4d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))) caused by: ConnectionError(HTTPConnectionPool(host='es-g2.isolated', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3361f2d4d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)))
```

my configuration file looks like the following

```
writeback_index: elastalert_status
alert_time_limit:
  days: 2

rules_folder: /opt/elastalert/rules

run_every:
  minutes: 2
buffer_time:
  minutes: 15

# SSL Settings
es_username: 'admin'
es_password: 'REDACTED'

# Connection settings
es_host: 'es-g2.isolated'
es_port: 9200

# Alerting settings
alert:
- "email"
```

Any help would be gratefully received with this project

**Comment by RichardLaing** [comment]
You are indeed correct there was an error within the network settings and I now have the alerting connection fixed and is posting correctly. Thank you for the confirmation consider this issue solved :+1:
