### ISSUE TITLE
aggregation rule - AttributeError: 'dict' object has no attribute 'microseconds'

### ISSUE THREAD

**Issue by royir** [Yelp/elastalert#1796]
Hi,
I'm trying to alert on cost exceeded threshold over a month period,

this is my rule:

```
type: metric_aggregation
index: cluster_cost
timestamp_field: timestamp
ignore_null: true
alert:
 command
realert:
  minutes: 240
use_run_every_query_size: true
query_key: cluster_id.keyword
doc_type: ""
metric_agg_key: cost
metric_agg_type: sum
max_threshold: 500
buffer_time:
  days: 30
bucket_interval:
  hours: 1
run_every:
  hours: 1
pipe_match_json: true
new_style_string_format: true
name: CostThresholdMonth
command: ["/scripts/rule.py", "-c", '{match}', "-r", "CostThresholdMonth", "-n", ""]

```
when trying to run **elastalert-test-rule** this is the exception I got:
```
Traceback (most recent call last):
  File "/usr/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert', 'console_scripts', 'elastalert-test-rule')()
  File "/opt/elastalert/elastalert/test_rule.py", line 374, in main
    test_instance.run_rule_test()
  File "/opt/elastalert/elastalert/test_rule.py", line 369, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/opt/elastalert/elastalert/test_rule.py", line 207, in run_elastalert
    load_modules(rule)
  File "/opt/elastalert/elastalert/config.py", line 343, in load_modules
    rule['type'] = rule['type'](rule, args)
  File "/opt/elastalert/elastalert/ruletypes.py", line 951, in __init__
    super(MetricAggregationRule, self).__init__(*args)
  File "/opt/elastalert/elastalert/ruletypes.py", line 911, in __init__
    if total_seconds(self.rules['run_every']) % total_seconds(self.rules['bucket_interval_timedelta']) != 0:
  File "/opt/elastalert/elastalert/util.py", line 217, in total_seconds
    return (dt.microseconds + (dt.seconds + dt.days * 24 * 3600) * 10**6) / 10**6
AttributeError: 'dict' object has no attribute 'microseconds'

```

**Comment by Qmando** [comment]
Looks like a bug when using a custom bucket_interval with elastalert-test-rule. I see what the issue is. Thank you very much for reporting.

Before the fix is in place, you might want to test via ``elastalert --debug`` instead.

**Comment by royir** [comment]
the issue is with elastalert too so the workaround don't really work:

`/opt/rules # elastalert --debug --config /opt/config/elastalert_config.yaml 
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
Traceback (most recent call last):
  File "/usr/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert', 'console_scripts', 'elastalert')()
  File "/opt/elastalert/elastalert/elastalert.py", line 1803, in main
    client = ElastAlerter(args)
  File "/opt/elastalert/elastalert/elastalert.py", line 129, in __init__
    self.conf = load_rules(self.args)
  File "/opt/elastalert/elastalert/config.py", line 462, in load_rules
    rule = load_configuration(rule_file, conf, args)
  File "/opt/elastalert/elastalert/config.py", line 113, in load_configuration
    load_modules(rule, args)
  File "/opt/elastalert/elastalert/config.py", line 343, in load_modules
    rule['type'] = rule['type'](rule, args)
  File "/opt/elastalert/elastalert/ruletypes.py", line 951, in __init__
    super(MetricAggregationRule, self).__init__(*args)
  File "/opt/elastalert/elastalert/ruletypes.py", line 911, in __init__
    if total_seconds(self.rules['run_every']) % total_seconds(self.rules['bucket_interval_timedelta']) != 0:
  File "/opt/elastalert/elastalert/util.py", line 217, in total_seconds
    return (dt.microseconds + (dt.seconds + dt.days * 24 * 3600) * 10**6) / 10**6
AttributeError: 'dict' object has no attribute 'microseconds'
`

**Comment by Qmando** [comment]
Aha, so the issue is that you've got ``run_every`` defined in your rule yaml, despite it being a global setting. Put it in config.yaml instead. It doesn't make a difference if you change it per rule anyway, well, other than causing this error 😄 

I'll fix this error by adding a warning and popping it out of the rule config immediately.

**Comment by royir** [comment]
bucket_interval cannot be smaller than run_every, and this is a major issue since I'm accumulating 1 month of data each time (I'm checking monthly cost) 
when using bucket_interval of 1 minute the query is taking long long time...

**Comment by Qmando** [comment]
Without a bucket_interval, does the query time out?

With a bucket_interval, it performs the check against the threshold for each interval, not the total, so that's probably not what you want anyway.

**Comment by abhishekjiitr** [comment]
Was it fixed @Qmando?
```I'll fix this error by adding a warning and popping it out of the rule config immediately.```
