### ISSUE TITLE
elastalert-test-rule  - TypeError: can't multiply sequence by non-int of type 'str'

### ISSUE THREAD

**Issue by JeffAshton** [Yelp/elastalert#1815]
Just upgraded from v0.1.28 to 0.1.33, and now failing.

```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/elastalert/test_rule.py", line 421, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/site-packages/elastalert/test_rule.py", line 406, in run_rule_test
    data_file.write(json.dumps([doc['_source'] for doc in hits], indent='    '))
  File "/usr/local/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/local/lib/python2.7/json/encoder.py", line 300, in _iterencode_list
    newline_indent = '\n' + (' ' * (_indent * _current_indent_level))
TypeError: can't multiply sequence by non-int of type 'str'
Exited with code 1
```

**Comment by JeffAshton** [comment]
I think it was probably caused by switching from ```simplejson``` to ```json```

https://github.com/Yelp/elastalert/commit/86988c78a45911c66112b6afbca67fcd543cb645

**Comment by JeffAshton** [comment]
Ohhh, I see what's going on.  They are passing indent as a string, instead of a number

**Comment by asottile** [comment]
> json is stdlib and since elastalert doesn't support python2.6 it doesn't
provide any speed benefits.  It also looks like (?) it was only being used in
a test?

beyond that, yeah was just trying to eliminate a dependency that required a C toolchain when the stdlib would suffice.  looks like I missed that `indent` usage though (it works in python3!).
