### ISSUE TITLE
Getting timestamp Error

### ISSUE THREAD

**Issue by abdur03** [Yelp/elastalert#1819]
Getting timestamp error while testing an elastalert rule.Basically my timestamp filter on my kibana dashboard is as below

timestamp |   | July 24th 2018, 08:16:14.417
-- | -- | --

> Error running your filter:
RequestError(400, u'search_phase_execution_exception', {u'status': 400, u'error': {u'failed_shards': [{u'node': u'aX65YXp4QsSGNsDBPvy4aA', u'index': u'graylog_251', u'reason': {u'caused_by': {u'reason': u'Parse failure at index [10] of [2018-07-23T02:42:31.662379Z]', u'type': u'illegal_argument_exception'}, u'reason': u'failed to parse date field [2018-07-23T02:42:31.662379Z] with format [yyyy-MM-dd HH:mm:ss.SSS]', u'type': u'parse_exception'}, u'shard': 0}], u'root_cause': [{u'reason': u'failed to parse date field [2018-07-23T02:42:31.662379Z] with format [yyyy-MM-dd HH:mm:ss.SSS]', u'type': u'parse_exception'}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'}})
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
ERROR:root:Error running query: TransportError(400, u'search_phase_execution_exception', u'failed to parse date field [2018-07-23T02:42:31.705034Z] with format [yyyy-MM-dd HH:mm:ss.SSS]')

> Would have written the following documents to writeback index (default is elastalert_status):

> elastalert_error - {'message': "Error running query: TransportError(400, u'search_phase_execution_exception', u'failed to parse date field [2018-07-23T02:42:31.705034Z] with format [yyyy-MM-dd HH:mm:ss.SSS]')", 'traceback': ['Traceback (most recent call last):', '  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.33-py2.7.egg/elastalert/elastalert.py", line 390, in get_hits', '    **extra_args', '  File "/usr/local/lib/python2.7/site-packages/elasticsearch-6.3.0-py2.7.egg/elasticsearch/client/utils.py", line 76, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/usr/local/lib/python2.7/site-packages/elasticsearch-6.3.0-py2.7.egg/elasticsearch/client/__init__.py", line 655, in search', "    doc_type, '_search'), params=params, body=body)", '  File "/usr/local/lib/python2.7/site-packages/elasticsearch-6.3.0-py2.7.egg/elasticsearch/transport.py", line 318, in perform_request', '    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)', '  File "/usr/local/lib/python2.7/site-packages/elasticsearch-6.3.0-py2.7.egg/elasticsearch/connection/http_requests.py", line 90, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "/usr/local/lib/python2.7/site-packages/elasticsearch-6.3.0-py2.7.egg/elasticsearch/connection/base.py", line 125, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: TransportError(400, u'search_phase_execution_exception', u'failed to parse date field [2018-07-23T02:42:31.705034Z] with format [yyyy-MM-dd HH:mm:ss.SSS]')"], 'data': {'query': {'sort': [{'timestamp': {'order': 'asc'}}], 'query': {'bool': {'filter': {'bool': {'must': [{'range': {'timestamp': {'gt': '2018-07-23T02:42:31.705034Z', 'lte': '2018-07-23T02:57:31.705034Z'}}}]}}}}}, 'rule': 'Testing'}}

Have tried adding timestamp on elastalert rule as below

```
timestamp_field: timestamp
timestamp_type: custom
```

Can anyone please help me here

**Comment by abdur03** [comment]
Please help me here

**Comment by Qmando** [comment]
Try adding ``timestamp_format_expr: 'ts[:23] + ts[26:]'`` to your rule
