### ISSUE TITLE
Right after installing traceback errors

### ISSUE THREAD

**Issue by zeemaffin** [Yelp/elastalert#1824]
So i freshly installed elastalert as a guide mentioned. Step by step. 
I am at a line

>    bin/elastalert --config config.yaml --verbose

and 

>   bin/elastalert-create-index

```
Traceback (most recent call last):
  File "bin/elastalert", line 11, in <module>
    load_entry_point('elastalert==0.1.33', 'console_scripts', 'elastalert')()
  File "/tmp/elastalert/local/lib/python2.7/site-packages/elastalert-0.1.33-py2.7.egg/elastalert/elastalert.py", line 1910, in main
    client = ElastAlerter(args)
  File "/tmp/elastalert/local/lib/python2.7/site-packages/elastalert-0.1.33-py2.7.egg/elastalert/elastalert.py", line 130, in __init__
    self.conf = load_rules(self.args)
  File "/tmp/elastalert/local/lib/python2.7/site-packages/elastalert-0.1.33-py2.7.egg/elastalert/config.py", line 485, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file example_rules/example_new_term.yaml: Error initializing rule Example new term rule: Error searching for existing terms: ConnectionTimeout('TIMEOUT', "HTTPConnectionPool(host='MYIP', port="Port"): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc729722d10>, 'Connection to MYIP timed out. (connect timeout=50)'))", ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='MYIP', port=PORT): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc729722d10>, 'Connection to MYIP timed out. (connect timeout=50)'))",),))
```

I changed the timeout settings i tough its too sort to create index but nope. 

Also, it says this when i  check the status: 

```
..../tmp/elastalert# /etc/init.d/elastalert restart
[ ok ] Restarting elastalert (via systemctl): elastalert.service.
...:/tmp/elastalert# /etc/init.d/elastalert status
● elastalert.service - LSB: ElastAlert service
   Loaded: loaded (/etc/init.d/elastalert; generated; vendor preset: enabled)
   Active: active (running) since Wed 2018-07-25 14:59:01 CEST; 55s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 29959 ExecStop=/etc/init.d/elastalert stop (code=exited, status=0/SUCCESS)
  Process: 29966 ExecStart=/etc/init.d/elastalert start (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/elastalert.service
           └─29981 /tmp/elastalert/bin/python /tmp/elastalert/bin/elastalert --config /tmp/elastalert/config.yaml --debug --verbose

```
 Sometimes it says 1 already running 2 errors

Any tips how can i countinue ? 

Thanks 

Adam

**Comment by Qmando** [comment]
You don't have connectivity to elasticsearch. You can test this by doing ``$ curl myip:port`` and it should return the info about the cluster. If that doesn't work, elastalert won't work.

**Comment by zeemaffin** [comment]
I solved it, now i have a new problem and its more complicated :| 
#1847
