### ISSUE TITLE
Command not executing 

### ISSUE THREAD

**Issue by macedemo** [Yelp/elastalert#1854]
I have a real simple rule and it find matches but the command fails to   run  and I can't get it to work. I have tried a lot of things like shell scripts and actual binaries in the command and all fail. I have no idea why. used this as reference:
http://elastalert.readthedocs.io/en/latest/ruletypes.html#command

Rule.yaml
--------------
name: alert_ssh
es_host: localhost
es_port: 9200

type: frequency

index: filebeat-*

num_events: 1

timeframe:
   seconds: 1

realert:
   seconds: 0

filter:
- match_phrase:
   system.auth.program : "sshd"

alert:
  - command
command: ["cat /etc/hosts"]

I get 
ERROR:root:Error while running alert command: Error while running command cat /etc/hosts: [Errno 2] No such file or directory

elastalert_error - {'message': 'Error while running alert command: Error while running command cat /etc/hosts: [Errno 2] No such file or directory', 'traceback': ['Traceback (most recent call last):', '  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 1410, in send_alert', '    alert.alert(matches)', '  File "/usr/lib/python2.7/site-packages/elastalert/alerts.py", line 914, in alert', '    raise EAException("Error while running command %s: %s" % (\' \'.join(command), e))', 'EAException: Error while running command cat /etc/hosts: [Errno 2] No such file or directory'], 'data': {'rule': 'alert_ssh'}}

**Comment by macedemo** [comment]
figured it out. command: ["cat /etc/hosts"] should be command: ["cat", "/etc/hosts"]
