### ISSUE TITLE
Maximum time to wait for Elasticsearch to become responsive is set to 0 by default and is not configurable

### ISSUE THREAD

**Issue by spacepatcher** [Yelp/elastalert#1984]
Hi!

I use ElastAlert in docker-compose with dedicated Elasticsearch container. Of course, it takes some time for the services to start operating.
ElastAlert always starts before Elasticsearch and it tries to connect to an unhealthy service. There are no multiple tries to Elasticsearch due to value of `self.args.timeout` is set to 0 by default: https://github.com/Yelp/elastalert/blob/2d08813ef24b777e85aaa4db05889ca33bb98fac/elastalert/elastalert.py#L86. 
Because of this, an attempt to create an index is not performed with the message:
```
elastalert       | 16:45:39.739Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
elastalert       | 16:45:39.739Z  INFO elastalert-server: ProcessController:  Creating index
elastalert       | 16:45:51.949Z ERROR elastalert-server:
elastalert       |     ProcessController:  Traceback (most recent call last):
elastalert       |       File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
elastalert       |         "__main__", fname, loader, pkg_name)
elastalert       |       File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
elastalert       |         exec code in run_globals
elastalert       |       File "/opt/elastalert/elastalert/create_index.py", line 277, in <module>
elastalert       |         main()
elastalert       |       File "/opt/elastalert/elastalert/create_index.py", line 129, in main
elastalert       |         esversion = es.info()["version"]["number"]
elastalert       |       File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/utils.py", line 76, in _wrapped
elastalert       |         return func(*args, params=params, **kwargs)
elastalert       |       File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/__init__.py", line 241, in info
elastalert       |         return self.transport.perform_request('GET', '/', params=params)
elastalert       |       File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/transport.py", line 318, in perform_request
elastalert       |         status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
elastalert       |       File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 85, in perform_request
elastalert       |         raise ConnectionError('N/A', str(e), e)
elastalert       |     elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='elasticsearch', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection objec
t at 0x7f04ebbf4090>: Failed to establish a new connection: [Errno 111] Connection refused',))) caused by: ConnectionError(HTTPConnectionPool(host='elasticsearch', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError
('<urllib3.connection.HTTPConnection object at 0x7f04ebbf4090>: Failed to establish a new connection: [Errno 111] Connection refused',)))
elastalert       |
elastalert       | 16:45:51.949Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
elastalert       | 16:45:51.949Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
elastalert       | 16:45:51.951Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
elastalert       | 16:45:51.968Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 49)
elastalert       | 16:45:51.971Z  INFO elastalert-server: Server:  Server listening on port 3030
elastalert       | 16:45:51.972Z  INFO elastalert-server: Server:  Server started
```

Is it possible to set the default value of `self.args.timeout` for at least 10 seconds or make it possible to configure timeout parameter via file `config.yaml`?

Thanks!

**Comment by alankis** [comment]
@spacepatcher Hey Alex. There is, in fact, a property for backend timeout, but it is missing from the config.yaml. More details on this can be found in the official [documentation](https://elastalert.readthedocs.io/en/latest/elastalert.html#configuration). Keep an eye on `es_conn_timeout`. The documentation states that this value is already set to 20, but I will check the elastalert.py file for this property definition and if needed create a PR.
