### ISSUE TITLE
Relaert is not working in frequency rule type

### ISSUE THREAD

**Issue by skatakar** [Yelp/elastalert#2036]
I am using below parameters in frequency rule type but realert is not working on specified time duration. I have mentioned relaert with hours : 1 and queary_key : "Hostname" ie since realert is 1 hour I assume it should aggregate records based on hostname field for the hour (assume from 9:00 to 10:00) and as num_events : 1 hence it should raise only one alarm per hostname eventhough hostname have more events in that hr. it is working as expected. But if the event comes after one hr ie at 10:25, the alarm is not getting generated. currently I haven't configured any alert notification. I can see them are supressed in console.

rule file has:
es_host: localhost
es_port: 9200
rules_folder : "D:\elastalert-master\example_rules"
buffer_time :
hours : 4

timeframe:
days : 4

writeback_index : test_elastalert1
name: test5 rule
type: frequency
timestamp_field: "time"
index: test_elastalert1
num_events: 1
aggregation:
#minutes: 10
days : 1
aggregation_key : "Hostname"
query_key : "Hostname"

realert :
hours : 1
filter:

query:
match :
"event_message" : "Ping"
alert: "email"
alert_subject: "Issue is occurred "
alert_info: "event from "

elastalert-test-rule

D:\elastalert-master\example_rules>elastalert-test-rule test5.yaml
Successfully loaded test5 rule

Got 4 hits from the last 1 day

Available terms in first hit:
event_message
event_sev
Hostname
event_source
time

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
To send them but remain verbose, use --verbose instead.
INFO:elastalert:Queried rule test5 rule from 2018-12-16 14:13 Central Standard Time to 2018-12-16 18:13 Central Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule test5 rule from 2018-12-16 18:13 Central Standard Time to 2018-12-16 22:13 Central Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule test5 rule from 2018-12-16 22:13 Central Standard Time to 2018-12-17 02:13 Central Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule test5 rule from 2018-12-17 02:13 Central Standard Time to 2018-12-17 06:13 Central Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule test5 rule from 2018-12-17 06:13 Central Standard Time to 2018-12-17 10:13 Central Standard Time: 4 / 4 hits
INFO:elastalert:Queried rule test5 rule from 2018-12-17 10:13 Central Standard Time to 2018-12-17 14:13 Central Standard Time: 0 / 0 hits
INFO:elastalert:New aggregation for test5 rule, aggregation_key: lv00001. next alert at 2018-12-18 20:13:44.943000+00:00.
INFO:elastalert:Ignoring match for silenced rule test5 rule.lv00001
INFO:elastalert:New aggregation for test5 rule, aggregation_key: lv00002. next alert at 2018-12-18 20:13:44.950000+00:00.
INFO:elastalert:Ignoring match for silenced rule test5 rule.lv00002

Would have written the following documents to writeback index (default is elastalert_status):

silence - {'rule_name': u'test5 rule.lv00001', '@timestamp': datetime.datetime(2018, 12, 17, 20, 13, 44, 938000, tzinfo=tzutc()), 'exponent': 0, 'until': d
atetime.datetime(2018, 12, 17, 21, 13, 44, 938000, tzinfo=tzutc())}

elastalert - {'alert_info': {}, 'alert_sent': False, 'match_body': {'_type': u'record', u'event_source': u'BPPM', '_index': u'test_elastalert1', 'num_hits'
: 4, u'event_sev': u'Critical', u'Hostname': u'lv00001', u'event_message': u'ping response is failed ', u'time': '2018-12-17T13:01:04.572Z', 'num_matches':
4, '_id': u'9'}, 'rule_name': 'test5 rule', 'match_time': '2018-12-17T13:01:04.572Z', 'alert_time': datetime.datetime(2018, 12, 18, 20, 13, 44, 943000, tz
info=tzutc()), 'aggregation_key': u'lv00001', 'alert_exception': None}

silence - {'rule_name': u'test5 rule.lv00002', '@timestamp': datetime.datetime(2018, 12, 17, 20, 13, 44, 949000, tzinfo=tzutc()), 'exponent': 0, 'until': d
atetime.datetime(2018, 12, 17, 21, 13, 44, 949000, tzinfo=tzutc())}

elastalert - {'alert_info': {}, 'alert_sent': False, 'match_body': {'_type': u'record', u'event_source': u'DYNA', '_index': u'test_elastalert1', 'num_hits'
: 4, u'event_sev': u'Critical', u'Hostname': u'lv00002', u'event_message': u'ping response is failed ', u'time': '2018-12-17T13:05:27.706Z', 'num_matches':
4, '_id': u'13'}, 'rule_name': 'test5 rule', 'match_time': '2018-12-17T13:05:27.706Z', 'alert_time': datetime.datetime(2018, 12, 18, 20, 13, 44, 950000, t
zinfo=tzutc()), 'aggregation_key': u'lv00002', 'alert_exception': None}

elastalert_status - {'hits': 4, 'matches': 4, '@timestamp': datetime.datetime(2018, 12, 17, 20, 13, 44, 952000, tzinfo=tzutc()), 'rule_name': 'test5 rule',
'starttime': datetime.datetime(2018, 12, 16, 20, 13, 44, 869000, tzinfo=tzutc()), 'endtime': datetime.datetime(2018, 12, 17, 20, 13, 44, 869000, tzinfo=tz
utc()), 'time_taken': 0.06799983978271484}

D:\elastalert-master\example_rules>

**Comment by Qmando** [comment]
It doesn't make any sense to use an aggregation and realert with the same value with query_key and aggregation_key with the same value.

An aggregation is used to send multiple alerts together as one, however, if you have realert also set, there will be a maximum of one alert per aggregation. What your doing is effectively delaying the alerts by an hour. You should either remove realert if you want multiple alerts for one host sent together every hour, or, remove aggregation if you want 1 alert per hour per host.

When you say "But if the event comes after one hr ie at 10:25, the alarm is not getting generated.", are you talking about a different `elastalert-test-rule` run? Or are you actually running elastalert? That's not in your logs at all. If you get another hit within an hour of the `New aggregation`, it will be added to that aggregation. If it's after, the old aggregation will be sent and a new one created.

**Comment by skatakar** [comment]
Thanks Quentin Long for your reply.

I am running only one elastalert-test-script one time by inserting records at different time period. I think I need to use elastalert for running per each one hr.

for getting one record per one hostname based on message match per hour , I need to use aggregation and realert to use hours:1 and aggregation_key for hostname. correct me if I am wrong.

**Comment by skatakar** [comment]
thanks Quentin Long for your detailed explanation.

I need to send immediate alert when event comes and ignore for next one hr. then I have to use realert with one hr and no aggregation.

Do I need to use aggregation_key and query_key to point to Hostname field?

**Comment by Qmando** [comment]
You don't need aggregation_key, but you should use `query_key`. With `query_key: hostname`, the realert only applies to the same hostname. If you didn't have `query_key`, it would stop alerts for ALL hostnames for 1 hour.

**Comment by skatakar** [comment]
Hi Quentin,

Thanks for your answers. I see one strange behavior here.

have rule file as follows:
++++
es_host: localhost
es_port: 9200
rules_folder : "D:\elastalert-master\example_rules"

buffer_time :
    hours : 4    
run_every :
    minutes: 10
timeframe:
    hours : 8   
   
writeback_index : test_elastalert1
name: test6 rule
type: frequency
timestamp_field: "time"
index: test_elastalert1
num_events: 1

use_local_time : true

query_key : "Hostname"
realert : 
   minutes : 10
filter:
- query:
    match :
        "event_message" : "Ping"


alert: "email"
alert_subject: "Issue is occurred "
alert_info: "event from "
email:
- "u3xl@oncor.com"
+++++++++

have inserted few records in index. records are not found when I run elastalert where as its found with elastalert-test-rule. it seems there is time issue here.

elastalert:

__________
D:\elastalert-master\example_rules>python -m elastalert.elastalert --verbose --rule test6.yaml --config "..\config.yaml"
INFO:elastalert:Starting up
INFO:elastalert:Queried rule test6 rule from 2018-12-27 12:02 Central Standard Time to 2018-12-27 16:02 Central Standard Time: 0 / 0 hits
WARNING:elasticsearch:POST http://localhost:9200/elastalert_status_status/elastalert_status [status:403 request:0.000s]
ERROR:root:Error writing alert info to Elasticsearch: AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only /
 allow delete (api)];')
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\elastalert\elastalert.py", line 1494, in writeback
    doc_type=doc_type, body=body)
  File "D:\Python27\lib\site-packages\elasticsearch\client\utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "D:\Python27\lib\site-packages\elasticsearch\client\__init__.py", line 319, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "D:\Python27\lib\site-packages\elasticsearch\transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "D:\Python27\lib\site-packages\elasticsearch\connection\http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "D:\Python27\lib\site-packages\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
AuthorizationException: AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
**INFO:elastalert:Ran test6 rule from 2018-12-27 12:02 Central Standard Time to 2018-12-27 16:02 Central Standard Time: 0 query hits (0 already seen), 0 matc**
hes, 0 alerts sent
INFO:elastalert:Sleeping for 59.951 seconds
________________

with elastalert test rule script , the event is found between 2018-12-27 07:59 Central Standard Time to 2018-12-27 11:59 Central Standard Time: 1 / 1 hits. But actual inserted time of record is @ time: 2018-12-27T14:46:07.737Z.  see below result:

_________________
C:\Users\u3xlbes>elastalert-test-rule D:\elastalert-master\example_rules\test6.yaml
Successfully loaded test6 rule

INFO:elastalert:Queried rule test6 rule from 2018-12-27 07:59 Central Standard Time to 2018-12-27 11:59 Central Standard Time: 1 / 1 hits
INFO:elastalert:Queried rule test6 rule from 2018-12-27 11:59 Central Standard Time to 2018-12-27 15:59 Central Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule test6 rule from 2018-12-27 15:59 Central Standard Time to 2018-12-27 16:03 Central Standard Time: 0 / 0 hits
INFO:elastalert:Alert for test6 rule, lv00001 at 2018-12-27T14:46:07.737Z:
INFO:elastalert:test6 rule

At least 1 events occurred between 2018-12-27 00:46 Central Standard Time and 2018-12-27 08:46 Central Standard Time

Hostname: lv00001
_id: 3
_index: test_elastalert1
_type: record
event_message: ping response is failed
event_sev: Critical
event_source: BPPM
num_hits: 1
num_matches: 1
time: 2018-12-27T14:46:07.737Z


Would have written the following documents to writeback index (default is elastalert_status):

silence - {'rule_name': u'test6 rule.lv00001', '@timestamp': datetime.datetime(2018, 12, 27, 22, 3, 50, 939000, tzinfo=tzutc()), 'exponent': 0, 'until': da
tetime.datetime(2018, 12, 27, 22, 13, 50, 939000, tzinfo=tzutc())}

elastalert_status - {'hits': 1, 'matches': 1, '@timestamp': datetime.datetime(2018, 12, 27, 22, 3, 50, 954000, tzinfo=tzutc()), 'rule_name': 'test6 rule',
'starttime': datetime.datetime(2018, 12, 27, 13, 59, 2, 894000, tzinfo=tzutc()), 'endtime': datetime.datetime(2018, 12, 27, 22, 3, 50, 894000, tzinfo=tzutc
()), 'time_taken': 0.059999942779541016}


C:\Users\u3xlbes>
________

all my systems are in CST time zone only. But its not finding the records .Can you please check and let me know how to use the current CST time for seacrhing?

**Comment by skatakar** [comment]
I have seen the similar issue  and tried to implement enhancements file to use local time (CST).
but getting the below error:
enhancements.py:
....
...

from elastalert.util import pretty_ts
from elastalert.enhancements import BaseEnhancement

class TimeEnhancement(BaseEnhancement):
    def process(self, match):
		match['@timestamp'] = pretty_ts(match['@timestamp'])


when I run the elastalert or elastalert-test-rule, getting the following error:

D:\elastalert-master\example_rules>elastalert-test-rule test6.yaml
Traceback (most recent call last):
  File "D:\Python27\Scripts\elastalert-test-rule-script.py", line 11, in <module>
    load_entry_point('elastalert==0.1.38', 'console_scripts', 'elastalert-test-rule')()
  File "d:\python27\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "d:\python27\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "d:\python27\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "d:\python27\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\python27\lib\site-packages\elastalert\test_rule.py", line 20, in <module>
    import elastalert.config
  File "d:\python27\lib\site-packages\elastalert\config.py", line 11, in <module>
    import enhancements
  File "d:\python27\lib\site-packages\elastalert\enhancements.py", line 21, in <module>
    from elastalert.util import pretty_ts
  File "d:\python27\lib\site-packages\elastalert\elastalert.py", line 22, in <module>
    from config import get_rule_hashes
ImportError: cannot import name get_rule_hashes

D:\elastalert-master\example_rules>

please suggest me how to fix the enhancement to get elastalert to use local time(system time is CST) not UTC.

**Comment by skatakar** [comment]
I changed the code in enhancement to use util folder instead elastalert.util as enahancement file is under elastalert fodler.
now the script is not giving error. but still its not finding events

elastalert with start and end time, its able to find event but in differnt time period.
-----------------
D:\elastalert-master\example_rules>python -m elastalert.elastalert --debug --rule test6.yaml --config ..\config.yaml --start 20190102T11:30:00 --end 201901
02T12:00:00
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
INFO:elastalert:Starting up
INFO:elastalert:Queried rule test6 rule from 2019-01-02 05:30 Central Standard Time to 2019-01-02 05:40 Central Standard Time: 0 / 0 hits
INFO:elastalert:Queried rule test6 rule from 2019-01-02 05:40 Central Standard Time to 2019-01-02 05:50 Central Standard Time: 1 / 1 hits
INFO:elastalert:Queried rule test6 rule from 2019-01-02 05:50 Central Standard Time to 2019-01-02 06:00 Central Standard Time: 0 / 0 hits
INFO:elastalert:Skipping writing to ES: {'rule_name': u'test6 rule.lv00001', '@timestamp': '2019-01-02T17:48:48.521Z', 'exponent': 0, 'until': '2019-01-02T
17:58:48.521Z'}
INFO:elastalert:Alert for test6 rule, lv00001 at 2019-01-02T11:46:46.762Z:
INFO:elastalert:test6 rule

At least 1 events occurred between 2019-01-02 05:36 Central Standard Time and 2019-01-02 05:46 Central Standard Time

Hostname: lv00001
_id: 7
_index: test_elastalert1
_type: record
event_message: ping response is failed
event_sev: Critical
event_source: BPPM
num_hits: 1
num_matches: 1
time: 2019-01-02T11:46:46.762Z

INFO:elastalert:Skipping writing to ES: {'hits': 1, 'matches': 1, '@timestamp': '2019-01-02T17:48:48.534Z', 'rule_name': 'test6 rule', 'starttime': '2019-0
1-02T11:30:00Z', 'endtime': '2019-01-02T12:00:00Z', 'time_taken': 0.03299999237060547}
INFO:elastalert:Ran test6 rule from 2019-01-02 05:30 Central Standard Time to 2019-01-02 06:00 Central Standard Time: 1 query hits (0 already seen), 1 matc
hes, 0 alerts sent
______________--

But its not finding while running without start and end time:

_______
D:\elastalert-master\example_rules>python -m elastalert.elastalert --debug --rule test6.yaml --config ..\config.yaml
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
INFO:elastalert:Starting up
INFO:elastalert:Queried rule test6 rule from 2019-01-02 11:38 Central Standard Time to 2019-01-02 11:48 Central Standard Time: 0 / 0 hits
INFO:elastalert:Skipping writing to ES: {'hits': 0, 'matches': 0, '@timestamp': '2019-01-02T17:48:56.787Z', 'rule_name': 'test6 rule', 'starttime': '2019-0
1-02T17:38:56.771Z', 'endtime': '2019-01-02T17:48:56.771Z', 'time_taken': 0.016000032424926758}
INFO:elastalert:Ran test6 rule from 2019-01-02 11:38 Central Standard Time to 2019-01-02 11:48 Central Standard Time: 0 query hits (0 already seen), 0 matc
hes, 0 alerts sent
INFO:elastalert:Sleeping for 599.969 seconds

____________

I ahve added use_local_time: true in config file.

Can anyone plz suggest, how to find the current time events with elastalert?

**Comment by skatakar** [comment]
My JSON is as follows for testing ( I have generated manually and inserted using python).

doc = {
	"event_message": "ping response is failed ",
	"event_sev": "Critical",
	"event_source": "BPPM",
	"Hostname" : "lv00001",
	"time" : datetime.datetime.now()
	}

so it has time filed with current time. inserted these data with below command, we execute doc command each time and change the id number while inserting

es.index(index='test_elastalert1', doc_type='record', id=1, body=doc)

Can anyone let me know why its not finding the event in current time period?

**Comment by skatakar** [comment]
Any comments on this?

**Comment by skatakar** [comment]
Thanks Quentin, its searching with current time(internally it uses UTC timezone only as the record time stamp is in UTC). Do I need to have one more field with localtimestamp , if I want to put the localtime in the email?

**Comment by Qmando** [comment]
Yeah.. that's the easiest way to get the local time. There's a option `use_local_time` but this only changes the timestamp in the default text strings, ie "There were more than 5 events between <localized timestamp>..." or "Between <localized timestamp> and ... there were less than 1 event".

If you're trying to put a local timestamp in via `alert_text`, you can do what you suggest, or you'd need an enhancement to accomplish the same thing if you don't control the data. This is a feature lots of people request so maybe this will change at some point.

**Comment by Qmando** [comment]
You'll want something like https://github.com/Yelp/elastalert/issues/1385#issuecomment-423281701
