### ISSUE TITLE
Issue with HTTP POST Alerter

### ISSUE THREAD

**Issue by sangeethsuseelan** [Yelp/elastalert#2042]
I am trying to integrate elastalert with Phantom and I am able to send the event using the below configuration.

alert: post
http_post_url: "https://10.1.0.33/rest/handler/restdatasource_$$$%%&&*^%$$/elkrest"
#http_post_payload:
http_post_ignore_ssl_errors: 'False'
http_post_headers:
  Content-Type: 'application/json'
  ph-auth-token: '%%%%%%%%%%'
http_post_static_payload:
  "container_data":
    "name": "Critical Service Stopped"
    "artifact_data":
      "cef":
        "host": "ManageEngine"
        "service": "winlogbeat"

But when I am trying to send the Dynamic Data (Using the http_post_payload) it is throwing the below error. 

ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 1342, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 1431, in send_alert
    alert.alert(matches)
  File "/usr/lib/python2.7/site-packages/elastalert/alerts.py", line 1675, in alert
    payload[post_key] = lookup_es_key(match, es_key)
  File "/usr/lib/python2.7/site-packages/elastalert/util.py", line 109, in lookup_es_key
    value_dict, value_key = _find_es_dict_by_key(lookup_dict, term)
  File "/usr/lib/python2.7/site-packages/elastalert/util.py", line 52, in _find_es_dict_by_key
    if term in lookup_dict:
TypeError: unhashable type: 'dict'

ERROR:root:Uncaught exception running rule Winlogbeat Service Status Monitoring: unhashable type: 'dict'

Please assist.

**Comment by Qmando** [comment]
Why did you remove the setting that is causing it to crash?

I'm guessing you had something like
```
http_post_payload:
  foo:
     bar: baz
```

You can't have nested objects in the `http_post_payload`, only key value pairs.

**Comment by aymenwerg** [comment]
I have the same issues when i'm trying to send Dunamic `data` @sangeethsuseelan @Qmando 
Can you help me if you have a solution ?

`alert: post
    http_post_url: "https://itsm.xxxxxxx.de/api/v1/tickets"
    http_post_payload:
      kubernetes_pod_name: kubernetes.pod.name
    http_post_headers:
      Content-Type: application/json
      Authorization: xxxxxxxxxxxx
      kbn-xsrf: professionally-crafted-string-of-text
    http_post_all_values: true
    http_post_static_payload: 
      title: Elastalert-zammad test!
      group: "Users"
      why: just a test
      article: 
        subject: Critical Pod Memory
        body: "<div><h1>## POD Memory Alert ##</h1></div>
          <div><h3><b>1. You exceeded the 90 % threshold of total Memory</b></h3></div>
        content_type: text/html
        type: note`

**Comment by aymenwerg** [comment]
I have the same issues when i'm trying to send Dunamic data @sangeethsuseelan @Qmando
Can you help me if you have a solution ?

alert: post
    http_post_url: "https://itsm.xxxxxxx.de/api/v1/tickets"
    http_post_payload:
      kubernetes_pod_name: kubernetes.pod.name
    http_post_headers:
      Content-Type: application/json
      Authorization: BeaZSUZnSxxxxxxxxC7zB5hSDVvfYYah6cjMAzZ4mkU8
      kbn-xsrf: professionally-crafted-string-of-text
    http_post_all_values: true
    http_post_static_payload: 
      title: Elastalert-zammad test!
      group: "Users"
      why: just a test
      article: 
        subject: Critical Pod Memory
        body: "<div><h1>## POD Memory Alert ##</h1></div>
          <div><h3><b>1. You exceeded the 90 % threshold of total Memory</b></h3></div>
