### ISSUE TITLE
cannot test custom rule type

### ISSUE THREAD

**Issue by sp1thas** [Yelp/elastalert#2070]
I have the following elastalert project structure:

```
../elastic_monitoring
├── config.yaml
├── __init__.py
├── README.md
└── rules
    ├── HostsStatus.yml
    ├── __init__.py
    ├── __init__.pyc
    ├── not_exist_rule.py
    ├── not_exist_rule.pyc
    └── Unittests.yaml

```

`Unittests.yaml` rule works fine:
```

➜ python -m elastalert.elastalert --verbose --rule rules/Unittests.yaml        
INFO:elastalert:Starting up
INFO:elastalert:Found expired previous run for Unittests at 2018-01-04 00:00:00+00:00
INFO:elastalert:Queried rule Unittests from 2019-01-10 11:37 EET to 2019-01-10 15:37 EET: 8 / 8 hits
INFO:elastalert:Ignoring match for silenced rule Unittests
INFO:elastalert:Ran Unittests from 2019-01-10 11:37 EET to 2019-01-10 15:37 EET: 8 query hits (0 already seen), 1 matches, 0 alerts sent
INFO:elastalert:Sleeping for 3599.927184 seconds
^CINFO:elastalert:SIGINT received, stopping ElastAlert...
```

but when I'm trying to test this rule using `elastalert-test-rule` I'm getting the following error.

```
➜ elastalert-test-rule rules/Unittests.yaml 
Successfully loaded Unittests
    
Traceback (most recent call last):
File "/home/simakis/.p2env/bin/elastalert-test-rule", line 11, in <module>
sys.exit(main())
File "/home/simakis/.p2env/local/lib/python2.7/site-packages/elastalert/test_rule.py", line 463, in main
test_instance.run_rule_test()
File "/home/simakis/.p2env/local/lib/python2.7/site-packages/elastalert/test_rule.py", line 455, in run_rule_test
self.run_elastalert(rule_yaml, conf, args)
File "/home/simakis/.p2env/local/lib/python2.7/site-packages/elastalert/test_rule.py", line 227, in run_elastalert
load_modules(rule, load_modules_args)
File "/home/simakis/.p2env/local/lib/python2.7/site-packages/elastalert/config.py", line 364, in load_modules
rule['type'] = get_module(rule['type'])
File "/home/simakis/.p2env/local/lib/python2.7/site-packages/elastalert/config.py", line 109, in get_module
base_module = __import__(module_path, globals(), locals(), [module_class])
elastalert.util.EAException: Could not import module rules.not_exist_rule.Unittests: No module named rules.not_exist_rule
```

`Unittests.yaml`:

```
name: "Unittests"
type: "rules.not_exist_rule.Unittests"
index: "unittests"
run_every:
hours: 8

buffer_time:
hours: 4
classes:
- "Vkt"
- "Twt"

realert:
minutes: 0
timeframe:
days: 1

ms_teams_webhook_url: https://outlook.office.com/webhook/...

ms_teams_alert_summary: Unittest Status
alert:
- ms_teams
```

Is this some kind of bug or propably I miss somthing?

**Comment by Qmando** [comment]
Try `python -m elastalert.test_rule` instead of `elastalert-test-rule`. When you use the entrypoints (the script shortcut instead of calling python directly) it messes with where python looks for modules to import. That's why the `python -m elastalert.elastalert` worked fine.

You can also set `$PYTHONPATH` to avoid this. Eg:
```
$ export PYTHONPATH=`pwd`
$ elastalert-test-rule rules/unittests.yaml
```

**Comment by sp1thas** [comment]
Thanks @Qmando for you quick reply. You are totally right! I'm closing the issue.
