### ISSUE TITLE
运行报错(6.X)

### ISSUE THREAD

**Issue by usajohn** [Yelp/elastalert#2207]
ES:6.5.4
Kibana:6.5.4

[root@localhost conf.d]# /usr/local/python27/bin/elastalert-test-rule  /usr/local/elastalert/example_rules/my_rule.yaml 

/usr/local/python27/lib/python2.7/site-packages/elastalert/config.py:31: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  rule_schema = jsonschema.Draft4Validator(yaml.load(open(os.path.join(os.path.dirname(__file__), 'schema.yaml'))))
Successfully loaded xxx alert 0415

WARNING:elasticsearch:GET http://10.240.86.1:9200/logstash-*/_search?ignore_unavailable=true&size=1 [status:400 request:0.002s]
Error running your filter:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'[query_string] query malformed, no start_object after query name', u'type': u'parsing_exception', u'line': 1, u'col': 199}], u'type': u'parsing_exception', u'reason': u'[query_string] query malformed, no start_object after query name', u'col': 199}})
WARNING:elasticsearch:GET http://10.240.86.1:9200/logstash-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.002s]
ERROR:root:Error running query: RequestError(400, u'parsing_exception', u'[query_string] query malformed, no start_object after query name')

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_error - {'message': "Error running query: RequestError(400, u'parsing_exception', u'[query_string] query malformed, no start_object after query name')", 'traceback': ['Traceback (most recent call last):', '  File "/usr/local/python27/lib/python2.7/site-packages/elastalert/elastalert.py", line 376, in get_hits', '    **extra_args', '  File "/usr/local/python27/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/usr/local/python27/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 811, in search', '    "GET", _make_path(index, "_search"), params=params, body=body', '  File "/usr/local/python27/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request', '    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)', '  File "/usr/local/python27/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 91, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "/usr/local/python27/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 131, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: RequestError(400, u'parsing_exception', u'[query_string] query malformed, no start_object after query name')"], 'data': {'query': {'sort': [{'@timestamp': {'order': 'asc'}}], 'query': {'bool': {'filter': {'bool': {'must': [{'range': {'@timestamp': {'gt': '2019-04-15T08:53:48.507183Z', 'lte': '2019-04-15T08:54:49.107183Z'}}}, {'query_string': None, 'query': 'field: ERROR'}]}}}}}, 'rule': 'xxx alert 0415'}}

[root@localhost conf.d]#

**Comment by usajohn** [comment]
![image](https://user-images.githubusercontent.com/49050786/56120172-32036480-5fa0-11e9-9a42-3514bebb9843.png)

**Comment by usajohn** [comment]
![image](https://user-images.githubusercontent.com/49050786/56120317-78f15a00-5fa0-11e9-91ee-13a8b5d1b3d3.png)

**Comment by usajohn** [comment]
ES:6.5.4
Kibana:6.5.4

**Comment by usajohn** [comment]
no support
