### ISSUE TITLE
query_key crashes if key field is empty or missing

### ISSUE THREAD

**Issue by schawt** [Yelp/elastalert#222]
```
INFO:root:Queried rule Test Alert from 8-21 6:26 PDT to 8-21 7:11 PDT: 1 hits
Traceback (most recent call last):
  File "/nail/home/wilson/pg/elastalert/virtualenv_run/bin/elastalert-test-rule", line 11, in <module>
    sys.exit(main())
  File "/nail/home/wilson/pg/elastalert/virtualenv_run/lib/python2.6/site-packages/elastalert/test_rule.py", line 289, in main
    test_instance.run_rule_test()
  File "/nail/home/wilson/pg/elastalert/virtualenv_run/lib/python2.6/site-packages/elastalert/test_rule.py", line 284, in run_rule_test
    self.run_elastalert(rule_yaml, args)
  File "/nail/home/wilson/pg/elastalert/virtualenv_run/lib/python2.6/site-packages/elastalert/test_rule.py", line 251, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "/nail/home/wilson/pg/elastalert/virtualenv_run/lib/python2.6/site-packages/elastalert/elastalert.py", line 490, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/nail/home/wilson/pg/elastalert/virtualenv_run/lib/python2.6/site-packages/elastalert/elastalert.py", line 372, in run_query
    data = self.get_hits(rule, start, end, index)
  File "/nail/home/wilson/pg/elastalert/virtualenv_run/lib/python2.6/site-packages/elastalert/elastalert.py", line 265, in get_hits
    self.process_hits(rule, hits)
  File "/nail/home/wilson/pg/elastalert/virtualenv_run/lib/python2.6/site-packages/elastalert/elastalert.py", line 235, in process_hits
    hit['_source'][rule['query_key']] = ', '.join(values)
TypeError: sequence item 3: expected string or Unicode, NoneType found
```

**Comment by Qmando** [comment]
Same problem as #202, fixed by #206
