### ISSUE TITLE
CentOS 7, elastalert-create-index and "ImportError: No module named urllib3"

### ISSUE THREAD

**Issue by ghenry** [Yelp/elastalert#2232]
Current master, this works fine:

`sudo python setup.py install`

but loading, gives:

elastalert-create-index 
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.1.39', 'console_scripts', 'elastalert-create-index')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.39-py2.7.egg/elastalert/create_index.py", line 10, in <module>
    import elasticsearch.helpers
  File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/__init__.py", line 24, in <module>
    from .client import Elasticsearch
  File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/client/__init__.py", line 4, in <module>
    from ..transport import Transport
  File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/transport.py", line 4, in <module>
    from .connection import Urllib3HttpConnection
  File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/connection/__init__.py", line 3, in <module>
    from .http_urllib3 import Urllib3HttpConnection, create_ssl_context
  File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/connection/http_urllib3.py", line 3, in <module>
    import urllib3
ImportError: No module named urllib3

Help? Thanks.

**Comment by Qmando** [comment]
Can you share the output of setup.py install? I'm surprised it wouldn't install urllib3

Elastalert requires requrests (https://github.com/Yelp/elastalert/blob/master/setup.py#L44) and requests requires urllib3: (https://github.com/kennethreitz/requests/blob/master/setup.py#L47)

**Comment by ghenry** [comment]
Sorry, missed this!
[elastalert-centos-7-setup.py-install.txt](https://github.com/Yelp/elastalert/files/3151796/elastalert-centos-7-setup.py-install.txt)

**Comment by ghenry** [comment]
Probably an ElasticSearch 7 issue?

`File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/connection/http_urllib3.py", line 3, in <module>
    import urllib3
ImportError: No module named urllib3`

**Comment by ghenry** [comment]
Anything I can do to help? Thanks.

**Comment by Qmando** [comment]
Hm, I see `Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python2.7/site-packages (from elasticsearch>=7.0.0->-r requirements.txt (line 6)) (1.22)` so it should be there.. I'm not really sure right now what the issue is.

Does running `python -c "import urllib3"` give you the same error?

**Comment by ghenry** [comment]
Thanks. I get:

```
python -c "import urllib3"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named urllib3
```

**Comment by ghenry** [comment]
Weird too:

```
locate urllib3
/usr/lib/python2.7/site-packages/urllib3
/usr/lib/python2.7/site-packages/urllib3-1.22.dist-info
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/__init__.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/_collections.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/connection.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/connectionpool.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/contrib
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/exceptions.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/fields.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/filepost.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/packages
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/poolmanager.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/request.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/response.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/util
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/contrib/__init__.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/contrib/ntlmpool.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/contrib/pyopenssl.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/packages/__init__.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/packages/ordered_dict.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/packages/six.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/packages/ssl_match_hostname
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/util/__init__.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/util/connection.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/util/request.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/util/response.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/util/retry.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/util/ssl_.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/util/timeout.py
/usr/lib/python2.7/site-packages/botocore-1.12.140-py2.7.egg/botocore/vendored/requests/packages/urllib3/util/url.py
/usr/lib/python2.7/site-packages/elasticsearch-7.0.0-py2.7.egg/elasticsearch/connection/http_urllib3.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/__init__.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/__init__.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/_collections.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/_collections.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/connection.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/connection.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/connectionpool.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/connectionpool.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/exceptions.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/exceptions.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/fields.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/fields.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/filepost.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/filepost.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/poolmanager.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/poolmanager.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/request.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/request.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/response.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/response.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/__init__.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/__init__.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/_appengine_environ.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/_appengine_environ.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/_securetransport
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/appengine.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/appengine.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/securetransport.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/securetransport.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/socks.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/socks.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/_securetransport/__init__.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/_securetransport/__init__.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/_securetransport/bindings.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/_securetransport/bindings.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/_securetransport/low_level.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/_securetransport/low_level.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/__init__.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/__init__.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/backports
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/six.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/six.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/ssl_match_hostname
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/backports/__init__.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/backports/__init__.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/backports/makefile.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/backports/makefile.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/ssl_match_hostname/__init__.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/ssl_match_hostname/__init__.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/ssl_match_hostname/_implementation.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/packages/ssl_match_hostname/_implementation.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/__init__.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/__init__.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/connection.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/connection.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/queue.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/queue.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/request.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/request.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/response.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/response.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/retry.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/retry.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/timeout.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/timeout.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/url.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/url.pyc
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/wait.py
/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/util/wait.pyc
/usr/lib/python2.7/site-packages/urllib3/contrib
/usr/lib/python2.7/site-packages/urllib3/packages
/usr/lib/python2.7/site-packages/urllib3/util
/usr/lib/python2.7/site-packages/urllib3/contrib/_securetransport
/usr/lib/python2.7/site-packages/urllib3/contrib/appengine.py
/usr/lib/python2.7/site-packages/urllib3/contrib/appengine.pyc
/usr/lib/python2.7/site-packages/urllib3/contrib/securetransport.py
/usr/lib/python2.7/site-packages/urllib3/contrib/securetransport.pyc
/usr/lib/python2.7/site-packages/urllib3/contrib/socks.py
/usr/lib/python2.7/site-packages/urllib3/contrib/socks.pyc
/usr/lib/python2.7/site-packages/urllib3/contrib/_securetransport/__init__.py
/usr/lib/python2.7/site-packages/urllib3/contrib/_securetransport/__init__.pyc
/usr/lib/python2.7/site-packages/urllib3/contrib/_securetransport/bindings.py
/usr/lib/python2.7/site-packages/urllib3/contrib/_securetransport/bindings.pyc
/usr/lib/python2.7/site-packages/urllib3/contrib/_securetransport/low_level.py
/usr/lib/python2.7/site-packages/urllib3/contrib/_securetransport/low_level.pyc
/usr/lib/python2.7/site-packages/urllib3/packages/backports
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname;5b82fdd0
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname;5b83e0a0
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname;5b83e174
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname;5c31047a
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname;5c310688
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname;5c310701
/usr/lib/python2.7/site-packages/urllib3/packages/backports/__init__.py
/usr/lib/python2.7/site-packages/urllib3/packages/backports/__init__.pyc
/usr/lib/python2.7/site-packages/urllib3/packages/backports/makefile.py
/usr/lib/python2.7/site-packages/urllib3/packages/backports/makefile.pyc
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname/__init__.py
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname/__init__.pyc
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname/_implementation.py
/usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname/_implementation.pyc
/usr/lib/python2.7/site-packages/urllib3/util/selectors.py
/usr/lib/python2.7/site-packages/urllib3/util/selectors.pyc
/usr/lib/python2.7/site-packages/urllib3/util/wait.py
/usr/lib/python2.7/site-packages/urllib3/util/wait.pyc
/usr/lib/python2.7/site-packages/urllib3-1.22.dist-info/DESCRIPTION.rst
/usr/lib/python2.7/site-packages/urllib3-1.22.dist-info/INSTALLER
/usr/lib/python2.7/site-packages/urllib3-1.22.dist-info/METADATA
/usr/lib/python2.7/site-packages/urllib3-1.22.dist-info/RECORD
/usr/lib/python2.7/site-packages/urllib3-1.22.dist-info/WHEEL
/usr/lib/python2.7/site-packages/urllib3-1.22.dist-info/metadata.json
/usr/lib/python2.7/site-packages/urllib3-1.22.dist-info/top_level.txt
```

**Comment by ghenry** [comment]
Weird still as it will uninstall:

```
[suretec@tommen ~]$ python -m pip uninstall urllib3
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Uninstalling urllib3-1.22:
  Would remove:
    /usr/lib/python2.7/site-packages/urllib3-1.22.dist-info/*
    /usr/lib/python2.7/site-packages/urllib3/contrib/_securetransport/*
    /usr/lib/python2.7/site-packages/urllib3/contrib/appengine.py
    /usr/lib/python2.7/site-packages/urllib3/contrib/securetransport.py
    /usr/lib/python2.7/site-packages/urllib3/contrib/socks.py
    /usr/lib/python2.7/site-packages/urllib3/packages/backports/*
    /usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname/*
    /usr/lib/python2.7/site-packages/urllib3/util/selectors.py
    /usr/lib/python2.7/site-packages/urllib3/util/wait.py
Proceed (y/n)? n

[suretec@tommen ~]$ python -c "import urllib3"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named urllib3
```

**Comment by Qmando** [comment]
What does `which python` output? Maybe it's possible that you have multiple Python installations? I know this happens on MacOS a lot because of conflicting system vs package-manager installs.

**Comment by ghenry** [comment]
So I can fix it like so (the urllib3 import error):

```
pip uninstall requests
pip uninstall urllib3
yum remove python-urllib3
yum remove python-requests
yum install python-urllib3
yum install python-requests
```

but then the index command fails:

```
 elastalert-create-index 
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests>=2.10.0' distribution was not found and is required by elastalert
[suretec@tommen elastalert]$ rpm -q python-requests
python-requests-2.6.0-1.el7_1.noarch
```

**Comment by ghenry** [comment]
If I update requests by pip, I get:

```
[suretec@tommen elastalert]$ sudo pip install --upgrade requests
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting requests
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python2.7/site-packages (from requests) (2.6)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests)
  Using cached https://files.pythonhosted.org/packages/39/ec/d93dfc69617a028915df914339ef66936ea976ef24fa62940fd86ba0326e/urllib3-1.25.2-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests) (2017.7.27.1)
ERROR: botocore 1.12.140 has requirement urllib3<1.25,>=1.20, but you'll have urllib3 1.25.2 which is incompatible.
Installing collected packages: urllib3, requests
  Found existing installation: urllib3 1.10.2
    Uninstalling urllib3-1.10.2:
      Successfully uninstalled urllib3-1.10.2
  Found existing installation: requests 2.6.0
ERROR: Cannot uninstall 'requests'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
WARNING: You are using pip version 19.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[suretec@tommen elastalert]$ python -c "import urllib3"
[suretec@tommen elastalert]$
```

**Comment by ghenry** [comment]
Any ideas?

**Comment by ghenry** [comment]
Shame no one else is experiencing this. What's the preferred OS to run this on/?

**Comment by ghenry** [comment]
Going to use a docker image for this. Thanks.
