### ISSUE TITLE
Error executing elastalert-test-rule during args/conf readout

### ISSUE THREAD

**Issue by malud** [Yelp/elastalert#2274]
I am trying to get the latest elastalert version to run with ELK 6 Stack.. however:

executing `elastalert-test-rule --config config.yaml my-rule.yaml` throws:

```
...
Traceback (most recent call last):
File "/usr/bin/elastalert-test-rule", line 11, in <module>
     load_entry_point('elastalert==0.2.0b2', 'console_scripts', 'elastalert-test-rule')()
   File "/usr/lib/python2.7/site-packages/elastalert/test_rule.py", line 441, in main
     test_instance.run_rule_test()
   File "/usr/lib/python2.7/site-packages/elastalert/test_rule.py", line 408, in run_rule_test
     conf = load_conf(args, defaults, overwrites)
   File "/usr/lib/python2.7/site-packages/elastalert/config.py", line 47, in load_conf
     configure_logging(args, conf)
   File "/usr/lib/python2.7/site-packages/elastalert/config.py", line 106, in configure_logging
     if args.verbose and args.debug:
AttributeError: 'Namespace' object has no attribute 'verbose'
```

config content:

```yaml
rules_folder: /opt/elastalert/rules/

buffer_time:
  minutes: 30

run_every:
  seconds: 10

es_host: elasticsearch-status
es_port: 9200

writeback_index: elastalert_status
```

I have tried all suggestions mentioned in #2204

**Comment by Atem18** [comment]
Same issue here with an older ELK. And from what i see, it has nothing to do with the version of ELK.

**Comment by zffocussss** [comment]
> Same issue here with an older ELK. And from what i see, it has nothing to do with the version of ELK. The error is gone if you run Elastalert with --verbose or --debug.

really?

**Comment by malud** [comment]
> Same issue here with an older ELK. And from what i see, it has nothing to do with the version of ELK. The error is gone if you run Elastalert with --verbose or --debug.

I am talking about `elastalert-test-rule` which has no verbose or debug option.

Error thrown: `elastalert-test-rule: error: unrecognized arguments: --verbose`

```
usage: elastalert-test-rule [-h] [--schema-only] [--days DAYS] [--start START]
                            [--end END] [--stop-error] [--formatted-output]
                            [--data FILENAME] [--alert] [--save-json FILENAME]
                            [--use-downloaded]
                            [--max-query-size MAX_QUERY_SIZE] [--count-only]
                            [--config CONFIG]
                            rule
```

Related: https://github.com/Yelp/elastalert/issues/2303

**Comment by Idriel** [comment]
Same here with Docker version: 3.0.0-beta.0

**Comment by Qmando** [comment]
Fixed in #2339
