### ISSUE TITLE
Elastalert-0.2.0b2 and ES-7.1.1: 24 query hits (0 already seen), 0 matches, 0 alerts sent

### ISSUE THREAD

**Issue by Djyamss** [Yelp/elastalert#2292]
I am currently triying to integrate elastalert with ES-7.1.1.

Config.yaml:
`
es_host: x.x.x.x

es_port: 9200

rules_folder: rules

run_every:
  seconds: 30

buffer_time:
  minutes: 1

aggregation:
 minutes: 5

writeback_index: elastalert_status

alert_time_limit:
  days: 1
`
Below is my rule:

`name: Metricbeat CPU Spike Rule
type: metric_aggregation

index: metricbeat-*

buffer_time:
  minutes: 1

metric_agg_key: system.cpu.user.pct
metric_agg_type: avg
query_key: beat.hostname

  
sync_bucket_interval: true

min_threshold: 0
max_threshold: 0.1

filter:
- term:
    metricset.name: cpu

alert:
- email:
     from_addr: "xxx@gmail.com"
     email: "xx@domain"
`
I tried to set "realert to 0 min, ... but no value matches.

I am getting this output:
`WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
INFO:elastalert:Ran Metricbeat CPU Spike Rule from 2019-06-13 12:27 WAT to 2019-06-13 12:28 WAT: 24 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Background configuration change check run at 2019-06-13 12:28 WAT
INFO:elastalert:Background alerts thread 0 pending alerts sent at 2019-06-13 12:28 WAT
INFO:elastalert:Sleeping for 29.99999 seconds
`
Need your support please.
Regards!

**Comment by Djyamss** [comment]
Found this in my elasticsearch.log file. Maybe it'll be halpfull:

`Caused by: org.apache.lucene.queryparser.classic.ParseException: Encountered "<EOF>" at line 1, column 10.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    
	at org.apache.lucene.queryparser.classic.QueryParser.generateParseException(QueryParser.java:931) ~[lucene-queryparser-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 12:00:09]
	at org.apache.lucene.queryparser.classic.QueryParser.jj_consume_token(QueryParser.java:813) ~[lucene-queryparser-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 12:00:09]
	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:373) ~[lucene-queryparser-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 12:00:09]
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:244) ~[lucene-queryparser-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 12:00:09]
	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215) ~[lucene-queryparser-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 12:00:09]
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109) ~[lucene-queryparser-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 12:00:09]
	at org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:784) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:909) ~[elasticsearch-7.1.1.jar:7.1.1]
	... 22 more
`

**Comment by dsen19** [comment]
Note: If you're using Elasticsearch 7, you'll need to install a beta release of Elastalert: `pip install "elastalert>=0.2.0b"`

**Comment by Djyamss** [comment]
I'm great now. It is sending email. Very glad this morning!

**Comment by moix** [comment]
Hi @Djyamss , can you say then that 0.2.0b2 works fine with elastic 7.1.x? I wanted to move as well but better if I know in advance that it works

**Comment by Djyamss** [comment]
@moix yes it works fine with  ES-7.1.1. By default, it installes ES-7.0.2 in the pip command. Took me  a bit time but it is running now as well.

**Comment by akamzin** [comment]
@Djyamss How did you install python pip module for ES-7.1.1?

**Comment by Qmando** [comment]
7.0.2 is still the newest version available. Source: https://pypi.org/simple/elasticsearch/

Probably works fine with 7.1.1

**Comment by PedroMSantosD** [comment]
Hi, using elasticsearch 7.0.2 [release](https://github.com/elastic/elasticsearch-py/releases/tag/7.0.2) , I have found that aggregation  queries do not work; the aggregated value is empty, as reported by elasticseach query.   Not sure if elastalert is not generating the proper query, or if it is the elasticsearch module not able to match elasticsearch 7.1.1 syntax?. 

@Djyamss , do you have a newer module for elasticsearch ?? Do these type of rules/queries work for you?

I have successfully tested rules of type:
- change
- spike and
- flatline.
and I have validated in Kibana  that the aggregated key is aggregable.

Details follow:

installed packages:
```
pip freeze | grep elast
elastalert==0.2.0b2
elasticsearch==7.0.2
```
Example Rule
```
name: slow_transaction
type: metric_aggregation
index: apm-7.1.0-transaction-*

metric_agg_key: transaction.duration.us
metric_agg_type: avg
doc_type: doc
max_threshold: 2

filter:
- query:
    query_string:
      query: "service.environment:dev AND service.name:my-application-name AND transaction.name:some-http-transaction"

alert:
- "alerta"
- "hipchat"

#ommiting_alerta_and_hipchat: from_this_post
```

the --es_debub_trace logs the following queries (which should not use localhost, but my elastisearch hostname instead!)
```
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/apm-7.1.0-transaction-*/doc/_search?pretty&ignore_unavailable=true&size=0' -d '{
  "aggs": {
    "metric_transaction.duration.us_avg": {
      "avg": {
        "field": "transaction.duration.us"
      }
    }
  },
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2019-07-24T08:11:37.473354Z",
                  "lte": "2019-07-24T08:12:37.473354Z"
                }
              }
            },
            {
              "query_string": {
                "query": "service.environment:dev AND service.name:my-application-name AND transaction.name:some-http-transaction"
              }
            }
          ]
        }
      }
    }
  }
}'
curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/elastalert_status_status/_doc?pretty' -d '{
  "@timestamp": "2019-07-24T08:13:18.237350Z",
  "endtime": "2019-07-24T08:12:37.473354Z",
  "hits": 0,
  "matches": 0,
  "rule_name": "slow_transaction",
  "starttime": "2019-07-24T08:09:37.473354Z",
  "time_taken": 0.04545402526855469
}'
curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/elastalert_status_status/_doc?pretty' -d '{
  "@timestamp": "2019-07-24T08:13:18.237350Z",
  "endtime": "2019-07-24T08:12:37.473354Z",
  "hits": 0,
  "matches": 0,
  "rule_name": "slow_transaction",
  "starttime": "2019-07-24T08:09:37.473354Z",
  "time_taken": 0.04545402526855469
}'
```

with a reply of the forrm:
```
{
  "took" : 63,
  "timed_out" : false,
  "_shards" : {
    "total" : 42,
    "successful" : 42,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "metric_transaction.duration.us_avg" : {
      "value" : null
    }
  }
}
```

**Comment by Djyamss** [comment]
@PedroMSantosD aggregation type was not sending alert while hiting. So I changed the rule type to "any" so that solved it for me. Below is a sample which is running for me:

`name: Metricbeat CPU Spike Rule
type: any
index: metricbeat-*
metric_agg_key: system.cpu.user.pct
metric_agg_type: avg
query_key: beat.hostname
timeframe:
  minutes: 5
min_threshold: 0.2
max_threshold: 0.8
filter:
- term:
    metricset.name: "cpu"
realert:
  minutes: 0
aggregation:
 minutes: 30

alert:
- "email"
email:
- "email"
smtp_host: "IP" 
smtp_port: XX
smtp_ssl: false

from_addr: "email"`

**Comment by PedroMSantosD** [comment]
as per [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/search-aggregations.html)
should be aggregations, instead of aggs;
```
"aggregations" : {
    "<aggregation_name>" : {
        "<aggregation_type>" : {
            <aggregation_body>
        }
        [,"meta" : {  [<meta_data_body>] } ]?
        [,"aggregations" : { [<sub_aggregation>]+ } ]?
    }
    [,"<aggregation_name_2>" : { ... } ]*
}
```

**Comment by PedroMSantosD** [comment]
@Djyamss will check; thanks.

**Comment by PedroMSantosD** [comment]
I just found that if I set the doc_type to '' on the yaml rule configuration; the CURL is made to the proper URL
```
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/apm-7.1.0-transaction-*/_search?pretty&ignore_unavailable=true&size=0' -d '{
  "aggs": {
```
that is, without the doc.
Now aggregations work!
