### ISSUE TITLE
'Rejecting mapping update to elastalert' ES 6/7

### ISSUE THREAD

**Issue by devansh2001** [Yelp/elastalert#2294]
Hello! I am trying to setup the ElastAlert from scratch. I followed the official documentation and got everything working till the point where I have the rule tested. Now, I want to run ElastAlert using `python -m elastalert.elastalert --verbose --rule example_frequency.yaml `. I did that and I see this output

```
INFO:elastalert:Starting up
WARNING:elasticsearch:GET http://localhost:9200/elastalert/_search?size=1000 [status:404 request:0.002s]
ERROR:root:Error finding recent pending alerts: NotFoundError(404, u'index_not_found_exception', u'no such index', elastalert, index_or_alias) {'sort': {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'alert_time': {'to': '2019-06-13T16:53:22.419734Z', 'from': '2019-06-11T16:53:22.419699Z'}}}, 'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}}}}
Traceback (most recent call last):
  File "/<Path>/elastalert/elastalert/elastalert.py", line 1519, in find_recent_pending_alerts
    res = self.writeback_es.search(index=self.writeback_index, body=query, size=1000)
  File "/<Path>/Library/Python/2.7/lib/python/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/<Path>/Library/Python/2.7/lib/python/site-packages/elasticsearch/client/__init__.py", line 819, in search
    "GET", _make_path(index, "_search"), params=params, body=body
  File "/<Path>/Library/Python/2.7/lib/python/site-packages/elasticsearch/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/<Path>/Library/Python/2.7/lib/python/site-packages/elasticsearch/connection/http_requests.py", line 155, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/<Path>/Library/Python/2.7/lib/python/site-packages/elasticsearch/connection/base.py", line 178, in _raise_error
    status_code, error_message, additional_info
NotFoundError: NotFoundError(404, u'index_not_found_exception', u'no such index', elastalert, index_or_alias)
INFO:elastalert:Queried rule Example frequency rule from 2019-06-13 12:38 EDT to 2019-06-13 12:53 EDT: 0 / 0 hits
WARNING:elasticsearch:POST http://localhost:9200/elastalert_status/_doc [status:400 request:0.007s]
ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, u'illegal_argument_exception', u'Rejecting mapping update to [elastalert_status] as the final mapping would have more than 1 type: [elastalert, _doc]')
Traceback (most recent call last):
  File "/<Path>/elastalert/elastalert/elastalert.py", line 1493, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/<Path>/Library/Python/2.7/lib/python/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/<Path>/Library/Python/2.7/lib/python/site-packages/elasticsearch/client/__init__.py", line 364, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/<Path>/Library/Python/2.7/lib/python/site-packages/elasticsearch/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/<Path>/Library/Python/2.7/lib/python/site-packages/elasticsearch/connection/http_requests.py", line 155, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/<Path>/Library/Python/2.7/lib/python/site-packages/elasticsearch/connection/base.py", line 178, in _raise_error
    status_code, error_message, additional_info
RequestError: RequestError(400, u'illegal_argument_exception', u'Rejecting mapping update to [elastalert_status] as the final mapping would have more than 1 type: [elastalert, _doc]')
INFO:elastalert:Ran Example frequency rule from 2019-06-13 12:38 EDT to 2019-06-13 12:53 EDT: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59.974204 seconds
```

As mentioned in #1479 , I did try to change the `writeback_index` name to `elastalert` from `elastalert_status`, but the output is the same. Any support on the issue is highly appreciated.

**Comment by dperetti** [comment]
I think the type is now deprecated in Elasticsearch 7 and you get into trouble when you try to use one that is not `_doc`.

**Comment by chicken231** [comment]
> the final mapping would have more than 1 type: [elastalert, _doc]')

Looks like reserved field `_type` was changed after this index was created. It will only index documents when `_type` is exactly the same for every document. You can either re-index it, make changes to that field for every document. Or delete the index and proceed with a single value for `_type`, which in ES 7.x is supposed to be `_doc` all the way around.

**Comment by AshleyDumaine** [comment]
+1, I'm also having this issue on K8s using Elasticsearch 6.7.0. This is when I try to run the following in the dev console per the [README for the Helm chart](https://github.com/helm/charts/tree/master/stable/elastalert):
```
PUT /elastalert/_mapping/elastalert
{
  "properties": {
      "alert_time": {"type": "date"}
  }
}
```
Output:
```
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[efk-stack-elasticsearch-master-0][10.2.2.57:9300][indices:admin/mapping/put]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Rejecting mapping update to [elastalert] as the final mapping would have more than 1 type: [elastalert, _doc]"
  },
  "status": 400
}
```

**Comment by AshleyDumaine** [comment]
FWIW I was able to fix the above by switching the curl to the following:
```
PUT /elastalert/_mapping/_doc
{
  "properties": {
      "alert_time": {"type": "date"}
  }
}
```
