### ISSUE TITLE
ImportError: cannot import name DEFAULT_CIPHERS

### ISSUE THREAD

**Issue by weiwendi** [Yelp/elastalert#2306]
# python -m elastalert.elastalert --verbose --rule nginx_access.yaml 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.39-py2.7.egg/elastalert/elastalert.py", line 19, in <module>
    import kibana
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.39-py2.7.egg/elastalert/kibana.py", line 5, in <module>
    from util import EAException
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.39-py2.7.egg/elastalert/util.py", line 10, in <module>
    from auth import Auth
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.39-py2.7.egg/elastalert/auth.py", line 3, in <module>
    import boto3
  File "/usr/lib/python2.7/site-packages/boto3-1.9.172-py2.7.egg/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/lib/python2.7/site-packages/boto3-1.9.172-py2.7.egg/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/lib/python2.7/site-packages/botocore-1.12.172-py2.7.egg/botocore/session.py", line 30, in <module>
    import botocore.credentials
  File "/usr/lib/python2.7/site-packages/botocore-1.12.172-py2.7.egg/botocore/credentials.py", line 42, in <module>
    from botocore.utils import InstanceMetadataFetcher, parse_key_val_file
  File "/usr/lib/python2.7/site-packages/botocore-1.12.172-py2.7.egg/botocore/utils.py", line 31, in <module>
    import botocore.httpsession
  File "/usr/lib/python2.7/site-packages/botocore-1.12.172-py2.7.egg/botocore/httpsession.py", line 7, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name DEFAULT_CIPHERS

**Comment by flippakitten** [comment]
If anyone every comes across this again, you basically need to update urllib3:
`pip install --upgrade urllib3 --user`

or if you have different versions of Python:
`python -m pip install --upgrade urllib3 --user`

**Comment by kaushik98y** [comment]
python -m pip install --upgrade urllib3 --user 
Command solves the issue.

> If anyone every comes across this again, you basically need to update urllib3: `pip install --upgrade urllib3 --user`
> 
> or if you have different versions of Python: `python -m pip install --upgrade urllib3 --user`

**Comment by CliveCorbishleyTAL** [comment]
`DEFAULT_CIPHERS` is removed from urllib3 `2.0.0`

If you encounter this in 2023 or later, you might want want to pin to a version < 2

```
pip install 'urllib3<2'
```

**Comment by ali86tx** [comment]
I tried it and it's still not working :/

**Comment by saharudra** [comment]
@CliveCorbishleyTAL Where did you get `DEFAULT_CIPHERS is removed from urllib3 2.0.0` information from?

**Comment by chanlawrencet** [comment]
@saharudra -- looks like it's in the `urllib` changelog: https://github.com/urllib3/urllib3/blob/b234aaf7ccbcb64012d8b33d21eb8bc9f768935d/CHANGES.rst#L43
