### ISSUE TITLE
Line Notify Error and Rule of Change Error

### ISSUE THREAD

**Issue by roke1845** [Yelp/elastalert#2307]
I use docker to build elastalert.
This is my rule yaml

`type: change
index: heartbea*
compare_key: monitor.status
ignore_null: true
query_key: url.domain
timeframe:
  seconds: 10
filter:
- query_string:
    query: "url.domain: linxpa-pecass00"
alert:
- "linenotify"
linenotify_access_token: "line token"`

`01:33:37.669Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Could not load rule rules/test.yaml: Error initiating alert ['linenotify']: Could not import module linenotify: need more than 1 value to unpack`

`
01:44:07.682Z ERROR elastalert-server:
    ProcessController:  ERROR:apscheduler.executors.default:Job "ElastAlerter.handle_config_change (trigger: interval[0:00:15], next run at: 2019-06-24 01:44:22 UTC)" raised an exception
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/APScheduler-3.6.0-py2.7.egg/apscheduler/executors/base.py", line 125, in run_job
        retval = job.func(*job.args, **job.kwargs)
      File "/opt/elastalert/elastalert/elastalert.py", line 1211, in handle_config_change
        self.load_rule_changes()
      File "/opt/elastalert/elastalert/elastalert.py", line 1082, in load_rule_changes
        self.send_notification_email(exception=e, rule=rule_yaml)
      File "/opt/elastalert/elastalert/elastalert.py", line 1914, in send_notification_email
        rule_name = rule['name']
    KeyError: 'name'`

**Comment by crow1011** [comment]
Не хватает поля name в правиле
добавьте:
name: testrule
type: change  
index: heartbea*  
compare_key: monitor.status  
ignore_null: true  
query_key: url.domain  
timeframe:  
  seconds: 10  
filter:  
-   query_string:  
    query: "url.domain: hostname"  
alert:  
-   "linenotify"  
linenotify_access_token: "line token"

**Comment by nsano-rururu** [comment]
elastalert/loaders.py

before

```
'hivealerter': alerts.HiveAlerter
```

after

```
'hivealerter': alerts.HiveAlerter,
'linenotify': alerts.LineNotifyAlerter

```
