### ISSUE TITLE
Regarding install elastalert for ES7.1.1.

### ISSUE THREAD

**Issue by LeeYuLai** [Yelp/elastalert#2317]
Hi All, 

I am new to elastalert (also GitHub in general). 

After researching for a few days about using elastalert with ES7,

I am really confused about how to get it to work.

Can anyone had experience with elastalert on ES7 give me some suggestion on installation and configuration?

My elasticsearch in running on an Ubuntu server.

Any suggestion will be appreciated.

**Comment by Qmando** [comment]
Try
```
pip install elastalert==0.2.0b2
pip install "elasticsearch>7"
```

**Comment by LeeYuLai** [comment]
Hi Qmando,

Thanks for the reply.

I will try it.

**Comment by lsoumille** [comment]
Hi @Qmando 
When are you planning to make an official release for ElasticSearch 7 ?
Thanks

**Comment by zozo6015** [comment]
When I am trying to run elastalert-test-rule I am getting the following error:

    Traceback (most recent call last):
      File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/dist-packages/elastalert/test_rule.py", line 441, in main
         test_instance.run_rule_test()
      File "/usr/local/lib/python2.7/dist-packages/elastalert/test_rule.py", line 408, in run_rule_test
        conf = load_conf(args, defaults, overwrites)
      File "/usr/local/lib/python2.7/dist-packages/elastalert/config.py", line 44, in load_conf
        conf = yaml_loader(filename)
      File "/usr/local/lib/python2.7/dist-packages/staticconf/loader.py", line 167, in yaml_loader
        with open(filename) as fh:
    TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by Qmando** [comment]
elastalert-test-rule is broken for 7 right now unfortunately, sorry about that.

**Comment by zozo6015** [comment]
The file was provided as part of the command. But anyways.
