### ISSUE TITLE
ElastAlert docker image cannot run successfully

### ISSUE THREAD

**Issue by wl105500396** [Yelp/elastalert#2325]
Hi, 
I'm now considering about using latestelastalert server docker image ( which could be found in the docker hub bitsensor/elastalert, tag:latest), but the image are not be able to run successfully and docker logs command shows below 2 error messages:
1. ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/create_index.py", line 275, in <module>
        main()
      File "/opt/elastalert/elastalert/create_index.py", line 252, in main
        es.indices.put_mapping(index=index, doc_type='elastalert', body=es_mapping)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/indices.py", line 339, in put_mapping
        "PUT", _make_path(index, "_mapping", doc_type), params=params, body=body
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/transport.py", line 353, in perform_request
        timeout=timeout,
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 143, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/connection/base.py", line 168, in _raise_error
        status_code, error_message, additional_info
    elasticsearch.exceptions.RequestError: RequestError(400, u'illegal_argument_exception', u'Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.')

2. ERROR elastalert-server:
    ProcessController:      "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/elastalert.py", line 1929, in <module>
        sys.exit(main(sys.argv[1:]))
      File "/opt/elastalert/elastalert/elastalert.py", line 1925, in main

09:49:06.039Z ERROR elastalert-server:
    ProcessController:      client.start()
      File "/opt/elastalert/elastalert/elastalert.py", line 1106, in start

09:49:06.039Z ERROR elastalert-server:
    ProcessController:      self.run_all_rules()
      File "/opt/elastalert/elastalert/elastalert.py", line 1158, in run_all_rules

09:49:06.040Z ERROR elastalert-server:
    ProcessController:      self.send_pending_alerts()
      File "/opt/elastalert/elastalert/elastalert.py", line 1534, in send_pending_alerts

09:49:06.040Z ERROR elastalert-server:
    ProcessController:      pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
      File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts

09:49:06.040Z ERROR elastalert-server:
    ProcessController:      size=1000)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
    TypeError:
09:49:06.041Z ERROR elastalert-server:
    ProcessController:  search() got an unexpected keyword argument 'doc_type'

I also tried some other versions like tag: 3.0.0-beta.0 and it seems like different image occurs different error but won't be running. due to some internet access limitation I can not build the docker image locally on that server, can anyone give any advices on this and thanks in advance. (I'm using ES 7.0.1).

**Comment by cmeisinger** [comment]
I'm seeing the same thing here.

**Comment by wl105500396** [comment]
> I'm seeing the same thing here.

hi cmeisinger,

Since there is no reply at all and after trying several different image versions and I found this image (tag: 3.0.0-beta.0) could work through but only occurs a  permission exception ( mounted file cannot be read due to the user in the container is node but it's not outside in the host machine in my case). in order to solve this, I have to grant them 777 access permission ( could be lower but it doesn't matter) in the host machine. I think you could give it a shoot. 🙂
BYW, I still want to hear from alert team  ...

**Comment by azbesthu** [comment]
It seems Elastalert has the latest elasticsearch python package as dependency. But Elasticsearch fastly progressing with versions, so it downloads now the package made for Elasticsearch7. 
If you change "elasticsearch" to "elasticsearch6" in setup.py, it will be able to build it. (other method is to add >5,<7 version limit to elasticsearch.)

Is 3.0.0-beta.0 from Bitsensor's repo? That is a REST API extension for Yelp's elastalert and that  downloads elastalert.zip from here or from a specific custom url - you can add with that you modded version of elastalert.

**Comment by qakart** [comment]
@azbesthu thanks for your input i am using ESS 7.3.3  still ima getting following error i am using https://github.com/Yelp/elastalert/archive/v0.2.1.zip

`10:47:29.843Z  INFO elastalert-server: Server:  Server started
10:47:31.134Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/elastalert.py", line 1929, in <module>
    
10:47:31.134Z ERROR elastalert-server:
    ProcessController:      sys.exit(main(sys.argv[1:]))
      File "/opt/elastalert/elastalert/elastalert.py", line 1925, in main
        client.start()
      File "/opt/elastalert/elastalert/elastalert.py", line 1106, in start
        self.run_all_rules()
      File "/opt/elastalert/elastalert/elastalert.py", line 1158, in run_all_rules
        self.send_pending_alerts()
      File "/opt/elastalert/elastalert/elastalert.py", line 1534, in send_pending_alerts
        pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
      File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts
    
10:47:31.136Z ERROR elastalert-server:
    ProcessController:      size=1000)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
    TypeError: search() got an unexpected keyword argument 'doc_type'
`

any input would be great and please let me know is there any way I can contribute as well

**Comment by qakart** [comment]
@here i have managed to fix the issue to upgrade to latest version 0.2.1 and working fine

**Comment by gabricar** [comment]
I'm having the same issue. my elasticsearch version is 7.5. ElastAlert does not start:

14:34:02.081Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    
14:34:02.081Z ERROR elastalert-server:
    ProcessController:      exec code in run_globals
      File "/opt/elastalert/elastalert/elastalert.py", line 1929, in <module>
        sys.exit(main(sys.argv[1:]))
      File "/opt/elastalert/elastalert/elastalert.py", line 1925, in main
    
14:34:02.081Z ERROR elastalert-server:
    ProcessController:      client.start()
      File "/opt/elastalert/elastalert/elastalert.py", line 1106, in start
    
14:34:02.082Z ERROR elastalert-server:
    ProcessController:      self.run_all_rules()
    
14:34:02.082Z ERROR elastalert-server:
    ProcessController:    File "/opt/elastalert/elastalert/elastalert.py", line 1158, in run_all_rules
    
14:34:02.082Z ERROR elastalert-server:
    ProcessController:      self.send_pending_alerts()
    
14:34:02.082Z ERROR elastalert-server:
    ProcessController:    File "/opt/elastalert/elastalert/elastalert.py", line 1534, in send_pending_alerts
    
14:34:02.082Z ERROR elastalert-server:
    ProcessController:      pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
    
14:34:02.083Z ERROR elastalert-server:
    ProcessController:    File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts
    
14:34:02.083Z ERROR elastalert-server:
    ProcessController:      size=1000)
    
14:34:02.083Z ERROR elastalert-server:
    ProcessController:    File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
    TypeError: search() got an unexpected keyword argument 'doc_type'
    
14:34:02.107Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
14:34:02.107Z  INFO elastalert-server: Server:  Stopping server
14:34:02.108Z  INFO elastalert-server: ProcessController:  ElastAlert is not running
14:34:02.108Z  INFO elastalert-server: Server:  Server stopped. Bye!

**Comment by daichi703n** [comment]
@gabricar 
Which DockerImage are you using? `bitsensor/elastalert:3.0.0-beta.1`?

**Comment by gabricar** [comment]
@daichi703n I'm running the latest. Let me try this beta tag

**Comment by gabricar** [comment]
@daichi703n  thx it looks better with the beta release.

**Comment by aliasmee** [comment]
docker run -d -p 3030:3030 \
    -v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml \
    -v `pwd`/config/config.json:/opt/elastalert-server/config/config.json \
    -v `pwd`/rules:/opt/elastalert/rules \
    -v `pwd`/rule_templates:/opt/elastalert/rule_templates \
    --net="host" \
    --name elastalert bitsensor/elastalert:3.0.0-beta.1
