### ISSUE TITLE
IOError: [Errno 14] Bad address

### ISSUE THREAD

**Issue by jeff-cook** [Yelp/elastalert#2332]
I get the following error when testing a rule.

Elastalert versions tested. `v0.2.0b2` and master (`7980f9b4c3`)

Elasticsearch version `docker.elastic.co/elasticsearch/elasticsearch:7.1.1`

```
/opt/elastalert # elastalert --verbose --rule rules/metricbeat_anything.yaml
Traceback (most recent call last):
  File "/usr/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert==0.1.39', 'console_scripts', 'elastalert')()
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.39-py2.7.egg/elastalert/elastalert.py", line 1936, in main
    client = ElastAlerter(args)
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.39-py2.7.egg/elastalert/elastalert.py", line 109, in __init__
    self.conf = load_rules(self.args)
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.39-py2.7.egg/elastalert/config.py", line 505, in load_rules
    rule = load_configuration(rule_file, conf, args)
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.39-py2.7.egg/elastalert/config.py", line 131, in load_configuration
    raise e
IOError: [Errno 14] Bad address
```
The rule

```YAML
/opt/elastalert # cat rules/metricbeat_anything.yaml
alert:
- post
description:
    template_id: metricbeat
es_host: elasticsearch
es_port: 9200
es_use_ssl: false
filter:
-   query_string:
        query: '*'
http_post_all_values: true
http_post_static_payload:
    alert_index_pattern: metricbeat-*
    alert_rule_description:
        template_id: metricbeat
    alert_rule_name: metricbeat anything
    template_id: metricbeat
http_post_url: http://alerthandler:8080/alert
index: metricbeat-*
name: metricbeat anything
num_events: 1
realert:
    minutes: 1
timeframe:
    seconds: 60
type: frequency
```

The config.yaml
```YAML
/opt/elastalert # cat config.yaml
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
# es_host: elasticsearch
# # The elasticsearch port
# es_port: 9200

# ca_certs: /opt/elastalert/internal_ca_root.pem
# es_ca_certs: /opt/elastalert/internal_ca_root.pem
# tls_process_server_certificate: /opt/elastalert/internal_ca_root.pem
verify_certs: false

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 60

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

http_post_url: http://alerthandler:8080/alert
http_post_all_values: true
```
The environment
```
/opt/elastalert # env
HOSTNAME=18b93f941578
SHLVL=1
HOME=/root
CA_CERTS=/opt/elastalert/internal_ca_root.pem
ES_USERNAME=
ES_USE_SSL=false
ELASTALERT_CONFIG_DIR=/opt/elastalert
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ES_PASSWORD=
ES_HOST=elasticsearch
PWD=/opt/elastalert
TZ=Etc/UTC
ES_PORT=9200
```

**Comment by jeff-cook** [comment]
To show I have connection to Elasticsearch.

```
/opt/elastalert # elastalert-create-index
Elastic Version: 7.1.1
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
Index elastalert_status already exists. Skipping index creation.
/opt/elastalert # curl $ES_HOST:$ES_PORT
{
  "name" : "elasticsearch",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "jl2AfRWiSg6hGg-aPmW3BQ",
  "version" : {
    "number" : "7.1.1",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "7a013de",
    "build_date" : "2019-05-23T14:04:00.380842Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by gerbdla** [comment]
I am not getting the error but my co-worker is and we are on the same version of Mojave on mac.  Very strange.

**Comment by jeff-cook** [comment]
Any chance they are using Vagrant or a linked folder for the rule? 
I think I have it narrowed down to a file (owner/mode/link) issue and not the content of the rule file itself.

**Comment by jeff-cook** [comment]
There is something about using a Vagrant mounted directory. After I copied the rules files from that directory to a local directory on the guest, then Elastalert was able to run the rule(s).

Not sure if this was strictly a Vagrant issue or a Docker issue or the mix of the two. The provided error message was not useful in solving the issue.

**Comment by gerbdla** [comment]
Can you be a little more specific?  The guest meaning what?  Did you remove
the mounting in Vagrant where did you copy the files to?  The guest meaning
the docker
container?  How is that done.  I didn't think you could copy files to the
docker container.  Sorry a little confused.

**Comment by jeff-cook** [comment]
Mac OSX physical host running Vagrant.
Vagrant/VBox RedHat guest to run lab system running Docker.
Vagrant guest has directory mounted to Mac OSX (allowing me to use my code editor on the files).
Docker container running Elasticsearch and Elastalert. 
Elastalert container has bind mount to directory with rules. 
When the bind mount points to the directory that is mounted the Mac, the error happen.
When the bind mount points to a directory that is NOT mounted the Mac, the error does NOT happen.
The error happens when the files are give mode 0777 from the Mac thru the Docker container.
