### ISSUE TITLE
server startup error

### ISSUE THREAD

**Issue by DavenAaron** [Yelp/elastalert#2362]
> @bitsensor/elastalert@2.0.1 start /opt/elastalert-server
> sh ./scripts/start.sh
11:43:18.307Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
11:43:18.309Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
11:43:18.310Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
11:43:18.319Z  INFO elastalert-server: Router:  Listening for GET request on /.
11:43:18.319Z  INFO elastalert-server: Router:  Listening for GET request on /status.
11:43:18.319Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
11:43:18.319Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
11:43:18.319Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
11:43:18.321Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
11:43:18.322Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
11:43:18.322Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
11:43:18.322Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
11:43:18.322Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
11:43:18.322Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
11:43:18.322Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
11:43:18.323Z  INFO elastalert-server: Router:  Listening for POST request on /test.
11:43:18.326Z  INFO elastalert-server: Router:  Listening for GET request on /config.
11:43:18.326Z  INFO elastalert-server: Router:  Listening for POST request on /config.
11:43:18.326Z  INFO elastalert-server: Router:  Listening for POST request on /download.
11:43:18.326Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/:type.
11:43:18.327Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
11:43:18.327Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
11:43:18.330Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
11:43:18.330Z  INFO elastalert-server: ProcessController:  Creating index
11:43:19.139Z  INFO elastalert-server:
    ProcessController:  Elastic Version:6
    Mapping used for string:{'type': 'keyword'}
    Index elastalert_status already exists. Skipping index creation.

11:43:19.140Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
11:43:19.140Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
11:43:19.150Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 50)
11:43:19.151Z  INFO elastalert-server: Server:  Server listening on port 3030
11:43:19.152Z  INFO elastalert-server: Server:  Websocket listening on port 3333
11:43:19.153Z  INFO elastalert-server: Server:  Server started
11:43:19.839Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main

11:43:19.839Z ERROR elastalert-server:
    ProcessController:      "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/elastalert.py", line 1929, in <module>
        sys.exit(main(sys.argv[1:]))
      File "/opt/elastalert/elastalert/elastalert.py", line 1925, in main
        client.start()
      File "/opt/elastalert/elastalert/elastalert.py", line 1106, in start

11:43:19.839Z ERROR elastalert-server:
    ProcessController:      self.run_all_rules()
      File "/opt/elastalert/elastalert/elastalert.py", line 1158, in run_all_rules

11:43:19.840Z ERROR elastalert-server:
    ProcessController:      self.send_pending_alerts()
      File "/opt/elastalert/elastalert/elastalert.py", line 1534, in send_pending_alerts

11:43:19.840Z ERROR elastalert-server:
    ProcessController:      pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
      File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts

11:43:19.841Z ERROR elastalert-server:
    ProcessController:      size=1000)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped

11:43:19.841Z ERROR elastalert-server:
    ProcessController:      return func(*args, params=params, **kwargs)
    TypeError: search() got an unexpected keyword argument 'doc_type'

11:43:19.880Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
11:43:19.880Z  INFO elastalert-server: Server:  Stopping server
11:43:19.880Z  INFO elastalert-server: ProcessController:  ElastAlert is not running
11:43:19.880Z  INFO elastalert-server: Server:  Server stopped. Bye!

**Comment by Qmando** [comment]
If you're using Elasticsearch 7, you'll need to install a beta release of Elastalert: pip install "elastalert>=0.2.0b"
