### ISSUE TITLE
elastalert-test-rule nonfunctional

### ISSUE THREAD

**Issue by lsc-dotsource** [Yelp/elastalert#237]
Due to the recent move of the host and port into the configuration, it is now mandatory in `load_option()`.
`test_rule()` does not provide `load_option()` with a configuration (only a rule).
Thus, the following error happens when trying to use it:

Traceback (most recent call last):
  File "/usr/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.0.57', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/test_rule.py", line 289, in main
    test_instance.run_rule_test()
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/test_rule.py", line 277, in run_rule_test
    hits = self.test_file(copy.deepcopy(rule_yaml), args)
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/test_rule.py", line 46, in test_file
    load_options(conf)
TypeError: load_options() takes at least 2 arguments (1 given)

**Comment by Qmando** [comment]
Oops! Fixed in https://github.com/Yelp/elastalert/commit/be291b163f19d388525d78265f4f1300ccf7629c
