### ISSUE TITLE
alerts fail when text contains unicode characters

### ISSUE THREAD

**Issue by lsc-dotsource** [Yelp/elastalert#238]
attempting to use a filter on a field containing a unicode/non-ASCII character will cause the following exception in case of an alert:

ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/elastalert.py", line 826, in alert
    return self.send_alert(matches, rule, alert_time=None)
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/elastalert.py", line 887, in send_alert
    alerter.alert(matches)
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/alerts.py", line 166, in alert
    logging.info(str(BasicMatchString(self.rule, match)))
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/alerts.py", line 84, in __str__
    self._add_match_items()
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/alerts.py", line 62, in _add_match_items
    value_str = str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)

after replacing the `str()` call with a `unicode()` call, the following exception occurs:

ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/elastalert.py", line 826, in alert
    return self.send_alert(matches, rule, alert_time=None)
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/elastalert.py", line 887, in send_alert
    alerter.alert(matches)
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.57-py2.6.egg/elastalert/alerts.py", line 166, in alert
    logging.info(str(BasicMatchString(self.rule, match)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 268: ordinal not in range(128)

after replacing the `str()` call with a `unicode()` call, the alert appears to work.

**Comment by gopalganu** [comment]
Will this be handled in any coming releases?

**Comment by Qmando** [comment]
I just merged a change which fixes this particular bug, and several more related to unicode. It's in master branch. I'll make a release with it soon.

**Comment by rogerioms** [comment]
is it in V0.0.73?

**Comment by Qmando** [comment]
This should be fixed. If you encounter another similar error, please post a stack trace.

**Comment by tanxiaolong** [comment]
@Qmando  it is still "UnicodeEncodeError ascii" there.  it can't send Chinese characters by email...

**Comment by Qmando** [comment]
Can you post the stack trace?

**Comment by tanxiaolong** [comment]
@Qmando  sorry that i made a mistake~  and do you know how to make "\n\r" or "<br>" work in email alert?

**Comment by Qmando** [comment]
If you want newlines, you have to use YAML block syntax
```
alert_text: |
  Foo bar baz
  This will be on a new line
  blah blah
```

Whether this technically includes "\r" I think depends on your operating system.

**Comment by ahaii** [comment]
@tanxiaolong 您好，麻烦问下您的问题解决了么？我也遇到同样的问题。
