### ISSUE TITLE
SyntaxError in new release 0.2.1

### ISSUE THREAD

**Issue by yichingwu** [Yelp/elastalert#2388]
I just try to install the new version 0.2.1 using pip3 install elasticalert. but once I start the elastalert then got an error message as below.

```
[root@ELASTALERT-01D bin]# python -V
Python 3.7.4
[root@ELASTALERT-01D bin]# pip freeze | grep elast
elastalert==0.2.1
elasticsearch==7.0.2
[root@ELASTALERT-01D bin]# pip freeze | grep jira
jira==1.0.14
```
---
```
Aug  9 13:43:57 ELASTALERT-01D systemd: Started Elastalert.
Aug  9 13:43:57 ELASTALERT-01D elastalert: Traceback (most recent call last):
Aug  9 13:43:57 ELASTALERT-01D elastalert: File "/usr/local/bin/elastalert", line 6, in <module>
Aug  9 13:43:57 ELASTALERT-01D elastalert: from elastalert.elastalert import main
Aug  9 13:43:57 ELASTALERT-01D elastalert: File "/usr/local/lib/python3.7/site-packages/elastalert/elastalert.py", line 29, in <module>
Aug  9 13:43:57 ELASTALERT-01D elastalert: from .alerts import DebugAlerter
Aug  9 13:43:57 ELASTALERT-01D elastalert: File "/usr/local/lib/python3.7/site-packages/elastalert/alerts.py", line 26, in <module>
Aug  9 13:43:57 ELASTALERT-01D elastalert: from jira.client import JIRA
Aug  9 13:43:57 ELASTALERT-01D elastalert: File "/usr/local/lib/python3.7/site-packages/jira/__init__.py", line 10, in <module>
Aug  9 13:43:57 ELASTALERT-01D elastalert: from jira.client import Comment  # noqa: E402
Aug  9 13:43:57 ELASTALERT-01D elastalert: File "/usr/local/lib/python3.7/site-packages/jira/client.py", line 225
Aug  9 13:43:57 ELASTALERT-01D elastalert: validate=False, get_server_info=True, async=False, logging=True, max_retries=3, proxies=None,
Aug  9 13:43:57 ELASTALERT-01D elastalert: ^
Aug  9 13:43:57 ELASTALERT-01D elastalert: SyntaxError: invalid syntax
Aug  9 13:43:57 ELASTALERT-01D systemd: elastalert.service: main process exited, code=exited, status=1/FAILURE
Aug  9 13:43:57 ELASTALERT-01D systemd: Unit elastalert.service entered failed state.
Aug  9 13:43:57 ELASTALERT-01D systemd: elastalert.service failed.
```

**Comment by Qmando** [comment]
Looks like that library is broken for py3.7. I didn't realize that. You'll need to use py3.6 OR try to upgrade the jira library.

**Comment by yichingwu** [comment]
I try to use python 3.6.9 and it's work fine now, thanks.
