### ISSUE TITLE
[v0.2.1] Elastalert failed to start with python 3.5

### ISSUE THREAD

**Issue by Moep90** [Yelp/elastalert#2392]
Hey there,

I just tested to start elastalert testing with python3.5+ and pip3.
I hope I just missed documentation on this error...

My test Docker-Container:
- `debian:9`

ES_VERSION: 
- `6.3.0`

I tried Elastalert versions:
- `v0.2.0`
- `v0.2.1`

```
$ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
What I install as prequesit: (is there a list for every OS? I couldnt find it..)
```
$ apt-get install libmagic-dev libmagic-mgc libmagic1 libyaml-0-2 musl musl-dev python3-yaml python3-pip python3-dev
```
Verify installed python3 packages
```
$ dpkg -l |grep python3
ii  libpython3-dev:amd64        3.5.3-1                    amd64        header files and a static library for Python (default)
ii  libpython3-stdlib:amd64     3.5.3-1                    amd64        interactive high-level object-oriented language (default python3 version)
ii  libpython3.5:amd64          3.5.3-1+deb9u1             amd64        Shared Python runtime library (version 3.5)
ii  libpython3.5-dev:amd64      3.5.3-1+deb9u1             amd64        Header files and a static library for Python (v3.5)
ii  libpython3.5-minimal:amd64  3.5.3-1+deb9u1             amd64        Minimal subset of the Python language (version 3.5)
ii  libpython3.5-stdlib:amd64   3.5.3-1+deb9u1             amd64        Interactive high-level object-oriented language (standard library, version 3.5)
ii  python3                     3.5.3-1                    amd64        interactive high-level object-oriented language (default python3 version)
ii  python3-cffi-backend        1.9.1-2                    amd64        Foreign Function Interface for Python 3 calling C code - runtime
ii  python3-crypto              2.6.1-7                    amd64        cryptographic algorithms and protocols for Python 3
ii  python3-cryptography        1.7.1-3+deb9u1             amd64        Python library exposing cryptographic recipes and primitives (Python 3)
ii  python3-dbus                1.2.4-1+b1                 amd64        simple interprocess messaging system (Python 3 interface)
ii  python3-dev                 3.5.3-1                    amd64        header files and a static library for Python (default)
ii  python3-gi                  3.22.0-2                   amd64        Python 3 bindings for gobject-introspection libraries
ii  python3-idna                2.2-1                      all          Python IDNA2008 (RFC 5891) handling (Python 3)
ii  python3-keyring             10.1-1                     all          store and access your passwords safely - Python 3 version of the package
ii  python3-keyrings.alt        1.3-1                      all          alternate backend implementations for python3-keyring
ii  python3-minimal             3.5.3-1                    amd64        minimal subset of the Python language (default python3 version)
ii  python3-pip                 9.0.1-2+deb9u1             all          Python package installer
ii  python3-pkg-resources       33.1.1-1                   all          Package Discovery and Resource Access using pkg_resources
ii  python3-pyasn1              0.1.9-2                    all          ASN.1 library for Python (Python 3 module)
ii  python3-secretstorage       2.3.1-2                    all          Python module for storing secrets - Python 3.x version
ii  python3-setuptools          33.1.1-1                   all          Python3 Distutils Enhancements
ii  python3-six                 1.10.0-3                   all          Python 2 and 3 compatibility library (Python 3 interface)
ii  python3-wheel               0.29.0-2                   all          built-package format for Python
ii  python3-xdg                 0.25-4                     all          Python 3 library to access freedesktop.org standards
ii  python3-yaml                3.12-1                     amd64        YAML parser and emitter for Python3
ii  python3.5                   3.5.3-1+deb9u1             amd64        Interactive high-level object-oriented language (version 3.5)
ii  python3.5-dev               3.5.3-1+deb9u1             amd64        Header files and a static library for Python (v3.5)
ii  python3.5-minimal           3.5.3-1+deb9u1             amd64        Minimal subset of the Python language (version 3.5)

```
Here is a List of installed python3 modules
```
$ pip3 list
Package               Version  
--------------------- ---------
APScheduler           3.6.1    
aws-requests-auth     0.4.2    
blist                 1.3.6    
boto3                 1.9.205  
botocore              1.12.205 
certifi               2019.6.16
cffi                  1.12.3   
chardet               3.0.4    
configparser          3.8.1    
croniter              0.3.30   
cryptography          1.7.1    
defusedxml            0.6.0    
docopt                0.6.2    
docutils              0.14     
elastalert            0.2.1    
elasticsearch         7.0.2    
envparse              0.2.0    
exotel                0.1.5    
future                0.17.1   
idna                  2.8      
jira                  1.0.14   
jmespath              0.9.4    
jsonschema            2.6.0    
keyring               10.1     
keyrings.alt          1.3      
mock                  3.0.5    
oauthlib              3.1.0    
pbr                   5.4.2    
pip                   19.2.1   
pyasn1                0.1.9    
pycparser             2.19     
pycrypto              2.6.1    
pygobject             3.22.0   
PyJWT                 1.7.1    
PySocks               1.7.0    
PyStaticConfiguration 0.10.4   
python-dateutil       2.6.1    
python-magic          0.4.15   
pytz                  2019.2   
pyxdg                 0.25     
PyYAML                3.12     
requests              2.22.0   
requests-oauthlib     1.2.0    
requests-toolbelt     0.9.1    
s3transfer            0.2.1    
SecretStorage         2.3.1    
setuptools            33.1.1   
six                   1.10.0   
stomp.py              4.1.22   
texttable             1.6.2    
thehive4py            1.6.0    
twilio                6.0.0    
tzlocal               2.0.0    
urllib3               1.25.3   
wheel                 0.29.0   
WARNING: You are using pip version 19.2.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Run installed binary:
```
$ /usr/local/bin/elastalert --config /etc/elastalert/config.yaml
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/elastalert/elastalert.py", line 2034, in main
    client = ElastAlerter(args)
  File "/usr/local/lib/python3.5/dist-packages/elastalert/elastalert.py", line 136, in __init__
    self.conf = load_conf(self.args)
  File "/usr/local/lib/python3.5/dist-packages/elastalert/config.py", line 90, in load_conf
    rules_loader = rules_loader_class(conf)
  File "/usr/local/lib/python3.5/dist-packages/elastalert/loaders.py", line 94, in __init__
    yaml.load(open(os.path.join(os.path.dirname(__file__), 'schema.yaml')), Loader=yaml.FullLoader))
AttributeError: module 'yaml' has no attribute 'FullLoader'
```

Run with python3.5 explicit:
```
$ python3.5 /usr/local/bin/elastalert --config /etc/elastalert/config.yaml
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/elastalert/elastalert.py", line 2034, in main
    client = ElastAlerter(args)
  File "/usr/local/lib/python3.5/dist-packages/elastalert/elastalert.py", line 136, in __init__
    self.conf = load_conf(self.args)
  File "/usr/local/lib/python3.5/dist-packages/elastalert/config.py", line 90, in load_conf
    rules_loader = rules_loader_class(conf)
  File "/usr/local/lib/python3.5/dist-packages/elastalert/loaders.py", line 94, in __init__
    yaml.load(open(os.path.join(os.path.dirname(__file__), 'schema.yaml')), Loader=yaml.FullLoader))
AttributeError: module 'yaml' has no attribute 'FullLoader'

```

**Comment by Qmando** [comment]
Ah this was my mistake. PyYAML needs to be upgraded. I forgot to include this in the requirements.txt changes. I will do so now.

`pip install PyYAML==5.1` should fix the problem. 🤞 

I've also only really been testing with py3.6 but py3.5 might work too.

**Comment by Moep90** [comment]
> `pip install PyYAML==5.1` should fix the problem.

You'r right. Thank you!
