### ISSUE TITLE
Testing rules on CentOS 7

### ISSUE THREAD

**Issue by ThibaultLaplace** [Yelp/elastalert#2411]
Hi, I'm implementing Elastalert on CentOS 7 and I have some problems. I'm trying to test the rules with this command: elastalert-test-rule --config config.yaml example_rules/example_frequency.yaml but I have a mistake:

```
Traceback (most recent call last):
File "/usr/bin/elastalert-test-rule", line 11, in 
load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
File "/usr/lib/python2.7/site-packages/pkg_resources/init.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.7/site-packages/pkg_resources/init.py", line 2852, in load_entry_point
return ep.load()
File "/usr/lib/python2.7/site-packages/pkg_resources/init.py", line 2443, in load
return self.resolve()
File "/usr/lib/python2.7/site-packages/pkg_resources/init.py", line 2449, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "/usr/lib/python2.7/site-packages/elastalert-0.2.1-py2.7.egg/elastalert/test_rule.py", line 61
print('Invalid filter provided:', str(ea), file=sys.stderr)
```

I tried to install Python3 but I have a different error telling me that a package is missing and commands like pip no longer work. Does anyone know how to properly install Python3 on CentOS or does anyone know a solution to my problem?

Thank you ! :)

**Comment by Qmando** [comment]
Have you tried `pip3` instead of `pip`? A lot of the packages have a different name, like `python3-pip`. If you must use python2, you have to use elastalert v0.1.39

**Comment by weiofcn** [comment]
Same here
