### ISSUE TITLE
Connection aborted - Remote end closed connection without response

### ISSUE THREAD

**Issue by smavroud** [Yelp/elastalert#2425]
Hi and thank you for your time in advance,

We recently upgraded the library to the [latest version](https://github.com/Yelp/elastalert/commit/3affdd7ebf2b6d82c5cfcad0092df97dc27cd8b1) and we also upgraded the running Python version form `2.7 `to `3.6`.

We use the  `elastalert` on a minutely run Lambda function.
After the upgrade we started getting the following error: (Not on every execution)  
####  urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

```
[WARNING]	2019-08-28T12:07:37.264Z	5ccedfbd-0058-4be8-b838-0e020a394e82	GET http://redacted-host/redacted-index-*/_search?_source_includes=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:N/A request:1.109s]
Traceback (most recent call last):
File "/var/task/urllib3/connectionpool.py", line 603, in urlopen
chunked=chunked)
File "/var/task/urllib3/connectionpool.py", line 387, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/var/task/urllib3/connectionpool.py", line 383, in _make_request
httplib_response = conn.getresponse()
File "/var/lang/lib/python3.6/http/client.py", line 1331, in getresponse
response.begin()
File "/var/lang/lib/python3.6/http/client.py", line 297, in begin
version, status, reason = self._read_status()
File "/var/lang/lib/python3.6/http/client.py", line 266, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/task/requests/adapters.py", line 449, in send
timeout=timeout
File "/var/task/urllib3/connectionpool.py", line 641, in urlopen
_stacktrace=sys.exc_info()[2])
File "/var/task/urllib3/util/retry.py", line 368, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/var/task/urllib3/packages/six.py", line 685, in reraise
raise value.with_traceback(tb)
File "/var/task/urllib3/connectionpool.py", line 603, in urlopen
chunked=chunked)
File "/var/task/urllib3/connectionpool.py", line 387, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/var/task/urllib3/connectionpool.py", line 383, in _make_request
httplib_response = conn.getresponse()
File "/var/lang/lib/python3.6/http/client.py", line 1331, in getresponse
response.begin()
File "/var/lang/lib/python3.6/http/client.py", line 297, in begin
version, status, reason = self._read_status()
File "/var/lang/lib/python3.6/http/client.py", line 266, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/task/elasticsearch/connection/http_requests.py", line 124, in perform_request
response = self.session.send(prepared_request, **send_kwargs)
File "/var/task/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/var/task/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```
- I added the '--debug', '--verbose' arguments but I have no any info that might help more.
- I tried also to handle the `ProtocolError` exception but still fails.
- No changes at the code.
- No changes on ElasticSearch cluster.

**Comment by tomfotherby** [comment]
_Update_: We found that once we increased the Lambda Memory from `128M` to `256M`, invokation errors stopped.

It seems the Python 3 version of ElastAlert is more memory hungry and slower. This shows the lambda _duration_ increase after our upgrade:

![Selection_387](https://user-images.githubusercontent.com/140179/64168329-317e4400-ce43-11e9-9a15-7874d84e79a2.jpg)

**Comment by aidan-** [comment]
@tomfotherby I am experiencing similar issues, having also upgraded from 2.7 to 3.6.  I am running Elastalert in a container, and using AWS Elasticsearch as the target.

Memory and CPU don't seem to be bottle necking in my environments so I'm going to try increasing the `es_conn_timeout` to 30seconds (max for AWS ES).  

Have you experienced this since increasing the memory in your Lambda?

**Comment by tomfotherby** [comment]
@aidan- We have not managed to get a 100% stable version of ElastAlert running via a Lambda even after increasing the memory. It works most of the time, but gets flaky several times per day. Our `es_conn_timeout` is 20 - I can't say whether or not that affects us but I do notice when our ES cluster is a bit stretched the ElastAlert lambda fails more often.

Our conclusion was that ElastAlert is not designed to run stateless. It has a in-built cron-like timing mechanism and uses a `buffer_time` window to cache results which doesn't work very well in a stateless environment like Lambda where a isolated new ElastAlert starts each minute. We are planning to migrate from running ElastAlert in a Lambda to running it in a Pod of our Kubernetes cluster.

**Comment by aidan-** [comment]
@tomfotherby Thanks for the additional information.  It sounds like we are hitting the same issue (besides the running in Lambda and state issues).  From one of our environments, we are getting an extreme increase in the occurrences of this error during times of increased ingestion and search.  Looking into the cluster metrics, it seems the data nodes are pegging CPU during this period.

Hopefully increasing cluster resources fixes this, I'll report back here in case it helps anyone else.
