### ISSUE TITLE
version 0.2.1 broken for python 3.7 (jira)

### ISSUE THREAD

**Issue by aeftef** [Yelp/elastalert#2437]
Hello,

Summary: python3.7+elastalert+python jira1.x(elastalert dependency) is incompatible, jira 2.x brings compatibility with python 3.7 so this dependency might be needed to update its version.

And in detail:
New elastalert versions using python3 won't run with python 3.7 (but works with python 3.6).

Is seems caused by dependent python jira library (currently jira>=1.0.10,<1.0.15) that is incompatible with python 3.7 (see https://github.com/pycontribs/jira/issues/618).

This issue has been fixed since jira package version 2.0.0, so I guess jira needs to be updated (I have compiled elasticsearch with python 3.7 and jira 2.0.0 it sems to work, but as I don't use jira i cant test elastalert-jira integration...)

Best regards

**Comment by ex0ns** [comment]
I can confirm that there is an issue with Jira and the `async` keyword for python3.7. Forcing the upgrade to Jira 2.0 displays a warning about incompatible version, but elastalert seems to work fine with version 2.0 of Jira.

**Comment by caleb15** [comment]
@ex0ns when you say "but elastalert seems to work fine with version 2.0 of Jira." what testing did you do specifically?

**Comment by caleb15** [comment]
Also I ran into this issue as well when running `elastalert -h` - upgrading jira to v2 fixed it

**Comment by goferito** [comment]
I'm still getting this error with jira upgraded to v2

**Comment by goferito** [comment]
Made a workaround by editing my /home/pi/.local/lib/python3.7/site-packages/elastalert/alerts.py

Changing lines:
```
  26 from jira.client import JIRA
  27 from jira.exceptions import JIRAError
```
to:
```
  26 #from jira.client import JIRA
  27 #from jira.exceptions import JIRAError
  28 JIRAError = RequestException
```

That way Jira gets disabled, which is good enough to me.

**Comment by idrissneumann** [comment]
I have the same problem. Here is a simple Dockerfile:

```
FROM balenalib/raspberrypi3-debian:latest

RUN apt-get update -y && \
    apt-get install curl telnet net-tools wget python3 python3-pip -y && \
    pip3 install elastalert

CMD ["elastalert", "--debug", "--verbose", "--config /config.yaml"]
```

And here is an extract of my docker-compose file:

```
  elastalert:
    image: myproject/elastalert
    container_name: myproject_elastalert
    build:
      context: docker/elastalert
      dockerfile: Dockerfile
    volumes:
      - ./elastalert/elastalert/config.yaml:/config.yaml:z
      - ./elastalert/rules:/rules:z
    restart: always
```

The Python version installed by the apt command on the docker build:

```
The following additional packages will be installed:
  libcurl4 libexpat1 libmpdec2 libpcre2-8-0 libpython3-stdlib
  libpython3.7-minimal libpython3.7-stdlib mime-support python-pip-whl
  python3-distutils python3-lib2to3 python3-minimal python3.7
  python3.7-minimal
```

When I start a container, here is the error I got:

```
myproject_elastalert       | Traceback (most recent call last):
myproject_elastalert       |   File "/usr/local/bin/elastalert", line 6, in <module>
myproject_elastalert       |     from elastalert.elastalert import main
myproject_elastalert       |   File "/usr/local/lib/python3.7/dist-packages/elastalert/elastalert.py", line 29, in <module>
myproject_elastalert       |     from .alerts import DebugAlerter
myproject_elastalert       |   File "/usr/local/lib/python3.7/dist-packages/elastalert/alerts.py", line 26, in <module>
myproject_elastalert       |     from jira.client import JIRA
myproject_elastalert       |   File "/usr/local/lib/python3.7/dist-packages/jira/__init__.py", line 10, in <module>
myproject_elastalert       |     from jira.client import Comment  # noqa: E402
myproject_elastalert       |   File "/usr/local/lib/python3.7/dist-packages/jira/client.py", line 225
myproject_elastalert       |     validate=False, get_server_info=True, async=False, logging=True, max_retries=3, proxies=None,
myproject_elastalert       |                                               ^
myproject_elastalert       | SyntaxError: invalid syntax
myproject_elastalert exited with code 1
```

It seems connected to [this issue](https://github.com/pycontribs/jira/issues/618) that seems to have been fixed on July 2018. Maybe it's time to upgrade the python jira module version ?

For now I'll try the @goferito workaround on my Dockerfile because I don't need to work with Jira.

Thanks in advance.
