### ISSUE TITLE
ImportError: No module named error

### ISSUE THREAD

**Issue by a-bo** [Yelp/elastalert#2439]
[root@localhost elasticAlert]# python -m elastalert.elastalert --config ./config.yaml
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/elastalert-0.2.1-py2.7.egg/elastalert/elastalert.py", line 29, in <module>
    from . import kibana
  File "/usr/lib/python2.7/site-packages/elastalert-0.2.1-py2.7.egg/elastalert/kibana.py", line 4, in <module>
    import urllib.error
ImportError: No module named error

**Comment by ThinkMo** [comment]
use python3.6+

**Comment by benjamin-huynh408** [comment]
Hello, I am having a similar issue, but I ran python3.6

> :/etc/elastalert/elastalert$ python3.6 -m elastalert.elastalert --config ./config.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/etc/elastalert/elastalert/elastalert.py", line 29, in <module>
    from . import kibana
ImportError: attempted relative import with no known parent package

**Comment by richard-pal** [comment]
Hi,

The same problem experienced as a-bo
Then with python3.6...:

$ python3.6 -m elastalert.elastalert --config ./config.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/elastalert/elastalert.py", line 2040, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.6/dist-packages/elastalert/elastalert.py", line 2034, in main
    client = ElastAlerter(args)
  File "/usr/local/lib/python3.6/dist-packages/elastalert/elastalert.py", line 136, in __init__
    self.conf = load_conf(self.args)
  File "/usr/local/lib/python3.6/dist-packages/elastalert/config.py", line 90, in load_conf
    rules_loader = rules_loader_class(conf)
  File "/usr/local/lib/python3.6/dist-packages/elastalert/loaders.py", line 94, in __init__
    yaml.load(open(os.path.join(os.path.dirname(__file__), 'schema.yaml')), Loader=yaml.FullLoader))
AttributeError: module 'yaml' has no attribute 'FullLoader'

**Comment by ThinkMo** [comment]
The FullLoader class is only available in PyYAML 5.1 and later. Version 5.1 was released on March 13, 2019 and has probably not filtered down to many distributions yet.
See https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader

**Comment by ThinkMo** [comment]
> Hello, I am having a similar issue, but I ran python3.6
> 
> > :/etc/elastalert/elastalert$ python3.6 -m elastalert.elastalert --config ./config.yaml
> > Traceback (most recent call last):
> > File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
> > mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> > File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
> > **import**(pkg_name)
> > File "/etc/elastalert/elastalert/elastalert.py", line 29, in 
> > from . import kibana
> > ImportError: attempted relative import with no known parent package

maybe elasticsearch version problem

**Comment by richard-pal** [comment]
Thanks for the hints.

Meanwhile I came up with a configuration which seems to be working and helps to install elastalert on ubuntu with ansible.
It may not be the most optimal stuff, but here it is... I added the exact package versions for future reference.

Ubuntu:18.04, Elasticsearch:7.3.2

- name: Install packages for pip
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
      - python3-venv=3.6.7-1~18.04
      - python-setuptools=39.0.1-2
      - python3-setuptools=39.0.1-2
      - python3-pip=9.0.1-2.3~ubuntu1.18.04.1
      - python-dev=2.7.15~rc1-1
      - libffi-dev=3.2.1-8
      - libssl-dev=1.1.1-1ubuntu2.1~18.04.4
  tags: elastalert

- name: Install elastalert
  pip:
    name:
      - pyOpenSSL==17.5.0
      - elasticsearch==7.0.4
      - PyYAML==5.1
      - elastalert==0.2.1
    executable: pip3
  tags: elastalert
