### ISSUE TITLE
mapper parsing exception when triggering alert from journalbeat index

### ISSUE THREAD

**Issue by jmcclelland** [Yelp/elastalert#2444]
I'm working on a custom alert and when it triggers, I get the following backtrace. The trigger code does execute properly, so I suspect this backtrace happens when elastalert tries to write back the info to the elastalert_status index.

That index seems to expect the value of process.capabilities to be a long, but journalbeat passes a string.

Am I doing something wrong? I'm not sure if this is something I can configure?

Thanks for any insight you can provide.

I'm running elastalert 0.2.1 and elasticsearch 7.3.

I'm generating the elastalert indexes using `elastalert-create-index`

```
WARNING:elasticsearch:POST https://log-001.mayfirst.test:9200/elastalert_status/_doc [status:400 request:0.014s]
ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.process.capabilites] of type [long] in document with id 'MazvDm0BENOSXOXVf0mD'. Preview of field's value: 'a00425fb'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/elastalert-0.2.1-py3.7.egg/elastalert/elastalert.py", line 1599, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch-7.0.3-py3.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch-7.0.3-py3.7.egg/elasticsearch/client/__init__.py", line 364, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch-7.0.3-py3.7.egg/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch-7.0.3-py3.7.egg/elasticsearch/connection/http_requests.py", line 156, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch-7.0.3-py3.7.egg/elasticsearch/connection/base.py", line 181, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.process.capabilites] of type [long] in document with id 'MazvDm0BENOSXOXVf0mD'. Preview of field's value: 'a00425fb'")
```

Elastalert status mapping:
```

{
  "mapping": {
    "dynamic_templates": [
      {
        "strings_as_keyword": {
          "match_mapping_type": "string",
          "mapping": {
            "ignore_above": 1024,
            "type": "keyword"
          }
        }
      }
    ],
    "date_detection": false,
    "numeric_detection": true,
    "properties": {
      "@timestamp": {
        "type": "date",
        "format": "date_optional_time"
      },
      "aggregate_id": {
        "type": "keyword"
      },
      "alert_info": {
        "properties": {
          "command": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "type": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "alert_sent": {
        "type": "boolean"
      },
      "alert_time": {
        "type": "date",
        "format": "date_optional_time"
      },
      "match_body": {
        "properties": {
          "@timestamp": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "_id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "_index": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "_type": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "agent": {
            "properties": {
              "ephemeral_id": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "hostname": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "id": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "type": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "version": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "ecs": {
            "properties": {
              "version": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "event": {
            "properties": {
              "created": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "dataset": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "duration": {
                "type": "long"
              },
              "module": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "host": {
            "properties": {
              "architecture": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "boot_id": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "containerized": {
                "type": "boolean"
              },
              "hostname": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "id": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "os": {
                "properties": {
                  "codename": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "family": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "kernel": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "name": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "platform": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "version": {
                    "type": "keyword",
                    "ignore_above": 1024
                  }
                }
              }
            }
          },
          "journald": {
            "properties": {
              "custom": {
                "properties": {
                  "selinux_context": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "stream_id": {
                    "type": "keyword",
                    "ignore_above": 1024
                  }
                }
              }
            }
          },
          "message": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "metricset": {
            "properties": {
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "num_hits": {
            "type": "long"
          },
          "num_matches": {
            "type": "long"
          },
          "process": {
            "properties": {
              "capabilites": {
                "type": "long"
              },
              "cmd": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "pid": {
                "type": "long"
              },
              "uid": {
                "type": "long"
              }
            }
          },
          "service": {
            "properties": {
              "type": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "syslog": {
            "properties": {
              "facility": {
                "type": "long"
              },
              "identifier": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "priority": {
                "type": "long"
              }
            }
          },
          "system": {
            "properties": {
              "filesystem": {
                "properties": {
                  "available": {
                    "type": "long"
                  },
                  "device_name": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "files": {
                    "type": "long"
                  },
                  "free": {
                    "type": "long"
                  },
                  "free_files": {
                    "type": "long"
                  },
                  "mount_point": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "total": {
                    "type": "long"
                  },
                  "type": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "used": {
                    "properties": {
                      "bytes": {
                        "type": "long"
                      },
                      "pct": {
                        "type": "float"
                      }
                    }
                  }
                }
              }
            }
          },
          "systemd": {
            "properties": {
              "cgroup": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "invocation_id": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "slice": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "transport": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "unit": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          }
        }
      },
      "match_time": {
        "type": "date",
        "format": "date_optional_time"
      },
      "rule_name": {
        "type": "keyword"
      }
    }
  }
}
```

**Comment by jmcclelland** [comment]
I'm not sure why this happened, but after re-installing elasticsearch from scrach and re-creating the indices, I know have in the mapper settings:

```
"process": {
            "properties": {
              "capabilites": {
                "type": "keyword",
                "ignore_above": 1024
              },
```

And no errors...
