### ISSUE TITLE
test_rule.py not following import 

### ISSUE THREAD

**Issue by JeffAshton** [Yelp/elastalert#2450]
`test_rule.py` calls to the file loader's `get_yaml` function

https://github.com/Yelp/elastalert/blob/e82ab25a337c3f85f6426ee5fd08aa166b4c1f69/elastalert/test_rule.py#L413

Which for `FileRulesLoader`, calls directly to `yaml_loader` 

https://github.com/Yelp/elastalert/blob/e82ab25a337c3f85f6426ee5fd08aa166b4c1f69/elastalert/loaders.py#L515 

to load the file, instead of calling `load_yaml` which handles the import logic.

https://github.com/Yelp/elastalert/blob/e82ab25a337c3f85f6426ee5fd08aa166b4c1f69/elastalert/loaders.py#L204

As a result, if the index is defined in a common import file, you get a schema validation error since the import is not processed:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elastalert/loaders.py", line 229, in load_options
    self.rule_schema.validate(rule)
  File "/usr/local/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'index' is a required property
```

**Comment by JeffAshton** [comment]
I feel as though `test_rule.py` should be calling `load_yaml` instead, which in tern calls `get_yaml`.  Thoughts from the maintainers?

**Comment by JeffAshton** [comment]
Fixed
