### ISSUE TITLE
Elastalert error when testing created rule

### ISSUE THREAD

**Issue by Domas709** [Yelp/elastalert#2461]
Hi. I am having a little trouble when running the test rule. I get this after running this command:

elastalert-test-rule --config config.yaml example_rules/example_frequency.yaml

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
WARNING:elasticsearch:GET http://localhost:9200/logs/_search?ignore_unavailable=true&size=1 [status:400 request:0.027s]
Error running your filter:
RequestError(400, 'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[tIdgurqZRxK4A8G3_1k2Lg][logs][0]: SearchParseException[[logs][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:25:12.894230Z","lte":"2019-09-17T13:25:12.894230Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][1]: SearchParseException[[logs][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:25:12.894230Z","lte":"2019-09-17T13:25:12.894230Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][2]: SearchParseException[[logs][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:25:12.894230Z","lte":"2019-09-17T13:25:12.894230Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][3]: SearchParseException[[logs][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:25:12.894230Z","lte":"2019-09-17T13:25:12.894230Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][4]: SearchParseException[[logs][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
1 rules loaded
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
WARNING:elasticsearch:GET http://localhost:9200/logs/_search?_source_include=%2A%2Ctimestamp&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.023s]
ERROR:root:Error running query: RequestError(400, 'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[tIdgurqZRxK4A8G3_1k2Lg][logs][0]: SearchParseException[[logs][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][1]: SearchParseException[[logs][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k... (3635 characters removed)

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_error - {'message': 'Error running query: RequestError(400, \'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[tIdgurqZRxK4A8G3_1k2Lg][logs][0]: SearchParseException[[logs][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][1]: SearchParseException[[logs][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k... (3635 characters removed)', 'traceback': ['Traceback (most recent call last):', '  File "C:\\Users\\Domas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\elastalert\\elastalert.py", line 383, in get_hits', '    **extra_args', '  File "C:\\Users\\Domas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\elasticsearch\\client\\utils.py", line 84, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "C:\\Users\\Domas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\elasticsearch\\client\\__init__.py", line 819, in search', '    "GET", _make_path(index, "_search"), params=params, body=body', '  File "C:\\Users\\Domas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\elasticsearch\\transport.py", line 350, in perform_request', '    timeout=timeout,', '  File "C:\\Users\\Domas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\elasticsearch\\connection\\http_requests.py", line 156, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "C:\\Users\\Domas\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\elasticsearch\\connection\\base.py", line 181, in _raise_error', '    status_code, error_message, additional_info', 'elasticsearch.exceptions.RequestError: RequestError(400, \'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[tIdgurqZRxK4A8G3_1k2Lg][logs][0]: SearchParseException[[logs][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][1]: SearchParseException[[logs][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][2]: SearchParseException[[logs][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][3]: SearchParseException[[logs][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][4]: SearchParseException[[logs][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }]\', \'SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[tIdgurqZRxK4A8G3_1k2Lg][logs][0]: SearchParseException[[logs][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][1]: SearchParseException[[logs][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][2]: SearchParseException[[logs][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][3]: SearchParseException[[logs][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }{[tIdgurqZRxK4A8G3_1k2Lg][logs][4]: SearchParseException[[logs][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"filter":{"bool":{"must":[{"range":{"timestamp":{"gt":"2019-09-17T13:24:12.333202Z","lte":"2019-09-17T13:25:12.933202Z"}}},{"term":null,"message":"error"}]}}}},"sort":[{"timestamp":{"order":"asc"}}]}]]]; nested: QueryParsingException[[logs] [_na] filter malformed, no field after start_object]; }]\')'], 'data': {'rule': 'ErrorTestRule_1', 'query': {'query': {'filtered': {'filter': {'bool': {'must': [{'range': {'timestamp': {'gt': '2019-09-17T13:24:12.333202Z', 'lte': '2019-09-17T13:25:12.933202Z'}}}, {'term': None, 'message': 'error'}]}}}}, 'sort': [{'timestamp': {'order': 'asc'}}]}}}

`My config file:
 rules_folder: example_rules

 run_every:
  minutes: 1

 buffer_time:
  minutes: 15

 es_host: localhost

 es_port: 9200

 writeback_index: elastalert_status
 writeback_alias: elastalert_alerts
 timestamp_field: timestamp

 alert_time_limit:
   days: 2
`

My Rule:
`# Alert when the rate of events exceeds a threshold

 es_host: localhost

 es_port: 9200

 name: ErrorTestRule_1

 type: frequency

 index: logs

 num_events: 2

 timeframe:
  minutes: 1

 filter:
  - term:
    message: "error"
   
 timestamp_format_expr: 'ts[:23] + ts[26:]'
    
 alert:
 - "email"

 email:
 - "domass@unifysquare.com"
`

I assume it has something to do with with Date types, since I can see that in my Logs indice the time field is called "timestamp" and in the elastalert_status indice its called "@timestamp". 

Thx for any kind of help :)

**Comment by Domas709** [comment]
By the way, I am using ElastAlert 0.2.0b1 with Elasticsearch v1.7.5
Sorry for the horrible first post :/

**Comment by Qmando** [comment]
What version on elasticsearch python do you have?
```
pip freeze | grep elasticsearch
```
