### ISSUE TITLE
Elastalert request timeout

### ISSUE THREAD

**Issue by Unsenta** [Yelp/elastalert#2469]
Hi,
I have only 2 rules to catch some test patterns in index records. Both rules are very similar have type: any and simple filters to catch and alert.
All is running good for 3-5 days till ElastAlert gets timeout on request. Service is running and active, but elastalert do not make any request and do not alerting. 
```
Sep 15 11:54:04 someserver python[25146]: WARNING:elasticsearch:GET https://192.168.0.2:9200/elastalert_status/_search?size=1000 [status:N/A request:20.325s]
Sep 15 11:54:04 someserver python[25146]: Traceback (most recent call last):
Sep 15 11:54:04 someserver python[25146]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 123, in perform_request
Sep 15 11:54:04 someserver python[25146]:     response = self.session.send(prepared_request, **send_kwargs)
Sep 15 11:54:04 someserver python[25146]:   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
Sep 15 11:54:04 someserver python[25146]:     r = adapter.send(request, **kwargs)
Sep 15 11:54:04 someserver python[25146]:   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 529, in send
Sep 15 11:54:04 someserver python[25146]:     raise ReadTimeout(e, request=request)
Sep 15 11:54:04 someserver python[25146]: ReadTimeout: HTTPSConnectionPool(host='192.168.0.2', port=9200): Read timed out. (read timeout=20)
Sep 15 11:54:04 someserver python[25146]: ERROR:root:Error finding recent pending alerts: ConnectionTimeout caused by - ReadTimeout(HTTPSConnectionPool(host='192.168.0.2', port=9200): Read timed out. (read timeout=20)) {'sort': {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'alert_time': {'to': '2019-09-15T11:53:44.627660Z', 'from': '2019-09-15T11:33:44.627577Z'}}}, 'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}}}}
Sep 15 11:54:04 someserver python[25146]: Traceback (most recent call last):
Sep 15 11:54:04 someserver python[25146]:   File "/usr/local/share/elastalert/elastalert/elastalert.py", line 1528, in find_recent_pending_alerts
Sep 15 11:54:04 someserver python[25146]:     res = self.writeback_es.search(index=self.writeback_index, body=query, size=1000)
Sep 15 11:54:04 someserver python[25146]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
Sep 15 11:54:04 someserver python[25146]:     return func(*args, params=params, **kwargs)
Sep 15 11:54:04 someserver python[25146]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 819, in search
Sep 15 11:54:04 someserver python[25146]:     "GET", _make_path(index, "_search"), params=params, body=body
Sep 15 11:54:04 someserver python[25146]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 353, in perform_request
Sep 15 11:54:04 someserver python[25146]:     timeout=timeout,
Sep 15 11:54:04 someserver python[25146]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 138, in perform_request
Sep 15 11:54:04 someserver python[25146]:     raise ConnectionTimeout("TIMEOUT", str(e), e)
Sep 15 11:54:04 someserver python[25146]: ConnectionTimeout: ConnectionTimeout caused by - ReadTimeout(HTTPSConnectionPool(host='192.168.0.2', port=9200): Read timed out. (read timeout=20))
```

It seems that it hangs because of the timeout of 20 seconds, but for both rules i have es_conn_timeout: 30 which should override these 20 seconds but it seems its not.
Only service restart helps.

**Comment by Unsenta** [comment]
es_conn_timeout parameter added to main config.yaml and it's works now.
