### ISSUE TITLE
Elastalert does not find rule after updates its "name:" value

### ISSUE THREAD

**Issue by gabibritto** [Yelp/elastalert#2472]
Hello,

I'm getting error when update rule's name during Elastalert execution.  It seems like there's some issue on rules_loader operation. After the rule update I get error and the rule does not run anymore until that I manually reboot elastalert.  I've tested with different rule types but I've got the same problem. Could you help me please on identifying what could be causing this?

```
 python -m elastalert.elastalert --verbose
elastalert/loaders.py:93: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full
 details.
  yaml.load(open(os.path.join(os.path.dirname(__file__), 'schema.yaml'))))
1 rules loaded
INFO:elastalert:Starting up
INFO:elastalert:Sleeping for 59.999984 seconds
INFO:elastalert:Queried rule Spike Email Test from 2019-09-19 14:02 -03 to 2019-09-19 14:08 -03: 0 / 0 hits
INFO:elastalert:Ran Spike Email Test from 2019-09-19 14:02 -03 to 2019-09-19 14:08 -03: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Background alerts thread 0 pending alerts sent at 2019-09-19 14:09 -03
INFO:elastalert:Reloading configuration for rule rules_test/email/spike_test_email.yaml
ERROR:apscheduler.executors.default:Job "ElastAlerter.handle_config_change (trigger: interval[0:01:00], next run at: 2019-09-19 14:10:52 -03)" raised an exception
Traceback (most recent call last):
  File “*************/.virtualenvs/alerts_test/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "*************/elastalert.py", line 1211, in handle_config_change
    self.load_rule_changes()
  File "*************/elastalert.py", line 1094, in load_rule_changes
    new_rule = self.init_rule(new_rule, False)
  File "*************/elastalert.py", line 957, in init_rule
    self.scheduler.remove_job(job_id=new_rule['name'])
  File “*************/.virtualenvs/alerts_test/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 621, in remove_job
    raise JobLookupError(job_id)
JobLookupError: u'No job by the id of Spike Email Test 2 was found'
INFO:elastalert:Sleeping for 59.999965 seconds
```

**Comment by jonscyr** [comment]
The similar error occurs when the rules `is_enabled` is False when elasrtalert starts and it gets updated to True in run time. 
`INFO:elastalert:Reloading configuration for rule Test Flatline T1
ERROR:apscheduler.executors.default:Job "ElastAlerter.handle_config_change (trigger: interval[0:00:05], next run at: 2020-05-21 08:34:20 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 1235, in handle_config_change
    self.load_rule_changes()
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 1112, in load_rule_changes
    new_rule = self.init_rule(new_rule, False)
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 970, in init_rule
    self.scheduler.remove_job(job_id=new_rule['name'])
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 621, in remove_job
    raise JobLookupError(job_id)
apscheduler.jobstores.base.JobLookupError: 'No job by the id of Test Flatline T1 was found'`

**Comment by jonscyr** [comment]
https://github.com/Yelp/elastalert/pull/2826

init_rule tries to stop the job irrespective of whether its running or not.
