### ISSUE TITLE
elastalert-test-rule error jira.client import

### ISSUE THREAD

**Issue by Mfisher925** [Yelp/elastalert#2475]
When trying to perform a rule test I get this error.  

`#  elastalert-test-rule --config config.yaml example_rules/example_frequency.yaml
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/elastalert-0.2.1-py3.7.egg/elastalert/test_rule.py", line 15, in <module>
    from elastalert.config import load_conf
  File "/usr/local/lib/python3.7/dist-packages/elastalert-0.2.1-py3.7.egg/elastalert/config.py", line 9, in <module>
    from . import loaders
  File "/usr/local/lib/python3.7/dist-packages/elastalert-0.2.1-py3.7.egg/elastalert/loaders.py", line 14, in <module>
    from . import alerts
  File "/usr/local/lib/python3.7/dist-packages/elastalert-0.2.1-py3.7.egg/elastalert/alerts.py", line 26, in <module>
    from jira.client import JIRA
  File "/usr/local/lib/python3.7/dist-packages/jira-1.0.14-py3.7.egg/jira/__init__.py", line 10, in <module>
    from jira.client import Comment  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/jira-1.0.14-py3.7.egg/jira/client.py", line 225
    validate=False, get_server_info=True, async=False, logging=True, max_retries=3, proxies=None,
                                              ^
SyntaxError: invalid syntax
`

My alert rule looks like this:

`name: VPN Connection Established

type: frequency

index: cisco-asa*

num_events: 3

timeframe:
  hours: 24

filter:
- term:
    message:"First"

alert:
- "email"

email:
- "email@email.com"
`

**Comment by jusmitch** [comment]
Same issue here. Base Amazon Linux 2 VM. Installed with "pip3 install elastalert".

`# elastalert --help
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/elastalert/elastalert.py", line 29, in <module>
    from .alerts import DebugAlerter
  File "/usr/local/lib/python3.7/site-packages/elastalert/alerts.py", line 26, in <module>
    from jira.client import JIRA
  File "/usr/local/lib/python3.7/site-packages/jira/__init__.py", line 10, in <module>
    from jira.client import Comment  # noqa: E402
  File "/usr/local/lib/python3.7/site-packages/jira/client.py", line 225
    validate=False, get_server_info=True, async=False, logging=True, max_retries=3, proxies=None,
                                              ^
`

**Comment by Brian-Williams** [comment]
`async` is a keyword in py3.7+.

Read more about the parameter keyword collision [here](https://github.com/pycontribs/jira/issues/603)

**Comment by dyipon** [comment]
pip uninstall jira and pip install jira>2.0.0

**Comment by Mfisher925** [comment]
I've installed virtualenv and created a virtual environment using python 3.6.4 that has uses an older compatible jira package.

This solved the problem.  Thanks all.

**Comment by Jiboss** [comment]
> pip uninstall jira and pip install jira>2.0.0

Better with <2.0.0 :)
