### ISSUE TITLE
elastalert feels very unhappy (circuit_breaking_exception, Data too large)

### ISSUE THREAD

**Issue by Trolldemorted** [Yelp/elastalert#2485]
My elastalert test instance is continuously throwing exceptions:

```
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1442489726/1.3gb], which is larger than the limit of [1394606080/1.2gb], real usage: [1442489056/1.3gb], new bytes reserved: [670/670b]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1599, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/client/__init__.py", line 364, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/connection/http_requests.py", line 156, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/connection/base.py", line 181, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1442493394/1.3gb], which is larger than the limit of [1394606080/1.2gb], real usage: [1442489056/1.3gb], new bytes reserved: [4338/4.2kb]')
WARNING:elasticsearch:GET http://helk-elasticsearch:9200/logstash-*/_search?_source_includes=%2A%2C%40timestamp&ignore_unavailable=true&scroll=30s&size=10000 [status:429 request:0.005s]
ERROR:root:Error running query: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1442490142/1.3gb], which is larger than the limit of [1394606080/1.2gb], real usage: [1442489056/1.3gb], new bytes reserved: [1086/1kb]')
WARNING:elasticsearch:POST http://helk-elasticsearch:9200/elastalert_status_error/_doc [status:429 request:0.004s]
ERROR:root:Error writing alert info to Elasticsearch: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1442493804/1.3gb], which is larger than the limit of [1394606080/1.2gb], real usage: [1442489056/1.3gb], new bytes reserved: [4748/4.6kb]')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 383, in get_hits
    **extra_args
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/client/__init__.py", line 819, in search
    "GET", _make_path(index, "_search"), params=params, body=body
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/connection/http_requests.py", line 156, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/connection/base.py", line 181, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1442490142/1.3gb], which is larger than the limit of [1394606080/1.2gb], real usage: [1442489056/1.3gb], new bytes reserved: [1086/1kb]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1599, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/client/__init__.py", line 364, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/connection/http_requests.py", line 156, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch-7.0.4-py3.6.egg/elasticsearch/connection/base.py", line 181, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1442493804/1.3gb], which is larger than the limit of [1394606080/1.2gb], real usage: [1442489056/1.3gb], new bytes reserved: [4748/4.6kb]')
ERROR:root:Error running query: ['Failed to parse query [(event_id:1 AND process_parent_name:"services.exe" AND NOT (process_path:"\\windows\\system32" OR process_path:"\\program files\\windows defender\\mpcmdrun.exe" OR "\\program files (x86)\\google\\update\\googleupdate.exe" OR "c:\\windows\\servicing"))]']
```

Is my test system's memory insufficient or is this an elastalert bug? It is running in Docker on a hyper-v vm with dynamic memory enabled, in case that matters. ES version is 7.0.1.

**Comment by neu5ron** [comment]
just curious.. what java garbage collection are you using? if its G1GC, there is a known bug.. 
and actually looking at this - are you using HELK? if so, move this over to the HELK github - I can help you out, as I am one of the commiters

**Comment by Trolldemorted** [comment]
Yeah my setup is based on HELK, but is this issue HELK-related?

Helk's elasticsearch is just a `FROM docker.elastic.co/elasticsearch/elasticsearch:7.0.1`, nothing extraordinary or custom, do you know which GC they use?

I noticed I can make the problem disappear by throwing more memory at elasticsearch, but this still is an elasticsearch or elastalert bug, isn't it?

**Comment by Qmando** [comment]
Not sure if this is relevant, but you can change `max_query_size` to a lower amount (10k is default) to lower the size of each query.

**Comment by Trolldemorted** [comment]
Closing for https://github.com/Cyb3rWard0g/HELK/issues/349

**Comment by aniketpant1** [comment]
hey @Qmando i have set max_query_size to 5000 i am not seeing this above error

**Comment by nsano-rururu** [comment]
@aniketpant1 

I don't usually use Elast Alert at all. Of course, it is not in operation. 
Please note that we are not the developer of ElastAlert and cannot guarantee that the advice will be helpful to your issue.

Java heap memory exhausted due to over-opening of indexes

circuit_breaking_exception may occur
→ ElasticSearch heap size change
→ Elastic Search
Changes to indices.breaker.total.limit
→ Delete Index data of ElasticSearch, or close unnecessary Index data
[Elasticsearchのインデックス開きすぎによるヒープメモリ枯渇](http://n-agetsuma.hatenablog.com/entry/2017/12/06/000000)
[elastalert feels very unhappy (circuit_breaking_exception, Data too large) #2485](https://github.com/Yelp/elastalert/issues/2485)
[circuit_breaking_exception, Data too large #349](https://github.com/Cyb3rWard0g/HELK/issues/349)
[After Upgrade to 6.2.4 Circuitbreaker Exception Data too large #31197](https://github.com/elastic/elasticsearch/issues/31197)
[Elastalert deployment failed](https://stackoverflow.com/questions/59014095/elastalert-deployment-failed)
