### ISSUE TITLE
elastalert-test-rule always returns: print('Invalid filter provided:', str(ea), file=sys.stderr)

### ISSUE THREAD

**Issue by ghenry** [Yelp/elastalert#2500]
Hi all,

I'm running this 'as-is' and can can't see what is causing this error:

```
 elastalert-test-rule

Traceback (most recent call last):
  File "/usr/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/elastalert-0.2.1-py2.7.egg/elastalert/test_rule.py", line 61
    print('Invalid filter provided:', str(ea), file=sys.stderr)
                                                   ^
SyntaxError: invalid syntax
```

It's the same if I use the default rules.

```
elastalert-test-rule example_rules/example_change.yaml 
Traceback (most recent call last):
  File "/usr/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/elastalert-0.2.1-py2.7.egg/elastalert/test_rule.py", line 61
    print('Invalid filter provided:', str(ea), file=sys.stderr)
                                                   ^
SyntaxError: invalid syntax
```

Any ideas?

Thanks.

**Comment by ghenry** [comment]
Needs python3 as per https://github.com/Yelp/elastalert/issues/2390 I think the docs should state `pip3`
