### ISSUE TITLE
elastalert-create-index throws error

### ISSUE THREAD

**Issue by zozo6015** [Yelp/elastalert#2505]
I have upgraded the elasticsearch to 7.3.2 and I have also upgraded elastalert to the latest version available via pip. I have deleted the old indices and I wanted to recreate the elastalert indexes with elastalert-create-index.  When running the command I am getting the following error message:

```
elastalert-create-index 
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/create_index.py", line 195, in main
    data = yaml.load(config_file, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'
```

Is there anything I miss?

**Comment by Qmando** [comment]
Try upgrading the `pyyaml` package.

**Comment by zozo6015** [comment]
Great that fixed the problem.
