### ISSUE TITLE
How to fix it: ERROR:root:Traceback  ?

### ISSUE THREAD

**Issue by lijiakof** [Yelp/elastalert#2529]
```
1 rules loaded
INFO:elastalert:Starting up
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 59.999904 seconds
ERROR:root:Traceback (most recent call last):
  File "/root/elastalert/elastalert/elastalert.py", line 1270, in handle_rule_execution
    num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime'))
  File "/root/elastalert/elastalert/elastalert.py", line 905, in run_rule
    if not self.run_query(rule, rule['starttime'], endtime):
  File "/root/elastalert/elastalert/elastalert.py", line 634, in run_query
    data = self.get_hits(rule, start, end, index, scroll)
  File "/root/elastalert/elastalert/elastalert.py", line 385, in get_hits
    **extra_args
  File "/usr/local/python3/lib/python3.6/site-packages/elasticsearch-7.0.5-py3.6.egg/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: search() got an unexpected keyword argument '_source_include'

ERROR:root:Uncaught exception running rule lidongtest rule: search() got an unexpected keyword argument '_source_include'
```

**Comment by aidan-** [comment]
You're going to need to give more information than that.  What version of Elasticsearch are you using?

I hit this error running Elasticsearch 5.x.  To resolve it, I downgraded the `elasticsearch` dependency to a lower version:
```
pip3 uninstall elasticsearch -y
pip3 install "elasticsearch>=5.5.3,<6.0.0"
```
