### ISSUE TITLE
Is the config option "end" available?

### ISSUE THREAD

**Issue by pcxg** [Yelp/elastalert#2532]
Hello！
I'm running the docker version of elastalert, when I set endtime in the config.json like this: 
 "start": "2015-05-18T00:00:00",
  "end": "2015-05-23T00:00:00"
then the ElastAlert exited with code 0 in a second without any warning.
I found these lines in the start(self) function in elastalert.py:
```
        while self.running:
            next_run = datetime.datetime.utcnow() + self.run_every

            # Quit after end_time has been reached
            if self.args.end:
                endtime = ts_to_dt(self.args.end)

                if next_run.replace(tzinfo=dateutil.tz.tzutc()) > endtime:
                    exit(0)
```
It seems the next_run is always now+run_every,so when I set endtime(2015-05-23),the elastAlert will stop running and exit,which means I cant set end in the config.
Is there other ways to set endtime in the past?Thanks!

**Comment by Qmando** [comment]
`elastalert --verbose --start 2015-05-18 --end 2015-0523`

**Comment by pcxg** [comment]
Thanks for your reply!
However I tried the config --end 2015-0523,and 0523 seems can't be parse to the right month format.
Here's the log:

> 08:35:54.142Z ERROR elastalert-server:
>     ProcessController:  Traceback (most recent call last):
>       File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     
> 08:35:54.164Z ERROR elastalert-server:
>     ProcessController:      "__main__", fname, loader, pkg_name)
>       File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>         exec code in run_globals
>       File "/opt/elastalert/elastalert/elastalert.py", line 2019, in <module>
>         sys.exit(main(sys.argv[1:]))
>       File "/opt/elastalert/elastalert/elastalert.py", line 2015, in main
>         client.start()
>       File "/opt/elastalert/elastalert/elastalert.py", line 1148, in start
>         endtime = ts_to_dt(self.args.end)
>       File "elastalert/util.py", line 127, in ts_to_dt
>         dt = dateutil.parser.parse(timestamp)
>       File "/usr/lib/python2.7/site-packages/python_dateutil-2.6.1-py2.7.egg/dateutil/parser.py", line 1182, in parse
>         return DEFAULTPARSER.parse(timestr, **kwargs)
>       File "/usr/lib/python2.7/site-packages/python_dateutil-2.6.1-py2.7.egg/dateutil/parser.py", line 578, in parse
>         if cday > monthrange(cyear, cmonth)[1]:
>       File "/usr/lib/python2.7/calendar.py", line 120, in monthrange
>     
> 08:35:54.185Z ERROR elastalert-server:
>     ProcessController:      raise IllegalMonthError(month)
>     calendar.IllegalMonthError: bad month number 523; must be 1-12

**Comment by pbavail** [comment]
I have made a comment on this in #2666
