### ISSUE TITLE
ElastAlert Installation Error

### ISSUE THREAD

**Issue by stoksoz1** [Yelp/elastalert#2552]
root@pardus:~/elastalert# elastalert-create-index
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert/create_index.py", line 264, in main
    create_index_mappings(es_client=es, ea_index=index, recreate=args.recreate, old_ea_index=old_index)
  File "/usr/local/lib/python2.7/dist-packages/elastalert/create_index.py", line 23, in create_index_mappings
    esversion = es_client.info()["version"]["number"]
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 259, in info
    return self.transport.perform_request("GET", "/", params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 144, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='elasticsearch.example.com', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59fc1c3f50>: Failed to establish a new connection: [Errno -2] Name or service not known',))) caused by: ConnectionError(HTTPConnectionPool(host='elasticsearch.example.com', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f59fc1c3f50>: Failed to establish a new connection: [Errno -2] Name or service not known',)))

**Comment by farrukhahmed4220** [comment]
You are using python2.7 ... python3.6 is required.
Check this requirement for Elastalert...
https://elastalert.readthedocs.io/en/latest/running_elastalert.html#requirements

**Comment by stoksoz1** [comment]
Is there any good instruction for installation ElastAlert to Debian 10 ?

**Comment by Theoooooo** [comment]
@stoksoz1 Just install the requirements on Debian so. There is no need to add another chapter for debian because the installation method is exactly the same. For CentOS 7 it's a bit different if you want the very last version of python but it's quite easy to found how to install it, on Debian or not.
