### ISSUE TITLE
ElastAlert: Error running filter and query, parsing exception.

### ISSUE THREAD

**Issue by farrukhahmed4220** [Yelp/elastalert#2555]
```
(elast_venv) [farrukh@server elastalert]$ elastalert-test-rule --config config.yaml example_rules/example_frequency.yaml
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
WARNING:elasticsearch:GET http://server.elk.com:9200/filebeat-*/_search?ignore_unavailable=true&size=1 [status:400 request:0.009s]
Error running your filter:
RequestError(400, 'parsing_exception', {'error': {'root_cause': [{'type': 'parsing_exception', 'reason': '[term] query malformed, no start_object after query name',                         'line': 1, 'col': 151}], 'type': 'parsing_exception', 'reason': '[term] query malformed, no start_object after query name', 'line': 1, 'col': 151}, 'status': 400})
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
1 rules loaded
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
WARNING:elasticsearch:GET http://server.elk.com:9200/filebeat-*/_search?_source_includes=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400                         request:0.008s]
ERROR:root:Error running query: RequestError(400, 'parsing_exception', '[term] query malformed, no start_object after query name')

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_error - {'message': "Error running query: RequestError(400, 'parsing_exception', '[term] query malformed, no start_object after query name')", 'traceback'                        : ['Traceback (most recent call last):', '  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 383, in get_hits', '    **extra_args', '  Fi                        le "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/usr/lo                        cal/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 805, in search', '    "GET", _make_path(index, "_search"), params=params, body=body', '  File                         "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 350, in perform_request', '    timeout=timeout,', '  File "/usr/local/lib/python3.6/site-p                        ackages/elasticsearch/connection/http_requests.py", line 160, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "/usr/local/lib/p                        ython3.6/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error', '    status_code, error_message, additional_info', "elasticsearch.exceptions.Re                        questError: RequestError(400, 'parsing_exception', '[term] query malformed, no start_object after query name')"], 'data': {'rule': 'A quick demo for email alerting',                         'query': {'query': {'bool': {'filter': {'bool': {'must': [{'range': {'@timestamp': {'gt': '2019-11-07T11:39:33.247423Z', 'lte': '2019-11-07T11:54:33.247423Z'}}}, {'                        term': 'process.name= "JUSTME"'}]}}}}, 'sort': [{'@timestamp': {'order': 'asc'}}]}}}

```

**Comment by Theoooooo** [comment]
if you never post your config file, you will never get help ...

**Comment by farrukhahmed4220** [comment]
here is my example_rules/example_frequency.yaml:
```
(elast_venv) [farrukh@server elastalert]$ vi example_rules/example_frequency.yaml
 es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
 es_username: elastic
 es_password: FHxHNZ0XLsVFjD67t3Mv

# (Required)
# Rule name, must be unique
 name: A quick demo for email alerting

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
 type: frequency

# (Required)
# Index to search, wildcard supported
 index: filebeat-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
 num_events: 3

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
 timeframe:
   hours: 1

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
 filter:
   - term:
      #some_field: "some_value"
       process.name= "JUSTME"

# (Required)
# The alert is use when a match is found
 alert:
    - "email"

# (required, email specific)
# a list of email addresses to send alerts to
 email:
    - "teamaugmeticfyp2016@gmail.com"

```

**Comment by Theoooooo** [comment]
The only thing weird i see is that the "term" filter is not placed correctly in the file. The term filter should be in the same lever that the filter itself :

```
 filter:
   - term:
      #some_field: "some_value"
       process.name= "JUSTME"
```

Try this :
```
 filter:
 - term:
    #some_field: "some_value"
     process.name= "JUSTME"
```

**Comment by farrukhahmed4220** [comment]
my config.yaml :
```
(elast_venv) [farrukh@server elastalert]$ vi config.yaml
# If you want to setup your own logging configuration to log into
# files as well or to Logstash and/or modify log levels, use
# the configuration below and adjust to your needs.
# Note: if you run ElastAlert with --verbose/--debug, the log level of
# the "elastalert" logger is changed to INFO, if not already INFO/DEBUG.
#logging:
#  version: 1
#  incremental: false
#  disable_existing_loggers: false
#  formatters:
#    logline:
#      format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'
#
#    handlers:
#      console:
#        class: logging.StreamHandler
#        formatter: logline
#        level: DEBUG
#        stream: ext://sys.stderr
#
#      file:
#        class : logging.FileHandler
#        formatter: logline
#        level: DEBUG
#        filename: elastalert.log
#
#    loggers:
#      elastalert:
#        level: WARN
#        handlers: []
#        propagate: true
#
#      elasticsearch:
#        level: WARN
#        handlers: []
#        propagate: true
#
#      elasticsearch.trace:
#        level: WARN
#        handlers: []
#        propagate: true
#
#      '':  # root logger
#        level: WARN
#          handlers:
#            - console
#            - file
#        propagate: false

```

**Comment by farrukhahmed4220** [comment]
I have corrected the indentation... still same giving same issue...

**Comment by Theoooooo** [comment]
Try this :
```
 filter:
   - term:
      #some_field: "some_value"
       process.name: "JUSTME"
```

Unstead of :
```
 filter:
 - term:
    #some_field: "some_value"
     process.name= "JUSTME"
```

**Comment by farrukhahmed4220** [comment]
Excellent... It worked for me....
Thanks alot .....

**Comment by ivssh** [comment]
@farrukhahmed4220, Does it send you email alerts without specifying `smtp_host` and `smtp_port` parameters in the config.yaml?

**Comment by Truong-td** [comment]
> Try this :
> 
> ```
>  filter:
>    - term:
>       #some_field: "some_value"
>        process.name: "JUSTME"
> ```
> 
> Unstead of :
> 
> ```
>  filter:
>  - term:
>     #some_field: "some_value"
>      process.name= "JUSTME"
> ```
> 
> Lucene engine don't deal with '=' operator if i remember

@Theoooooo 
I have a error the same issue in here. althought  i followed same you, But it error.
Please help me!

**Comment by Truong-td** [comment]
> > Try this :
> > ```
> >  filter:
> >    - term:
> >       #some_field: "some_value"
> >        process.name: "JUSTME"
> > ```
> > 
> > 
> > Unstead of :
> > ```
> >  filter:
> >  - term:
> >     #some_field: "some_value"
> >      process.name= "JUSTME"
> > ```
> > 
> > 
> > Lucene engine don't deal with '=' operator if i remember
> 
> @Theoooooo
> I have a error the same issue in here. althought i followed same you, But it error.
> Please help me!

The file config.yaml
# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
es_host: localhost

# (Optional)
# Elasticsearch port
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
es_username: elastic
es_password: changeme

# (Required)
# Rule name, must be unique
name: Truongtd test alert email

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: api-log

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 5

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  hours: 1

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- term:
  latencies.request : 2

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "truongtd@nal.vn"
