### ISSUE TITLE
Issue in elastalert.py

### ISSUE THREAD

**Issue by Theoooooo** [Yelp/elastalert#2556]
I've opened an issue recently about an error i got while adding a new alerter #2546 

I've found an issue in the code of elastalert.py that doesn't allowed me to send alert with my new alerter. A variable was missing in the send_alert def :

Before
```
1444     def send_alert(self, matches, rule, alert_time=None, retried=False):
1445         """ Send out an alert.
1446
1447         :param matches: A list of matches.
1448         :param rule: A rule configuration.
1449         """
1450         if not matches:
1451             return
1452
1453         if alert_time is None:
1454             alert_time = ts_now()

```

After :
```
1444     def send_alert(self, matches, rule, alert_time=None, retried=False):
1445         self.thread_data.alerts_sent = 0
1446         """ Send out an alert.
1447
1448         :param matches: A list of matches.
1449         :param rule: A rule configuration.
1450         """
1451         if not matches:
1452             return
1453
1454         if alert_time is None:
1455             alert_time = ts_now()
```

Adding this variable fix my issue and i don't have errors anymore. Could you look into this and tell me if it's the correct solution ? I'm sure i'm not the only one who encounter this issue

**Comment by thethomp** [comment]
Can confirm, I've hit this error as well. Doesn't seem to affect sending the alert, at least so far, but I get the exception as follows when sending email alert:
```
INFO:elastalert:Sent email to ['thomp@email.com']
ERROR:root:Traceback (most recent call last):
  File "/home/thomp/elastalert/lib/python3.6/site-packages/elastalert/elastalert.py", line 1440, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/home/thomp/elastalert/lib/python3.6/site-packages/elastalert/elastalert.py", line 1534, in send_alert
    self.thread_data.alerts_sent += 1
AttributeError: '_thread._local' object has no attribute 'alerts_sent'

ERROR:root:Uncaught exception running rule New LoadErrors from the past day: '_thread._local' object has no attribute 'alerts_sent'
```

**Comment by Qmando** [comment]
Strange. It should be initialized before we get to any code that sends alerts, in both handle_pending_alerts and handle_rule_execution. The first code change will "Fix" the issue but the alerts_sent may will be wrong, if you care anyway. I'll try to look into this more.

**Comment by Folyd** [comment]
The same error happened when I test my rule with the command `elastalert-test-rule --config /opt/config/elastalert_config.yaml --alert /opt/rules/nginx_frequency.yaml`

```log
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 1440, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 1534, in send_alert
    self.thread_data.alerts_sent += 1
AttributeError: '_thread._local' object has no attribute 'alerts_sent'
```

Elastalert version : `0.2.1`

**Comment by gcnote** [comment]
add self.thread_data.alerts_sent = 0 in elastalert.py and it will works

**Comment by Maixy** [comment]
Seeing this issue as well running `elastalert-test-rule` with yaml config and alert definition + the `--alert` param.

Is there a specific line where adding `self.thread_data.alerts_sent = 0` would be safe to add in `elastalert.py`?

**Comment by daichi703n** [comment]
@Maixy 
This fix works for me. Please test your environment.

```
        self.replace_dots_in_field_names = self.conf.get('replace_dots_in_field_names', False)
        self.thread_data.num_hits = 0
        self.thread_data.num_dupes = 0
        self.thread_data.alerts_sent = 0  #add
        self.scheduler = BackgroundScheduler()
```

https://github.com/Yelp/elastalert/blob/master/elastalert/elastalert.py#L162-L163

**Comment by balusarakesh** [comment]
I'm also seeing a similar issue when querying the metrics for ElasticSearch in the `.monitoring-es-*` index.
We are using the helm-chart elastalert version `1.2.3`
Here's my alert rule:
```
   name: ElasticSearch cluster status changed
   type: frequency
   timestamp_field: timestamp
   index: .monitoring-es-*
   num_events: 1
   timeframe:
     minutes: 1
   filter:
   - query:
      query_string:
        query: "_exists_:cluster_stats.status"
   alert:
   - "slack"
   slack:
   slack_channel_override: "#channel"
```


```
ERROR:apscheduler.executors.default:Job "ElastAlerter.handle_rule_execution (trigger: interval[0:01:00], next run at: 2020-02-19 22:46:49 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 1268, in handle_rule_execution
    self.thread_data.num_hits, self.thread_data.num_dupes, num_matches,
AttributeError: '_thread._local' object has no attribute 'num_hits'
```

**Comment by daichi703n** [comment]
@balusarakesh 
From helm-chart, ElastAlert is installed by pip.
https://github.com/jertel/elastalert-docker
Released v2.0.1 has some bugs.
Can you mount and replace to the latest src that is downloaded by `git clone` (master branch)?

I can’t describe detailed step, because I don’t have testing k8s env... sorry.

**Comment by mrfroggg** [comment]
It would be nice to have a PR on this, I have the same issue on 0.2.4

**Comment by apiszcz** [comment]
This change does not appear to be in 0.2.4 or the latest master.
LINE 165: elastalert.py
self.thread_data.alerts_sent = 0  #add

**Comment by nsano-rururu** [comment]
The addition of "self.thread_data.alerts_sent = 0" has been merged into elastalert2
https://github.com/jertel/elastalert2
