### ISSUE TITLE
` elastalert-test-rule ` command seems not compatible with python 2.7

### ISSUE THREAD

**Issue by zhang-shengping** [Yelp/elastalert#2559]
The `elastalert-test-rule` seems not comptible with python 2.7

```
[root@elasticsearch ~]# elastalert-test-rule example_rules/example_frequency.yaml
Traceback (most recent call last):
  File "/usr/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/elastalert-0.2.1-py2.7.egg/elastalert/test_rule.py", line 61
    print('Invalid filter provided:', str(ea), file=sys.stderr)
```

**Comment by emixam3** [comment]
You need Python 3.6 for Elastalert.

**Comment by sysword** [comment]
> You need Python 3.6 for Elastalert.
> Check this: https://elastalert.readthedocs.io/en/latest/running_elastalert.html#requirements

does the kibana plugin need python 3.6 too? I use kibana-oss 7.20 image, and its python version is 2.7, when try to install the plugin, the kibana server will never be ready.

**Comment by SrinivasChoudhury** [comment]
> You need Python 3.6 for Elastalert.
> Check this: https://elastalert.readthedocs.io/en/latest/running_elastalert.html#requirements

I have both 2.7 and 3.7 in my machine. When I run "elastalert-test-rule", it points 2.7 and throws error as shown above . How would fix it?
@Qmando
