### ISSUE TITLE
Issue with numeric detection

### ISSUE THREAD

**Issue by ScottPeterJohnson** [Yelp/elastalert#2567]
The default elastalert index enables the Elasticsearch "numeric_detection" feature, described here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html#numeric-detection

And enabled here:
https://github.com/Yelp/elastalert/blob/master/elastalert/es_mappings/6/elastalert.json#L2

Unfortunately this can cause Elasticsearch to fail requests if it tries to alert on any field which has text fields that are subjected to "numeric detection" but are too large to fit in a float.
```
ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.event_id] of type [float] in document with id '1scvaW4BMyMmd5kjobjp'. Preview of field's value: '35095188898298459521615298175139735357954906557641326601'")
Traceback (most recent call last):
  File "/home/bitnami/.local/lib/python3.5/site-packages/elastalert/elastalert.py", line 1599, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/home/bitnami/.local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/bitnami/.local/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 364, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/home/bitnami/.local/lib/python3.5/site-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/home/bitnami/.local/lib/python3.5/site-packages/elasticsearch/connection/http_requests.py", line 160, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/home/bitnami/.local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.event_id] of type [float] in document with id '1scvaW4BMyMmd5kjobjp'. Preview of field's value: '35095188898298459521615298175139735357954906557641326601'")

```

Is it necessary to have numeric detection enabled, given that it can break Elastalert like this?

**Comment by chandru9279** [comment]
Bump
