### ISSUE TITLE
PagerTree not mapped loaders.py

### ISSUE THREAD

**Issue by AaronSeibert** [Yelp/elastalert#2571]
Setting up pagertree alerts today, I was getting an error:

`Nov 18 20:57:04 dashboards elastalert[8878]: elastalert.util.EAException: Error initiating alert ['pagertree']: Could not import module pagertree: not enough values to unpack (expected 2, got 1)
Nov 18 20:57:04 dashboards elastalert[8878]: During handling of the above exception, another exception occurred:
Nov 18 20:57:04 dashboards elastalert[8878]: Traceback (most recent call last):
Nov 18 20:57:04 dashboards elastalert[8878]:   File "/usr/local/bin/elastalert", line 11, in <module>
Nov 18 20:57:04 dashboards elastalert[8878]:     load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert')()
Nov 18 20:57:04 dashboards elastalert[8878]:   File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 2050, in main
Nov 18 20:57:04 dashboards elastalert[8878]:     client = ElastAlerter(args)
Nov 18 20:57:04 dashboards elastalert[8878]:   File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 140, in __init__
Nov 18 20:57:04 dashboards elastalert[8878]:     self.rules = self.rules_loader.load(self.conf, self.args)
Nov 18 20:57:04 dashboards elastalert[8878]:   File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/loaders.py", line 125, in load
Nov 18 20:57:04 dashboards elastalert[8878]:     raise EAException('Error loading file %s: %s' % (rule_file, e))
Nov 18 20:57:04 dashboards elastalert[8878]: elastalert.util.EAException: Error loading file /opt/elastalert/rules/heartbeat-monitor-down.yaml: Error initiating alert ['pagertree']: Could not import module pagertree: not enough values to unpack (expected 2, got 1)`

I had to modify the loaders.py file adding the pagertree loader:

`        'pagertree': alerts.PagerTreeAlerter,`

Once re-running setup.py and restarting elastalert all was then well.

**Comment by nsano-rururu** [comment]
elastalert2 solved this problem
https://github.com/jertel/elastalert2
