### ISSUE TITLE
elastalert-test-rule, cannot use --alert together with import statement

### ISSUE THREAD

**Issue by andres-tw** [Yelp/elastalert#2600]
Running elastalert 0.2.1
When using `elastalert-test-rule` with rule files that contain the `import` keyword and the `--alert` parameter. `elastalert-test-rule` fails with the following output:

```python
/opt/app/elastalert/venv/bin/elastalert-test-rule --config /etc/elastalert/config.yaml --start 2019-12-09T07:09:50 --end 2019-12-09T08:00:00 --alert /path/to/rule/errors.yml
Didn't get any results.
Traceback (most recent call last):
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/loaders.py", line 461, in load_alerts
    alert_field = [create_alert(a, b) for a, b in alert_field]
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/loaders.py", line 461, in <listcomp>
    alert_field = [create_alert(a, b) for a, b in alert_field]
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/loaders.py", line 451, in create_alert
    raise EAException('Missing required option(s): %s' % (', '.join(missing_options)))
elastalert.util.EAException: Missing required option(s): hive_connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app/elastalert/venv/bin/elastalert-test-rule", line 11, in <module>
    sys.exit(main())
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/test_rule.py", line 446, in main
    test_instance.run_rule_test()
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/test_rule.py", line 438, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/test_rule.py", line 233, in run_elastalert
    conf['rules_loader'].load_modules(rule, load_modules_args)
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/loaders.py", line 428, in load_modules
    rule['alert'] = self.load_alerts(rule, alert_field=rule['alert'])
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/loaders.py", line 464, in load_alerts
    raise EAException('Error initiating alert %s: %s' % (rule['alert'], e)).with_traceback(sys.exc_info()[2])
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/loaders.py", line 461, in load_alerts
    alert_field = [create_alert(a, b) for a, b in alert_field]
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/loaders.py", line 461, in <listcomp>
    alert_field = [create_alert(a, b) for a, b in alert_field]
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/loaders.py", line 451, in create_alert
    raise EAException('Missing required option(s): %s' % (', '.join(missing_options)))
elastalert.util.EAException: Error initiating alert ['hivealerter']: Missing required option(s): hive_connection
```

If I change `test_rule.py` according to cfa98a1 the `--alert` keyword starts to work i.e. it actually sends the alert, but stacktraces with:

```python
/opt/app/elastalert/venv/bin/elastalert-test-rule --config /etc/elastalert/config.yaml --start 2019-12-09T07:09:50 --end 2019-12-09T08:00:00 --alert /path/to/ruletest/errors.yml
Didn't get any results.
1 rules loaded
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:elastalert:Queried rule ${RULE_NAME} from 2019-12-09 07:09 UTC to 2019-12-09 08:00 UTC: 1 / 1 hits
ERROR:root:Traceback (most recent call last):
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/elastalert.py", line 1440, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/elastalert.py", line 1534, in send_alert
    self.thread_data.alerts_sent += 1
AttributeError: '_thread._local' object has no attribute 'alerts_sent'

ERROR:root:Uncaught exception running rule ${RULE_NAME}: '_thread._local' object has no attribute 'alerts_sent'

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_error - {'message': "Uncaught exception running rule ${RULE_NAME}: '_thread._local' object has no attribute 'alerts_sent'", 'traceback': ['Traceback (most recent call last):', '  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/elastalert.py", line 1440, in alert', '    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)', '  File "/opt/app/elastalert/venv/lib/python3.6/site-packages/elastalert/elastalert.py", line 1534, in send_alert', '    self.thread_data.alerts_sent += 1', "AttributeError: '_thread._local' object has no attribute 'alerts_sent'"], 'data': {'rule': '${RULE_NAME}'}}

elastalert_status - {'rule_name': '${RULE_NAME}', 'endtime': datetime.datetime(2019, 12, 9, 8, 0, tzinfo=<UTC>), 'starttime': datetime.datetime(2019, 12, 9, 7, 9, 50, tzinfo=<UTC>), 'matches': 1, 'hits': 1, '@timestamp': datetime.datetime(2019, 12, 9, 7, 11, 0, 693551, tzinfo=tzutc()), 'time_taken': 0.8679583072662354}
```

**Comment by primeroz** [comment]
I am having the same issue with the `import` , i run my CI with 

`elastalert-test-rule --config ./mock/config.yaml --schema-only rules/rule1.yaml` 

In every rule i do `import` another file with all the alert settings, since switchting to 0.2.1 i was getting problems with the CI because the schema validatio always errored out as 

`elastalert.util.EAException: Invalid Rule file: rules/rule1.yaml                                       
'alert' is a required property`

Chaing the line in https://github.com/Yelp/elastalert/commit/cfa98a12bb7739cfc21a16a418fe95375277f1fd fixed the issue

**Comment by daichi703n** [comment]
@andres-tw  I had fixed this issue with @primeroz 's solution. Do you have still problem? If not, please close this issue.

**Comment by andres-tw** [comment]
@daichi703n As I said, in my original post. The change in cfa98a1, fixes `elastalert-test-rule` running with the --alert parameter.
The problem I could not figure out is that cfa98a1 seems to introduce another stacktrace. Although this stacktrace does not block the alert from being sent, I thought it might still be worth brining attention to this.
Namely the: `ERROR:root:Uncaught exception running rule ${RULE_NAME}: '_thread._local' object has no attribute 'alerts_sent'`
I will check again, but afaik the problem resulting from the change made in cfa98a1 is not fixed.

**Comment by daichi703n** [comment]
Fix in these issues solve your stack trace, doesn’t it?
https://github.com/Yelp/elastalert/issues/2546
https://github.com/Yelp/elastalert/issues/2556

**Comment by andres-tw** [comment]
Ahh cool. I'll update and check it out. Does look like those will fix this. Thanks :)
