### ISSUE TITLE
Elastalert 0.2.1 with Python3.6 upgrade - Local Timezone issue

### ISSUE THREAD

**Issue by MinnMoto** [Yelp/elastalert#2602]
I have recently upgraded our Red Hat linux servers to 7.7 and Elastalert stopped working. I've searched and believe I have properly upgraded to Python 3.6 following these tickets:
[https://github.com/Yelp/elastalert/issues/2385](url)
[https://github.com/Yelp/elastalert/issues/2391](url)

Elasstalert appears to be running now, but I am having an issue with util.py can't determine my timezone. Same issue on Ubuntu install on Windows 10 too.

`ed2@ED2-L2:/opt/elastalert$ elastalert-test-rule rules/test.yaml
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
Didn't get any results.
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
1 rules loaded
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/test_rule.py", line 445, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/test_rule.py", line 437, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/test_rule.py", line 307, in run_elastalert
    client = ElastAlerter(['--debug'])
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 173, in __init__
    if not self.init_rule(rule):
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1037, in init_rule
    jitter=5)
  File "/home/ed2/.local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/home/ed2/.local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/home/ed2/.local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/home/ed2/.local/lib/python3.6/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/home/ed2/.local/lib/python3.6/site-packages/apscheduler/util.py", line 96, in astimezone
    'Unable to determine the name of the local timezone -- you must explicitly '
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (such as Europe/Helsinki).`

I have added "**use_local_time: true**" to my config.yaml and my test.yaml file. No luck so far. 
Recommendations?

**Comment by DanyelleAngelo** [comment]
I have the same problem. Did you find the solution?

**Comment by MinnMoto** [comment]
> I have the same problem. Did you find the solution?

No. Still haven't gotten Elastalert to work again.

**Comment by DanyelleAngelo** [comment]
on linux, i edited the timezone file (directory etc), putting "America/Sao_Paulo", then i gave a sudo apt-get upgrade in terminal and went back to normal

**Comment by MinnMoto** [comment]
I'll have to get my installation back to normal first. Did you do the other processes of upgrading to Python 3.6?

**Comment by DanyelleAngelo** [comment]
Yes,ith python3.7 an error occurs when running   elastalert-test-rule.  you must also install python3.6-dev

**Comment by kevintynfron** [comment]
I've just hit this exact  problem, has anybody made any progress? It's a fresh install of the Elastic stack stack.

> on linux, i edited the timezone file (directory etc), putting "America/Sao_Paulo", then i gave a sudo apt-get upgrade in terminal and went back to normal

Is that `/etc/timezone`?

Centos 7.8 
`yum tzdata` up to date
`/etc/timezone` is `Europe/London`
`$TZ` is `/usr/share/zoneinfo/Europe/London`
`zdump /etc/localtime` gives `/etc/localtime  Wed Feb  3 21:13:31 2021 GMT`
tried with and without ` --start 2021-02-01T12:00:00`

The rule I'm trying to test (the first one I've tried) is 
```
name: Filesystem Alert
type: metric_aggregation
index: metricbeat-*
metric_agg_key: system.filesystem.used.pct
metric_agg_type: avg
query_key: beat.hostname
doc_type: metricsets
bucket_interval:
  seconds: 10
sync_bucket_interval: true
#min_threshold: 0.1
max_threshold: 0.50
filter:
- term:
    metricset.name: filesystem
alert:
- debug
```

**Comment by kevintynfron** [comment]
I have managed to bodge it - ` elastalert-test-rule` runs without the error and looks like it is running correctly. 

The problem is with `util.py` in APScheduler (I've got version 3.7.0).

Look at  util.py (/home/ed2/.local/lib/python3.6/site-packages/apscheduler/util.py) in the original question. The error seems to be whatever is calling `astimezone` isn't passing the correct timezone in. I added line 90 `obj='Europe/London'` and it runs OK.

Not a fix, but at least I can get going and then double-back to   https://github.com/agronholm/apscheduler
```
     83 def astimezone(obj):
     84     """
     85     Interprets an object as a timezone.
     86
     87     :rtype: tzinfo
     88
     89     """
     90     obj='Europe/London'
     91     if isinstance(obj, six.string_types):
     92         return timezone(obj)
     93     if isinstance(obj, tzinfo):
     94         if not hasattr(obj, 'localize') or not hasattr(obj, 'normalize'):
     95             raise TypeError('Only timezones from the pytz library are supported')
     96         if obj.zone == 'local':
     97             raise ValueError(
     98                 'Unable to determine the name of the local timezone -- you must explicitly '
     99                 'specify the name of the local timezone. Please refrain from using timezones like '
    100                 'EST to prevent problems with daylight saving time. Instead, use a locale based '
    101                 'timezone name (such as Europe/Helsinki).')
    102         return obj
    103     if obj is not None:
    104         raise TypeError('Expected tzinfo, got %s instead' % obj.__class__.__name__)
    105
    106
```
