### ISSUE TITLE
index() missing 1 required positional argument: 'doc_type'

### ISSUE THREAD

**Issue by javadevmtl** [Yelp/elastalert#2618]
Hi, running Elastalert 0.21 with Elasticsearch 6.4.2 and getting the following error.

ERROR:root:Uncaught exception running rule XXXXXX rule: index() missing 1 required positional argument: 'doc_type'

When I pass the below rule to elastalert-test-rule it works fine.

```
#Test rule...
name: My rule
type: frequency
index: XXXXXX-*
num_events: 2
timeframe:
    minutes: 1
filter:
- term:
    myfield: "XXXXXX"
alert:
- "email"
email:
- "XXXXXX@gmail.com"
```
But when I run it using...

`elastalert --verbose --config ./config.yaml --rule ./rules/my-rule.yaml`

I get...

```
ERROR:root:Uncaught exception running rule Tazz rule: index() missing 1 required positional argument: 'doc_type'
ERROR:apscheduler.executors.default:Job "ElastAlerter.handle_rule_execution (trigger: interval[0:01:00], next run at: 2019-12-16 16:45:37 EST)" raised an exception
Traceback (most recent call last):
  File "/Users/XXXXXX/.pyenv/versions/3.8.0/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/elastalert.py", line 1270, in handle_rule_execution
    num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime'))
  File "/Users/XXXXXX/.pyenv/versions/3.8.0/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/elastalert.py", line 963, in run_rule
    self.writeback('elastalert_status', body)
  File "/Users/XXXXXX/.pyenv/versions/3.8.0/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/elastalert.py", line 1615, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/Users/XXXXXX/.pyenv/versions/3.8.0/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: index() missing 1 required positional argument: 'doc_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXXXXX/.pyenv/versions/3.8.0/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/XXXXXX/.pyenv/versions/3.8.0/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/elastalert.py", line 1274, in handle_rule_execution
    self.handle_uncaught_exception(e, rule)
  File "/Users/XXXXXX/.pyenv/versions/3.8.0/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/elastalert.py", line 1938, in handle_uncaught_exception
    self.handle_error('Uncaught exception running rule %s: %s' % (rule['name'], exception), {'rule': rule['name']})
  File "/Users/XXXXXX/.pyenv/versions/3.8.0/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/elastalert.py", line 1933, in handle_error
    self.writeback('elastalert_error', body)
  File "/Users/XXXXXX/.pyenv/versions/3.8.0/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/elastalert.py", line 1615, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/Users/XXXXXX/.pyenv/versions/3.8.0/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: index() missing 1 required positional argument: 'doc_type'
```

**Comment by javadevmtl** [comment]
Ok I reverted to 0.1.39 and it seems to be working with 6.x

**Comment by javadevmtl** [comment]
Hi any news on this? I just want to confirm. Is Elastalert 0.2x only compatible with Elasticsearch 7.x?

**Comment by daichi703n** [comment]
@javadevmtl 
From reading code.
ElastAlert 0.2.1 uses `elasticsearch>=7.0.0` client.
https://github.com/Yelp/elastalert/blob/v0.2.1/requirements.txt#L9

Client `elasticsearch` is only compatible with each major version.
https://elasticsearch-py.readthedocs.io/en/master/#compatibility

Therefore, at the moment, **Elastalert 0.2x only compatible with Elasticsearch 7.x**. You are right.

**Comment by fatalglitch** [comment]
Is this expected to be fixed, or is support for ES 6.X removed from all future elastalert versions?

**Comment by virtyaluk** [comment]
@javadevmtl, @fatalglitch, I had the same issue with `elasticsearch==6.8` and elastalert 0.2.4. Upgrading to `elasticsearch==7.0` helped me to get through this keeping my elasticsearch 6.8 untouched. It works ok so far except a small issue where a rule keeps on triggering even though it was disabled. Not sure whether it's internal elastalert issue or something else.
