### ISSUE TITLE
This rule apparently doesn't fit the schema

### ISSUE THREAD

**Issue by johnbchron** [Yelp/elastalert#2631]
I have a rule which I have constructed, but when I run it elastalert gives this giant complaint about it not fitting into the schema. Here is the rule

    # Flatline rule to alert if we haven't heard from a machine in over 5 minutes
    name: Logging Flatline Rule
    type: flatline
    index: metricbeat*
    threshold: 2
    timeframe: 5m
    use_count_query: true
    query_key: host.name
    alert:
    - email
    # (required, email specific)
    # a list of email addresses to send alerts to
    email:
    - "address@nonsense.com"
    smtp_host: "smtp.gmail.com"
    smtp_port: 465
    smtp_ssl: true
    smtp_auth_file: "/home/kainos/elastalert/smtp_auth_file"

   The smtp stuff is not the issue; it works with another rule. This is the error:
  
    Traceback (most recent call last):
      File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
        load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
      File "/home/kainos/.local/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/test_rule.py", line 445, in main
        test_instance.run_rule_test()
      File "/home/kainos/.local/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/test_rule.py", line 414, in run_rule_test
        conf['rules_loader'].load_options(rule_yaml, conf, args.file)
      File "/home/kainos/.local/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/loaders.py", line 231, in load_options
        raise EAException("Invalid Rule file: %s\n%s" % (filename, e))
    elastalert.util.EAException: Invalid Rule file: rules_folder/host_flatline
    {'name': 'Logging Flatline Rule', 'type': 'flatline', 'index': 'metricbeat*', 'threshold': 2, 'timeframe': '5m', 'use_count_query': True, 'query_key': 'host.name', 'alert': ['email'], 'email': ['jlewis@kainostech.com'], 'smtp_host': 'smtp.gmail.com', 'smtp_port': 465, 'smtp_ssl': True, 'smtp_auth_file': '/home/kainos/elastalert/smtp_auth_file', 'rule_file': 'rules_folder/host_flatline'} is not valid under any of the given schemas
    
    Failed validating 'oneOf' in schema:

    [ridiculously long json string here]

    On instance:
    {'alert': ['email'],
	    'email': ['jlewis@kainostech.com'],
	    'index': 'metricbeat*',
	    'name': 'Logging Flatline Rule',
	    'query_key': 'host.name',
	    'rule_file': 'rules_folder/host_flatline',
	    'smtp_auth_file': '/home/kainos/elastalert/smtp_auth_file',
	    'smtp_host': 'smtp.gmail.com',
	    'smtp_port': 465,
	    'smtp_ssl': True,
	    'threshold': 2,
	    'timeframe': '5m',
	    'type': 'flatline',
	    'use_count_query': True}

Tell me what I'm missing please

**Comment by johnbchron** [comment]
I found the answer: I needed to change 
```timeframe: 5m```
to
```
timeframe:
  minutes: 5
```
