### ISSUE TITLE
Configurations take no effects

### ISSUE THREAD

**Issue by xupengyao** [Yelp/elastalert#2633]
Hi,

​	I Just start the elastalert server in docker container,but when i test a rule,it occurred some errors:

```shell
01:27:10.950Z ERROR elastalert-server:
    TestController:  Error querying Elasticsearch:
    TypeError("count() got multiple values for keyword argument 'doc_type'",)
    
    WARNING:elasticsearch:GET http://localhost:9200/ [status:N/A request:0.002s]
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.2-py2.7.egg/elasticsearch/connection/http_requests.py", line 123, in perform_request
        response = self.session.send(prepared_request, **send_kwargs)
      File "/usr/lib/python2.7/site-packages/requests-2.22.0-py2.7.egg/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/site-packages/requests-2.22.0-py2.7.egg/requests/adapters.py", line 516, in send
        raise ConnectionError(e, request=request)
    ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabe8a080d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

​	I'm using ES7 and bitsensor/elastalert:3.0.0-beta.Here is my configurations:

config.json:

```
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "192.168.5.73",
  "es_port": 30651,
  "writeback_index": "elastalert_status"
}
```

elastalert.yaml:

```
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: 192.168.5.73

# The elasticsearch port
es_port: 30651

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 5

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2
```

​	I just don't understand why there use default ES url 'localhost:9200' but not '192.168.5.73:30651',anything wrong with my configurations?Thanks.

**Comment by xupengyao** [comment]
Sorry,here is my rule config:

```
es_host: 192.168.5.73
es_port: 30651
type: blacklist
index: k8s-event-logs*

timestamp_field: Metadata.creationTimestamp

timeframe:
    minutes: 1

compare_key: Type

blacklist:
    - "Normal"
    - "Warning"

smtp_host: smtp.qq.com
smtp_port: 25
smtp_auth_file: /opt/elastalert/rule_templates/smtp_auth_file.yaml   #帐号密码配置在此
from_addr: "22445566@qq.com"
alert:
- "email"
email:
- "22445566@qq.com"
```

**Comment by SVronskiy** [comment]
Hello, @xupengyao ! 
Have similar problem here? Did you find a solution?
