### ISSUE TITLE
Compound query not working correctly

### ISSUE THREAD

**Issue by siddharth99** [Yelp/elastalert#2643]
I am trying to setup elastalert to send alerts when disk usage group by (user, machine) increases beyond a number. I am using `query_key: [user, machine]` but I'm running into a python exception.

```
Traceback (most recent call last):
  File "/opt/persist/venv-py3_elk/lib/python3.7/pdb.py", line 1699, in main
    pdb._runscript(mainpyfile)
  File "/opt/persist/venv-py3_elk/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/opt/persist/venv-py3_elk/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/opt/persist/venv-py3_elk/bin/elastalert-test-rule", line 3, in <module>
    __requires__ = 'elastalert==0.2.1'
  File "/opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/test_rule.py", line 445, in main                                                                                                                            
    test_instance.run_rule_test()
  File "/opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/test_rule.py", line 437, in run_rule_test                                                                                                                   
    self.run_elastalert(rule_yaml, conf, args)
  File "/opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/test_rule.py", line 318, in run_elastalert                                                                                                                  
    client.run_rule(rule, endtime, starttime)
  File "/opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/elastalert.py", line 888, in run_rule                                                                                                                       
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/elastalert.py", line 649, in run_query                                                                                                                      
    rule_inst.add_aggregation_data(data)
  File "/opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/ruletypes.py", line 1005, in add_aggregation_data                                                                                                           
    self.unwrap_term_buckets(timestamp, payload_data['bucket_aggs']['buckets'])
  File "/opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/ruletypes.py", line 1019, in unwrap_term_buckets                                                                                                            
    self.check_matches(timestamp, term_data['key'], term_data)
  File "/opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/ruletypes.py", line 1058, in check_matches                                                                                                                  
    self.check_matches_recursive(timestamp, query_key, aggregation_data, self.rules['compound_query_key'], dict())
  File "/opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/ruletypes.py", line 1081, in check_matches_recursive                                                                                                        
    match_data)
  File "/opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/ruletypes.py", line 1084, in check_matches_recursive                                                                                                        
    metric_val = aggregation_data[self.metric_key]['value']
KeyError: 'metric_blocks_used_max'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /opt/persist/venv-py3_elk/lib/python3.7/site-packages/elastalert-0.2.1-py3.7.egg/elastalert/ruletypes.py(1084)check_matches_recursive()                                                                                                                       
-> metric_val = aggregation_data[self.metric_key]['value']
(Pdb) p aggregation_data.keys()
dict_keys(['key', 'doc_count', 'interval_aggs'])
(Pdb) p aggregation_data
{'key': 'host1.gcs', 'doc_count': 12, 'interval_aggs': {'buckets': [{'key_as_string': '2020-01-15 16:30:00.000000 Z', 'key': 1579105800000, 'doc_count': 3, 'metric_blocks_used_max': {'value': 5206760.0}}, {'key_as_string': '2020-01-15 17:00:00.000000 Z', 'key': 1579107600000, 'doc_count': 6, 'metric_blocks_used_max': {'value': 5206792.0}}, {'key_as_string': '2020-01-15 17:30:00.000000 Z', 'key': 1579109400000, 'doc_count': 3, 'metric_blocks_used_max': {'value': 5206860.0}}]}}                                                          

```

My config is:
```
name: Metricbeat Disk Usage Spike Rule
type: metric_aggregation

es_host: 127.0.0.1
es_port: 9200

index: disk_usage_user*

timestamp_field: time
timestamp_type: custom
timestamp_format: '%Y-%m-%d %H:%M:%S.%f %Z'

buffer_time:
  hours: 1

metric_agg_key: blocks_used
metric_agg_type: max
query_key: [ 'user', 'machine' ]
# aggregation_key: [ 'user', 'machine' ]
doc_type: default_type
  
bucket_interval:
  minutes: 30
  
sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true

min_threshold: 0
max_threshold: 250000000
```

Please advise if this is a config issue or a geniune bug.

**Comment by siddharth99** [comment]
After some hit & trial I was able to make the config work after removing `bucket_interval:` though I still can't understand how it works; the count of alerts on stdout/stderr is different from the number of slack alerts I am getting which is much smaller.

Additionally, I have a quick question - I want to send the alert to the 'user' from the matching row so I need support to be able to have dynamic slack channel/user. Any suggestions on how to support that easily; I can try copy-pasting some handling from the alert_subject_args code ?
