### ISSUE TITLE
urllib3.connection.HTTPConnection

### ISSUE THREAD

**Issue by stoksoz1** [Yelp/elastalert#2680]
Hi, on elastalert I am getting this error, any help would be appreciated.

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb1f9c085f8>: Failed to establish a new connection: [Errno 111] Connection refused
`

**Comment by daichi703n** [comment]
Hi, @stoksoz1 
Please paste your `elastalert.yaml` and `elasticsearch.yml`.
New installation? Can you curl to the Elasticsearch?

**Comment by daichi703n** [comment]
@stoksoz1 Ping

**Comment by nsano-rururu** [comment]
@stoksoz1  Ping

**Comment by SpeTr0x** [comment]
PONG
