### ISSUE TITLE
Not able to run the rules, getting formal parameter name expected error, any workaround is appreciated

### ISSUE THREAD

**Issue by rpotnuru** [Yelp/elastalert#2691]
Dear Team, I am having some issues while running my rules after setup, appreciate any help in this regard. This is wr.r.t. to the JIRA package that we are pullinging

bash-3.2$ elastalert-test-rule 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/test_rule.py", line 15, in <module>
    from elastalert.config import load_conf
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/config.py", line 9, in <module>
    from . import loaders
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/loaders.py", line 14, in <module>
    from . import alerts
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/alerts.py", line 26, in <module>
    from jira.client import JIRA
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jira-1.0.14-py3.8.egg/jira/__init__.py", line 10, in <module>
    from jira.client import Comment  # noqa: E402
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jira-**1.0.14-py3.8.egg/jira/client.py", line 225
    validate=False, get_server_info=True, async=False, logging=True, max_retries=3, proxies=None,**
                                          ^
SyntaxError: invalid syntax

**Comment by rpotnuru** [comment]
Upon doing some further investigation into the error, found out that this an issue when using python version > 3.6.

Here is the release notes of 3.7 : https://docs.python.org/3.7/whatsnew/3.7.html#summary-release-highlights

> Backwards incompatible syntax changes:
> **async** and **await** are now reserved keywords.

And async is causing issues to me. Let me downgrade my python to 3.6 for now while I wait for a fix available for this issue.

**Comment by rpotnuru** [comment]
I am able to deploy after downgrading the python version to 3.6.0, please let me know if you want me to close this issue??
