### ISSUE TITLE
elastalert-create-index / errs / not working / not Idempotence

### ISSUE THREAD

**Issue by PedroMSantosD** [Yelp/elastalert#2718]
Hi, elastalert-create-index is failing for me, can you advise how to troubleshoot, resolve?
i have followed this [issue]( https://github.com/Yelp/elastalert/issues/2454), but I'm loss.

I was expecting the script to validate if the index exists prior to try to create it, and report that it does with exitcode 0 (index already exists); or to create the index again if using --recreate , but can't find the parameter for --recreate

>  [--recreate RECREATE]

Second, can you point to the documentation that explains the Permissions on ElasticSearch, when using TLS? The user has all read permissions on elastalert (create index will be requested) and on the index where the data to alert on is, but it is obvious from the 403 that I still lack some permissions

Lastly, the output of execution
tryes to create es_6 mappings into es_7 cluster, is this safe? can it be configured somewhere?

execution error
```
(virtual_env) alertuser@elastalert-1.local config$ elastalert-create-index --config config.yaml
Elastic Version: 7.5.0
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
Traceback (most recent call last):
  File "/usr/local/elastalert/bin/virtual_env/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/elastalert/bin/virtual_env/lib64/python3.6/site-packages/elastalert/create_index.py", line 264, in main
    create_index_mappings(es_client=es, ea_index=index, recreate=args.recreate, old_ea_index=old_index)
  File "/usr/local/elastalert/bin/virtual_env/lib64/python3.6/site-packages/elastalert/create_index.py", line 30, in create_index_mappings
    if es_index.exists(ea_index):
  File "/usr/local/elastalert/bin/virtual_env/lib64/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/elastalert/bin/virtual_env/lib64/python3.6/site-packages/elasticsearch/client/indices.py", line 294, in exists
    return self.transport.perform_request("HEAD", _make_path(index), params=params)
  File "/usr/local/elastalert/bin/virtual_env/lib64/python3.6/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/elastalert/bin/virtual_env/lib64/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 163, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/elastalert/bin/virtual_env/lib64/python3.6/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, '')

```
execution with recreate:
```
(virtual_env) esportz@monitoring-elastalert-1.mdev.internal config$ elastalert-create-index --config config.yaml  --recreate ''
Elastic Version: 7.5.0
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
Traceback (most recent call last):
  File "/sites/monitoring-elastalert.internal/bin/virtual_env/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-create-index')()
  File "/sites/monitoring-elastalert.internal/bin/virtual_env/lib64/python3.6/site-packages/elastalert/create_index.py", line 264, in main
    create_index_mappings(es_client=es, ea_index=index, recreate=args.recreate, old_ea_index=old_index)
  File "/sites/monitoring-elastalert.internal/bin/virtual_env/lib64/python3.6/site-packages/elastalert/create_index.py", line 30, in create_index_mappings
    if es_index.exists(ea_index):
  File "/sites/monitoring-elastalert.internal/bin/virtual_env/lib64/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/sites/monitoring-elastalert.internal/bin/virtual_env/lib64/python3.6/site-packages/elasticsearch/client/indices.py", line 294, in exists
    return self.transport.perform_request("HEAD", _make_path(index), params=params)
  File "/sites/monitoring-elastalert.internal/bin/virtual_env/lib64/python3.6/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/sites/monitoring-elastalert.internal/bin/virtual_env/lib64/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 163, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/sites/monitoring-elastalert.internal/bin/virtual_env/lib64/python3.6/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, '')
```
python version

> (virtual_env) alertuser@elastalert-1.local config$ python
> Python 3.6.2 (default, Jul 18 2017, 22:59:34)
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
> Type "help", "copyright", "credits" or "license" for more information.

elastalert version

> alertuser@elastalert-1.local ~$ source /usr/local/elastalert/bin/virtual_env/bin/activate
> (virtual_env) alertuser@elastalert-1.local ~$ pip freeze | grep elast
> elastalert==0.2.1
> elasticsearch==7.5.1

config file:
```
(virtual_env) alertuser@elastalert-1.local config$ cat config.yaml
# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: /usr/local/elastalert/config/rules.d

# How often ElastAlert will query Elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  minutes: 3

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# The Elasticsearch hostname for metadata writeback
# Note that every rule can have its own Elasticsearch host
es_host: elasticsearch-node-1.local.internal
# The Elasticsearch port
es_port: 9200
# Connect with TLS to Elasticsearch
use_ssl: True
# Verify TLS certificates
verify_certs: True
# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
es_send_get_body_as: GET
# Option basic-auth username and password for Elasticsearch
#es_username: someusername
es_username: elastalert
es_password: super_password_123
# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
# defaults: elastalert_status
writeback_index: elastalert_status
####
# Options from ElastAlert Documentation:
# https://elastalert.readthedocs.io/en/latest/elastalert.html#configuration
client_key: elastalert.local.key
client_cert: elastalert-1.local.cert
ca_certs: root_ca.crt
scan_subdirectories: True
old_query_limit:
  minutes: 60
disable_rules_on_error: True
add_metadata_alert: True
skip_invalid: True
scroll_keepalive: 10m
```

**Comment by PedroMSantosD** [comment]
Taking it back.

Looks like it does check.
```

(virtual_env) alertuser@elastalert-1.local config$ elastalert-create-index --config config.yaml
Elastic Version: 7.5.0
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
Index elastalert_status already exists. Skipping index creation.
(virtual_env) esportz@monitoring-elastalert-1.mdev.internal config$ echo $?
0
```
