### ISSUE TITLE
Unable to execute rule with metric_aggregation type

### ISSUE THREAD

**Issue by kvskjava** [Yelp/elastalert#2729]
Hi Team,

I've installed ElastAlert in my CentOS Linux 8 server and able to executed example_frequency.yaml successfully as per the ElastAlert read the docs.

My requirement is to send a alert to ActiveMQ whenever method execution time exceeds 3 seconds(3000 milliseconds). I have a field called 'TotalTimeTakenInMilliseconds' in my index and data is proper as expected.

I've read the ElastAlert docs and thought that metric_aggregation  would be suitable for me in order to get an alert in case of method execution crossed max threshold.
So I've created a rule with below content(by checking all mandatory fields as per the docs):

My rule yaml file content:
--------------------------------------------------------------------
name: Method Execution Time Spike Rule
type: metric_aggregation

index: test_*

metric_agg_key: TotalTimeTakenInMilliseconds
metric_agg_type: max
doc_type: string

max_threshold: 3000

filter:
- term:
    IsError: "false"

alert:
- "stomp"
--------------------------------------------------------------------

I thought that filter is also mandatory field to have, so added one filed(IsError which is available in my index) and included as above. Is it mandatory to have filter?

When I try to test my rule with elastalert-test-rule --config config.yaml rules/test_rule.yaml command:

It's showing below content:
-----------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python3.6/site-packages/elastalert/test_rule.py", line 445, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python3.6/site-packages/elastalert/test_rule.py", line 437, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/local/lib/python3.6/site-packages/elastalert/test_rule.py", line 318, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 883, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 630, in run_query
    data = self.get_hits_aggregation(rule, start, end, index, rule.get('query_key', None))
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 564, in get_hits_aggregation
    body=query, size=0, ignore_unavailable=True)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
TypeError: deprecated_search() got an unexpected keyword argument 'headers'
-----------------------------------------------------------------------------------------

Am I doing anything wrong/missing anything?
Kindly please help me. Any help would be highly appreciated.

**Comment by kvskjava** [comment]
Seems there is an already existing issue with this error(https://github.com/Yelp/elastalert/issues/2725), so closing it.
