### ISSUE TITLE
Erro mock requires setuptools>=17.1. Aborting installation on CentOS

### ISSUE THREAD

**Issue by darioajr** [Yelp/elastalert#273]
Extracting elastalert-0.0.63-py2.7.egg to /usr/lib/python2.7/site-packages
elastalert 0.0.63 is already the active version in easy-install.pth
Installing elastalert-create-index script to /usr/bin
Installing elastalert-rule-from-kibana script to /usr/bin
Installing elastalert-test-rule script to /usr/bin

Installed /usr/lib/python2.7/site-packages/elastalert-0.0.63-py2.7.egg
Processing dependencies for elastalert==0.0.63
Searching for mock
Reading https://pypi.python.org/simple/mock/
Best match: mock 1.3.0
Downloading https://pypi.python.org/packages/source/m/mock/mock-1.3.0.tar.gz#md5=73ee8a4afb3ff4da1b4afa287f39fdeb
Processing mock-1.3.0.tar.gz
Writing /tmp/easy_install-tZTFYV/mock-1.3.0/setup.cfg
Running mock-1.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-tZTFYV/mock-1.3.0/egg-dist-tmp-5e5y16
mock requires setuptools>=17.1. Aborting installation
error: Setup script exited with 1

**Comment by svanommen** [comment]
Had the same problem. It took some googling to figure out how to update setuptools. This got me past the error: sudo pip install -U setuptools

Now to just resolve the new error =) 
Using /usr/lib/python2.6/site-packages
Finished processing dependencies for elastalert==0.0.63
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 258, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable

**Comment by MalcyB** [comment]
I'm trying to install on RHEL6.5 and have the same issues as svanommen.  I'm now also stuck with the "TypeError: 'NoneType' object is not callable" error.

**Comment by zsengineer** [comment]
@svanommen ..were you ever able to resolve that latest error you encountered:

TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 258, in _exit_functi                                                                             on
    info('process shutting down')
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 258, in _exit_functi                                                                             on
    info('process shutting down')
TypeError: 'NoneType' object is not callable

**Comment by khamlaoui** [comment]
Hello,
I got the same error, you should upgrade your setuptools:
curl https://bootstrap.pypa.io/ez_setup.py -o - | python

**Comment by arushidogra** [comment]
Did anyone got past this error?

**Comment by jacopoch** [comment]
Thanks @khamlaoui that helped :tada:

**Comment by liaoaoyang** [comment]
@khamlaoui thx 4 it

**Comment by nsano-rururu** [comment]
I have an inventory of problems.
I think this problem has been solved.
If it has been resolved, close it.
