### ISSUE TITLE
Error writing alert info to Elasticsearch

### ISSUE THREAD

**Issue by Ripcurl99983** [Yelp/elastalert#2747]
I am running Elastalert on Windows (Don't laugh). Elastalert version Version 0.2.4 and Elasticsearch version 7.6.0. The rule is new_term. I'm running the rule on Winlogbeat data (ECS mappings), and the alert info doesn't write to Elasticsearch if the port is not a number. The official ECS field is a keyword, but Elastalert thinks it should be a long, so it fails when the port field is empty (when the value is a '-'). 

I've tried uninstalling, reinstalling, used PIP install, built with setup.py. I also tried to sidestep by indexing a document with a '-' value so the mapping would get set to keyword. That worked to set the mapping as a keyword, but the error still happens as shown below. 

I'm new to Elastalert, but I've been working with Elasticsearch for a while. Is this causing incorrect alerts to fire?

> WARNING:elasticsearch:POST http://x.x.x.x:9200/elastalert_status/_doc [status:400 request:0.078s]
ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.winlog.event_data.IpPort] of type [long] in document with id 'H36amnEBT7X4R8V_u_hU'. Preview of field's value: '-'")
Traceback (most recent call last):
  File "c:\ELK\Elastalert\elastalert-master\elastalert\elastalert.py", line 1614, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\elasticsearch\client\utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\elasticsearch\client\__init__.py", line 362, in index
    body=body,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\elasticsearch\transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\elasticsearch\connection\http_requests.py", line 91, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\elasticsearch\connection\base.py", line 131, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.winlog.event_data.IpPort] of type [long] in document with id 'H36amnEBT7X4R8V_u_hU'. Preview of field's value: '-'")

Settings in rule YAML:

`name: Example new term rule`
`type: new_term`
`index: winlogbeat-7.6.0*`
`fields:`
    `- "winlog.computer_name"`
`terms_window_size:`
  `days: 90`
`filter:`
`- term:`
    `winlog.event_id: 4624`
`alert:`
`- "email"`

**Comment by Ripcurl99983** [comment]
For anyone having the same issue, I was able to fix by indexing a document with the correct mapping to the field after creating the new indexes, but before starting Elastalert. 

My initial attempt to try this failed because I didn't see the "match_body" token that encapsulated the winlog.event_data.IpPort. Errors are gone.

POST /elastalert_status/_doc
`{
  "@timestamp": "2020-04-21T01:56:24.378Z",
  "match_body": {
    "winlog": {
      "event_data": {
        "IpPort": "-"
      }
    }
  }
}`
