### ISSUE TITLE
Got Error at Write back Index

### ISSUE THREAD

**Issue by rehannali** [Yelp/elastalert#2765]
Hi, index write had problem with writing back to elasticsearch. Alerts and query woring fine but having problem writeback.

**Exception**

```
WARNING:elasticsearch:POST http://localhost:9200/elastalert_status/_doc [status:400 request:0.046s]
ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'mapper_parsing_exception', 'object mapping for [match_body.service] tried to parse field [service] as object, but found a concrete value')
Traceback (most recent call last):
  File "/home/nadeem/.local/lib/python3.6/site-packages/elastalert/elastalert.py", line 1614, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/home/nadeem/.local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/nadeem/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 362, in index
    body=body,
  File "/home/nadeem/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/nadeem/.local/lib/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 91, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/home/nadeem/.local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 131, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'object mapping for [match_body.service] tried to parse field [service] as object, but found a concrete value')
```

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert2.
https://github.com/jertel/elastalert2
