### ISSUE TITLE
ImportError: from . import kibana

### ISSUE THREAD

**Issue by ghl1024** [Yelp/elastalert#2776]
### use python3.6.7 install 
```
(root367) [root@aliyun elastalert]$ python -m elastalert.elastalert --verbose --config config/config.yaml --rule es_rules/wechart.yaml
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.7/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/.pyenv/versions/3.6.7/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/elastalert/elastalert/elastalert.py", line 29, in <module>
    from . import kibana
ImportError: attempted relative import with no known parent package
(root367) [root@aliyun elastalert]$ 
```

**Comment by ghl1024** [comment]
### use python2.7.5 install
```
[root@hayden elastalert]$ python -m elastalert.elastalert --verbose --config ../config/config.yaml --rule wechart.yaml
/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/elastic/alert/elastalert/elastalert/elastalert.py", line 29, in <module>
    from . import kibana
  File "elastalert/kibana.py", line 4, in <module>
    import urllib.error
ImportError: No module named error
[root@hayden elastalert]$ 
```

**Comment by ghl1024** [comment]
@Qmando 
help me, please.

**Comment by Qmando** [comment]
Sounds like your python installation is broken. 
python -v says 3.6.9
venv folder says 3.6.7
pip gives you a python2.7 warning

**Comment by ghl1024** [comment]
> Sounds like your python installation is broken.
> python -v says 3.6.9
> venv folder says 3.6.7
> pip gives you a python2.7 warning

#### I hava a new python3.6.9 env, then to start, but it still show this error.

```
[root@aliyun elastalert]$ python -m elastalert.elastalert --verbose --config ../config.yaml --rule ../rules/log_error.yaml 
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/python/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/elastalert/elastalert/elastalert.py", line 28, in <module>
    from . import kibana
ImportError: attempted relative import with no known parent package
[root@aliyun elastalert]$ python -V
Python 3.6.9
[root@aliyun elastalert]$ pip list|grep elasticsearch
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
elasticsearch                    7.0.0
[root@aliyun elastalert]$ 
```

**Comment by shiyongsway** [comment]
I have  solved  this problems. remove  elastalert.py to upper folder,don't let __main__.py and 
 __init__.py  at same folder.and  change from  .  import kibana to from  elastalert  import kibana ,etc

**Comment by elnacho-grande** [comment]
> 
> 
> I have solved this problems. remove elastalert.py to upper folder,don't let **main**.py and
> **init**.py at same folder.and change from . import kibana to from elastalert import kibana ,etc

I tried that but had no luck. I have no **main**.py and **init**.py which I could seperate and changing from . import kibana to from elastalert import kibana left me with this error:

` File "C:\Users\user\elastalert\elastalert\elastalert.py", line 29, in <module>
    from elastalert import kibana
ImportError: cannot import name 'kibana' from partially initialized module 'elastalert' (most likely due to a circular import) (C:\Users\user\elastalert\elastalert\elastalert.py)`

Any ideas?

**Comment by ashishkaransingh** [comment]
Getting the same error
Running command inside docker

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/elastalert/elastalert/elastalert.py", line 29, in <module>
    from . import kibana
ImportError: attempted relative import with no known parent package

**Comment by dunter-d** [comment]
Getting similar error w/ python 3.8.5. Anyone found a solution?
```
Traceback (most recent call last):
  File "elastalert/elastalert.py", line 29, in <module>
    from . import kibana
ImportError: attempted relative import with no known parent package
```

**Comment by ashishkaransingh** [comment]
Hello,
Are you getting this while running elastalert directly?
Are you using Elastalert in docker?

**Comment by dgempiuc** [comment]
i was using forked project elastalert2, and i had problem at below when running elastalert2 in my local environment

Traceback (most recent call last):
  File "C:\Users\...\elastalert2\elastalert\elastalert.py", line 32, in <module>
    from elastalert import kibana
  File "C:\Users\...\elastalert2\elastalert\elastalert.py", line 32, in <module>
    from elastalert import kibana
ImportError: cannot import name 'kibana' from partially initialized module 'elastalert' (most likely due to a circular import) (C:\Users\...\elastalert2\elastalert\elastalert.py)

the running command is "python elastalert/elastalert.py" in documentation (https://elastalert2.readthedocs.io/en/latest/running_elastalert.html#configuration-flags).

i copyed elastalert/elastalert.py file to root directory, then removed elastalert/elastalert.py file.

then running below command

python elastalert.py 

problem solved.

**Comment by iamrahulramesh** [comment]
> Python 3.8 Getting the same error
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
>     __import__(pkg_name)
>   File "/opt/elastalert/elastalert/elastalert.py", line 29, in <module>
>     from . import kibana
> ImportError: attempted relative import with no known parent package
> ```

Hi @ashishkaransingh  Is this issue resolved ? I am facing the same
