### ISSUE TITLE
elastalert-create-index Not working

### ISSUE THREAD

**Issue by ramasamy-t** [Yelp/elastalert#2810]
Im using Elasticsearch cluster 7.4.2 , Elastalert 0.2.4 and Python client for Elasticsearch 7.0.0

When I do elastalert-create-index Im getting following error

Elastic Version: 7.4.2
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/elastalert/create_index.py", line 264, in main
    create_index_mappings(es_client=es, ea_index=index, recreate=args.recreate, old_ea_index=old_index)
  File "/usr/local/lib/python3.6/dist-packages/elastalert/create_index.py", line 64, in create_index_mappings
    body=es_index_mappings['elastalert'], include_type_name=True)
  File "/home/elastalert/.local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/elastalert/.local/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 321, in put_mapping
    "PUT", _make_path(index, "_mapping", doc_type), params=params, body=body
  File "/home/elastalert/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/elastalert/.local/lib/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 91, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/home/elastalert/.local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 131, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Mapper for [@timestamp] conflicts with existing mapping:\n[mapper [@timestamp] has different [format] values]')

Can somebody help me with this?

**Comment by Lelik13a** [comment]
Edit:
`'es_mappings/6/silence.json'
'es_mappings/6/elastalert_status.json'
'es_mappings/6/elastalert.json'
'es_mappings/6/past_elastalert.json'
'es_mappings/6/elastalert_error.json'`

And delete all `"format": "dateOptionalTime"` options, like:
`"@timestamp": {
  "type": "date"
}`

**Comment by nsano-rururu** [comment]
@Lelik13a 

How can I reproduce it?
