### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 723: ordinal not in range(128)

### ISSUE THREAD

**Issue by Theoooooo** [Yelp/elastalert#2825]
The issue i'm having here is specificaly not working while executing elastalert from a PHP script with the shell_exec function.

Exemple :
```
$command = 'elastalert-test-rule --schema-only --config /etc/elastalert/config-elastalert.yaml ' . $path;
$output = shell_exec($command);
```

The command itself with the parameter :
```
elastalert-test-rule --schema-only --config /etc/elastalert/config-elastalert.yaml /etc/elastalert/rules-disabled/rule_lvl_10.yaml
```

Output :
```
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.1-py3.6.egg/elastalert/test_rule.py", line 445, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.1-py3.6.egg/elastalert/test_rule.py", line 413, in run_rule_test
    rule_yaml = conf['rules_loader'].get_yaml(args.file)
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.1-py3.6.egg/elastalert/loaders.py", line 516, in get_yaml
    return yaml_loader(filename)
  File "/usr/local/lib/python3.6/site-packages/staticconf/loader.py", line 168, in yaml_loader
    return yaml.load(fh, Loader=SafeLoader) or {}
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/local/lib64/python3.6/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib64/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib64/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib64/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 723: ordinal not in range(128)
```

The apache user has all the right to read and exec the config file as well as the rules directory and the rule itself :
```
/etc/elastalert]# getfacl config-elastalert.yaml
# file: config-elastalert.yaml
# owner: root
# group: root
user::rw-
user:apache:r-x
group::r--
mask::r-x
other::r--
```

```
/etc/elastalert]# getfacl rules-disabled/
# file: rules-disabled/
# owner: root
# group: root
user::rwx
user:apache:rwx
group::r-x
mask::rwx
other::r-x
```

```
/etc/elastalert/rules-disabled]# getfacl rule_lvl_10.yaml
# file: rule_lvl_10.yaml
# owner: root
# group: root
user::rwx
user:apache:rwx
group::r-x
mask::rwx
other::r-x
```

Otherwise, the command works properly from the shell.
Perhaps environment variables are missing ? Or is it a bug ?

**Comment by Theoooooo** [comment]
NVM i found out the shell PHP start doesn't use the correct language.

Linux shell :
```
echo $LANG
en_US.UTF-8
```
PHP language:
![image](https://user-images.githubusercontent.com/33425208/82911179-dd386880-9f6b-11ea-9bfe-f2cb0308421b.png)


To fix this, just put this line at the start of your php script :
```
putenv('LANG=en_US.UTF-8');
```

I hope this will help peoples who got the same issue as me ^^
