### ISSUE TITLE
Elastalert hit a security event but no email alert was sent

### ISSUE THREAD

**Issue by BadboyXMP** [Yelp/elastalert#2832]
**_Problem overview_**
Previously, my Elastalert was deployed under centos under a local VMware virtual machine, which can normally match security events and send alarms. Then I got Alibaba Cloud with the same configuration and made the exact same configuration, so I can be sure that the rule itself is not a problem, but ELastalert on Alibaba Cloud can hit a security event, but I cannot receive the alert email There are the following warnings: "WARNING:apscheduler.scheduler:Execution of job "ElastAlerter.handle_rule_execution (trigger: interval[0:01:00], next run at: 2020-06-03 10:39:07 CST)" skipped: maximum number of running instances reached (1)"

**_Detailed log_**
**_And this my rule and elart email config:_**
filter:
- query:
    query_string:
      query: "message: union"
# The alert is use when a match is found
alert:
- "email"

#邮件正文显示你定义的alert_text
alert_text: "Ref log http://192.168.136.134"
smtp_host: smtp.163.com
smtp_port: 25
smtp_auth_file: /opt/elastalert/smtp_auth.yaml
#回复给哪个邮箱
email_reply_to: XXX@163.com
from_addr: XXX@163.com
# a list of email addresses to send alerts to
email:
- "XXX2@qq.com"

**_The content output after executing Elastalert_**
INFO:elastalert:Queried rule sql注入 from 2020-06-03 10:11 CST to 2020-06-03 10:26 CST: 0 / 0 hits
INFO:elastalert:Queried rule sql注入 from 2020-06-03 10:26 CST to 2020-06-03 10:37 CST: 7 / 7 hits
INFO:elastalert:Background configuration change check run at 2020-06-03 10:37 CST
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 59.99985 seconds
WARNING:apscheduler.scheduler:Execution of job "ElastAlerter.handle_rule_execution (trigger: interval[0:01:00], next run at: 2020-06-03 10:38:05 CST)" skipped: maximum number of running instances reached (1)
WARNING:apscheduler.scheduler:Execution of job "ElastAlerter.handle_pending_alerts (trigger: interval[0:01:00], next run at: 2020-06-03 10:38:58 CST)" skipped: maximum number of running instances reached (1)
INFO:elastalert:Background configuration change check run at 2020-06-03 10:38 CST
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 59.999884 seconds
WARNING:apscheduler.scheduler:Execution of job "ElastAlerter.handle_rule_execution (trigger: interval[0:01:00], next run at: 2020-06-03 10:39:07 CST)" skipped: maximum number of running instances reached (1)

**_Then even more strange is that I query the result returned by elastalert_status and the number of ‘hits’ is 0, but my output above shows that the number of ‘hits’ is 7_**
[root@xmp elastalert]# curl 47.114.134.139:9200/elastalert_status/elasalert_error/_search?pretty=true
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}

**The above is the description of my problem, the help I hope to get is, if you need more detailed information, please let me know
(1) Point out the reason why the email alert cannot be sent or provide me with a troubleshooting idea**

**Comment by BadboyXMP** [comment]
To add, I checked elastalert_status_error and found the following alarm message

message:Error while running alert email: Error connecting to SMTP host: [Errno 110] Connection timed out traceback:Traceback (most recent call last):, File "/usr/local/elastalert/elastalert/alerts.py", line 475, in alert, self.smtp = SMTP(self.smtp_host, self.smtp_port), File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__, (code, msg) = self.connect(host, port), File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect, self.sock = self._get_socket(host, port, self.timeout), File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket, self.source_address), File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection, raise err, File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection, sock.connect(sa), TimeoutError: [Errno 110] Connection timed out, , During handling of the above exception, another exception occurred:, , Traceback (most recent call last):, File "/usr/local/elastalert/elastalert/elastalert.py", line 1544, in send_alert, alert.alert(matches), File "/usr/local/elastalert/elastalert/alerts.py", line 484, in alert, raise EAException("Error connecting to SMTP host: %s" % (e)), elastalert.util.EAException: Error connecting to SMTP host: [Errno 110] Connection timed out data.rule:sql注入 @timestamp:June 3rd 2020, 00:03:56.160 _id:26fGdXIBKzF_WLdyZoCB _type:_doc _index:elastalert_status_error _score: -
