### ISSUE TITLE
Error posting HTTP Post alert: 500 Server Error:  for url <Spring boot url>

### ISSUE THREAD

**Issue by rashmichoudhary07** [Yelp/elastalert#2847]
@Qmando 
I have a rule file with http_post alert. It gets matches however the below error occurs and rule get silent when num_events is encountered. PFB elastalert error stack trace. What could be the reason?
snap1: 
     {
        "_index" : "elastalert_status_error",
        "_type" : "_doc",
        "_id" : "Rn48oHIBSn3I_RspLdtD",
        "_score" : 1.0,
        "_source" : {
          "data" : {
            "rule" : "Alert404"
          },
          "traceback" : [
            "Traceback (most recent call last):",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/elastalert/alerts.py", line 1978, in alert""",
            "    response.raise_for_status()",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/requests/models.py", line 941, in raise_for_status""",
            "    raise HTTPError(http_error_msg, response=self)",
            "requests.exceptions.HTTPError: 500 Server Error:  for url: http://hostname:9000/../../errorcode",
            "",
            "During handling of the above exception, another exception occurred:",
            "",
            "Traceback (most recent call last):",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/elastalert/elastalert.py", line 1544, in send_alert""",
            "    alert.alert(matches)",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/elastalert/alerts.py", line 1980, in alert""",
            """    raise EAException("Error posting HTTP Post alert: %s" % e)""",
            "elastalert.util.EAException: Error posting HTTP Post alert: 500 Server Error:  for url: http://hostname:9000/../../errorcode"
          ],
          "message" : "Error while running alert http_post: Error posting HTTP Post alert: 500 Server Error:  for url: http://hostname:9000/../../errorcode",
          "@timestamp" : "2020-06-10T21:56:37.825126Z"
        }

snap 2:
INFO:elastalert:Ignoring match for silenced rule Alert404
/opt/app/cwlogai/python35/lib/python3.5/site-packages/urllib3/connectionpool.py:986: 
INFO:elastalert:Ran Alert404 from 2020-06-10 17:46 EDT to 2020-06-10 18:01 EDT: 3143 query hits (2899 already seen), 12 matches, 0 alerts sent
ERROR:root:Error while running alert http_post: Error posting HTTP Post alert: 500 Server Error:  for url: http://hostname:9000/../../errorcode

Any help would be highly appreciated.

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert2.
https://github.com/jertel/elastalert2
