### ISSUE TITLE
ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'illegal_argument_exception', 'mapper [match_body.error.log.stacktrace.vars.a] of different type, current_type [keyword], merged_type [ObjectMapper]')

### ISSUE THREAD

**Issue by clearloveyin** [Yelp/elastalert#2857]
ifferent type, current_type [keyword], merged_type [ObjectMapper]')
Traceback (most recent call last):
  File "/Users/yuyin/Desktop/workerspace/elastalert-0.2.4/elastalert/elastalert.py", line 1614, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/Users/yuyin/elastalert-0.2.4/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/yuyin/elastalert-0.2.4/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 362, in index
    body=body,
  File "/Users/yuyin/elastalert-0.2.4/lib/python3.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/Users/yuyin/elastalert-0.2.4/lib/python3.7/site-packages/elasticsearch/connection/http_requests.py", line 91, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/Users/yuyin/elastalert-0.2.4/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 131, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

my version is elastalert-0.2.4
how to fix it?

**Comment by nsano-rururu** [comment]
I have to delete the index and recreate it, but...

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert

**Comment by clearloveyin** [comment]
I  change  the source code to solve this problem

> We also recommend asking questions on the Gitter channel
> https://gitter.im/Yelp/elastalert

**Comment by clearloveyin** [comment]
I  change  the source code to solve this problem

**Comment by puzzlewrj** [comment]
> I change the source code to solve this problem

@clearloveyin i have the same problem.how to change the source code to fix it?thank u.
