### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 53: ordinal not in range(128)

### ISSUE THREAD

**Issue by gktrainer** [Yelp/elastalert#286]
Hi people!

I installed Elastalert on Windows Server, but when i running the command line for my rule, occurs the error below:

Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "E:\Servicos\ClearCred\Monitor\ElasticAlert\elastalert\elastalert.py", line 1279, in <module>
    sys.exit(main(sys.argv[1:]))
  File "E:\Servicos\ClearCred\Monitor\ElasticAlert\elastalert\elastalert.py", line 1274, in main
    client = ElastAlerter(args)
  File "E:\Servicos\ClearCred\Monitor\ElasticAlert\elastalert\elastalert.py", line 86, in __init__
    self.conf = load_rules(self.args)
  File "elastalert\config.py", line 355, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 53: ordinal not in range(128)

Command line: python -m elastalert.elastalert --verbose --rule .\rules\clearcred_propostas_pendentes_periodo.yaml

Rule file: https://dl.dropboxusercontent.com/u/56411996/clearcred_propostas_pendentes_periodo.yaml

**Comment by gktrainer** [comment]
People, i found the error, sorry for inconvenience.

**Comment by ahaii** [comment]
hello,i update my elastalert to 0.1.37

**Comment by ahaii** [comment]
Hello,
I got this error after update elastalert to 0.1.37.
Elasticsearch is 5.5
Error msg:
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1361, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/usr/local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1450, in send_alert
    alert.alert(matches)
  File "/usr/local/lib/python2.7/site-packages/elastalert/alerts.py", line 902, in alert
    command = [resolve_string(command_arg, matches[0]) for command_arg in self.rule['command']]
  File "/usr/local/lib/python2.7/site-packages/elastalert/util.py", line 410, in resolve_string
    string = string.format(**dd_match)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 118-121: ordinal not in range(128)

Please tell me how to fix it?
Thinks so much.

**Comment by ahaii** [comment]
add  `reload(sys)
sys.setdefaultencoding('utf-8')` to elastalert.py & alert.py  can fix it
@Qmando
