### ISSUE TITLE
Problem using array field in compare_key property

### ISSUE THREAD

**Issue by abilash-sethu** [Yelp/elastalert#2872]
Hi, I'm new to Elastalert, I have a set of services which generates logs, we use Filebeat to ship the logs to elastic search. I need to generate some useful alerts when there is a WARNING  OR ERROR comes in. I created a blacklist rule, the compare_key is "kibana.log.tags" the tags property is an array. so when I run the rule, I'm getting the below issue, couldn't find a solution. I spend lot of time to figure out nothing works.
The Error Log:

INFO:elastalert:Queried rule Log errors for kibana from 2020-07-01 17:16 India Standard Time to 2020-07-01 17:31 India Standard Time: 5 / 5 hits
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python36\Scripts\elastalert-test-rule-script.py", line 11, in <module>
    load_entry_point('elastalert==0.2.4', 'console_scripts', 'elastalert-test-rule')()
  File "c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\elastalert-0.2.4-py3.6.egg\elastalert\test_rule.py", line 445, in main
    test_instance.run_rule_test()
  File "c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\elastalert-0.2.4-py3.6.egg\elastalert\test_rule.py", line 437, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\elastalert-0.2.4-py3.6.egg\elastalert\test_rule.py", line 318, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\elastalert-0.2.4-py3.6.egg\elastalert\elastalert.py", line 889, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\elastalert-0.2.4-py3.6.egg\elastalert\elastalert.py", line 652, in run_query
    rule_inst.add_data(data)
  File "c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\elastalert-0.2.4-py3.6.egg\elastalert\ruletypes.py", line 124, in add_data
    if self.compare(event):
  File "c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\elastalert-0.2.4-py3.6.egg\elastalert\ruletypes.py", line 138, in compare
    if term in self.rules['blacklist']:
TypeError: unhashable type: 'list'

Here is My rules file configurations

name: Log errors for kibana
type: blacklist

index: filebeat-kibana-*

compare_key: kibana.log.tags #tags is an  array field

blacklist:
    - "ERROR"
    - "WARNING"

alert:
- "email"

**Comment by nsano-rururu** [comment]
I'm getting an error. It seems that writing yaml is not good.
By the way, does it work with other alert types?

>TypeError: unhashable type: 'list'

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert. Questions to the discussion below
https://github.com/jertel/elastalert/discussions
