### ISSUE TITLE
top_count_keys does not work with multiple query_key due to a unexpected leading space in filter

### ISSUE THREAD

**Issue by raymanound** [Yelp/elastalert#2874]
I have set up a frequency rule as follows.
```
name: test

index: wazuh-archives-3.x-*

type: frequency

num_events: 10

timeframe:
  hours: 1

filter:
- bool:
    must:
      - exists:
          field: "data.srcip"
      - exists:
          field: "data.dstip"

top_count_keys: ["data.dstuser", "data.srcip", "data.srcport", "data.dstip", "data.dstport"]

top_count_number: 5

raw_count_keys: false

query_key: ["data.srcip", "data.dstip"]
```
It will fail with top_count_keys:
```
Traceback (most recent call last):,
File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1450, in alert,
  return self.send_alert(matches, rule, alert_time=alert_time, retried=retried),
File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1485, in send_alert,
  counts = self.get_top_counts(rule, start, end, keys, qk=qk),
File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1997, in get_top_counts,
  buckets = list(hits_terms.values())[0], IndexError: list index out of range
```
I found out it is because there is a leading space for the second query_key in the filter query which leading query parsing error in elasticsearch for my case. (" YYY.YY.YY.YY" instead of "YYY.YY.YY.YY")
```
{
  "term": {
    "data.srcip": "XXX.XX.XX.XX"
  }
},
{
  "term": {
    "data.dstip": " YYY.YY.YY.YY"
  }
}
```
The reason is because a space is added for compound key during the join()
```
            if rule.get('compound_query_key'):
                values = [lookup_es_key(hit['_source'], key) for key in rule['compound_query_key']]
                hit['_source'][rule['query_key']] = ', '.join([str(value) for value in values])

            if rule.get('compound_aggregation_key'):
                values = [lookup_es_key(hit['_source'], key) for key in rule['compound_aggregation_key']]
                hit['_source'][rule['aggregation_key']] = ', '.join([str(value) for value in values])
```
but the qk_list is splitted by a single comma only which causing the issue
```
def get_hits_terms(self, rule, starttime, endtime, index, key, qk=None, size=None):
        rule_filter = copy.copy(rule['filter'])
        if qk:
            qk_list = qk.split(",")
```
For a fix, use ','.join instead of ', '.join for compound key.

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert. Questions to the discussion below
https://github.com/jertel/elastalert/discussions
