### ISSUE TITLE
Disabled rule can't be returned after deletion

### ISSUE THREAD

**Issue by vvvlad** [Yelp/elastalert#2893]
**Issue description:**

_elastalert 0.2.4_

When a rule gets disabled it shows in logs like this:
```
Disabled rules are: ['myrule']
```
Based on documentation, it can be re-enabled by ether restarting the server, or by changing the rule yaml content.
My assumption was that it would be also possible to delete the rule and later introduce it again.
What actually happens is that even when the rule gets deleted it stays in disabled rules and if later a rule with the same name introduced, an exception is thrown:

```
ERROR    [base.py:131] Job "ElastAlerter.handle_config_change (trigger: interval[0:00:30], next run at: 2020-07-21 19:09:43 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/APScheduler-3.6.3-py3.6.egg/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1235, in handle_config_change
    self.load_rule_changes()
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1133, in load_rule_changes
    if self.init_rule(new_rule):
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1036, in init_rule
    jitter=5)
  File "/usr/local/lib/python3.6/site-packages/APScheduler-3.6.3-py3.6.egg/apscheduler/schedulers/base.py", line 443, in add_job
    self._real_add_job(job, jobstore, replace_existing)
  File "/usr/local/lib/python3.6/site-packages/APScheduler-3.6.3-py3.6.egg/apscheduler/schedulers/base.py", line 867, in _real_add_job
    store.add_job(job)
  File "/usr/local/lib/python3.6/site-packages/APScheduler-3.6.3-py3.6.egg/apscheduler/jobstores/memory.py", line 41, in add_job
    raise ConflictingIdError(job.id)
apscheduler.jobstores.base.ConflictingIdError: 'Job identifier (myrule) conflicts with an existing job'
```

Any way to overcome this? Any fix?

Thanks

**Comment by nsano-rururu** [comment]
I haven't tried it yet, but the following pull request seems relevant.

[Removing/Disabling rule should stop scheduler jobs #2826](https://github.com/Yelp/elastalert/pull/2826)

**Comment by vvvlad** [comment]
> I haven't tried it yet, but the following pull request seems relevant.
> 
> [Removing/Disabling rule should stop scheduler jobs #2826](https://github.com/Yelp/elastalert/pull/2826)

the pull request refers to is_enabled, which is not working at all for us - elastalert ignores it... so not sure if it is relevant.
In our case, we remove yaml file while the rule in disabled state due to exception.

**Comment by nsano-rururu** [comment]
>the pull request refers to is_enabled, which is not working at all for us - elastalert ignores it... so not sure if it is relevant.
In our case, we remove yaml file while the rule in disabled state due to exception.

Ask the person who made the pull request?

**Reference information**

[Deleting a rule does not stop alerts #2043](https://github.com/Yelp/elastalert/issues/2043)
>clone the master branch instead of using the released version, it has the solution. ref: #2484

[Elastalert does not find rule after updates its "name:" value #2472](https://github.com/Yelp/elastalert/issues/2472)

**Comment by nsano-rururu** [comment]
**Reference information**

https://github.com/johnsusek/praeco/issues/165#issuecomment-585083702
>I also comment on ElastAlert Issue.
>Yelp/elastalert#1677 (comment)
>I don't create PR yet, because my fixes are poor and redundant...
>
>This fix on ElastAlert seems to be taken long time... Do you have any plan of workaround?
>If you have time, please test my code above and consider to adding like this temporary fix to servercentral/elastalert Docker Image.

https://github.com/johnsusek/praeco/issues/165#issuecomment-643801295
>Noticed qmando said this in the upstream issue:
"One workaround right now is instead of adding is_enabled: false, rename the file whatever.yaml.disabled or similar."
>
>So I might do something like this for enabling/disabling rules, and deleting rules.essential rename them first, then delete or disable.

**Comment by vvvlad** [comment]
@nsano_rururu
This is exactly the advice we are following, and it is exactly the source of the issue I describe:
"One workaround right now is instead of adding is_enabled: false, rename the file whatever.yaml.disabled or similar."

When file extension gets changed, it is equivalent to deleting a file. 

Let me go over the steps to reproduce the issue:
1. Create a custom rule which just throws an exception.  Add yaml file, lets call it ex_wa.yaml with rule name ex_wa.
2. When that rule is called by Elastalert it will get disabled. You will see a following message in the log:
Disabled rules are: ['ex_wa']
3. Now if you rename the file extension to .tm - the log message "Disabled rules are: ['ex_wa']" keeps showing.
4. Rename the file extension back to yaml.
5. You get the exception:

```
ERROR    [base.py:131] Job "ElastAlerter.handle_config_change (trigger: interval[0:00:30], next run at: 2020-07-21 19:09:43 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/APScheduler-3.6.3-py3.6.egg/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1235, in handle_config_change
    self.load_rule_changes()
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1133, in load_rule_changes
    if self.init_rule(new_rule):
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/elastalert.py", line 1036, in init_rule
    jitter=5)
  File "/usr/local/lib/python3.6/site-packages/APScheduler-3.6.3-py3.6.egg/apscheduler/schedulers/base.py", line 443, in add_job
    self._real_add_job(job, jobstore, replace_existing)
  File "/usr/local/lib/python3.6/site-packages/APScheduler-3.6.3-py3.6.egg/apscheduler/schedulers/base.py", line 867, in _real_add_job
    store.add_job(job)
  File "/usr/local/lib/python3.6/site-packages/APScheduler-3.6.3-py3.6.egg/apscheduler/jobstores/memory.py", line 41, in add_job
    raise ConflictingIdError(job.id)
apscheduler.jobstores.base.ConflictingIdError: 'Job identifier (ex_wa) conflicts with an existing job'
```

Hope I made this issue clearer now. Really appreciate your help.

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert
