### ISSUE TITLE
found unknown escape character ':'

### ISSUE THREAD

**Issue by zoudaqiang** [Yelp/elastalert#2895]
Hi!

I have a question about escape special characters

I want to be alerted when the characters "message": \\: occurs.

so, set it up like below
----------------------------------------------------------------------------------------------------------------
filter:
- query:
     query_string:
       query: "message: \\:"
----------------------------------------------------------------------------------------------------------------
However, running elastalert results in the following error
Traceback (most recent call last):
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/loaders.py", line 526, in get_yaml
    return yaml_loader(filename)
  File "/usr/local/python36/lib/python3.6/site-packages/staticconf/loader.py", line 168, in yaml_loader
    return yaml.load(fh, Loader=SafeLoader) or {}
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/scanner.py", line 1152, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "/usr/local/python36/lib/python3.6/site-packages/yaml/scanner.py", line 1224, in scan_flow_scalar_non_spaces
    "found unknown escape character %r" % ch, self.get_mark())
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "/usr/local/src/elastalert-master/example_rules/frequency.yaml", line 48, column 15
found unknown escape character ':'
  in "/usr/local/src/elastalert-master/example_rules/frequency.yaml", line 48, column 26

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/loaders.py", line 115, in load
    rule = self.load_configuration(rule_file, conf, args)
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/loaders.py", line 179, in load_configuration
    rule = self.load_yaml(filename)
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/loaders.py", line 197, in load_yaml
    loaded = self.get_yaml(filename)
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/loaders.py", line 528, in get_yaml
    raise EAException('Could not parse file %s: %s' % (filename, e))
elastalert.util.EAException: Could not parse file /usr/local/src/elastalert-master/example_rules/frequency.yaml: while scanning a double-quoted scalar
  in "/usr/local/src/elastalert-master/example_rules/frequency.yaml", line 48, column 15
found unknown escape character ':'
  in "/usr/local/src/elastalert-master/example_rules/frequency.yaml", line 48, column 26

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/elastalert.py", line 2055, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/elastalert.py", line 2049, in main
    client = ElastAlerter(args)
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/elastalert.py", line 140, in __init__
    self.rules = self.rules_loader.load(self.conf, self.args)
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/loaders.py", line 126, in load
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file /usr/local/src/elastalert-master/example_rules/frequency.yaml: Could not parse file /usr/local/src/elastalert-master/example_rules/frequency.yaml: while scanning a double-quoted scalar
  in "/usr/local/src/elastalert-master/example_rules/frequency.yaml", line 48, column 15
_**found unknown escape character ':'**_
  in "/usr/local/src/elastalert-master/example_rules/frequency.yaml", line 48, column 26

-----------------------------------------------------------------------------------------------------
I’m search for days and didn’t find any solution
Thanks a lot
Joe

**Comment by nsano-rururu** [comment]
I think the following issues will be helpful

[Is it possible to use regular expression in filter ? #719](https://github.com/Yelp/elastalert/issues/719)
[How to escape special characters #2528](https://github.com/Yelp/elastalert/issues/2528)

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert. Questions to the discussion below
https://github.com/jertel/elastalert/discussions
