### ISSUE TITLE
python setup.py install

### ISSUE THREAD

**Issue by RAGHWENDRAPRATAPSINGH** [Yelp/elastalert#2910]
When I want to install setup. I am getting this error 
Extracting elastalert-0.2.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.2.4-py2.7.egg/elastalert/test_rule.py", line 61
    print('Invalid filter provided:', str(ea), file=sys.stderr)
                                                   ^
SyntaxError: invalid syntax
Running configparser-5.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-caRrz3/configparser-5.0.0/egg-dist-tmp-5EJvTT
error: Setup script exited with error: 'egg_base' must be a directory name (got `src`)

**Comment by nsano-rururu** [comment]
You need Python 3.6 for Elastalert.
Check this: https://elastalert.readthedocs.io/en/latest/running_elastalert.html#requirements

**Comment by rishi360** [comment]
I am also getting this error when ever i excute the command in OS  AMI of aws (Amazon Linux 2)

when i tried with python3
python3 setup.py install 
and get  error:
<copying elastalert.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    'cffi>=1.11.5'
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib64/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 218, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 269, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 379, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 416, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
>

**Comment by nsano-rururu** [comment]
@RAGHWENDRAPRATAPSINGH

Please tell me the OS and Elasticsearch version you are using.

**Comment by nsano-rururu** [comment]
@RAGHWENDRAPRATAPSINGH 

example 

Ubuntu 18.04 LTS

```
sudo apt update
sudo apt -y upgrade
sudo apt install -y python3.6-dev
sudo apt install -y libffi-dev libssl-dev
sudo apt install -y python3-pip
sudo apt install -y python3-venv

# Python3.6 Create virtual environment
python3.6 -m venv ~/elastalertvenv/

# Python3.6 Virtual environment switching
source ~/elastalertvenv/bin/activate

git clone https://github.com/Yelp/elastalert.git
cd elastalert
pip install "setuptools>=11.3"
python setup.py install

# Python3.6 Virtual environment End virtual environment
deactivate
```

**Comment by RAGHWENDRAPRATAPSINGH** [comment]
@nsano-rururu nsano-rururu , thanks . I have succesfully setup it. It's the issue of python versin. Thanks

**Comment by nsano-rururu** [comment]
@RAGHWENDRAPRATAPSINGH 

Did you solve? Or unsolved

**Comment by RAGHWENDRAPRATAPSINGH** [comment]
It's solved.
Thanks

**Comment by nsano-rururu** [comment]
@RAGHWENDRAPRATAPSINGH 

If the issue is resolved, click the close issue button to close the issue. Only the person who posted the issue or the administrator can close it.

**Comment by RAGHWENDRAPRATAPSINGH** [comment]
Thanks for help
