### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by KennedyDeswal** [Yelp/elastalert#2967]
I'm trying to install elastalert and during  elastalert-create-index   I'm getting the below error : 
kindly suggest how to rectify this.

Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.2.4', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.4-py3.6.egg/elastalert/create_index.py", line 195, in main
    data = yaml.load(config_file, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

**Comment by KennedyDeswal** [comment]
sudo -H pip3 install --ignore-installed PyYAML

It will work
