### ISSUE TITLE
Only timezones from the pytz library are supported

### ISSUE THREAD

**Issue by deric** [Yelp/elastalert#2968]
With `tzlocal==3.0b1` elastalert doesn't work:

```
1 rules loaded
Traceback (most recent call last):
  File "/usr/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.2.1', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/test_rule.py", line 445, in main
    test_instance.run_rule_test()
  File "/usr/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/test_rule.py", line 437, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/test_rule.py", line 307, in run_elastalert
    client = ElastAlerter(['--debug'])
  File "/usr/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/elastalert.py", line 173, in __init__
    if not self.init_rule(rule):
  File "/usr/lib/python3.8/site-packages/elastalert-0.2.1-py3.8.egg/elastalert/elastalert.py", line 1031, in init_rule
    job = self.scheduler.add_job(self.handle_rule_execution, 'interval',
  File "/usr/lib/python3.8/site-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/schedulers/base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/lib/python3.8/site-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/schedulers/base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/lib/python3.8/site-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/lib/python3.8/site-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/lib/python3.8/site-packages/APScheduler-3.6.3-py3.8.egg/apscheduler/util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
```

**Comment by deric** [comment]
Adding `'tzlocal<3.0',` to `setup.py` will ensure the old behavior.

**Comment by ManuelFFF** [comment]
Hi,

I'm having the same issue with Python 3.7. Any ideas?

Thanks

https://github.com/Yelp/elastalert/issues/2970

**Comment by ManuelFFF** [comment]
Please disregard. I tried downgrading "tzlocal" like you said (tzlocal<3.0) and that fixed the issue. ElastAlert is up and running.

Thank you

**Comment by nsano-rururu** [comment]
I didn't check the movement. I'm sorry.

**Comment by nsano-rururu** [comment]
**File to change**
requirements.txt
setup.py

**Comment by deric** [comment]
> @deric
> 
> Do you not issue a pull request?
> If there is no plan to support it, I will do it, so please reply anyway.

I'm not familiar with tzlocal changes, proposed fix is just a quick fix, not a proper solution to the problem.

**Comment by nsano-rururu** [comment]
@deric 

It doesn't matter if you're not familiar with it.
As a result, you have done the right thing, so feel confident. There is no mistake in correspondence. as a result
It means that the version before tzlocal 3.0b1 worked fine with APScheduler of the library used by ElastAlert.
See the APScheduler issue below.
https://github.com/agronholm/apscheduler/issues/461

**Comment by nsano-rururu** [comment]
However, in the current situation of ElastAlert, 
I feel that it is often left as it is without being imported when a pull request is issued.

**Comment by nsano-rururu** [comment]
I have ElastAlert's third party tools [johnsusek/elastalert-server](https://github.com/johnsusek/elastalert-server) and [johnsusek/praeco](https://github.com/johnsusek/praeco) Since I am the maintainer, 
I will incorporate this support into the Docker image of ElastAlertServer.

**Comment by nsano-rururu** [comment]
It's been 3 months since I became the maintainer, so I'm not so familiar with ElastAlert, so I'm studying every day ..

**Comment by nsano-rururu** [comment]
It may be included when you pip install APSchuler, so I will check it later. 
Maybe the latest version will include versions earlier than tzlocal 3.0b1 .

**Comment by nsano-rururu** [comment]
After the new version of APScheduler came out, 
I felt that it would be good to make a pull request to correct the description of "'apscheduler> = 3.3.0'" in setup.py and requirements.txt of ElastAlert.

>tzlocal >= 3.0b1, < 4.0
https://github.com/agronholm/apscheduler/blob/master/setup.cfg#L28

**Comment by nsano-rururu** [comment]
```
(myvenv) [CORP\sano@a-ngft53r34ong pywork]$ pip install 'apscheduler >= 3.3.0'
Requirement already satisfied: apscheduler>=3.3.0 in /home/sano/myvenv/lib/python3.7/site-packages/APScheduler-3.6.3-py3.7.egg (3.6.3)
Requirement already satisfied: pytz in /home/sano/myvenv/lib/python3.7/site-packages (from apscheduler>=3.3.0) (2020.1)
Requirement already satisfied: setuptools>=0.7 in /home/sano/myvenv/lib/python3.7/site-packages (from apscheduler>=3.3.0) (40.8.0)
Requirement already satisfied: six>=1.4.0 in /home/sano/myvenv/lib/python3.7/site-packages (from apscheduler>=3.3.0) (1.14.0)
Collecting tzlocal>=1.2 (from apscheduler>=3.3.0)
  Using cached https://files.pythonhosted.org/packages/5d/94/d47b0fd5988e6b7059de05720a646a2930920fff247a826f61674d436ba4/tzlocal-2.1-py2.py3-none-any.whl
Installing collected packages: tzlocal
Successfully installed tzlocal-2.1
```

**Comment by nsano-rururu** [comment]
It will not be installed unless tzlocal == 3.0b1 is explicitly specified. If that happens, I wonder if I need to issue a pull request

**Comment by stephendwolff** [comment]
@nsano-rururu i think it might be that APScheduler needs the pinned requirement for tzlocal. I came across this issue when i had a problem installing a project which had APScheduler as a requirement, but no pins (explicit versions specified)

**Comment by nsano-rururu** [comment]
@stephendwolff 

I will make a pull request to add the following specifications to setup.py and requirements.txt.
However, since ElastAlert is in hibernation, it is undecided when it will be imported.

tzlocal==2.1

**Comment by RafaelAzevedo** [comment]
> Adding `'tzlocal<3.0',` to `setup.py` will ensure the old behavior.

It worked to me!

Tks.

**Comment by zhuangh7** [comment]
> Adding `'tzlocal<3.0',` to `setup.py` will ensure the old behavior.

THKS, work for me too

**Comment by Sam0x90** [comment]
> Adding `'tzlocal<3.0',` to `setup.py` will ensure the old behavior.

Yep, works fine for me, thanks. 
Just add this line and re-run
`python3 setup.py install`

**Comment by Karlheinzniebuhr** [comment]
Same issue here
