### ISSUE TITLE
Python error on fresh ElastAlert installation

### ISSUE THREAD

**Issue by ManuelFFF** [Yelp/elastalert#2970]
Hi,

I just installed ElastAlert and when I try to test the app, I got an error regarding the pytz library from Python. 

Can anybody help?

Thanks
```

root@testserver:/opt/elastalert# python3 -m elastalert.elastalert --verbose --rule tss_frequency_TEST.yaml
1 rules loaded
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/elastalert/elastalert/elastalert.py", line 2057, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/opt/elastalert/elastalert/elastalert.py", line 2051, in main
    client = ElastAlerter(args)
  File "/opt/elastalert/elastalert/elastalert.py", line 173, in __init__
    if not self.init_rule(rule):
  File "/opt/elastalert/elastalert/elastalert.py", line 1038, in init_rule
    jitter=5)
  File "/usr/local/lib/python3.7/dist-packages/APScheduler-3.6.3-py3.7.egg/apscheduler/schedulers/base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python3.7/dist-packages/APScheduler-3.6.3-py3.7.egg/apscheduler/schedulers/base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python3.7/dist-packages/APScheduler-3.6.3-py3.7.egg/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/APScheduler-3.6.3-py3.7.egg/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/local/lib/python3.7/dist-packages/APScheduler-3.6.3-py3.7.egg/apscheduler/util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
```

**Comment by ManuelFFF** [comment]
Resolved in https://github.com/Yelp/elastalert/issues/2968

Solution: Downgrade `tzlocal `to `tzlocal<3.0`
