### ISSUE TITLE
Aggregation query exceeding indices.query.bool.max_clause_count

### ISSUE THREAD

**Issue by luanlucas** [Yelp/elastalert#2994]
# Environment
- ELK: 7.4.2
- Elastalert: jertel/elastalert-docker:0.2.4

## Alert rule
```
# (Required)
# Rule name, must be unique
name: Dropped Log Warning

# (Required)
# Index to search, wildcard supported
index: filebeat-*

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  minutes: 5

# (Required)
# A list of elasticsearch filters used for find events
filter:
 - term:
       message: "mapper_parsing_exception"

# Aggregation
aggregation:
  minutes: 5

alert_text: "Dropped log message on {1} for service {2} due to: {0}"
alert_text_type: alert_text_only
alert_text_args:
  - "reason"
  - "service_environment"
  - "service_name"

match_enhancements:
  - "elastalert_modules.my_enhancement.MyEnhancement"

alert:
  - "slack"

slack_webhook_url: "https://webhook"
```

## Stack trace
```
WARNING:elasticsearch:GET https://elasticsearch:443/elastalert/_search?size=1000 [status:400 request:1.515s]
ERROR:root:Error finding recent pending alerts: RequestError(400, 'search_phase_execution_exception', 'failed to create query: {\n  "bool" : {\n    "must" : [\n      {\n        "query_string" : {\n          "query" : "!_exists_:aggregate_id AND alert_sent:false",\n          "fields" : [ ],\n          "type" : "best_fields",\n          "default_operator" : "or",\n          "max_determinized_states" : 10000,\n          "enable_position_increments" : true,\n          "fuzziness" : "AUTO",\n          "fuzzy_prefix_length" : 0,\n          "fuzzy_max_expansions" : 50,\n          "phrase_slop" : 0,\n          "escape" : false,\n          "auto_generate_synonyms_phrase_query" : true,\n          "fuzzy_transpositions" : true,\n          "boost" : 1.0\n        }\n      }\n    ],\n    "filter" : [\n      {\n        "range" : {\n          "alert_time" : {\n            "from" : "2020-10-18T15:11:25.188958Z",\n            "to" : "2020-10-20T15:11:25.188999Z",\n            "include_lower" : true,\n            "include_upper" : true,\n            "boost" : 1.0\n          }\n        }\n      }\n    ],\n    "adjust_pure_negative" : true,\n    "boost" : 1.0\n  }\n}') {'query': {'bool': {'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'filter': {'range': {'alert_time': {'from': '2020-10-18T15:11:25.188958Z', 'to': '2020-10-20T15:11:25.188999Z'}}}}}, 'sort': {'alert_time': {'order': 'asc'}}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 1640, in find_recent_pending_alerts
    res = self.writeback_es.search(index=self.writeback_index, body=query, size=1000)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 811, in search
    "GET", _make_path(index, "_search"), params=params, body=body
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 91, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 131, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: {\n  "bool" : {\n    "must" : [\n      {\n        "query_string" : {\n          "query" : "!_exists_:aggregate_id AND alert_sent:false",\n          "fields" : [ ],\n          "type" : "best_fields",\n          "default_operator" : "or",\n          "max_determinized_states" : 10000,\n          "enable_position_increments" : true,\n          "fuzziness" : "AUTO",\n          "fuzzy_prefix_length" : 0,\n          "fuzzy_max_expansions" : 50,\n          "phrase_slop" : 0,\n          "escape" : false,\n          "auto_generate_synonyms_phrase_query" : true,\n          "fuzzy_transpositions" : true,\n          "boost" : 1.0\n        }\n      }\n    ],\n    "filter" : [\n      {\n        "range" : {\n          "alert_time" : {\n            "from" : "2020-10-18T15:11:25.188958Z",\n            "to" : "2020-10-20T15:11:25.188999Z",\n            "include_lower" : true,\n            "include_upper" : true,\n            "boost" : 1.0\n          }\n        }\n      }\n    ],\n    "adjust_pure_negative" : true,\n    "boost" : 1.0\n  }\n}')
WARNING:apscheduler.scheduler:Execution of job "ElastAlerter.handle_rule_execution (trigger: interval[0:01:00], next run at: 2020-10-20 15:11:35 UTC)" skipped: maximum number of running instances reached (1)
```
I believe this happens because ```fields``` is empty in the query therefore all fields are being considered and increasing ```indices.query.bool.max_clause_count``` would allow such behaviour, Is it possible to find a way around it? In this specific case I need only one field to be returned, is it possible to add the necessary fields to ```fields``` array? Do you have any other suggestion?
Thank you very much.

**Comment by nsano-rururu** [comment]
We also recommend asking questions on the Gitter channel
https://gitter.im/Yelp/elastalert

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert. 
https://github.com/jertel/elastalert
