### ISSUE TITLE
'Connection aborted.', error(54, 'Connection reset by peer')

### ISSUE THREAD

**Issue by karthik87mit** [Yelp/elastalert#301]
Hi,

Am trying to run the elastalert-test-rule. I configured the es_host and es_port to point to our elastic search. While, hitting the url manually I get the following response,

{
  "status" : 200,
  "name" : "elk-02",
  "cluster_name" : "****",
  "version" : {
    "number" : "1.4.5",
   ...
  
  },
  "tagline" : "You Know, for Search"
}

but when I run the test rule I get the above mentioned error. SSL is set to false and so is the basic auth.

What am I missing here?

Thanks,

**Comment by Qmando** [comment]
Hm, I've not experienced this problem before.

Can you try to run ``elastalert --debug --es_debug_trace trace.log``? That should log the exact request that ElastAlert is making, and that might have some helpful information.

**Comment by karthik87mit** [comment]
Hello,

I get the following error,

```
elastalert --debug --es_debug_trace trace.log
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 9, in <module>
    load_entry_point('elastalert==0.0.66', 'console_scripts', 'elastalert')()
  File "/Library/Python/2.7/site-packages/elastalert-0.0.66-py2.7.egg/elastalert/elastalert.py", line 1274, in main
    client = ElastAlerter(args)
  File "/Library/Python/2.7/site-packages/elastalert-0.0.66-py2.7.egg/elastalert/elastalert.py", line 86, in __init__
    self.conf = load_rules(self.args)
  File "/Library/Python/2.7/site-packages/elastalert-0.0.66-py2.7.egg/elastalert/config.py", line 361, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file example_rules/example_new_term.yaml: Error initializing rule Example rule: Error searching for existing terms: ConnectionError(('Connection aborted.', error(54, 'Connection reset by peer'))) caused by: ProtocolError(('Connection aborted.', error(54, 'Connection reset by peer')))
```
