### ISSUE TITLE
Elastalert throwing read timeout error for HTTP Post alert

### ISSUE THREAD

**Issue by rashmichoudhary07** [Yelp/elastalert#3050]
Hi @Qmando 

Greeting!

Need help urgently!

I have multiple http post alerts setup in environment. We see a high volumes of readtimeout exceptions from different rules mostly during the peak traffic hours which causes delay in alerts. Also, tried to increase http_post_timeout value. My http_post_url is tomcat api. My  PFB readtimeout error as observed in elastalert_status_error index:
{
        "_index" : "elastalert_status_error",
        "_type" : "_doc",
        "_id" : "z-i_AHYBTFeu9chC-Uyt",
        "_score" : null,
        "_source" : {
          "@timestamp" : "2020-11-25T18:52:29.994908Z",
          "data" : {
            "rule" : "Sample Rule Name"
          },
          "message" : "Error while running alert http_post: Error posting HTTP Post alert: HTTPConnectionPool(host='someurl', port=9000): Read timed out. (read timeout=120)",
          "traceback" : [
            "Traceback (most recent call last):",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/urllib3/connectionpool.py", line 426, in _make_request""",
            "    six.raise_from(e, None)",
            """  File "<string>", line 3, in raise_from""",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/urllib3/connectionpool.py", line 421, in _make_request""",
            "    httplib_response = conn.getresponse()",
            """  File "/opt/python35/lib/python3.5/http/client.py", line 1197, in getresponse""",
            "    response.begin()",
            """  File "/opt/python35/lib/python3.5/http/client.py", line 297, in begin""",
            "    version, status, reason = self._read_status()",
            """  File "/opt/python35/lib/python3.5/http/client.py", line 258, in _read_status""",
            """    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")""",
            """  File "/opt/python35/lib/python3.5/socket.py", line 575, in readinto""",
            "    return self._sock.recv_into(b)",
            "socket.timeout: timed out",
            "",
            "During handling of the above exception, another exception occurred:",
            "",
            "Traceback (most recent call last):",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/requests/adapters.py", line 449, in send""",
            "    timeout=timeout",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/urllib3/connectionpool.py", line 725, in urlopen""",
            "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/urllib3/util/retry.py", line 403, in increment""",
            "    raise six.reraise(type(error), error, _stacktrace)",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/urllib3/packages/six.py", line 735, in reraise""",
            "    raise value",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/urllib3/connectionpool.py", line 677, in urlopen""",
            "    chunked=chunked,",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/urllib3/connectionpool.py", line 428, in _make_request""",
            "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout""",
            """    self, url, "Read timed out. (read timeout=%s)" % timeout_value""",
            "urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='someurl', port=9000): Read timed out. (read timeout=120)",
            "",
            "During handling of the above exception, another exception occurred:",
            "",
            "Traceback (most recent call last):",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/elastalert/alerts.py", line 1977, in alert""",
            "    headers=headers, proxies=proxies, timeout=self.timeout)",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/requests/api.py", line 119, in post""",
            "    return request('post', url, data=data, json=json, **kwargs)",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/requests/api.py", line 61, in request""",
            "    return session.request(method=method, url=url, **kwargs)",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/requests/sessions.py", line 530, in request""",
            "    resp = self.send(prep, **send_kwargs)",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/requests/sessions.py", line 643, in send""",
            "    r = adapter.send(request, **kwargs)",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/requests/adapters.py", line 529, in send""",
            "    raise ReadTimeout(e, request=request)",
            "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='someurl', port=9000): Read timed out. (read timeout=120)",
            "",
            "During handling of the above exception, another exception occurred:",
            "",
            "Traceback (most recent call last):",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/elastalert/elastalert.py", line 1544, in send_alert""",
            "    alert.alert(matches)",
            """  File "/opt/app/cwlogai/python35/lib/python3.5/site-packages/elastalert/alerts.py", line 1980, in alert""",
            """    raise EAException("Error posting HTTP Post alert: %s" % e)""",
            "elastalert.util.EAException: Error posting HTTP Post alert: HTTPConnectionPool(host='someurl', port=9000): Read timed out. (read timeout=120)"
          ]
        },
        "sort" : [
          1606330349994
        ]
      }

**Comment by nsano-rururu** [comment]
No one answers. Search for past issues.

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert. 
https://github.com/jertel/elastalert
