### ISSUE TITLE
AttributeError: module 'yaml' has no attribute 'FullLoader'---centos8.1 with elastalert-0.2.4

### ISSUE THREAD

**Issue by snailair** [Yelp/elastalert#3063]
# elastalert-create-index --config config.yaml
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 11, in <module>
    load_entry_point('elastalert==0.2.4', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/create_index.py", line 195, in main
    data = yaml.load(config_file, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

env：
centos8
elk-7.10.0
elastalert-0.2.4

I am using python3 that comes with centos8.1.1911

**Comment by nsano-rururu** [comment]
pip install PyYAML>=5.1

**Comment by nsano-rururu** [comment]
By the way, you installed it by the following operation. That should install PyYAML as well.

```
git clone https://github.com/Yelp/elastalert.git

# Install the module:
pip install "setuptools>=11.3"
python setup.py install
```

**Comment by snailair** [comment]
thanks!
I have resolved
i remove the centos8.1 python3
and i Compile install python3 ,Use the following command

`tar xf Python-3.6.8.tar.xz
yum -y install wget sqlite-devel xz gcc automake zlib-devel openssl-devel epel-release
cd Python-3.6.8/
./configure && make && make install`

**Comment by nsano-rururu** [comment]
For CentOS 8

```
sudo dnf group install "Development Tools"
sudo dnf install python36 python3-devel python3-setuptools python3-libs python3-pip libffi-devel openssl-devel

# Python3.6 Create virtual environment
python3 -m venv ~/py36/

# Python3.6 Virtual environment switching
source ~/py36/bin/activate
```

**Comment by nsano-rururu** [comment]
Please close if resolved

**Comment by nsano-rururu** [comment]
Yelp/elastalert is no longer maintained. Please use jertel/elastalert2.
https://github.com/jertel/elastalert2
