### ISSUE TITLE
elastalert install fails

### ISSUE THREAD

**Issue by zsengineer** [Yelp/elastalert#307]
Someone posted a similar error on this but with not resolution and I was wondering if anyone has a solution to this error on the install:

TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 258, in _exit_functi                                                                             on
    info('process shutting down')
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 258, in _exit_functi                                                                             on
    info('process shutting down')
TypeError: 'NoneType' object is not callable

**Comment by chetasjoshi** [comment]
I am having the same issue. Not able to install ElastAlert due to this error. 
+1

**Comment by julienmusat** [comment]
I am having the same issue. Not able to install ElastAlert due to this error.
+1

**Comment by Khezen** [comment]
**Upgrading** **python** to **2.7.9** seems to fixed it.
