### ISSUE TITLE
unsupported operand type(s) for +: 'datetime.datetime' and 'dict'

### ISSUE THREAD

**Issue by wajika** [Yelp/elastalert#3103]
Do I need to change anything?

```
name: test
type: frequency
index: apm-*-transaction-*
exponential_realert:
  hours: 1
num_events: 10
timeframe:
  minutes: 1
summary_table_fields:
  - "@timestamp"
aggregation_key: "service.name"
filter:
- term:
    http.response.status_code: "200"
alert:
- debug
alert_text_type: aggregation_summary_only
```

```
2021-01-21 15:10:49,021     INFO        elasticsearch GET http://192.168.10.145:9200/elastalert_status_test/_search?size=1 [status:200 request:0.004s]
2021-01-21 15:10:49,023    ERROR                 root Traceback (most recent call last):
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/elastalert.py", line 1269, in handle_rule_execution
    num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime'))
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/elastalert.py", line 949, in run_rule
    self.add_aggregated_alert(match, rule)
  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/elastalert.py", line 1807, in add_aggregated_alert
    alert_time = ts_now() + rule['aggregation']
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'dict'

2021-01-21 15:10:49,023    ERROR                 root Uncaught exception running rule test: unsupported operand type(s) for +: 'datetime.datetime' and 'dict'
2021-01-21 15:10:49,023     INFO           elastalert Skipping writing to ES: {'message': "Uncaught exception running rule test: unsupported operand type(s) for +: 'datetime.datetime' and 'dict'", 'traceback': ['Traceback (most recent call last):', '  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/elastalert.py", line 1269, in handle_rule_execution', "    num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime'))", '  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/elastalert.py", line 949, in run_rule', '    self.add_aggregated_alert(match, rule)', '  File "/usr/local/python36/lib/python3.6/site-packages/elastalert/elastalert.py", line 1807, in add_aggregated_alert', "    alert_time = ts_now() + rule['aggregation']", "TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'dict'"], 'data': {'rule': 'test'}}

```

**Comment by nsano-rururu** [comment]
The following pull requests that have not yet been merged may be relevant
https://github.com/Yelp/elastalert/pull/2759

**Comment by wajika** [comment]
> The following pull requests that have not yet been merged may be relevant
> #2759
> 
> Currently, it is hardly maintained, so it seems unlikely that it will be merged.

Is there no other solution?

**Comment by nsano-rururu** [comment]
Do not know

**Comment by nsano-rururu** [comment]
No one answers. Search for past issues.

**Comment by nsano-rururu** [comment]
Few people answer elastalert issues anymore, so if you can't find past issues or do something about yourself, I think you should consider another tool.

**Comment by nsano-rururu** [comment]
Why don't you look it up yourself when you can find it?
https://github.com/Yelp/elastalert/issues/1727

**Comment by wajika** [comment]
> Why don't you look it up yourself when you can find it?
> #1727

I found this issue, but the problem is different

**Comment by nsano-rururu** [comment]
You shouldn't expect support from oss.

**Comment by nsano-rururu** [comment]
You shouldn't expect support from oss.

**Comment by nsano-rururu** [comment]
When fixing the program
Execute the process where the error occurs only in the case of datetime type

elastalert/elastalert.py

before

```
alert_time = ts_now() + rule['aggregation']
```

after


```
if isinstance(rule['aggregation'], datetime):
   alert_time = ts_now() + rule['aggregation']
```

**Comment by nsano-rururu** [comment]
elastalert/elastalert.py ・・・elastalert 0.2.4

「alert_time = ts_now() + rule['aggregation']」 is error

```
if rule.get('aggregate_by_match_time', False):
    match_time = ts_to_dt(lookup_es_key(match, rule['timestamp_field']))
    alert_time = match_time + rule['aggregation']
else:
    alert_time = ts_now() + rule['aggregation']
```

Specify aggregation
https://elastalert.readthedocs.io/en/latest/ruletypes.html#aggregation

example1

```
aggregation:
  hours: 2
```

example2

```
aggregation:
  schedule: '2 4 * * mon,fri'
```
