### ISSUE TITLE
New member

### ISSUE THREAD

**Issue by DoDuyen162000** [Yelp/elastalert#3232]
Hi. I am having problems creating elastalert in Elasticsearch. When I use the elastalert-create-index command it gives me the error:
root@elk-virtual-machine:~/elastalert# elastalert-create-index
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jsonschema>=3.0.2' distribution was not found and is required by elastalert
root@elk-virtual-machine:~/elastalert# python -m pip install urllib3[brotli]
/usr/bin/python: No module named pip

**Comment by nsano-rururu** [comment]
elastalert is not maintained. I'm not sure if the developers are alive, but the project is definitely dead.

>Recent changes: As of Elastalert 0.2.0, you must use Python 3.6. Python 2 will not longer be supported.

Doesn't work with python 2.7

**Comment by nsano-rururu** [comment]
You should only use elastalert if you can resolve past issues yourself.

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/3178

**Comment by himaniraghav3** [comment]
Hi! Looks like jsonschema>=3.0.2 was not installed during the setup. Try a `pip install` for the same.

**Comment by nsano-rururu** [comment]
If you don't need help, use elastalert. Use [elastalert2](https://github.com/jertel/elastalert2/discussions) if you need help.
