### ISSUE TITLE
problem when running verbose

### ISSUE THREAD

**Issue by bambangithub** [Yelp/elastalert#3235]
hi everyone,

```
root@Lab-ELK:/etc/elastalert# python3.8 -m elastalert.elastalert --verbose --rule sshtele.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/etc/elastalert/elastalert/elastalert.py", line 30, in <module>
    from .alerts import DebugAlerter
  File "/etc/elastalert/elastalert/alerts.py", line 26, in <module>
    from jira.client import JIRA
  File "/usr/local/lib/python3.8/dist-packages/jira/__init__.py", line 10, in <module>
    from jira.client import Comment  # noqa: E402
  File "/usr/local/lib/python3.8/dist-packages/jira/client.py", line 225
    validate=False, get_server_info=True, async=False, logging=True, max_retries=3, proxies=None,
                                          ^
SyntaxError: invalid syntax
```
what's wrong

**Comment by nsano-rururu** [comment]
```sh
pip uninstall jira
pip install 'jira>=2.0.0'
```

**Comment by nsano-rururu** [comment]
What happened after that? If it is resolved, please close it.

**Comment by nsano-rururu** [comment]
Is this repository a problem for users?

**Comment by nsano-rururu** [comment]
```
pip uninstall jira
pip install 'jira>=2.0.0'
```

**Comment by ikram-bn** [comment]
Hi, I had the same problem as you.
 please if you find a solution you can help me 
 thanks
