### ISSUE TITLE
elastalert-create-index problem | 2022

### ISSUE THREAD

**Issue by AARSH-JAWA** [Yelp/elastalert#3244]
Getting this error when I'm trying to use this command: elastalert-create-index 

isg-team@isg-machine:~/elastalert$ elastalert-create-index
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/isg-team/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/home/isg-team/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/isg-team/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/isg-team/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/isg-team/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/isg-team/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'elastalert==0.2.4' distribution was not found and is required by the application

**Comment by AARSH-JAWA** [comment]
Using:
Python 3.8.0 
Ubuntu 18.04.6 LTS

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/3178

**Comment by nsano-rururu** [comment]
Not compatible with python3.8

**Comment by nsano-rururu** [comment]
yelp/elastalert is unmaintained

**Comment by nsano-rururu** [comment]
Use yelp / elastalert only if you can self-solve

**Comment by nsano-rururu** [comment]
Please close

**Comment by AARSH-JAWA** [comment]
okay, so if it's not compatible with python3.8 and I'm using Ubuntu 18.04.6 LTS, 
Which Python and Elastalert Version would work properly??

**Comment by nsano-rururu** [comment]
I think it works with python 3.8, but the README says python 3.6. Please read the README and documentation yourself.

**Comment by nsano-rururu** [comment]
Please close

**Comment by AARSH-JAWA** [comment]
okay thanks

**Comment by nsano-rururu** [comment]
If you want something that also supports python 3.6 or later, consider using elastalert2.
https://github.com/jertel/elastalert2
