### ISSUE TITLE
elastalert test rule command error

### ISSUE THREAD

**Issue by 1998729** [Yelp/elastalert#3269]
$ elastalert-test-rule frequency.yaml
Traceback (most recent call last):
  File "/home/yuzongyang/python/env/elastalert/bin/elastalert-test-rule", line 33, in <module>
    sys.exit(load_entry_point('elastalert==0.2.4', 'console_scripts', 'elastalert-test-rule')())
  File "/home/yuzongyang/python/env/elastalert/bin/elastalert-test-rule", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/yuzongyang/python/env/elastalert/lib/python3.6/site-packages/importlib_metadata-5.0.0-py3.6.egg/importlib_metadata/__init__.py", line 207, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yuzongyang/python/env/elastalert/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/test_rule.py", line 15, in <module>
    from elastalert.config import load_conf
  File "/home/yuzongyang/python/env/elastalert/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/config.py", line 9, in <module>
    from . import loaders
  File "/home/yuzongyang/python/env/elastalert/lib/python3.6/site-packages/elastalert-0.2.4-py3.6.egg/elastalert/loaders.py", line 9, in <module>
    import jsonschema
  File "/home/yuzongyang/python/env/elastalert/lib/python3.6/site-packages/jsonschema-4.16.0-py3.6.egg/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/home/yuzongyang/python/env/elastalert/lib/python3.6/site-packages/jsonschema-4.16.0-py3.6.egg/jsonschema/_format.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

**Comment by 1998729** [comment]
python upgrade 3.7 closed
