### ISSUE TITLE
Facing issue with MS teams while using Power automate feature

### ISSUE THREAD

**Issue by ratnakumarchukkapalli** [Yelp/elastalert#3306]
Facing issue with MS teams while using Power automate feature.

I have created Workflow and copied the webhook. I have used Microsoft Power automate feature for sending alerts [[https://elastalert2.readthedocs.io/en/latest/alerts.html#microsoft-teams
feature ](https://elastalert2.readthedocs.io/en/latest/alerts.html#microsoft-power-automate)](https://elastalert2.readthedocs.io/en/latest/alerts.html#microsoft-power-automate)

Below is the configuration I have used for sending alerts using power automate but getting below error. Can anyone please help me to configure

alert:
  - ms_power_automate
ms_power_automate_alert_summary: "Bets on the Roulette Germany table have decreased below the threshold of 2 in the last 10 minutes."
ms_power_automate_webhook_url: >-
  https://prod-41.westeurope.logic.azure.com:443/workflows/b2f95016ec1b444ab3718badf68a5bd4/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=A072idGph7a5-1trJazMH3JRVd_5YlH6mmyXqDaylpA
ms_power_automate_alert_facts:
  - name: Team
    value: DM Team
  - name: Level
    value: Critical

elastalert.util.EAException: Error initiating alert ['ms_power_automate']: Could not import module ms_power_automate: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/elastalert/elastalert.py", line 1916, in main
    client = ElastAlerter(args)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/elastalert/elastalert.py", line 128, in __init__
    self.rules = self.rules_loader.load(self.conf, self.args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/elastalert/loaders.py", line 184, in load
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file rules/exceptions.yaml: Error initiating alert ['ms_power_automate']: Could not import module ms_power_automate: not enough values to unpack (expected 2, got 1)

**Comment by ratnakumarchukkapalli** [comment]
Team any help on this
