### ISSUE TITLE
Custom class is not recognized as subclass of RuleType

### ISSUE THREAD

**Issue by modprobe** [Yelp/elastalert#386]
I wrote a custom rule type that is a direct subclass of `ruletypes.SpikeRule`:

``` python
from ruletypes import SpikeRule
[…]

class ALSpike(SpikeRule):
    required_options = fronzenset(['timeframe', 'spike_height', 'spike_type'])

    def __init__(self, *args):
        super(ALSpike, self).__init__(*args)

    […]
```

As `SpikeRule` inherits directly from `RuleType`, and `issubclass(…)` returns True for indirect subclasses, I can't see a reason why this should fail, however:

```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.0.55', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.55-py2.7.egg/elastalert/test_rule.py", line 289, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.55-py2.7.egg/elastalert/test_rule.py", line 284, in run_rule_test
    self.run_elastalert(rule_yaml, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.55-py2.7.egg/elastalert/test_rule.py", line 197, in run_elastalert
    load_modules(rule)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.55-py2.7.egg/elastalert/config.py", line 245, in load_modules
    raise EAException('Rule module %s is not a subclass of RuleType' % (rule['type']))
elastalert.util.EAException: Rule module <class 'elastalert_modules.custom_spike.ALSpike'> is not a subclass of RuleType
```

What am I missing here?

**Comment by Qmando** [comment]
What is ``type`` set to in the rule? Perhaps get_module is not returning the correct object.

 Can you insert ``import pdb; pdb.set_trace()`` above this line https://github.com/Yelp/elastalert/blob/master/elastalert/config.py#L242 and see what rule['type'] is at that point?

**Comment by modprobe** [comment]
`rule['type']` *seems* to be set correctly:
```python
(Pdb) rule['type']
<class 'elastalert_modules.custom_spike.McoinsSpike'>
```
Still:
```python
(Pdb) issubclass(rule['type'], ruletypes.RuleType)
False
```

But it gets weirder:

```python
(Pdb) rule['type'].__bases__
(<class 'ruletypes.SpikeRule'>,)
(Pdb) issubclass(rule['type'].__bases__[0], ruletypes.RuleType)
False
(Pdb) issubclass(ruletypes.SpikeRule, ruletypes.RuleType)
True
```

Maybe I'm on the wrong path here, but to me that makes no sense at all. I'm simply at my knowledge's end.
