### ISSUE TITLE
ERROR: string indices must be integers and 400 errors

### ISSUE THREAD

**Issue by tomwganem** [Yelp/elastalert#398]
Keep running into this error when trying to run elastalert with a single rule

```bash
WARNING:elasticsearch:GET /elastalert_status/elastalert/_search?size=1000 [status:400 request:0.020s]
WARNING:elasticsearch:GET /elastalert_status/elastalert_status/_search?_source_include=endtime%2Crule_name&size=1 [status:400 request:0.007s]
ERROR:root:Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 732, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/opt/elastalert/elastalert/elastalert.py", line 507, in run_rule
    self.set_starttime(rule, endtime)
  File "/opt/elastalert/elastalert/elastalert.py", line 455, in set_starttime
    last_run_end = self.get_starttime(rule)
  File "/opt/elastalert/elastalert/elastalert.py", line 444, in get_starttime
    self.handle_error('Error querying for last run: %s' % (e), {'rule': rule['name']})
  File "build/bdist.linux-x86_64/egg/elasticsearch/exceptions.py", line 55, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers

ERROR:root:Uncaught exception running rule flatline-resque-update-package-statuses: string indices must be integers
```
The rule in question
```yaml
name: flatline-resque-update-package-statuses
type: flatline
es_host: ops-elasticsearch.service.internal.domain.com
es_port: 31313
index: logstash-*
threshold: 10
timeframe:
  minutes: 1

realert:
  minutes: 5

filter:
- query:
   query_string:
     analyze_wildcard: true
     query: UpdatePackageStatuses
alert:
 - email
 - hipchat
hipchat_auth_token: 999999
hipchat_room_id: 999999
email:
- tganem@asperasoft.com
```

**Comment by tomwganem** [comment]
Turns out, the cause of my issue was that when building elastalert, the latest elasticsearch-py lib was being downloaded and installed, which was in conflict with the version of elasticsearch that we're running(1.7.0). Modifying the `'elasticsearch'` dependecy  in setup.py with `elasticsearch<=1.7.0` resolved the issue.

**Comment by bean5** [comment]
I saw this as well, recently. I only see it in one of my dockerized instances. As they are dockerized, I don't have a clean way to modify `setup.py` before using it. Making sure to use elasticsearch version 2.4.2 seems to have fixed the problem. If using 2.4 isn't specified as a requirement, documentation needs to be updated.
