### ISSUE TITLE
ERROR:root:Error writing alert info to elasticsearch: TransportError(400, u'illegal_argument_exception')

### ISSUE THREAD

**Issue by anhlqn** [Yelp/elastalert#399]
I'm running ElastAlert 0.0.70 and Elasticsearch 2.2.0. ElastAlert used to work fine with Elasticsearch 2.0.0. After upgrading to ES 2.2.0, I got this error when running ElastAlert.
```
WARNING:elasticsearch:POST /elastalert_status/silence?op_type=create [status:400 request:0.239s]
ERROR:root:Error writing alert info to elasticsearch: TransportError(400, u'illegal_argument_exception')
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.70-py2.6.egg/elastalert/elastalert.py", line 962, in writeback
    doc_type=doc_type, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 230, in create
    return self.index(index, doc_type, body, id=id, params=params, op_type='create')
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 261, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

```
and below are from ES log

```
2016-02-16 09:51:14,699][DEBUG][action.index             ] [ESNode01] failed to execute [index {[elastalert_status][silence][AVLrNSQgnk5gJgheqV0Z], source[{"rule_name": "any_high_time-taken", "@timestamp": "2016-02-16T17:48:27.323731Z", "exponent": 0, "until": "2016-02-16T17:53:27.323717Z"}]}] on [[elastalert_status][0]]
java.lang.IllegalArgumentException: Mapper for [@timestamp] conflicts with existing mapping in other types:
[mapper [@timestamp] is used by multiple types. Set update_all_types to true to update [format] across all types.]
	at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:170)
	at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:402)
	at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:411)
	at org.elasticsearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:390)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:261)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[2016-02-16 09:51:14,699][INFO ][rest.suppressed          ] /elastalert_status/silence Params: {index=elastalert_status, op_type=create, type=silence}
RemoteTransportException[[ESNode01][192.168.1.10:9300][indices:data/write/index[p]]]; nested: IllegalArgumentException[Mapper for [@timestamp] conflicts with existing mapping in other types:
[mapper [@timestamp] is used by multiple types. Set update_all_types to true to update [format] across all types.]];
Caused by: java.lang.IllegalArgumentException: Mapper for [@timestamp] conflicts with existing mapping in other types:
[mapper [@timestamp] is used by multiple types. Set update_all_types to true to update [format] across all types.]
	at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:170)
	at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:402)
	at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:411)
	at org.elasticsearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:390)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:261)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
I've checked mappings for elastalert_status index, and every type uses the same format for @timestamp
```
"@timestamp": {
            "type": "date",
            "format": "dateOptionalTime"
```
Will upgrading to ElastAlert 0.0.75 fix the issue? I guess it has something to do with @timestamp format in ES 2.2.0.

**Comment by jraby** [comment]
I think this was fixed in https://github.com/Yelp/elastalert/commit/2ae777e551970b7efdb698f678a490f22d869133

I think you will need to add @timestamp to silence_mapping and error_mapping in elasticsearch.

**Comment by anhlqn** [comment]
Thanks @jraby . I run ElastAlert in an offline environment, so I don't have a chance to update to latest version regularly. I did manually make changes to create_index.py but haven't test it out yet. Instead I updated mappings for current index, and it seemed to work fine now. 
```
PUT elastalert_status/_mapping/silence
{
  "properties": {
    "@timestamp": {
      "type": "date",
      "format": "dateOptionalTime"
    }
  }
}

PUT elastalert_status/_mapping/elastalert_error
{
  "properties": {
    "@timestamp": {
      "type": "date",
      "format": "dateOptionalTime"
    }
  }
}
```
