### ISSUE TITLE
Starting ElastAlert

### ISSUE THREAD

**Issue by Gmanweb** [Yelp/elastalert#416]
Hi 

How do I run elastalert, I did run `python -m elastalert.elastalert --verbose --rule example_rules/example_frequency.yaml` but when I 'Ctrl c' it stops. I would like it to run all the time. Am I missing something?

**Comment by Gmanweb** [comment]
I did try` python -m elastalert.elastalert --verbose --rule example_rules/example_frequency.yaml &` and it seem to be running but I know this is not correct. 

On the elastalert docs [Running ElastAlert | http://elastalert.readthedocs.org/en/latest/running_elastalert.html#running-elastalert] it say to run ElasticAlert as a daemon using [Supervisord | http://supervisord.org/]. This is where I am kinda stuck and experience comes in handy. 

on the supervisord doc  [Installing a Distribution Package | http://supervisord.org/installing.html#installing-a-distribution-package] 

> Use the package management tools of your distribution to check availability, on CentOS you can run `yum info supervisor`

when yum info supervisor is run, I get

```
Loaded plugins: priorities, update-motd, upgrade-helper Error: 
No matching Packages to list
```

After that I ran 
`pip install supervisor `
which returns 

```
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2912, in <module>

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2898, in _call_aside

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 644, in _build_master

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 657, in _build_from_requirements

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 830, in resolve

pkg_resources.DistributionNotFound: The 'pip==6.1.1' distribution was not found and is required by the application
```

Also I did try 

`yum install supervisor`

which returns 

```
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main/latest                                                                                       | 2.1 kB     00:00
amzn-updates/latest                                                                                    | 2.3 kB     00:00
No package supervisor available.
Error: Nothing to do
```

Any idea what the errors are and how I can get this to run.

**Comment by Qmando** [comment]
A really easy way might be to run it in screen or tmux.
