### ISSUE TITLE
Using timestamp_field to replace @timestamp field

### ISSUE THREAD

**Issue by mzamora717** [Yelp/elastalert#426]
Hi, I have logs that don't use the label "@timestamp". Instead, the field name is "dt".
How and where do I configure my rule so that ElastAlert uses "dt" instead of "@timestamp"?
I've tried the following but it doesn't work:

name: Check Atlas Logs for 'Could not load items into queue' logs
description: This alert requires action from Operations. There are items that could not be loaded into queues. Please check the attached Kibana link to view logs.
type: frequency
index: atlas*
timestamp_field: dt
num_events: 10
timeframe:
  minutes: 5
filter:
- query:
    query_string:
      query: "message:\"ASP.NET session has expried or could not be found\""

alert: "email"
alert_subject: "CRITICAL: [PROD-NA11] - 'Could not load items into queue' logs are occurring. Check attached link."
email: "mzamora@springcm.com"

**Comment by Qmando** [comment]
timestamp_field is how you configure it. What do you mean by "it doesn't work"? Do have logs which show that it ran over the correct time period and got no hits? Have you tried using ``elastalert-test-rule``?

**Comment by mzamora717** [comment]
I've ran elastalert-test-rule example_rules/example_frequency.yaml  and this is what I get:

**NOTE that my index name is atlas*. I've tested this rule against logstash-* indices where the @timestamp field DOES exist, and the rule works correctly. Its only when I test the rule against the atlas* indices where the @timestamp field does not exist, do I get this error below:

Successfully loaded Check Atlas Logs for 'Could not load items into queue' logs

INFO:urllib3.connectionpool:Starting new HTTP connection (1): logselasticprodna11-lb1.atlas.cm.com
WARNING:elasticsearch:GET http://logselasticprodna11-lb1.atlas.cm.com:8081/atlas*/_search?ignore_unavailable=true&size=1 [status:N/A request:10.315s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 67, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 493, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 324, in _make_request
    self, url, "Read timed out. (read timeout=%s)" % read_timeout)
ReadTimeoutError: HTTPConnectionPool(host='logselasticprodna11-lb1.atlas.cm.com', port=8081): Read timed out. (read timeout=10)
Error running your filter:
ConnectionTimeout('TIMEOUT', "HTTPConnectionPool(host='logselasticprodna11-lb1.atlas.cm.com', port=8081): Read timed out. (read timeout=10)", ReadTimeoutError("HTTPConnectionPool(host='logselasticprodna11-lb1.atlas.cm.com', port=8081): Read timed out. (read timeout=10)",))
INFO:urllib3.connectionpool:Starting new HTTP connection (1): logselasticprodna11-lb1.atlas.cm.com
WARNING:elasticsearch:GET http://logselasticprodna11-lb1.atlas.cm.com:8081/atlas*/_search?_source_include=dt%2C%2A&ignore_unavailable=true&size=10000 [status:N/A request:10.253s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 67, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 493, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 324, in _make_request
    self, url, "Read timed out. (read timeout=%s)" % read_timeout)
ReadTimeoutError: HTTPConnectionPool(host='logselasticprodna11-lb1.atlas.cm.com', port=8081): Read timed out. (read timeout=10)
ERROR:root:Error running query: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='logselasticprodna11-lb1.atlas.cm.com', port=8081): Read timed out. (read timeout=10))

Would have written the following documents to elastalert_status:

elastalert_error - {'message': "Error running query: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='logselasticprodna11-lb1.atlas.cm.com', port=8081): Read timed out. (read timeout=10))", 'traceback': ['Traceback (most recent call last):', '  File "/usr/lib/python2.7/site-packages/elastalert-0.0.75-py2.7.egg/elastalert/elastalert.py", line 279, in get_hits', "    res = self.current_es.search(index=index, size=rule['max_query_size'], body=query, ignore_unavailable=True, **extra_args)", '  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 498, in search', '    params=params, body=body)', '  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 301, in perform_request', '    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)', '  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 75, in perform_request', "    raise ConnectionTimeout('TIMEOUT', str(e), e)", "ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='logselasticprodna11-lb1.atlas.cm.com', port=8081): Read timed out. (read timeout=10))"], 'data': {'rule': "Check Atlas Logs for 'Could not load items into queue' logs"}}

**Comment by Qmando** [comment]
If you have too many indexes matching "atlas*", your queries are likely to timeout because it's querying every single shard. Try using something like:
```
index: atlas-%Y.%m.%d
use_strftime_index: true
```

**Comment by mzamora717** [comment]
I don't have many indices matching "atlas*", just 14 open at any point in
time. However, they are large. Each index is about 50GB to 100GB in size.
I did make the change you recommended and it works now. Thanks!!

On Fri, Mar 11, 2016 at 12:33 PM Quentin Long <notifications@github.com>
wrote:

> If you have too many indexes matching "atlas*", your queries are likely to
> timeout because it's querying every single shard. Try using something like:
>
> index: atlas-%Y.%m.%d
> use_strftime_index: true
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yelp/elastalert/issues/426#issuecomment-195490802>.
>
-- 

Melanie Zamora
Application Performance Engineer
SpringCM
Springing since 2012

mzamora@springcm.com
+1.312.253.4723 <http://+1.312.253.4720/>

www.springcm.com
LinkedIn <http://www.linkedin.com/company/springcm> | Facebook
<http://www.facebook.com/SpringCMCloud> | Twitter
<https://twitter.com/springcm/>

-- 
 <https://appexchange.salesforce.com/results?keywords=springcm>
