### ISSUE TITLE
NoneType object has no attribute strip

### ISSUE THREAD

**Issue by jurgenhaas** [Yelp/elastalert#433]
Using Elasticsearch 2.2 on Ubuntu 14.04 I just installed ElastAlert and followed all instructions from ReadTheDocs. When I want to run my first rule test, I'm getting the error

```
$ > elastalert-test-rule rules/cardinality.yaml 
Successfully loaded Cardinality rule

Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.0.75', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/test_rule.py", line 289, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/test_rule.py", line 277, in run_rule_test
    hits = self.test_file(copy.deepcopy(rule_yaml), args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/test_rule.py", line 54, in test_file
    es_client = ElastAlerter.new_elasticsearch(es_config)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/elastalert.py", line 130, in new_elasticsearch
    timeout=es_conn_conf['es_conn_timeout'])
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 150, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 113, in __init__
    self.set_connections(hosts)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 166, in set_connections
    connections = map(_create_connection, hosts)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 165, in _create_connection
    return self.connection_class(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 48, in __init__
    self.pool = pool_class(host, port=port, timeout=self.timeout, maxsize=maxsize, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 232, in __init__
    ConnectionPool.__init__(self, host, port)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 162, in __init__
    host = host.strip('[]')
AttributeError: 'NoneType' object has no attribute 'strip'
```

My config.yaml:
```
rules_folder: rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: localhost
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2
```

And my cardinality.yaml rule is this:
```
index: logstash-*
name: Cardinality rule
type: cardinality
cardinality_field: "pid"
min_cardinality: 15
timeframe:
  hours: 4
filter:
  - term:
    host: "myhostname"
alert:
  - "email"
email:
  - "me@example.com"
```

What am I doing wrong?

**Comment by Qmando** [comment]
Try adding ``es_host`` to cardinality.yaml as well.

If that fixes it, looks like this is likely a residual bug from when es_host recently went from being required in every rule to being allowed to be set globally in config.yaml. Elastalert-test-rule was originally designed to run completely independently of config.yaml, so it required each rule to have the hostname set.

**Comment by jurgenhaas** [comment]
Thanks, that fixes it.
