### ISSUE TITLE
When i want to launch elastalert

### ISSUE THREAD

**Issue by FheA** [Yelp/elastalert#435]
Hello,

It's my first post here, for my work i must install elastalert with elasticsearch.

WHen i load my rule its works, but when i want to lauch elastalert i've this error:

`elastalert --config ../config.yaml --rule test.yaml
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 9, in <module>
    load_entry_point('elastalert==0.0.75', 'console_scripts', 'elastalert')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/elastalert.py", line 1332, in main
    client = ElastAlerter(args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/elastalert.py", line 90, in __init__
    self.conf = load_rules(self.args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/config.py", line 362, in load_rules
    raise EAException('Invalid time format used: %s' % (e))
elastalert.util.EAException: Invalid time format used: type object argument after ** must be a mapping, not NoneType`

If you have an idea to help me, thanks a lot !

Have a nice day !

**Comment by kiawin** [comment]
hi @FheA what's the content of `test.yaml`?

**Comment by Qmando** [comment]
timeframe must be of the format
```
timeframe:
  hours: 4
```
or
```
timeframe:
  days: 1
```
or similar. If you don't include the spaces before days/minutes/hours/etc, it will not be parsed correctly.

**Comment by FheA** [comment]
# From example_rules/example_frequency.yaml
es_host: server url

es_port: 9200
name: Example rule
type: frequency
index: ems*
num_events: 50
timeframe:
    hours: 4
filter:
- term:
    name: "blablabla"
alert:
- "email"
email:
- "mymail@email.com"
smtp_host: smtp.fr.mysmtp.com
smtp_port: 25
timestamp_field: timestamp
writeback_index: elastalert_florian

**Comment by FheA** [comment]
Hello i come back to you !

I've this error =

`python -m elastalert.elastalert --verbose --rule test.yaml
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dhalsim/elastalert/elastalert/elastalert.py", line 1337, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/dhalsim/elastalert/elastalert/elastalert.py", line 1332, in main
    client = ElastAlerter(args)
  File "/home/dhalsim/elastalert/elastalert/elastalert.py", line 90, in __init__
    self.conf = load_rules(self.args)
  File "elastalert/config.py", line 362, in load_rules
    raise EAException('Invalid time format used: %s' % (e))
elastalert.util.EAException: Invalid time format used: type object argument after ** must be a mapping, not NoneType
`

Thanks !

**Comment by Qmando** [comment]
```
timeframe:
  hours: 4
```
whitespace is important

**Comment by cseveer** [comment]
@Qmando  Same here, I followed your comments by adding white space but no luck. Here is my TestRule.yaml

name: Example rule
type: frequency
index: myindex-*
num_events: 2

timeframe:
    hours: 10
filter:
- term:
    CalledPartyNumber: "1234567890"
alert:
- "email"
email:
- "email@company.com"
smtp_host: smtp.company.com
smtp_port: 25
timestamp_field: DISC_DATE

**Comment by Qmando** [comment]
You get ``Invalid time format used: type object argument after ** must be a mapping, not NoneType`` from that config?

It's possible that one of the other time options is messed up in the global config.yaml? Something like buffer_time or alert_time_limit?
