### ISSUE TITLE
Setting up ElastAlert on Windows 7

### ISSUE THREAD

**Issue by rameedev** [Yelp/elastalert#444]
I am trying to set elastalert on my windows 7 laptop where my development ELK stack is working. I have done the below but I am not able to get a simple test rule to fire.

Steps Followed
1) git clone https://github.com/Yelp/elastalert.git -- downloaded to local folder
2)  pip install -r requirements.txt
     (the above step completed fine except for error for supervisor package complaining about version.My python version is 3.4.2).
3) renamed config.yam.example to config.yaml and changed the below settings
    rules_folder:myrules
    run_every(minutes):1
    es_host: 127.0.0.1
    es_port: 9200 (my http port)
    use_ssl: False

4) created a sample frequency type rule and tried running the below command
    " elastalert-test-rule myrules/myrule.yaml " . When executed the command gave the below error
    ImportError: No module named 'alerts'

Please help , also if there Is any guide to set this up on windows that would be helpful.

Thanks

**Comment by Qmando** [comment]
I don't see why it shouldn't work on Windows, but I have not tested it. I don't think there's anything specific to Unix-like environments. 

However, it does require Python 2 to work.

**Comment by phermann1988** [comment]
I try the same thin on win 7.  i installed python-2.7.11 and add python as Environment variable to start with the python command. testrule didn't work on my setup, too. But i tried to start my rule with:
python -m elastalert.elastalert --verbose --rule myrule.yaml
it seemed to work but then i got this error... i think it's a problem of missing packages, what do you think @Qmando?

INFO:elastalert:Starting up
ERROR:root:Traceback (most recent call last):
  File "C:\Users\pat\elastalert\elastalert\elastalert.py", line 746, in run_all_
rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "C:\Users\pat\elastalert\elastalert\elastalert.py", line 539, in run_rule

    if not self.run_query(rule, rule['starttime'], endtime):
  File "C:\Users\pat\elastalert\elastalert\elastalert.py", line 419, in run_quer
y
    data = self.get_hits(rule, start, end, index)
  File "C:\Users\pat\elastalert\elastalert\elastalert.py", line 309, in get_hits

    elastalert_logger.info("Queried rule %s from %s to %s: %s hits" % (rule['nam
e'], pretty_ts(starttime, lt), pretty_ts(endtime, lt), len(hits)))
  File "elastalert\util.py", line 106, in pretty_ts
    return dt.strftime('%Y-%m-%d %H:%M %Z')
  File "C:\Python27\lib\site-packages\dateutil\tz.py", line 41, in inner_func
    return myfunc(*args, **kwargs).encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 11: ordinal
 not in range(128)

ERROR:root:Uncaught exception running rule Example rule: 'ascii' codec can't dec
ode byte 0xe4 in position 11: ordinal not in range(128)
INFO:elastalert:Rule Example rule disabled
INFO:elastalert:Sleeping for 59 seconds

**Comment by phermann1988** [comment]
ok fixed it by changing from CET to UTC on my computer, elastalert runs. on my german windows it's called Mitteleuropäische Zeit and i think phython has a problem with the 'ä'. is there a way to keep my timezone and running elastalert?

**Comment by Qmando** [comment]
The problem is in the dateutil library. You can add this patch to fix the problem.

https://github.com/Yelp/elastalert/issues/471#issuecomment-209657248
