### ISSUE TITLE
create_index parameters are overwritten by config

### ISSUE THREAD

**Issue by dforste** [Yelp/elastalert#448]
Normally I would expect command flags to override what is in a config file. This is not the case with create_index. 

The default config even when passing arguments fails with:
```
New index name? (Default elastalert_status)
Name of existing index to copy? (Default None)
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 9, in <module>
    load_entry_point('elastalert==0.0.75', 'console_scripts', 'elastalert-create-index')()
  File "/usr/lib/python2.7/site-packages/elastalert-0.0.75-py2.7.egg/elastalert/create_index.py", line 95, in main
    es.indices.create(index)
  File "/usr/lib/python2.7/site-packages/elasticsearch-2.3.0-py2.7.egg/elasticsearch/client/utils.py", line 69, in _wrapped
  File "/usr/lib/python2.7/site-packages/elasticsearch-2.3.0-py2.7.egg/elasticsearch/client/indices.py", line 105, in create
  File "/usr/lib/python2.7/site-packages/elasticsearch-2.3.0-py2.7.egg/elasticsearch/transport.py", line 329, in perform_request
  File "/usr/lib/python2.7/site-packages/elasticsearch-2.3.0-py2.7.egg/elasticsearch/connection/http_urllib3.py", line 105, in perform_request
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5f179b5610>: Failed to establish a new connection: [Errno -2] Name does not resolve) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5f179b5610>: Failed to establish a new connection: [Errno -2] Name does not resolve)
```
A very misleading error. Doing something as simple as printing the config may also go a long way to preventing issues like this in the future.

**Comment by dforste** [comment]
Closed by merge of https://github.com/Yelp/elastalert/pull/449
