### ISSUE TITLE
Exception in `get_top_counts` prevents alert from being sent

### ISSUE THREAD

**Issue by lchi** [Yelp/elastalert#450]
I'm using elastalert to query for HTTP 500 error codes and I'm running into an issue where an uncaught exception in `get_top_counts` is causing ElastAlert to not send the alert that was triggered (stacktrace below). Is this intentional? Currently this is a problem because we are seeing timeouts on the top counts queries and as a result not being alerted to a problem.

I can set `disable_rules_on_error` to `False` and set `notify_email` but IMO an alert should still be sent but without the alert text filled in.

I'm happy to submit a patch if the intended behavior is to send an alert even if `get_top_counts` fails for some reason.

```
WARNING:elasticsearch:GET http://<ip>:9200/logstash-*/<index>/_search?search_type=count&ignore_unavailable=true [status:N/A request:10.010s]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.6/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 304, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ReadTimeoutError: HTTPConnectionPool(host='<ip>', port=9200): Read timed out. (read timeout=10)
ERROR:root:Error running query: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='<ip>', port=9200): Read timed out. (read timeout=10))
ERROR:root:Traceback (most recent call last):
  File "/home/.../elastalert/elastalert/elastalert.py", line 867, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
  File "/home/.../elastalert/elastalert/elastalert.py", line 890, in send_alert
    counts = self.get_top_counts(rule, start, end, keys, qk=qk)
  File "/home/.../elastalert/elastalert/elastalert.py", line 1256, in get_top_counts
    buckets = self.get_hits_terms(rule, starttime, endtime, index, key, qk, number).values()[0]
AttributeError: 'NoneType' object has no attribute 'values'

ERROR:root:Uncaught exception running rule 500s check: 'NoneType' object has no attribute 'values'
INFO:elastalert:Rule 500s check disabled
```

**Comment by Qmando** [comment]
Sending the alert if it fails is probably acceptable. It would also make sense to let you increase the timeout from the default 10 seconds. This is definitely poor error handling right now.

Just a note, if you put ``notify_email: foo@example.com`` in your config.yaml, you will get a notification if any uncaught exceptions occur.
