### ISSUE TITLE
Jira Alerter + CA

### ISSUE THREAD

**Issue by 0x9090** [Yelp/elastalert#451]
We use a CA for our certificate validation, but the Jira alerter doesn't seem to pick that up.

```
###@###:/opt/elastalert$ elastalert-test-rule rules/development/linux-sudo-jira.yaml
Successfully loaded Linux Sudo Session

INFO:urllib3.connectionpool:Starting new HTTP connection (1): ###
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ###
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.0.75', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/test_rule.py", line 289, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/test_rule.py", line 284, in run_rule_test
    self.run_elastalert(rule_yaml, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/test_rule.py", line 197, in run_elastalert
    load_modules(rule)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/config.py", line 255, in load_modules
    rule['alert'] = load_alerts(rule, alert_field=rule['alert'])
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/config.py", line 313, in load_alerts
    alert_field.append(alert(rule))
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/alerts.py", line 313, in __init__
    self.client = JIRA(self.server, basic_auth=(self.user, self.password))
  File "build/bdist.linux-x86_64/egg/jira/client.py", line 195, in __init__
  File "build/bdist.linux-x86_64/egg/jira/client.py", line 1328, in server_info
  File "build/bdist.linux-x86_64/egg/jira/client.py", line 1716, in _get_json
  File "/usr/local/lib/python2.7/dist-packages/requests-2.8.1-py2.7.egg/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.8.1-py2.7.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.8.1-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.8.1-py2.7.egg/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

WGET is able complete this TLS request successfully, because it is able to find the valid certs we have. What's the best way to point ElastAlert/Requests at our CA certificate?

**Comment by Qmando** [comment]
As a hot fix, you could change https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L326 to be `` self.client = JIRA(self.server, basic_auth=(self.user, self.password), options={'verify': False})

As for actually trusting your CA, it's definitely possible in requests, but I'm not sure how to use it with jira-python.

**Comment by 0x9090** [comment]
The elastalert-test-rule routine does not seem to respect the hotfix

**Comment by scott-conrad** [comment]
@0x9090 
I ran into the same issue.  I ultimately discovered that it was because python (or at least python 2.7) uses its own CA cert bundle in **/usr/local/lib/python2.7/dist-packages/requests/cacert.pem**, instead of using the typical system bundles (usually in **/usr/share/ca-certificates** or **/usr/local/share/ca-certificates**)
This is why adding your own cert to the system has no effect on Elastalert creating a TLS connection to to your JIRA.
A temporary fix is to copy your custom CA cert to the bottom of the python bundle, or to just replace that file with a link to the system's (or your own) bundle.  After I did this, I found that Elastalert no longer had an issue creating a SSL connection to my JIRA.

**Comment by Thinkgamer** [comment]
@scott-conrad  hello，i cannot find the cacert.pem of python 2.7 and i cannot solve the problem，can you help me ,my weichat is gyt13342445911， thank you

**Comment by tarinidash** [comment]
try **pip install certifi** . this resolved my issue.

**Comment by latundetoks** [comment]
@Qmando Have the same issue on the latest build of Elastalert. Tried pip install certifi but that doesnt work either.

Cannot connect to JIRA because of certificate verification (see error logs). Is there a "verification:false" switch that can be activated for the JIRA webhook.

`WARNING:root:Got recoverable error from GET https://jiraserver/rest/api/2/serverInfo, will retry [3/3] in 0.150050454059s. Err: HTTPSConnectionPool(host='jiraserver', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))`

Ideas and suggestions would be appreciated. Thankk you

**Comment by Qmando** [comment]
@latundetoks Did you try the hotfix in https://github.com/Yelp/elastalert/issues/451#issuecomment-202636110?

**Comment by latundetoks** [comment]
@Qmando @scott-conrad @0x9090  I was able to fix this by downloading a copy of the failing intermediate CA and cert from Entrust and the server and stick it at the end of the files here. Apparently the application uses its own truststore.

/home/elastalert/venv/lib/python2.7/site-packages/pip/_vendor/requests/cacert.pem
/home/elastalert/venv/lib/python2.7/site-packages/certifi/cacert.pem

**Comment by latundetoks** [comment]
Is there a way to modify the rest api url. The requested url is not found on my server

https://jiraserver.com/rest/api/2/serverInfo (Service Elastalert is requesting)
https://jiraserver.com/jira/rest/api/2/issue (Service is running here)

`<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /rest/api/2/serverInfo was not found on this server.</p>
</body></html>
`

Thank you.

**Comment by Qmando** [comment]
@latundetoks 
Try changing ``jira_server`` to include ``/jira`` at the end

```
jira_server: https://jiraserver.com/jira
```
