### ISSUE TITLE
LocationParseError exception

### ISSUE THREAD

**Issue by vchav73** [Yelp/elastalert#457]
I am getting the following when testing an example rules file on a CentOS 6.6 installation:

>[root@Analytics example_rules]# elastalert-test-rule example_change.yaml 
Successfully loaded New country login
>
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.0.75', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.0.75-py2.7.egg/elastalert/test_rule.py", line 289, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.0.75-py2.7.egg/elastalert/test_rule.py", line 277, in run_rule_test
    hits = self.test_file(copy.deepcopy(rule_yaml), args)
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.0.75-py2.7.egg/elastalert/test_rule.py", line 54, in test_file
    es_client = ElastAlerter.new_elasticsearch(es_config)
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.0.75-py2.7.egg/elastalert/elastalert.py", line 130, in new_elasticsearch
    timeout=es_conn_conf['es_conn_timeout'])
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 150, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 113, in __init__
    self.set_connections(hosts)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 166, in set_connections
    connections = map(_create_connection, hosts)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 165, in _create_connection
    return self.connection_class(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 48, in __init__
    self.pool = pool_class(host, port=port, timeout=self.timeout, maxsize=maxsize, **kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 144, in __init__
    ConnectionPool.__init__(self, host, port)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 70, in __init__
    raise LocationParseError(host)
urllib3.exceptions.LocationParseError: Failed to parse: None

My config.yaml is:

>rules_folder: /etc/elastalert/rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: localhost
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2

I've confirmed that Elasticsearch is running:

>[root@Analytics example_rules]# curl -XGET 'http://localhost:9200/_count?pretty' -d '{"query": {"match_all": {}}}'
{
  "count" : 3909430,
  "_shards" : {
    "total" : 236,
    "successful" : 236,
    "failed" : 0
  }
}

Any ideas why this is happening?

**Comment by Qmando** [comment]
Do you have ``es_host`` set in your rule? It looks like it's trying to use ``None`` as the host, which makes me think it is not parsing the yaml correctly or you have ``es_host:`` set without a value somewhere.

**Comment by vchav73** [comment]
I did not have es_host set in my rule. I was following the directions at the link below and assumed it would carry over from the config.yaml file. Thanks for your help!

http://elastalert.readthedocs.org/en/latest/running_elastalert.html#requirements

**Comment by Qmando** [comment]
It does carry over from config.yaml. Did your issue get resolved? What did you do?

**Comment by Qmando** [comment]
It does carry over, but only if ``es_host`` is completely missing, not just unset.

**Comment by vchav73** [comment]
I see. Thanks for the explanation. I had not set the `es_host` value in the example file I made, and was not using the config.yaml file shown in the example.
