### ISSUE TITLE
ElastAlert time field error running the rule

### ISSUE THREAD

**Issue by PhoenixGuru** [Yelp/elastalert#467]
Elastalert throws an error when the timestamp_field specified in the yaml is named 'time'.

`ERROR:root:Traceback (most recent call last):
  File "/home/ubuntu/elastalert/elastalert/elastalert.py", line 892, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
  File "/home/ubuntu/elastalert/elastalert/elastalert.py", line 965, in send_alert
    alert.alert(matches)
  File "/home/ubuntu/elastalert/elastalert/alerts.py", line 230, in alert
    body = self.create_alert_body(matches)
  File "/home/ubuntu/elastalert/elastalert/alerts.py", line 166, in create_alert_body
    body += unicode(BasicMatchString(self.rule, match))
  File "/home/ubuntu/elastalert/elastalert/alerts.py", line 100, in __str__
    self._add_rule_text()
  File "/home/ubuntu/elastalert/elastalert/alerts.py", line 56, in _add_rule_text
    self.text += self.rule['type'].get_match_str(self.match)
  File "/home/ubuntu/elastalert/elastalert/ruletypes.py", line 473, in get_match_str
    ts = match[self.rules['timestamp_field']]
KeyError: 'time'`

```
# Rule name, must be unique
name: impr-flatline

# (Required)
# Type of alert.
# the change rule will alert when a certain field changes in two documents within a timeframe
type: flatline

# (Required)
# Index to search, wildcard supported
index: logstash-impr-*
timestamp_field: time
threshold: 100

use_count_query: true
doc_type: impr

```

Was working fine with older version.

**Comment by Qmando** [comment]
Do you know which version it worked with?
I'll look into this bug.
If possible, could you print what is in match right before that error?
+ ``elastalert_logger.info(match)``
Curious to see if it's got ``@timestamp`` or just nothing.
