### ISSUE TITLE
UnicodeDecodeError: Response from ES cannot be parsed?

### ISSUE THREAD

**Issue by bjung82** [Yelp/elastalert#471]
ES is reachable, but i think the response contains some Unicode-Characters. Is this case not handled by elastalert?

Any hints welcome :-)

ERROR:root:Traceback (most recent call last):
  File "d:\tools\Python27\lib\site-packages\elastalert-0.0.77-py2.7.egg\elastalert\elastalert.py", line 746, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "d:\tools\Python27\lib\site-packages\elastalert-0.0.77-py2.7.egg\elastalert\elastalert.py", line 539, in run_rule
    if not self.run_query(rule, rule['starttime'], endtime):
  File "d:\tools\Python27\lib\site-packages\elastalert-0.0.77-py2.7.egg\elastalert\elastalert.py", line 419, in run_query
    data = self.get_hits(rule, start, end, index)
  File "d:\tools\Python27\lib\site-packages\elastalert-0.0.77-py2.7.egg\elastalert\elastalert.py", line 309, in get_hits
    elastalert_logger.info("Queried rule %s from %s to %s: %s hits" % (rule['name'], pretty_ts(starttime, lt), pretty_ts(endtime, lt), len(hits)))
  File "d:\tools\Python27\lib\site-packages\elastalert-0.0.77-py2.7.egg\elastalert\util.py", line 106, in pretty_ts
    return dt.strftime('%Y-%m-%d %H:%M %Z')
  File "build\bdist.win32\egg\dateutil\tz\_common.py", line 14, in adjust_encoding
    name = name.encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 11: ordinal not in range(128)

ERROR:root:Uncaught exception running rule Benni_Rule: 'ascii' codec can't decode byte 0xe4 in position 11: ordinal not in range(128)

**Comment by Qmando** [comment]
This looks like another case of https://github.com/Yelp/elastalert/issues/247. The underlying issue is that the timezone contains unicode characters and dateutil doesn't like that. I've got a version of dateutil pinned that has this bug https://bugs.launchpad.net/dateutil/+bug/1087306/+activity.

If you manually downgrade the dateutil package to 1.5, it should work.

**Comment by bjung82** [comment]
Thank you very much for your answer. How can I "pin" dateutil package to 1.5. and create
a new exe?

I'm a java gui, and was quite happy after I got a working elastalert.exe using easy_install ;-)
Pip didn't worked out too well on windows, and I'm behind a corporate proxy with a self_signed
certificate etc. Quite hard to get the stuff running. But elastalert looks very cool :-)

**Comment by Qmando** [comment]
Not sure about the first question. Never tried running elastalert on windows. But, I will fix the dateutil package and push a new version out to pypi today.

**Comment by bjung82** [comment]
Hi!

I just cloned from Master, the DateUtil dependency is set to 1.5 now.
But I cannot start this new version of elastalert, because "botocore" needs a more recent version
of DateUtil?

Regards
Benjamin

e:\tools\Python27\Scripts>elastalert
Traceback (most recent call last):
  File "e:\tools\Python27\Scripts\elastalert-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "E:\tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 3084, in <module>
    @_call_aside
  File "E:\tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "E:\tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "E:\tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "E:\tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "E:\tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 1.5 (e:\tools\python27\lib\site-packages\python_dateutil-1.5-py2.7.egg), Requirement.parse('python-dateutil<3.0.0,>=2.1'), set(['botocore']))

**Comment by Qmando** [comment]
Ah, crap. I'm gonna have to start making things extras. I'm gonna have to revert this for now and then deal with this later. There is a hotfix for this issue:

```
diff --git a/elastalert/util.py b/elastalert/util.py
index de67126..4fb7525 100644
--- a/elastalert/util.py
+++ b/elastalert/util.py
@@ -98,6 +98,7 @@ def pretty_ts(timestamp, tz=True):
     """Pretty-format the given timestamp (to be printed or logged hereafter).
     If tz, the timestamp will be converted to local time.
     Format: MM-DD HH:MM TZ"""
+    return timestamp
```

**Comment by bjung82** [comment]
Thanks, this hotfix fixed my issue :-)
