### ISSUE TITLE
Fails to run elastalert-create-index with python 3

### ISSUE THREAD

**Issue by ThomasdOtreppe** [Yelp/elastalert#479]
Using Ubuntu 16.04 64 bit, v0.0.79 (issue is also present in v0.0.77) and python 3, installation (```python3 setup.py install```) was successful.

However, running ```elastalert-create-index``` shows fails with the following exception:
```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 9, in <module>
    load_entry_point('elastalert==0.0.79', 'console_scripts', 'elastalert-create-index')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/elastalert-0.0.79-py3.5.egg/elastalert/create_index.py", line 14, in <module>
    from auth import Auth
ImportError: No module named 'auth'
```

There seems to be a missing dependency (that isn't checked at installation time) but I can't find the name of the package for 'auth' (containing 'Auth').

**Comment by Qmando** [comment]
ElastAlert doesn't work with python3 at the moment.

**Comment by ostavnaas** [comment]
Any progress with python3 support. Last comment Apr 15, 2016. Still get same error with Python3. Python2.7 is end of life in 2020.

**Comment by aboutbelka** [comment]
> ImportError: No module named 'auth'

This can be solved by `pip3 install auth`
But now I'm getting `  File "/usr/lib/python3.4/site-packages/elastalert/create_index.py", line 12, in <module>
    from auth import Auth
ImportError: cannot import name 'Auth'
`

**Comment by ostavnaas** [comment]
But it's not the correct library, because it's reffering to this [Class](https://github.com/Yelp/elastalert/blob/master/elastalert/auth.py#L39). So the correct thing to do `from elastalert.auth import Auth`

**Comment by ostavnaas** [comment]
And there are Python3 support on it's way PR [#1210](https://github.com/Yelp/elastalert/pull/1210)

**Comment by aboutbelka** [comment]
Thanks for the explanation. I gave up and got it working with Python2 for now, will wait for official Python3 support.

**Comment by nleo** [comment]
Hi, guys!

It already a middle of 2019 here and I have no python2 on my servers now. Also I have no reason to install it.
