### ISSUE TITLE
0 hits but matches in kibana/sense

### ISSUE THREAD

**Issue by vaibhavkhanduja** [Yelp/elastalert#482]
I am running a query using kibana/sense and do get back results but same query fails with elastalert rule. The query in sense looks like:

GET _search
{
  "filter" : {
    "query": {
      "query_string": {
        "default_field": "EntityName",
        "query": "docker_mysql_1"
      }
    }
  }
}

es_host: localhost
es_port: 9200
name: Example rule
type: any
index: event*
timestamp_field: Timestamp
filter:
- query:
      query_string:
        default_field: 'EntityName'
        query: 'docker_mysql_1'
alert:
- "email"
email:
- "elastalert@example.com"

Any suggestions on what is going wrong here?

Successfully loaded Example rule

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
INFO:elastalert:Queried rule Example rule from 2016-04-17 04:23 UTC to 2016-04-17 05:08 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 05:08 UTC to 2016-04-17 05:53 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 05:53 UTC to 2016-04-17 06:38 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 06:38 UTC to 2016-04-17 07:23 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 07:23 UTC to 2016-04-17 08:08 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 08:08 UTC to 2016-04-17 08:53 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 08:53 UTC to 2016-04-17 09:38 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 09:38 UTC to 2016-04-17 10:23 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 10:23 UTC to 2016-04-17 11:08 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 11:08 UTC to 2016-04-17 11:53 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 11:53 UTC to 2016-04-17 12:38 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 12:38 UTC to 2016-04-17 13:23 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 13:23 UTC to 2016-04-17 14:08 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 14:08 UTC to 2016-04-17 14:53 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 14:53 UTC to 2016-04-17 15:38 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 15:38 UTC to 2016-04-17 16:23 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 16:23 UTC to 2016-04-17 17:08 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 17:08 UTC to 2016-04-17 17:53 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 17:53 UTC to 2016-04-17 18:38 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 18:38 UTC to 2016-04-17 19:23 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 19:23 UTC to 2016-04-17 20:08 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 20:08 UTC to 2016-04-17 20:53 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 20:53 UTC to 2016-04-17 21:38 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 21:38 UTC to 2016-04-17 22:23 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 22:23 UTC to 2016-04-17 23:08 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 23:08 UTC to 2016-04-17 23:53 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-17 23:53 UTC to 2016-04-18 00:38 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-18 00:38 UTC to 2016-04-18 01:23 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-18 01:23 UTC to 2016-04-18 02:08 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-18 02:08 UTC to 2016-04-18 02:53 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-18 02:53 UTC to 2016-04-18 03:38 UTC: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-04-18 03:38 UTC to 2016-04-18 04:23 UTC: 0 hits

Would have written the following documents to elastalert_status:

elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2016, 4, 18, 4, 23, 40, 906168, tzinfo=tzutc()), 'rule_name': 'Example rule', 'starttime': datetime.datetime(2016, 4, 17, 4, 23, 39, 921786, tzinfo=tzutc()), 'endtime': datetime.datetime(2016, 4, 18, 4, 23, 39, 921786, tzinfo=tzutc()), 'time_taken': 0.9802320003509521}

**Comment by Qmando** [comment]
Are you sure the Timestamp of the document was in the correct range? Note that in Kibana, it will be adjusted to local time. Two things to try:

1. ``elastalert-test-rule --days=7`` by adding the days, you can see if any documents match over a larger time period. Add ``--count-only`` to make it run faster and just show you the number of documents.
2. Remove the filter and see if you get any documents. If you don't, perhaps something is wrong with the index name, or the timestamp field name.

**Comment by vaibhavkhanduja** [comment]
Thanks above suggestions helped. But now I see following exception. The timestamp over is unix timestamp going up-till milli-second.

Thx

Traceback (most recent call last):
  File "/tmp/elastigo/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.0.79', 'console_scripts', 'elastalert-test-rule')()
  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/test_rule.py", line 287, in main
    test_instance.run_rule_test()
  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/test_rule.py", line 282, in run_rule_test
    self.run_elastalert(rule_yaml, args)
  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/test_rule.py", line 249, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/elastalert.py", line 535, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/elastalert.py", line 419, in run_query
    data = self.get_hits(rule, start, end, index)
  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/elastalert.py", line 310, in get_hits
    hits = self.process_hits(rule, hits)
  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/elastalert.py", line 266, in process_hits
    hit['_source'][rule['timestamp_field']] = rule['ts_to_dt'](hit['_source'][rule['timestamp_field']])
  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/util.py", line 65, in ts_to_dt
    dt = dateutil.parser.parse(timestamp)
  File "/tmp/elastigo/local/lib/python2.7/site-packages/dateutil/parser.py", line 743, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/tmp/elastigo/local/lib/python2.7/site-packages/dateutil/parser.py", line 310, in parse
    ret = default.replace(**repl)
OverflowError: signed integer is greater than maximum

**Comment by vaibhavkhanduja** [comment]
The rule used is:

es_host: localhost
es_port: 9200
name: Example rule
type: any
index: event*
timestamp_field: Timestamp
filter:
- term:
     EntityName: "docker_mysql_1"
alert: "email"
email: "vaibhavkhanduja@gmail.com"

**Comment by vaibhavkhanduja** [comment]
Using timestamp_type: unix helped above. I get 41 hits with my rule now. I may be asking a basic question, but would I be able to query anything from elasticalert_status? I have not yet configured an email alert

Got 41 hits from the last 60 days

Available terms in first hit:
	Eventid
	MetricValue
	ReadableTimestamp
	Timestamp
	EntityName
	MetricType
	Host
	SCORE
	Algo
	EntityID
	RCA


Would have written the following documents to elastalert_status:

elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2016, 4, 26, 12, 23, 42, 307457, tzinfo=tzutc()), 'rule_name': 'Exa
mple rule', 'starttime': datetime.datetime(2016, 2, 26, 12, 23, 36, 999762, tzinfo=tzutc()), 'endtime': datetime.datetime(2016, 4, 26, 12, 23, 36
, 999762, tzinfo=tzutc()), 'time_taken': 5.304405927658081}

**Comment by vaibhavkhanduja** [comment]
I debugged it more but not getting any results, may be I am doing a basic mistake. The query from sense does give out values,
GET _search
{
  "filter": {
    "range": {
      "Timestamp": {
        "gte": "now-30d"
      }
    }
  }
}

=================
 My rule now looks like:
===================
es_host: localhost
es_port: 9200
name: Example rule
type: any
index: event
timestamp_field: Timestamp
buffer_time:
  days: 30
timestamp_type: unix
alert:
 - command
command: ["touch /tmp/test"]
========================

elastalert-test-rule --days=30 ./example.yaml

Got 41 hits from the last 30 days

Available terms in first hit:
	Eventid
	MetricValue
	ReadableTimestamp
	Timestamp
	EntityName
	MetricType
	Host
	SCORE
	Algo
	EntityID
	RCA

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
INFO:elastalert:Queried rule Example rule from 2016-03-27 06:15 PDT to 2016-04-26 06:15 PDT: 0 hits

Would have written the following documents to elastalert_status:

elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2016, 4, 26, 13, 15, 57, 608772, tzinfo=tzutc()), 'rule_name': 'Example rule', 'starttime': datetime.datetime(2016, 3, 27, 13, 15, 57, 600814, tzinfo=tzutc()), 'endtime': datetime.datetime(2016, 4, 26, 13, 15, 57, 600814, tzinfo=tzutc()), 'time_taken': 0.00498199462890625}
============

**Comment by vaibhavkhanduja** [comment]
Changing timestamp_type to unix_ms throws exception, as below. The mapping of "Timestamp" field is 

"""
"Timestamp": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
          }
"""

  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/elastalert.py", line 310, in get_hits
    hits = self.process_hits(rule, hits)
  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/elastalert.py", line 266, in process_hits
    hit['_source'][rule['timestamp_field']] = rule['ts_to_dt'](hit['_source'][rule['timestamp_field']])
  File "/tmp/elastigo/local/lib/python2.7/site-packages/elastalert-0.0.79-py2.7.egg/elastalert/util.py", line 157, in unixms_to_dt
    return unix_to_dt(ts / 1000)
TypeError: unsupported operand type(s) for /: 'unicode' and 'int'

**Comment by vaibhavkhanduja** [comment]
@Qmando any suggestions here?

**Comment by Qmando** [comment]
As for that last traceback, it looks like the timestamp is being returned as a string and not as a number. Changing util.py:157 to be ``return unix_to_dt(float(ts)/1000)`` should probably fix that. that appears to be a bug on elastalert's side if the format in ES is a date type.

As for why elastalert-test-rule shows documents in the count and then doesn't get any hits, I'm not entirely sure. Does the same thing happen if you run ElastAlert normally? elastalert-test-rule does some weird things and sometimes doesn't produce the correct results, but I'm not sure why in this case. It could potentially have something to do with the timestamp being in unix MS. Can you try adding the patch above in util.py and run the test again?

**Comment by vaibhavkhanduja** [comment]
The fix had made me progress, though I am still evaluating the results. I have created a pull request, if you feel ok, kindly accept it.

https://github.com/Yelp/elastalert/pull/499
