### ISSUE TITLE
Support Nested Time Fields

### ISSUE THREAD

**Issue by zinic** [Yelp/elastalert#505]
Currently, elastalert allows a user to specify a custom timestamp field in a rule configuration YAML file.

Example rule:
```yaml
name: Example Rule
type: frequency
timestamp_field: P.time

...
```

However, the code in [process_hits](https://github.com/Yelp/elastalert/blob/master/elastalert/elastalert.py#L266) given this rule configuration fails with the following exception:
```
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elastalert/elastalert.py", line 748, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/usr/local/lib/python2.7/dist-packages/elastalert/elastalert.py", line 541, in run_rule
    if not self.run_query(rule, rule['starttime'], endtime):
  File "/usr/local/lib/python2.7/dist-packages/elastalert/elastalert.py", line 421, in run_query
    data = self.get_hits(rule, start, end, index)
  File "/usr/local/lib/python2.7/dist-packages/elastalert/elastalert.py", line 312, in get_hits
    hits = self.process_hits(rule, hits)
  File "/usr/local/lib/python2.7/dist-packages/elastalert/elastalert.py", line 266, in process_hits
    hit['_source'][rule['timestamp_field']] = rule['ts_to_dt'](hit['_source'][rule['timestamp_field']])
KeyError: 'P.time'
```

Are there any plans to better support nested timestamp fields?

**Comment by Qmando** [comment]
This should definitely be supported. Anywhere where timestamp_field is referenced should be replaced with a lookup_es_key from util.py, which will automatically resolve nested fields.

**Comment by zinic** [comment]
Awesome, I'll code up a PR for this then if that's okay. I could really use the functionality and it appears that the tools are already in place - just gotta use them here.
