### ISSUE TITLE
403 Unauthorized

### ISSUE THREAD

**Issue by 0x9090** [Yelp/elastalert#535]
We recently added SSL and authentication to our main ElasticSearch instance, and I am working to convert the alerts to fit. The local ElasticSearch instance (the ElastAlert metadata one) does not have TLS or auth, due to it only being available to localhost.

I added use_ssl, es_username, and es_password, to all the rule definitions (not config.yaml), which seems to be working as ElastAlert is now able to query the cluster. But, when there is a valid hit, ElastAlert throws a 403.

```
WARNING:elasticsearch:POST /kibana-int/temp?op_type=create [status:403 request:0.045s]
ERROR:root:Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 879, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
  File "/opt/elastalert/elastalert/elastalert.py", line 909, in send_alert
    kb_link = self.generate_kibana_db(rule, matches[0])
  File "/opt/elastalert/elastalert/elastalert.py", line 790, in generate_kibana_db
    return self.upload_dashboard(db, rule, match)
  File "/opt/elastalert/elastalert/elastalert.py", line 824, in upload_dashboard
    body=db_body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 230, in create
    return self.index(index, doc_type, body, id=id, params=params, op_type='create')
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 261, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
AuthorizationException: TransportError(403, u'security_exception')
```

I'm not sure if this 403 is coming from the remote cluster, or the local ElasticSearch instance. Either of those scenarios wouldn't make sense, because the cluster is obviously reachable, and we didn't add TLS or auth to the local instance.

**Comment by Qmando** [comment]
Could there be a difference between GET and POST requests? I think this might occur if the index (kibana-int in this case) is set to read only mode. Though, if you open Kibana and then save a new dashboard, it should be making basically the same POST request.

If it's correctly posting documents to elastalert_status, you could work around this by removing ``generate_kibana_link`` and using ``kibana_dashboard`` instead. Kibana_dashboard will allow you to just link an existing dashboard instead of creating a brand new one.

**Comment by 0x9090** [comment]
The trick was indeed removing `generate_kibana_link` and `kibana_dashboard` from the alert. I removed those options, and the errors stopped. Will this functionality be ported to kibana 4? Having that dashboard generation was incredibly valuable to my alert recipients.

**Comment by Qmando** [comment]
The only supported feature for kibana 4 is ``use_kibana4_dashboard`` which just lets you link to a dashboard and it sets the time.

``use_kibana4_dashboard: "https://elasticsearch.0x9090.com/#/dashboard/MyDashboard"``

**Comment by 0x9090** [comment]
That's kind of a bummer. That one feature saved my analysts hours of time. Is this because of a limitation in Kibana 4, or has the dynamic dashboard generation just not been built into ElastAlert yet?

**Comment by Qmando** [comment]
Well, Kibana 3 dashboards were JSON documents stored in Elasticsearch, and they had a very easy to understand schema.

Kibana 4 dsahboards are more complicated, built up from saved searches and visualizations and use URL fragments to save state. The url fragment format is less documented than the kibana 3 dashbaord schema. It's definitely possible, but I have not built that functionality yet.

**Comment by 0x9090** [comment]
Fair enough. In that case, please consider this issue a feature request. Any way I can donate to the cause?  =)

**Comment by matkam11** [comment]
+1 I know this would make my life (and many other's lives) a lot easier!

**Comment by 0x9090** [comment]
@Qmando Could we use the Kibana 4 URL parameters to accomplish a similar thing? There appears to be a "query" parameter as part of the Kibana GET request.

Something like,

```
https://#####/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))&_a=(columns:!(_source),index:%5Blogstash-%5DYYYY.MM.DD,interval:auto,query:(query_string:(analyze_wildcard:!t,query:'source_host.raw:(%22host.domain.tld%22)')),sort:!('@timestamp',desc))
```

**Comment by Qmando** [comment]
You certainly could. I tried implementing basic filters and encountered some problems, but I didn't spend much time on it. It would be great to have.
