### ISSUE TITLE
Running elaslalert on windows 7 

### ISSUE THREAD

**Issue by AviralSri** [Yelp/elastalert#544]
My objective is to use elastalert to send email

During testing the rule, as specified in **http://elastalert.readthedocs.io/en/latest/running_elastalert.html**
D:\elastalert>elastalert-test-rule example_rules/example_frequency.yaml
Successfully loaded Example rule

Traceback (most recent call last):
  File "C:\Python27\Scripts\elastalert-test-rule-script.py", line 9, in <module>
    load_entry_point('elastalert==0.0.81', 'console_scripts', 'elastalert-test-rule')()
  File "C:\Python27\lib\site-packages\elastalert-0.0.81-py2.7.egg\elastalert\test_rule.py", line 287, in main
    test_instance.run_rule_test()
  File "C:\Python27\lib\site-packages\elastalert-0.0.81-py2.7.egg\elastalert\test_rule.py", line 275, in run_rule_test
    hits = self.test_file(copy.deepcopy(rule_yaml), args)
  File "C:\Python27\lib\site-packages\elastalert-0.0.81-py2.7.egg\elastalert\test_rule.py", line 54, in test_file
    es_client = ElastAlerter.new_elasticsearch(es_config)
  File "C:\Python27\lib\site-packages\elastalert-0.0.81-py2.7.egg\elastalert\elastalert.py", line 143, in new_elasticsearch
    send_get_body_as=es_conn_conf['send_get_body_as'])
  File "build\bdist.win-amd64\egg\elasticsearch\client\__init__.py", line 168, in __init__
  File "build\bdist.win-amd64\egg\elasticsearch\transport.py", line 112, in __init__
  File "build\bdist.win-amd64\egg\elasticsearch\transport.py", line 165, in set_connections
  File "build\bdist.win-amd64\egg\elasticsearch\transport.py", line 164, in _create_connection
  File "build\bdist.win-amd64\egg\elasticsearch\connection\http_requests.py", line 44, in __init__
TypeError: %d format: a number is required, not NoneType

I get TypeError at the bottom.

**Comment by Qmando** [comment]
Could you show me your rule file?

My first guess for this is that ``es_port`` is somehow set to None instead of a proper number, which would occur if your rule file had something like
```
es_host: elasticsearch.foo.com
es_port:
```

But that's just a guess. If you put ```print es_conn_conf``` here (https://github.com/Yelp/elastalert/blob/master/elastalert/elastalert.py#L135) then the output would probably reveal the problem.

**Comment by AviralSri** [comment]
Below is my rule file example_frequency.yaml. 

# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: 10.76.133.15

# (Optional)
# Elasticsearch port
# es_port: 9200

# (OptionaL) Connect with SSL to elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for elasticsearch
#es_username: username
#es_password: password

# (Required)
# Rule name, must be unique
name: Example rule

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: topbeat-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 50

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  hours: 4

# (Required)
# A list of elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter: []
#- term:
#   some_field: "some_value"

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "aviral.srivastava@appmon.com"

**Comment by AviralSri** [comment]
Below is my rule file example_frequency.yaml

# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: 10.76.133.15

# (Optional)
# Elasticsearch port
# es_port: 9200

# (OptionaL) Connect with SSL to elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for elasticsearch
#es_username: username
#es_password: password

# (Required)
# Rule name, must be unique
name: Example rule

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: topbeat-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 50

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  hours: 4

# (Required)
# A list of elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter: []
#- term:
#   some_field: "some_value"

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "aviral.srivastava@appmon.com"

**Comment by AviralSri** [comment]
# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
# es_host: 10.76.133.15

# (Optional)
# Elasticsearch port
# es_port: 9200

# (OptionaL) Connect with SSL to elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for elasticsearch
#es_username: kkhavale
#es_password: wosimosi3@@@@

# (Required)
# Rule name, must be unique
name: Example rule

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: topbeat-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 50

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  hours: 4

# (Required)
# A list of elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter: []
#- term:
#   some_field: "some_value"

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "aviral.srivastava@capgemini.com"

**Comment by AviralSri** [comment]
Thanks for your response, I found that I did a silly mistake the es_port : 9200 was commented.

I am getting output like this now.....

D:\elastalert>elastalert-test-rule example_rules/example_frequency.yaml
Successfully loaded Example rule

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 10.76.170.72
Got 3683 hits from the last 1 day

Available terms in first hit:
        beat.hostname
        beat.name
        count
        @timestamp
        proc.username
        proc.name
        proc.mem.share
        proc.mem.rss
        proc.mem.rss_p
        proc.mem.size
        proc.pid
        proc.cmdline
        proc.state
        proc.ppid
        proc.cpu.user_p
        proc.cpu.total
        proc.cpu.start_time
        proc.cpu.user
        proc.cpu.system
        type

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 10.76.170.72
INFO:elastalert:Queried rule Example rule from 2016-05-24 14:59 India Standard Time to 2016-05-24 15:44 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 15:44 India Standard Time to 2016-05-24 16:29 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 16:29 India Standard Time to 2016-05-24 17:14 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 17:14 India Standard Time to 2016-05-24 17:59 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 17:59 India Standard Time to 2016-05-24 18:44 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 18:44 India Standard Time to 2016-05-24 19:29 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 19:29 India Standard Time to 2016-05-24 20:14 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 20:14 India Standard Time to 2016-05-24 20:59 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 20:59 India Standard Time to 2016-05-24 21:44 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 21:44 India Standard Time to 2016-05-24 22:29 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 22:29 India Standard Time to 2016-05-24 23:14 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 23:14 India Standard Time to 2016-05-24 23:59 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-24 23:59 India Standard Time to 2016-05-25 00:44 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 00:44 India Standard Time to 2016-05-25 01:29 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 01:29 India Standard Time to 2016-05-25 02:14 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 02:14 India Standard Time to 2016-05-25 02:59 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 02:59 India Standard Time to 2016-05-25 03:44 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 03:44 India Standard Time to 2016-05-25 04:29 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 04:29 India Standard Time to 2016-05-25 05:14 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 05:14 India Standard Time to 2016-05-25 05:59 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 05:59 India Standard Time to 2016-05-25 06:44 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 06:44 India Standard Time to 2016-05-25 07:29 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 07:29 India Standard Time to 2016-05-25 08:14 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 08:14 India Standard Time to 2016-05-25 08:59 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 08:59 India Standard Time to 2016-05-25 09:44 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 09:44 India Standard Time to 2016-05-25 10:29 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 10:29 India Standard Time to 2016-05-25 11:14 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 11:14 India Standard Time to 2016-05-25 11:59 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 11:59 India Standard Time to 2016-05-25 12:44 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 12:44 India Standard Time to 2016-05-25 13:29 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 13:29 India Standard Time to 2016-05-25 14:14 India Standard Time: 0 hits
INFO:elastalert:Queried rule Example rule from 2016-05-25 14:14 India Standard Time to 2016-05-25 14:59 India Standard Time: 3771 hits
INFO:elastalert:Alert for Example rule at 2016-05-25T09:25:02.507Z:
INFO:elastalert:Example rule

At least 50 events occurred between 2016-05-25 10:55 India Standard Time and 2016-05-25 14:55 India Standard Time

@timestamp: 2016-05-25T09:25:02.507Z
_id: AVTnPHGyHdMUafG02gQH
_index: topbeat-2016.05.25
_type: process
beat: {
    "hostname": "DIN16000704",
    "name": "DIN16000704"
}
count: 1
proc: {
    "cmdline": "cacls  d:\\users\\kkhavale /T /E /C /P kkhavale:F",
    "cpu": {
        "start_time": "Nov04",
        "system": 48765,
        "total": 82024,
        "user": 33259,
        "user_p": 0.6713
    },
    "mem": {
        "rss": 4362240,
        "rss_p": 0,
        "share": 0,
        "size": 1994752
    },
    "name": "cacls.exe",
    "pid": 6052,
    "ppid": 0,
    "state": "running",
    "username": "CORP\\kkhavale"
}
type: process

INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule
INFO:elastalert:Ignoring match for silenced rule Example rule

Would have written the following documents to elastalert_status:

silence - {'rule_name': 'Example rule', '@timestamp': datetime.datetime(2016, 5, 25, 9, 29, 24, 390000, tzinfo=tzutc()), 'exponent': 0, 'until': datetim
e.datetime(2016, 5, 25, 9, 30, 24, 390000, tzinfo=tzutc())}

elastalert_status - {'hits': 3771, 'matches': 75, '@timestamp': datetime.datetime(2016, 5, 25, 9, 29, 24, 629000, tzinfo=tzutc()), 'rule_name': 'Example
 rule', 'starttime': datetime.datetime(2016, 5, 24, 9, 29, 22, 860000, tzinfo=tzutc()), 'endtime': datetime.datetime(2016, 5, 25, 9, 29, 22, 860000, tzi
nfo=tzutc()), 'time_taken': 1.7649998664855957}

**But when I am running elastalert, I am getting below output**
D:\elastalert>python -m elastalert.elastalert --verbose --rule example_frequency.yaml
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\elastalert\elastalert\elastalert.py", line 1397, in <module>
    sys.exit(main(sys.argv[1:]))
  File "D:\elastalert\elastalert\elastalert.py", line 1392, in main
    client = ElastAlerter(args)
  File "D:\elastalert\elastalert\elastalert.py", line 94, in __init__
    self.conf = load_rules(self.args)
  File "elastalert\config.py", line 356, in load_rules
    conf = yaml_loader(filename)
  File "build\bdist.win-amd64\egg\staticconf\loader.py", line 161, in yaml_loader
IOError: [Errno 2] No such file or directory: 'config.yaml'

**Comment by Qmando** [comment]
config.yaml either needs to be in the same folder where you are run elastalert from (D:\elastalert) OR you must specify a path to it with ie ``--config D:\elastalert\config.yaml``
