### ISSUE TITLE
Fails to run elastalert-create-index 

### ISSUE THREAD

**Issue by lilalone** [Yelp/elastalert#552]
Using CentOS 7 and python2.7,  installation (python setup.py install) was successful.

However, running elastalert-create-index shows fails with the following exception:

```
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 9, in <module>
    load_entry_point('elastalert==0.0.81', 'console_scripts', 'elastalert-create-index')()
  File "/usr/lib/python2.7/site-packages/elastalert-0.0.81-py2.7.egg/elastalert/create_index.py", line 107, in main
    if es_index.exists(index):
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 212, in exists
    self.transport.perform_request('HEAD', _make_path(index), params=params)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 301, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 72, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 102, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(502, u'')
```

Plz help me !! Thanks

**Comment by Qmando** [comment]
502 generally indicates an issue with a proxy. Are you using just the default HTTP settings?
Are you able to access Elasticsearch directly via CURL or something?

**Comment by lilalone** [comment]
Thanks, i fixed it !!!
