### ISSUE TITLE
Unable to install elastalert

### ISSUE THREAD

**Issue by kkorada** [Yelp/elastalert#569]
getting error while running below command
`python setup.py install`
running install
running bdist_egg
running egg_info
writing requirements to elastalert.egg-info/requires.txt
writing elastalert.egg-info/PKG-INFO
writing top-level names to elastalert.egg-info/top_level.txt
writing dependency_links to elastalert.egg-info/dependency_links.txt
writing entry points to elastalert.egg-info/entry_points.txt
reading manifest file 'elastalert.egg-info/SOURCES.txt'
writing manifest file 'elastalert.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/__init__.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/alerts.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/auth.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/config.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/create_index.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/elastalert.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/enhancements.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/kibana.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/opsgenie.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/rule_from_kibana.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/ruletypes.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/test_rule.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/util.py -> build/bdist.linux-x86_64/egg/elastalert
copying build/lib/elastalert/schema.yaml -> build/bdist.linux-x86_64/egg/elastalert
creating build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/__init__.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/alerts_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/base_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/config_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/conftest.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/kibana_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/rules_test.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib/tests/util_test.py -> build/bdist.linux-x86_64/egg/tests
byte-compiling build/bdist.linux-x86_64/egg/elastalert/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/alerts.py to alerts.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/auth.py to auth.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/config.py to config.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/create_index.py to create_index.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/elastalert.py to elastalert.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/enhancements.py to enhancements.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/kibana.py to kibana.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/opsgenie.py to opsgenie.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/rule_from_kibana.py to rule_from_kibana.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/ruletypes.py to ruletypes.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/test_rule.py to test_rule.pyc
byte-compiling build/bdist.linux-x86_64/egg/elastalert/util.py to util.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/alerts_test.py to alerts_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/base_test.py to base_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/config_test.py to config_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/conftest.py to conftest.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/kibana_test.py to kibana_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/rules_test.py to rules_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/util_test.py to util_test.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying elastalert.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
elastalert.config: module references __file__
creating 'dist/elastalert-0.0.85-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing elastalert-0.0.85-py2.7.egg
removing '/usr/lib/python2.7/site-packages/elastalert-0.0.85-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/elastalert-0.0.85-py2.7.egg
Extracting elastalert-0.0.85-py2.7.egg to /usr/lib/python2.7/site-packages
elastalert 0.0.85 is already the active version in easy-install.pth
Installing elastalert-create-index script to /usr/bin
Installing elastalert script to /usr/bin
Installing elastalert-test-rule script to /usr/bin
Installing elastalert-rule-from-kibana script to /usr/bin

Installed /usr/lib/python2.7/site-packages/elastalert-0.0.85-py2.7.egg
Processing dependencies for elastalert==0.0.85
Searching for aws-requests-auth
Reading https://pypi.python.org/simple/aws-requests-auth/
Download error on https://pypi.python.org/simple/aws-requests-auth/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765) -- Some packages may not be found!
Couldn't find index page for 'aws-requests-auth' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765) -- Some packages may not be found!
No local packages or download links found for aws-requests-auth
error: Could not find suitable distribution for Requirement.parse('aws-requests-auth')

python version **Python 2.7.5**

**Comment by Qmando** [comment]
Try ``pip install -r requirements.txt`` instead

**Comment by Pransh20** [comment]
Tried both of the methods but getting this error, 

  blist/_blist.c: At top level:
    blist/_blist.c:7404: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘init_blist’
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-V24s1d/blist/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ph69cd-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-V24s1d/blist/

**Comment by upendrapisupati** [comment]
HI,

I am also same facing same error. any solution??

Thanks,
Upendra

**Comment by Pransh20** [comment]
It's the GCC/blist version issue.
You need to upgrade/downgrade the GCC version.

It worked for me for gcc 4.4.6  and blist 1.2.1

**Comment by rore** [comment]
Try installing python develop
`$ sudo yum -y install python-devel`

**Comment by upendrapisupati** [comment]
Thanks @rore . It worked. Thank you so much!!!

**Comment by Thinkgamer** [comment]
@rore  hello，I have encountered this problem when I use the elastalert startup configuration file，but my python-dev has been installed，my system is ubuntu 16.04

**Comment by Thinkgamer** [comment]
WARNING:elasticsearch:GET https://localhost:9200/logstash-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:N/A request:0.026s]
Traceback (most recent call last):
  File "/home/master/.local/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 56, in perform_request
    response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
  File "/home/master/.local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/master/.local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/master/.local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
