### ISSUE TITLE
Fails to create instance when using AWSRequest sigining

### ISSUE THREAD

**Issue by dhawal55** [Yelp/elastalert#570]
I have specified `aws_region:us-west-2` in my config.yaml. I have access policy assigned to my AWS ES instance that allows access from IAM role assigned to the instance where I'm running elastalert container. But i get error when creating index:

```
elastalert-create-index --index elastalert_status --old-index ""
```
```
Creating Elastalert index in Elasticsearch...
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 9, in <module>
    load_entry_point('elastalert==0.0.85', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.85-py2.7.egg/elastalert/create_index.py", line 80, in main
    send_get_body_as=send_get_body_as)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 150, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 113, in __init__
    self.set_connections(hosts)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 166, in set_connections
    connections = map(_create_connection, hosts)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 165, in _create_connection
    return self.connection_class(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 35, in __init__
    http_auth = http_auth.split(':', 1)
AttributeError: 'AWSRequestsAuth' object has no attribute 'split'
```

**Comment by Qmando** [comment]
According to #551 you can fix this by upgrading setuptools and the elasticsearch library

pip install setuptools
pip install elasticsearch==1.7.0

Also listed that may need upgrading are mock, pbr, requests-oauthlib and configparser

**Comment by dhawal55** [comment]
@Qmando Thanks for the help. Updating elasticsearch to 1.7 gets me further but now i get auth error:

```
Creating Elastalert index in Elasticsearch...
/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py:53: UserWarning: Connecting to https://XXX:443 using SSL with verify_certs=False is insecure.
  'Connecting to %s using SSL with verify_certs=False is insecure.' % self.base_url)
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 9, in <module>
    load_entry_point('elastalert==0.0.85', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.85-py2.7.egg/elastalert/create_index.py", line 107, in main
    if es_index.exists(index):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 224, in exists
    params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 78, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthorizationException: TransportError(403, u'')
```

I also tried the following suggestions from @Gittyhub in issue #551 

```
pip install -U setuptools
pip install -U mock
pip install -U pbr
pip install -U requests-oauthlib
```
As well as update in requirements.txt
```
configparser==3.5.0
elasticsearch==1.7.0
```
but still get the above error.

**Comment by dhawal55** [comment]
I skipped the upgrade step for setuptools, mock, pbr & requestspoauthlib and just updated configparser and elasticsearch and now it works. Thanks for all the help @Qmando  & @Gittyhub

**Comment by nickedes** [comment]
:+1:
