### ISSUE TITLE
 elastalert config issues

### ISSUE THREAD

**Issue by orright** [Yelp/elastalert#571]
I am running a query using elastalert-test-rule and do get back results but same errors with elastalert. The query in sense looks like:

```
[root@localhost example_rules]# cat rule.yaml 
  es_host: 127.0.0.1
  es_port: 9200
  name: 001    （line 20）
  type: frequency
  index: logstash-*
  num_events: 8
  minutes: 2 
  filter:
  - range:
      response_code:
        from: 400
        to: 599
 alert:
 - "email"
 email:
 - "addins@gmail.com"
```
test output is:
```
[root@localhost elastalert]# elastalert-test-rule  example_rules/rule.yaml
Traceback (most recent call last):
  File "/usr/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.0.85', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.85-py2.6.egg/elastalert/test_rule.py", line 287, in main
    test_instance.run_rule_test()
  File "/usr/lib/python2.6/site-packages/elastalert-0.0.85-py2.6.egg/elastalert/test_rule.py", line 269, in run_rule_test
    rule_yaml = yaml.load(fh)
  File "/usr/lib64/python2.6/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.6/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/lib64/python2.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.6/site-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "/root/elk/elastalert/example_rules/rule.yaml", line 20, column 1
```
pls help me！thanks a lot！

**Comment by nixsix** [comment]
I am getting this error too! 
Sometime I guess no one's bothered to answer.
Perhaps, the biggest disadvantage of opensource plugins.

**Comment by Qmando** [comment]
Your YAML is invalid. Why do you have "(line 20)" on line 3 of your output?
Do you have something in brackets like "[foo]"? Because that would cause this error.
