### ISSUE TITLE
elastalert-create-index issue

### ISSUE THREAD

**Issue by sumanthakannantha** [Yelp/elastalert#587]
I am getting below error when I execute elastalert-create-index command
$ elastalert-create-index
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: botocore

**Comment by tom-haines** [comment]
Looks like you have not installed botocore lib

**Comment by bean5** [comment]
@sumanthakannantha did installing the botocore lib work for you? If so, could you close this issue?
