### ISSUE TITLE
Unknox mimetype

### ISSUE THREAD

**Issue by Christian1626** [Yelp/elastalert#594]
Hello, 
I have an mimetype error when executing **elastalert-test-rule** as following. 

```
$elastalert-test-rule test_rules/test.yaml
Successfully loaded Test rule

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): proxy.rd.francetelecom.fr
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: proxy.rd.francetelecom.fr
Error running your filter:
SerializationError('Unknown mimetype, unable to deserialize: text/html',)
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): proxy.rd.francetelecom.fr
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: proxy.rd.francetelecom.fr
ERROR:root:Error running query: Unknown mimetype, unable to deserialize: text/html

Would have written the following documents to elastalert_status:

elastalert_error - {'message': 'Error running query: Unknown mimetype, unable to deserialize: text/html', 'traceback': ['Traceback (most recent call last):', '  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.88-py2.7.egg/elastalert/elastalert.py", line 303, in get_hits', "    res = self.current_es.search(index=index, size=rule['max_query_size'], body=query, ignore_unavailable=True, **extra_args)", '  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 498, in search', '    params=params, body=body)', '  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 325, in perform_request', "    data = self.deserializer.loads(data, headers.get('content-type'))", '  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/serializer.py", line 71, in loads', "    raise SerializationError('Unknown mimetype, unable to deserialize: %s' % mimetype)", 'SerializationError: Unknown mimetype, unable to deserialize: text/html'], 'data': {'rule': 'Test rule'}}
```

How can I fix it ?

Chris.

**Comment by GillesDeBorger** [comment]
Hey Christian, have you found a fix for this? 

I have the same issue

**Comment by Christian1626** [comment]
I downloaded an older version of elastalert and it  did the trick. :/

**Comment by Qmando** [comment]
Have you tried upgrading or downgrading the Elasticsearch Python library? That's where this error is coming from. It seems that something (proxy, load balancer, ??) is converting the mimetype between ElastAlert and Elasticsearch. The actual content could be an error page or something similar.

Are you using any unusual connection or routing settings?

Can you hit elasticsearch directly with curl?

```
curl -v hostname:port
```
