### ISSUE TITLE
SSL with the elastalert

### ISSUE THREAD

**Issue by LazyerHong** [Yelp/elastalert#608]
If i want to use the ssl with the elastalert, how do i set the config in the elasticsearch.
Is there some good introduction about this operation? 
Thank you very much!

**Comment by Qmando** [comment]
``use_ssl: true``

**Comment by LazyerHong** [comment]
I konw that set use_ssl :ture in the  elastalert. But what i mean is that do i need set some something in the elasticsearch.yml ??Thank you

**Comment by rudijs** [comment]
@LazyerHong If you want to enable SSL on you connections to Elasticsearch .. this might suit you http://floragunn.com/searchguard/

**Comment by arunpragadesh** [comment]
I have installed ELK with SearchGuard and now all the nodes are secured. Afterwards i have installed ElastAlert and tried to execute "elastalert-create-index" command and it has failed and thrown following error,

root@abc:~# elastalert-create-index
Enter Elasticsearch host: 10.27.0.110
Enter Elasticsearch port: 9200
Use SSL? t/f: t
Verify TLS certificates? t/f: t
Enter optional basic-auth username (or leave blank): admin
Enter optional basic-auth password (or leave blank): 
Enter optional Elasticsearch URL prefix (prepends a string to the URL of every request): https://10.27.0.110:9200
New index name? (Default elastalert_status) 
Name of existing index to copy? (Default None) 
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 9, in <module>
    load_entry_point('elastalert==0.1.1', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.1-py2.7.egg/elastalert/create_index.py", line 116, in main
    if es_index.exists(index):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 212, in exists
    self.transport.perform_request('HEAD', _make_path(index), params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 301, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 61, in perform_request
    raise SSLError('N/A', str(e), e)
elasticsearch.exceptions.SSLError: ConnectionError([Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed) caused by: SSLError([Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed)

Can you please let me know what are certificate related configurations required to be added to config.yaml ?

**Comment by Qmando** [comment]
There isn't an easy way to pass in CA certificates right now. I would recommend you skip verification for now.

https://elasticsearch-py.readthedocs.io/en/master/#ssl-and-authentication describes the process of adding certs. I'll add this in at some point.
