### ISSUE TITLE
Test Cardinality rule

### ISSUE THREAD

**Issue by bennneuh** [Yelp/elastalert#620]
Hi,

I encounter an issue with the cardinality rule.

If i play the test:

```
/opt/rules # elastalert-test-rule  example_cardinality.yaml
Successfully loaded Example rule cardinality

Traceback (most recent call last):
  File "/usr/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert', 'console_scripts', 'elastalert-test-rule')()
  File "/opt/elastalert/elastalert/test_rule.py", line 287, in main
    test_instance.run_rule_test()
  File "/opt/elastalert/elastalert/test_rule.py", line 275, in run_rule_test
    hits = self.test_file(copy.deepcopy(rule_yaml), args)
  File "/opt/elastalert/elastalert/test_rule.py", line 54, in test_file
    es_client = ElastAlerter.new_elasticsearch(es_config)
  File "/opt/elastalert/elastalert/elastalert.py", line 143, in new_elasticsearch
    send_get_body_as=es_conn_conf['send_get_body_as'])
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 168, in __init__
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 112, in __init__
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 165, in set_connections
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 164, in _create_connection
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 44, in __init__
TypeError: %d format: a number is required, not NoneType
```

The rule:

```
name: Example rule cardinality
type: cardinality
index: logstash-*
cardinality_field: "hostname"
max_cardinality: 1
timeframe:
    minutes: 2
# Filter disabled for the test
filter: []
alert:
 - "telegram"
telegram_bot_token: "<token>"
telegram_room_id: "<id>"
```

I use the docker image from the hub : ivankrizsan/elastalert

Maybe it's linked to a strange behaviors when a use the rule (don't match or match twice for just 1 real event), i don't know... :/

Thanks

**Comment by Qmando** [comment]
ah. You need to add ``es_host`` and ``es_port``. It really should tell you about that. Or read them from config.yaml. Sorry about that.

**Comment by bennneuh** [comment]
Ok i was thinking that is it was ok when it's configured only in the config.yaml.
But finally not. I confirm the test work fine now with "es" values in the rule.
Thank you very much for your help

**Comment by Qmando** [comment]
It's only ``elastalert-test-rule`` that requires es_host and port in the rule itself. This is a remnant from when they used to be required in every rule in a previous version.

**Comment by bennneuh** [comment]
yes it's logic, I should test with these values earlier. :)
