### ISSUE TITLE
elastalert-create-index timeout option

### ISSUE THREAD

**Issue by panaman** [Yelp/elastalert#622]
1. current timeout of 10 seconds is too short for creating the index.
2. elastalert-create-index ignores es_conn_timeout setting in config.yaml

esalert1 elastalert]$ elastalert-create-index 
New index name? (Default elastalert_status) 
Name of existing index to copy? (Default None) 
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 9, in <module>
    load_entry_point('elastalert==0.0.91', 'console_scripts', 'elastalert-create-index')()
  File "/usr/lib/python2.7/site-packages/elastalert-0.0.91-py2.7.egg/elastalert/create_index.py", line 114, in main
    es.indices.put_mapping(index=index, doc_type='elastalert', body=es_mapping)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(_args, params=params, *_kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 276, in put_mapping
    params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 301, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 64, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='esm01', port=9200): Read timed out. (read timeout=10))

Adding timeout=60 option to create_index.py fixed my issue.
`es = Elasticsearch(
        host=host,
        port=port,
        timeout=60,
        use_ssl=use_ssl,
        connection_class=RequestsHttpConnection,
        http_auth=http_auth,
        url_prefix=url_prefix,
        send_get_body_as=send_get_body_as)
`

**Comment by PMDubuc** [comment]
It would also be nice if you could specify the number of primary shards for the index.
https://github.com/Yelp/elastalert/issues/596
