### ISSUE TITLE
KeyError: 'scroll_keepalive'

### ISSUE THREAD

**Issue by ashokc** [Yelp/elastalert#647]
Any pointers on why I get this error and try testing a simple rule... The install went through fine...

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
Traceback (most recent call last):
  File "/usr/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.0.93', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.7/site-packages/elastalert-0.0.93-py2.7.egg/elastalert/test_rule.py", line 316, in main
    test_instance.run_rule_test()
  File "/usr/lib/python2.7/site-packages/elastalert-0.0.93-py2.7.egg/elastalert/test_rule.py", line 311, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/lib/python2.7/site-packages/elastalert-0.0.93-py2.7.egg/elastalert/test_rule.py", line 225, in run_elastalert
    client = ElastAlerter(['--debug'])
  File "/usr/lib/python2.7/site-packages/elastalert-0.0.93-py2.7.egg/elastalert/elastalert.py", line 96, in __init__
    self.scroll_keepalive = self.conf['scroll_keepalive']
KeyError: 'scroll_keepalive'

**Comment by Qmando** [comment]
This is a bug that I just introduced yesterday. I'll try to fix this right away. You can install version 0.0.92 to fix it.

**Comment by ashokc** [comment]
Thanks, I will try to downgrade to 0.0.92.

**Comment by Qmando** [comment]
This should be fixed on master branch now, and I've released a new version 0.0.94 for it.

**Comment by omercnet** [comment]
shouldn't it pull the default value from https://github.com/Yelp/elastalert/blob/d033e26e49f487f28cc639350a88abfa254e9707/elastalert/config.py#L381 ?

**Comment by Qmando** [comment]
The test script doesn't call load_rules.
