### ISSUE TITLE
Issue Setting up - ImportError: No module named 

### ISSUE THREAD

**Issue by rhysxevans** [Yelp/elastalert#669]
Hi

I am trying to get elastalert up and running but having some trouble. (sorry its my first time)

I am running the following

OS: Centos  7.2.1511
Python: Python 2.7.5

I have installed the package as follows

yum install 'git','python-pip','python-blist','python-simplejson','libyaml','libyaml-devel'
/bin/git clone https://github.com/Yelp/elastalert.git /opt/elastalert
/bin/easy_install -U setuptools
/bin/pip install --upgrade pip
/bin/python /opt/elastalert/setup.py install
/bin/pip install -r /opt/elastalert/requirements.txt

I now try to create the index but get the following

[root@log01 elastalert]# elastalert-create-index
Traceback (most recent call last):
  File "/bin/elastalert-create-index", line 9, in <module>
    load_entry_point('elastalert==0.0.95', 'console_scripts', 'elastalert-create-index')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2570, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2230, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2236, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named elastalert.create_index

I have got around this particular issue by manually running the .py directly however I am getting the same issue on each elastalert-* command I run with the same errors.

Any help is appreciated

Thanks

**Comment by Qmando** [comment]
You can

**Comment by rhysxevans** [comment]
Hi

Thanks, see below

[root@log01 elastalert]#  python -m elastalert.elastalert
/bin/python: No module named elastalert


[root@log01 elastalert]#  pip install elastalert
Requirement already satisfied (use --upgrade to upgrade): elastalert in /opt/elastalert
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): elasticsearch in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): jira==0.32 in /usr/lib/python2.7/site-packages/jira-0.32-py2.7.egg (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): jsonschema in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): mock in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): PyStaticConfiguration in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python2.7/site-packages/PyYAML-3.11-py2.7-linux-x86_64.egg (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): simplejson in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): boto in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): botocore in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): blist in /usr/lib64/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): croniter in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): configparser in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): aws-requests-auth in /usr/lib/python2.7/site-packages (from elastalert)
Requirement already satisfied (use --upgrade to upgrade): urllib3<2.0,>=1.8 in /usr/lib/python2.7/site-packages (from elasticsearch->elastalert)
Requirement already satisfied (use --upgrade to upgrade): requests>=1.2.3 in /usr/lib/python2.7/site-packages (from jira==0.32->elastalert)
Requirement already satisfied (use --upgrade to upgrade): requests_oauthlib>=0.3.3 in /usr/lib/python2.7/site-packages (from jira==0.32->elastalert)
Requirement already satisfied (use --upgrade to upgrade): tlslite>=0.4.4 in /usr/lib/python2.7/site-packages (from jira==0.32->elastalert)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /usr/lib/python2.7/site-packages (from jira==0.32->elastalert)
Requirement already satisfied (use --upgrade to upgrade): jmespath<1.0.0,>=0.7.1 in /usr/lib/python2.7/site-packages/jmespath-0.9.0-py2.7.egg (from botocore->elastalert)
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.10 in /usr/lib/python2.7/site-packages/docutils-0.12-py2.7.egg (from botocore->elastalert)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from croniter->elastalert)
Requirement already satisfied (use --upgrade to upgrade): oauthlib>=0.6.2 in /usr/lib/python2.7/site-packages (from requests_oauthlib>=0.3.3->jira==0.32->elastalert)
[root@log01 elastalert]# ^C
[root@log01 elastalert]#   python -m elastalert.elastalert
/bin/python: No module named elastalert

**Comment by rhysxevans** [comment]
Hi

Sorry for just dumping text I forgot the pip install -e .  command output

[root@log01 elastalert]# pip install -e .
Obtaining file:///opt/elastalert
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): elasticsearch in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): jira==0.32 in /usr/lib/python2.7/site-packages/jira-0.32-py2.7.egg (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): jsonschema in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): mock in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): PyStaticConfiguration in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python2.7/site-packages/PyYAML-3.11-py2.7-linux-x86_64.egg (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): simplejson in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): boto in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): botocore in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): blist in /usr/lib64/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): croniter in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): configparser in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): aws-requests-auth in /usr/lib/python2.7/site-packages (from elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): urllib3<2.0,>=1.8 in /usr/lib/python2.7/site-packages (from elasticsearch->elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): requests>=1.2.3 in /usr/lib/python2.7/site-packages (from jira==0.32->elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): requests_oauthlib>=0.3.3 in /usr/lib/python2.7/site-packages (from jira==0.32->elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): tlslite>=0.4.4 in /usr/lib/python2.7/site-packages (from jira==0.32->elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /usr/lib/python2.7/site-packages (from jira==0.32->elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): jmespath<1.0.0,>=0.7.1 in /usr/lib/python2.7/site-packages/jmespath-0.9.0-py2.7.egg (from botocore->elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.10 in /usr/lib/python2.7/site-packages/docutils-0.12-py2.7.egg (from botocore->elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from croniter->elastalert==0.0.95)
Requirement already satisfied (use --upgrade to upgrade): oauthlib>=0.6.2 in /usr/lib/python2.7/site-packages (from requests_oauthlib>=0.3.3->jira==0.32->elastalert==0.0.95)
Installing collected packages: elastalert
  Running setup.py develop for elastalert
Successfully installed elastalert-0.0.95
[root@log01 elastalert]#  python -m elastalert.elastalert
/bin/python: No module named elastalert
[root@log01 elastalert]#
[root@log01 elastalert]#
[root@log01 elastalert]# ls
build        config.yaml.exampl   config.yaml.exampls  docs        elastalert.egg-info  LICENSE   README.md             requirements.txt  setup.cfg  supervisord.conf.example  tox.ini
config.yaml  config.yaml.example  dist                 elastalert  example_rules        Makefile  requirements-dev.txt  rules             setup.py   tests
[root@log01 elastalert]# pwd
/opt/elastalert
[root@log01 elastalert]#

Thanks

**Comment by Qmando** [comment]
Pip thinks elastalert is already installed ``Requirement already satisfied (use --upgrade to upgrade): elastalert in /opt/elastalert`` but that isn't in your python path.

I think ``pip install .`` should install it in /usr/lib/python which is where python is trying to import from.

I would probably recommend you just use a python virtualenv: http://docs.python-guide.org/en/latest/dev/virtualenvs/

This will make it much simpler to manage your dependencies and change them around.

**Comment by rhysxevans** [comment]
Ok, this is odd.

just did a 

rm -Rf /opt/elasasearch
/bin/git clone https://github.com/Yelp/elastalert.git /opt/elastalert
/bin/python /opt/elastalert/setup.py install
/bin/pip install -r /opt/elastalert/requirements.txt

And now it seems to work , go figure (sure I had done that before)

Ill look at the virtualenvs

Thanks

**Comment by Qmando** [comment]
pip and setuptools are odd.
¯\_(ツ)_/¯
Glad you got it working.

**Comment by rocky4bmw** [comment]
@Qmando 

Can you please help me in fixing below error

I am using redhat 6.7 version
python 2.6.6

 when I executed command in elastalert directory I get below error
path /var/elkdirectory/elastalert

# python -m elastalert.elastalert
WARNING:elasticsearch:GET http://localhost:9200/logstash-*/_search?ignore_unavailable=true&timeout=50s [status:N/A request:0.008s]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 67, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 541, in urlopen
    raise ConnectionError('Connection failed.', e)
ConnectionError: ('Connection failed.', BadStatusLine('',))
WARNING:elasticsearch:GET http://localhost:9200/logstash-*/_search?ignore_unavailable=true&timeout=50s [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 67, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 541, in urlopen
    raise ConnectionError('Connection failed.', e)
ConnectionError: ('Connection failed.', BadStatusLine('',))
WARNING:elasticsearch:GET http://localhost:9200/logstash-*/_search?ignore_unavailable=true&timeout=50s [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 67, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 541, in urlopen
    raise ConnectionError('Connection failed.', e)
ConnectionError: ('Connection failed.', BadStatusLine('',))
WARNING:elasticsearch:GET http://localhost:9200/logstash-*/_search?ignore_unavailable=true&timeout=50s [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 67, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 541, in urlopen
    raise ConnectionError('Connection failed.', e)
ConnectionError: ('Connection failed.', BadStatusLine('',))
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/var/elkdirectory/elastalert/elastalert/elastalert.py", line 1426, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/var/elkdirectory/elastalert/elastalert/elastalert.py", line 1421, in main
    client = ElastAlerter(args)
  File "/var/elkdirectory/elastalert/elastalert/elastalert.py", line 94, in __init__
    self.conf = load_rules(self.args)
  File "elastalert/config.py", line 409, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file example_rules/example_new_term.yaml: Error initializing rule Example rule: Error searching for existing terms: ConnectionError('N/A', "('Connection failed.', BadStatusLine('',))", ConnectionError('Connection failed.', BadStatusLine('',)))

**Comment by rocky4bmw** [comment]
when I try to run  # elastalert-create-index
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/distribute-0.6.14-py2.6.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/distribute-0.6.14-py2.6.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/distribute-0.6.14-py2.6.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: botocore



config.yaml file details


# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: example_rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  minutes: 1

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 15

# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: localhost

# The elasticsearch port
es_port: 9200

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with SSL to elasticsearch
#use_ssl: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
es_username: xxx
es_password: xxx

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2
