### ISSUE TITLE
Sheild authentication failure

### ISSUE THREAD

**Issue by burdzz** [Yelp/elastalert#670]
I have been using elastalert for a while however recently moved to a new cluster with shield authentication. When running the elastalert-test-rule I get the results however then it fails due to a 401 issue. 

```
elasticsearch:/opt/elastalert# elastalert-test-rule rules/new_user.yaml --config config.yaml 
Successfully loaded newuser

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
Got 12 hits from the last 1 day

Available terms in first hit:
	name
	calendarTime
	@timestamp
	decorations.username
	decorations.host_uuid
	unixTime
	action
	columns.tty
	columns.name
	columns.pid
	columns.cmdline
	columns.host
	columns.user
	columns.time
	columns.root
	columns.cwd
	hostIdentifier

INFO:urllib3.connectionpool:Starting new HTTP connection (1): localhost
WARNING:elasticsearch:GET /logstash-*/_search?ignore_unavailable=true&timeout=50s [status:401 request:0.002s]
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.0.95', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 317, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 312, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 180, in run_elastalert
    load_modules(rule)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/config.py", line 300, in load_modules
    raise EAException('Error initializing rule %s: %s' % (rule['name'], e))
elastalert.util.EAException: Error initializing rule newuser: Error searching for existing terms: AuthenticationException(401, {u'header': {u'WWW-Authenticate': u'Basic realm="shield"'}, u'root_cause': [{u'header': {u'WWW-Authenticate': u'Basic realm="shield"'}, u'reason': u'missing authentication token for REST request [/logstash-*/_search?ignore_unavailable=true&timeout=50s]', u'type': u'security_exception'}], u'type': u'security_exception', u'reason': u'missing authentication token for REST request [/logstash-*/_search?ignore_unavailable=true&timeout=50s]'}, {u'status': 401, u'error': {u'header': {u'WWW-Authenticate': u'Basic realm="shield"'}, u'root_cause': [{u'header': {u'WWW-Authenticate': u'Basic realm="shield"'}, u'reason': u'missing authentication token for REST request [/logstash-*/_search?ignore_unavailable=true&timeout=50s]', u'type': u'security_exception'}], u'type': u'security_exception', u'reason': u'missing authentication token for REST request [/logstash-*/_search?ignore_unavailable=true&timeout=50s]'}})
```

I can not run elastalert anymore due to this issue, I can only test rules like above.

**Comment by burdzz** [comment]
same issue when I have moved to AWS ES and am using instance profiles to get authentication
```
root@elastalert:/opt/elastalert# elastalert-test-rule rules/new_user.yaml 
Successfully loaded New user

INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.credentials:Found credentials from IAM Role: 
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 
Got 7 hits from the last 1 day

Available terms in first hit:
	name
	calendarTime
	decorations.username
	decorations.host_uuid
	unixTime
	action
	columns.tty
	columns.name
	columns.type
	columns.pid
	columns.cmdline
	columns.host
	columns.user
	columns.time
	columns.root
	columns.cwd
	hostIdentifier
Included term _timestamp may be missing or null

INFO:urllib3.connectionpool:Starting new HTTP connection (1): search-osquery-beta-sifulian3bnvteaoilgv6pmgy4.us-west-2.es.amazonaws.com
WARNING:elasticsearch:GET /osquery/_search?ignore_unavailable=true&timeout=50s [status:403 request:0.011s]
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.0.95', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 317, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 312, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 180, in run_elastalert
    load_modules(rule)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/config.py", line 300, in load_modules
    raise EAException('Error initializing rule %s: %s' % (rule['name'], e))
elastalert.util.EAException: Error initializing rule New user: Error searching for existing terms: AuthorizationException(403, u'{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet on resource: es"}', {u'Message': u'User: anonymous is not authorized to perform: es:ESHttpGet on resource: es'})
```

**Comment by Qmando** [comment]
The AWS issue is an easily fixable bug, specific to ``type: new_term``. https://github.com/Yelp/elastalert/blob/master/elastalert/ruletypes.py#L524 isn't using the proper auth methods.

As for shield, I'm not too sure how it works, so I don't think the fix is quite as easy.

**Comment by burdzz** [comment]
I figured out the shield issue before I migrated over. It seemed to be how the users were provisioned on my instance. Thanks for the tip about the type: new_term - I will take a look at that tomorrow!

**Comment by burdzz** [comment]
I tried checking out the pull request which gave me the following error:
```Successfully loaded New user

Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.0.95', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 317, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 304, in run_rule_test
    hits = self.test_file(copy.deepcopy(rule_yaml), args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 50, in test_file
    es_config = ElastAlerter.build_es_conn_config(conf)
AttributeError: class ElastAlerter has no attribute 'build_es_conn_config'
```
Is this why it is still in progress? Thanks.

**Comment by Qmando** [comment]
@burdzz Try again. There was an issue where test_rule.py was not properly updated, but it should work now.

**Comment by burdzz** [comment]
The rule loads and connect's which is great! however seems to get stuck on a different error after completing that. 
```
root@elastalert:/opt/elastalert# elastalert-test-rule rules/new_user.yaml 
Successfully loaded New user

INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.credentials:Found credentials from IAM Role: rolename
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): -beta-sifulian3bnvteaoilgv6pmgy4.us-west-2.es.amazonaws.com
Got 36 hits from the last 1 day

Available terms in first hit:
	name
	calendarTime
	decorations.host_uuid
	unixTime
	action
	columns.tty
	columns.name
	columns.type
	columns.pid
	columns.cmdline
	columns.host
	columns.user
	columns.time
	columns.root
	columns.cwd
	hostIdentifier
Included term _timestamp may be missing or null

INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.credentials:Found credentials from IAM Role: rolename
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): search-beta-sifulian3bnvteaoilgv6pmgy4.us-west-2.es.amazonaws.com
INFO:elastalert:Found no values for columns.user
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.credentials:Found credentials from IAM Role: rolename
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): search-beta-sifulian3bnvteaoilgv6pmgy4.us-west-2.es.amazonaws.com
INFO:elastalert:Queried rule New user from 2016-09-11 23:54 UTC to 2016-09-12 00:39 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 00:39 UTC to 2016-09-12 01:24 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 01:24 UTC to 2016-09-12 02:09 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 02:09 UTC to 2016-09-12 02:54 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 02:54 UTC to 2016-09-12 03:39 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 03:39 UTC to 2016-09-12 04:24 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 04:24 UTC to 2016-09-12 05:09 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 05:09 UTC to 2016-09-12 05:54 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 05:54 UTC to 2016-09-12 06:39 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 06:39 UTC to 2016-09-12 07:24 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 07:24 UTC to 2016-09-12 08:09 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 08:09 UTC to 2016-09-12 08:54 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 08:54 UTC to 2016-09-12 09:39 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 09:39 UTC to 2016-09-12 10:24 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 10:24 UTC to 2016-09-12 11:09 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 11:09 UTC to 2016-09-12 11:54 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 11:54 UTC to 2016-09-12 12:39 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 12:39 UTC to 2016-09-12 13:24 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 13:24 UTC to 2016-09-12 14:09 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 14:09 UTC to 2016-09-12 14:54 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 14:54 UTC to 2016-09-12 15:39 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 15:39 UTC to 2016-09-12 16:24 UTC: 12 / 12 hits
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.0.95', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 317, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 312, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/test_rule.py", line 234, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/elastalert.py", line 496, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/elastalert.py", line 374, in run_query
    data = self.get_hits(rule, start, end, index, scroll)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/elastalert.py", line 267, in get_hits
    hits = self.process_hits(rule, hits)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/elastalert.py", line 211, in process_hits
    set_es_key(hit['_source'], rule['timestamp_field'], rule['ts_to_dt'](ts))
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.95-py2.7.egg/elastalert/util.py", line 108, in ts_to_dt
    dt = dateutil.parser.parse(timestamp)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 743, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 300, in parse
    res = self._parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 358, in _parse
    l = _timelex.split(timestr)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 139, in split
    return list(cls(s))
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 136, in next
    return self.__next__()  # Python 2.x support
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 130, in __next__
    token = self.get_token()
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 61, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by Qmando** [comment]
Osquery data? :)

Are you using ``timestamp_field: _timestamp``?

This looks like it's missing a timestamp field where it expects one. It probably shouldn't crash like this, but maybe try adding to the filters
```
query:
  query_string:
    query: "_exists_: _timestamp"
```

**Comment by burdzz** [comment]
yes osquery data :) working on a big deployment of it :). 

yes I am using the `_timestamp` field and adding that as a separate query string it didn't crash. I expect this will be needed in every rule?

```
filter:
- query:
    query_string:
      query: '"_exists_: _timestamp"'
- query:
    query_string:
      query: 'name: "pack_incident-response_logged_in_users"'
```

**Comment by Qmando** [comment]
Right now, having the timestamp field in *every* document that matches the filters is a requirement, because there's a ton of code (like what caused that error) that expects the timestamp and doesn't do any error checking.

**Comment by burdzz** [comment]
When I include that filter for the_timestamp option although it doesn't crash it doesn't provide any hits. 
```
root@elastalert:/opt/elastalert# elastalert-test-rule rules/new_user.yaml 
Successfully loaded New user

INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.credentials:Found credentials from IAM Role: 
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): -beta-sifulian3bnvteaoilgv6pmgy4.us-west-2.es.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.credentials:Found credentials from IAM Role: 
INFO:elastalert:Found no values for columns.user
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.credentials:Found credentials from IAM Role: osquery-elastalert
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): -beta-sifulian3bnvteaoilgv6pmgy4.us-west-2.es.amazonaws.com
INFO:elastalert:Queried rule New user from 2016-09-12 00:23 UTC to 2016-09-12 01:08 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 01:08 UTC to 2016-09-12 01:53 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 01:53 UTC to 2016-09-12 02:38 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 02:38 UTC to 2016-09-12 03:23 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 03:23 UTC to 2016-09-12 04:08 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 04:08 UTC to 2016-09-12 04:53 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 04:53 UTC to 2016-09-12 05:38 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 05:38 UTC to 2016-09-12 06:23 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 06:23 UTC to 2016-09-12 07:08 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 07:08 UTC to 2016-09-12 07:53 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 07:53 UTC to 2016-09-12 08:38 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 08:38 UTC to 2016-09-12 09:23 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 09:23 UTC to 2016-09-12 10:08 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 10:08 UTC to 2016-09-12 10:53 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 10:53 UTC to 2016-09-12 11:38 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 11:38 UTC to 2016-09-12 12:23 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 12:23 UTC to 2016-09-12 13:08 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 13:08 UTC to 2016-09-12 13:53 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 13:53 UTC to 2016-09-12 14:38 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 14:38 UTC to 2016-09-12 15:23 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 15:23 UTC to 2016-09-12 16:08 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 16:08 UTC to 2016-09-12 16:53 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 16:53 UTC to 2016-09-12 17:38 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 17:38 UTC to 2016-09-12 18:23 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 18:23 UTC to 2016-09-12 19:08 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 19:08 UTC to 2016-09-12 19:53 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 19:53 UTC to 2016-09-12 20:38 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 20:38 UTC to 2016-09-12 21:23 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 21:23 UTC to 2016-09-12 22:08 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 22:08 UTC to 2016-09-12 22:53 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 22:53 UTC to 2016-09-12 23:38 UTC: 0 / 0 hits
INFO:elastalert:Queried rule New user from 2016-09-12 23:38 UTC to 2016-09-13 00:23 UTC: 0 / 0 hits

Would have written the following documents to elastalert_status:

elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2016, 9, 13, 0, 23, 0, 555441, tzinfo=tzutc()), 'rule_name': 'New user', 'starttime': datetime.datetime(2016, 9, 12, 0, 23, 0, 323665, tzinfo=tzutc()), 'endtime': datetime.datetime(2016, 9, 13, 0, 23, 0, 323665, tzinfo=tzutc()), 'time_taken': 0.2279949188232422}
```

**Comment by Qmando** [comment]
You added an extra set of quotation marks.
``query: '"_exists_: _timestamp"'`` should be ``query: "_exists_: _timestamp"``

**Comment by burdzz** [comment]
when I write the query that way it crashes the same as above.

**Comment by Qmando** [comment]
Hmm. Is _timestamp part of _source? Maybe since you've prefixed it with an underscore it's not showing up in the data. You could use calendarTime or unixTime instead.

**Comment by burdzz** [comment]
what would I have to modify to use either of those? just the timestamp_field?

**Comment by Qmando** [comment]
Try adding
```
timestamp_field: unixTime
timestamp_type: unix
```

**Comment by burdzz** [comment]
that was successful. thanks so much @Qmando!
