### ISSUE TITLE
Unable to execute elastalert-create-index

### ISSUE THREAD

**Issue by rocky4bmw** [Yelp/elastalert#677]
I have installed logstash, Kibana and ES along with searchguard on same server 

I tried following link http://elastalert.readthedocs.io/en/latest/running_elastalert.html#tutorial

at step when I execute   "elastalert-create-index" command  it gives below error

elastalert-create-index
Traceback (most recent call last):
  File "/usr/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/distribute-0.6.14-py2.6.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/distribute-0.6.14-py2.6.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/distribute-0.6.14-py2.6.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: botocore

*********************************************************************

python --version
Python 2.6.6

python-pip 7.1.0-1.el6

*******************************************************************
config.yaml file

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: example_rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  minutes: 1

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 15

# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: localhost

# The elasticsearch port
es_port: 9200

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with SSL to elasticsearch
#use_ssl: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
es_username: xxx
es_password: xxx

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

Can anyone help me here on how to get this working?

**Comment by rocky4bmw** [comment]
@jamesls
Now I am getting this error can you please help me

elastalert-create-index
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2793, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 673, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 576, in resolve
pkg_resources.DistributionNotFound: mock
****************************************************************************************************
 pip install mock
Collecting mock
/usr/local/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting six>=1.9 (from mock)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock)
  Using cached pbr-1.10.0-py2.py3-none-any.whl
Installing collected packages: funcsigs, six, pbr, mock
Successfully installed funcsigs-1.0.2 mock-2.0.0 pbr-1.10.0 six-1.10.0
/usr/local/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by floragunncom** [comment]
[Get python working with Search Guard](https://gist.github.com/floragunncom/9319a994ae09df64b2a173128f745ed2)
