### ISSUE TITLE
TypeError: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#714]
hi all,
I try using command alert ,but got the error as below,

```
# python -m elastalert.elastalert --config ./config.yaml --rule ./rules/linkup_test.yaml --verbose

/usr/local/lib/python2.7/dist-packages/MySQL_python-1.2.2-py2.7-linux-  x86_64.egg/MySQLdb/__init__.py:34: DeprecationWarning: the sets module is deprecated
INFO:elastalert:Starting up
INFO:elastalert:Found expired previous run for Test rule at 2016-09-20 05:58:59.749773+00:00
INFO:elastalert:Queried rule Test rule from 2016-09-20 14:21 CST to 2016-09-20 14:26 CST: 118 hits
ERROR:root:Traceback (most recent call last):
  File " ./elastalert/elastalert/elastalert.py", line 913, in alert
return self.send_alert(matches, rule, alert_time=alert_time)
  File "./elastalert/elastalert/elastalert.py", line 987, in send_alert
alert.alert(matches)
 File "elastalert/alerts.py", line 668, in alert
subp = subprocess.Popen(command, stdin=subprocess.PIPE, shell=self.shell)
File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
TypeError: execv() arg 2 must contain only strings
```

part of my rule about command alert as below,

```
 alert:
 - "command"
 command: ["./code/alert.sh","%(msg)s","%(user)s","%(ip)s","%(timestamp)s"]
```

Thanks by advance,

**Comment by Qmando** [comment]
Hmm. This is very strange. Could you add this print statement and try to reproduce?
```
--- a/elastalert/alerts.py
+++ b/elastalert/alerts.py
@@ -659,6 +659,7 @@ class CommandAlerter(Alerter):
         # Format the command and arguments
         try:
+            print repr(self.rule['command'])
             command = [command_arg % matches[0] for command_arg in self.rule['command']]
+            print repr(command)
             self.last_command = command
         except KeyError as e:
             raise EAException("Error formatting command: %s" % (e))
```

**Comment by woodkan** [comment]
hi, I met the same problem, event I tried to use new_style. I have added the print stgatement  and below is the error messages:
```
'/etc/elastalert/sendsms-http.sh', 'jianwu', '{match[message]}']
['/etc/elastalert/sendsms-http.sh', 'jianwu', '-DevIP=172.31.10.11; Sess[172.16.1.1/172.16.1.2, LD/RD:98/16411, Interface:XGE1/0/23, SessType:Ctrl, LinkType:INET], Ver:1, Sta: UP->DOWN, Diag: 1\x00']
ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 1066, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 1143, in send_alert
    alert.alert(matches)
  File "/usr/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/alerts.py", line 790, in alert
    subp = subprocess.Popen(command, stdin=subprocess.PIPE, shell=self.shell)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

ERROR:root:Uncaught exception running rule Network Devices Link Up/Down: execv() arg 2 must contain only strings
```

**Comment by Qmando** [comment]
I think the issue is that you have \x00 (null byte) in your command.
``'-DevIP=172.31.10.11; Sess[172.16.1.1/172.16.1.2, LD/RD:98/16411, Interface:XGE1/0/23, SessType:Ctrl, LinkType:INET], Ver:1, Sta: UP->DOWN, Diag: 1\x00'``

You can verify this by manually running the command without the \x00 at the end.
```
>>> import subprocess
>>> command = ['/etc/elastalert/sendsms-http.sh', 'jianwu', '-DevIP=172.31.10.11; Sess[172.16.1.1/172.16.1.2, LD/RD:98/16411, Interface:XGE1/0/23, SessType:Ctrl, LinkType:INET], Ver:1, Sta: UP->DOWN, Diag: 1']
>>> subp = subprocess.Popen(command, shell=False)
```

You can fix this exact issue by changing
```command = [command_arg.format(match=matches[0]) for command_arg in self.rule['command']]```
to 
```command = [command_arg.format(match=matches[0]).strip() for command_arg in self.rule['command']]```

I'll consider adding this or other normalizing functions to the command alerter.

**Comment by woodkan** [comment]
Thanks a lot. It works well
