### ISSUE TITLE
pin dependency on elastalert

### ISSUE THREAD

**Issue by beaugunderson** [Yelp/elastalert#770]
5.0 was just released which is backwards-incompatible and only supports ES 5.x servers. New installs of elastalert will get this version and explode (like my dockerized version just did).

From the `python-elastalert` docs:

```
The recommended way to set your requirements in your setup.py or requirements.txt is:

# Elasticsearch 2.x
elasticsearch>=2.0.0,<3.0.0
```

**Comment by nicorevin** [comment]
@beaugunderson second it.

Traceback of mine for instance:

```
ERROR:root:Uncaught exception running rule Somerule: create() takes at least 5 arguments (5 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1409, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1406, in main
    client.start()
  File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 706, in start
    self.run_all_rules()
  File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 747, in run_all_rules
    self.handle_uncaught_exception(e, rule)
  File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1293, in handle_uncaught_exception
    self.handle_error('Uncaught exception running rule %s: %s' % (rule['name'], exception), {'rule': rule['name']})
  File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1288, in handle_error
    self.writeback('elastalert_error', body)
  File "/root/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1018, in writeback
    doc_type=doc_type, body=body)
  File "/root/.local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 71, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: create() takes at least 5 arguments (5 given)
```

**Comment by vineet-rh** [comment]
+1 

Spent time dealing with the same error. Would be nice to pin this version.

**Comment by ddrozdov** [comment]
This has been fixed in `master` by https://github.com/Yelp/elastalert/commit/bc3b12a303d92d74c0ea6f129ff003733bc76f94

@Qmando would you please release a new version since all non-`latest` Docker images are broken now.

**Comment by Qmando** [comment]
Sure
