### ISSUE TITLE
Getting Dependency Errors on First Run

### ISSUE THREAD

**Issue by matthillary** [Yelp/elastalert#776]
I followed the instructions here: 

http://elastalert.readthedocs.io/en/latest/running_elastalert.html#tutorial

But i get the following failures (also had a failure from `import kibana` (had to install manually): 

```
$ python elastalert/elastalert.py
Traceback (most recent call last):
  File "elastalert/elastalert.py", line 20, in <module>
    from alerts import DebugAlerter
  File "/home/<user>/Git/elastalert/elastalert/alerts.py", line 19, in <module>
    from jira.client import JIRA
  File "build/bdist.macosx-10.12-intel/egg/jira/__init__.py", line 5, in <module>

  File "build/bdist.macosx-10.12-intel/egg/jira/config.py", line 17, in <module>
    from util import dt_to_ts_with_format
  File "build/bdist.macosx-10.12-intel/egg/jira/client.py", line 30, in <module>
ImportError: No module named html_parser
```

What am I doing wrong?

**Comment by matthillary** [comment]
running again on my linux box and will report if has errors.

**Comment by Qmando** [comment]
Looks like https://github.com/pycontribs/jira/issues/38

What version of jira-python do you have? Looks to be fixed in this PR https://github.com/pycontribs/jira/commit/d9ea51bfd658247b94d02a4fd15c3f41ccad396c

**Comment by matthillary** [comment]
wow thanks for the quick response!

installed it on my linux box + seems to have 0 issues. getting an alert setup to check and make sure all's good.

**Comment by matthillary** [comment]
no problems!
