### ISSUE TITLE
support other timestamp fields

### ISSUE THREAD

**Issue by Thermi** [Yelp/elastalert#778]
The ES indices that I need to alert on do not use the '@timestamp' field for timestamps. They use other fields for timestamps.  As far as I observed the errors and understood the source code of elastalert,
the field name for the timestamps are not variable. I am unable to find a way to work around this issue.
Is there a way we can easily add this feature?

This is the error I get:

```
Successfully loaded CPU usage

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 52.212.81.107
WARNING:elasticsearch:GET http://52.212.81.107:9200/heapster-cpu-*/_search?ignore_unavailable=true&size=1 [status:400 request:0.026s]
Error running your filter:
RequestError(400, u'search_phase_execution_exception', {u'status': 400, u'error': {u'failed_shards': [{u'node': u'50ZZ5unvTMaU8KIZaSCo2g', u'index': u'heapster-2016.10.26', u'reason': {u'reason': u'No mapping found for [@timestamp] in order to sort on', u'type': u'search_parse_exception'}, u'shard': 0}], u'root_cause': [{u'reason': u'No mapping found for [@timestamp] in order to sort on', u'type': u'search_parse_exception'}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'}})
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 52.212.81.107
WARNING:elasticsearch:GET http://52.212.81.107:9200/heapster-cpu-*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.031s]
ERROR:root:Error running query: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_error - {'message': "Error running query: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')", 'traceback': ['Traceback (most recent call last):', '  File "/opt/elastalert-monitoring/.local/lib/python2.7/site-packages/elastalert-0.1.2-py2.7.egg/elastalert/elastalert.py", line 250, in get_hits', "    res = self.current_es.search(scroll=scroll_keepalive, index=index, size=rule['max_query_size'], body=query, ignore_unavailable=True, **extra_args)", '  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 539, in search', "    doc_type, '_search'), params=params, body=body)", '  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 327, in perform_request', '    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 84, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 113, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')"], 'data': {'rule': 'CPU usage'}}
```

**Comment by Thermi** [comment]
Okay, I looked in the manual previously, but did not find the `timestamp_field` option. I think this should be featured more prominently.
