### ISSUE TITLE
es_conn_timeout not set in config.yaml.example

### ISSUE THREAD

**Issue by magic69** [Yelp/elastalert#783]
When running the tutorial example:
`python -m elastalert.elastalert --verbose --rule example_frequency.yaml --debug` 
elastalert says:

```INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/elastalert/elastalert/elastalert/elastalert.py", line 1409, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/elastalert/elastalert/elastalert/elastalert.py", line 1404, in main
    client = ElastAlerter(args)
  File "/home/elastalert/elastalert/elastalert/elastalert.py", line 115, in __init__
    self.writeback_es = elasticsearch_client(self.conf)
  File "elastalert/util.py", line 254, in elasticsearch_client
    es_conn_conf = build_es_conn_config(conf)
  File "elastalert/util.py", line 289, in build_es_conn_config
    parsed_conf['es_conn_timeout'] = conf['es_conn_timeout']
KeyError: 'es_conn_timeout'```

**Comment by Qmando** [comment]
Oops, sorry about this. Fixed on master now.

**Comment by magic69** [comment]
I was just preparing a pull request, thanks for the fix !
