### ISSUE TITLE
Error while pulling records unixms_to_dt

### ISSUE THREAD

**Issue by vaibhavkhanduja** [Yelp/elastalert#793]
While pulling records from ES with field tagged as "Date" the elastalart throwing exception as below. Apparently, this code worked with earlier version and Date filed marked should have returned a value equivalent to a number. Any suggestions?

2016-11-03 00:05:04,223 DEBG 'elastalert' stderr output:
ERROR:root:Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 743, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/opt/elastalert/elastalert/elastalert.py", line 532, in run_rule
    if not self.run_query(rule, rule['starttime'], endtime):
  File "/opt/elastalert/elastalert/elastalert.py", line 380, in run_query
    data = self.get_hits(rule, start, end, index, scroll)
  File "/opt/elastalert/elastalert/elastalert.py", line 271, in get_hits
    hits = self.process_hits(rule, hits)
  File "/opt/elastalert/elastalert/elastalert.py", line 211, in process_hits
    set_es_key(hit['_source'], rule['timestamp_field'], rule['ts_to_dt'](ts))
  File "elastalert/util.py", line 219, in unixms_to_dt
    return unix_to_dt(float(ts) / 1000)
ValueError: invalid literal for float(): 2016-11-03T06:46:29.344Z

**Comment by Qmando** [comment]
Did you set ``timestamp_format: unix``? Your documents appear to have ISO8601 (default) timestamp format, so the conversion is failing.
