### ISSUE TITLE
[beginner ] new_term rule 

### ISSUE THREAD

**Issue by mza97** [Yelp/elastalert#794]
Hello,

I'm new to elastalert, i'm getting logs from twitter, i try to get all the  new values from "place.country_code" field, my rule conf contains:

type: new_term
index: twitter
fields:
 - place.country_code
terms_window_size:
  days: 90
use_terms_query: true
doc_type: logs
query_key: "place.country_code"
filter: []

but when i run my logstash and elastalert, i'm getting alerts from place.country_code values that i already get, it's like it ignores the terms_window_size. (if I let the two run it works and alerts only on new values).

**Comment by Qmando** [comment]
Does it show ``Found X unique values for place.country_code`` when it starts? You can add ``--verbose`` if you aren't getting that line at all. Is that number 0?

**Comment by mza97** [comment]
Thank you for you reply,
I use --verbose but i don't get Found X unique values for place.country_code.
I don't get initial values: INFO:elastalert:Found no values for place.country_code
"place.country_code" has values like "ES", "US, "FR"... 

[...] 
INFO:elastalert:Ran Example rule from 2016-11-03 16:08 UTC to 2016-11-04 08:35 UTC: 6 query hits, 6 matches, 6 alerts sent
WARNING:root:Querying from 2016-11-03 16:08 UTC to 2016-11-04 08:35:11.965552+00:00 took longer than 0:00:05!
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:35 UTC to 2016-11-04 08:35 UTC: 0 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:35 UTC to 2016-11-04 08:35 UTC: 0 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:35 UTC to 2016-11-04 08:35 UTC: 0 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:35 UTC to 2016-11-04 08:35 UTC: 0 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:35 UTC to 2016-11-04 08:35 UTC: 0 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:35 UTC to 2016-11-04 08:35 UTC: 1 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:35 UTC to 2016-11-04 08:35 UTC: 3 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:35 UTC to 2016-11-04 08:35 UTC: 2 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:35 UTC to 2016-11-04 08:35 UTC: 1 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:35 UTC to 2016-11-04 08:36 UTC: 6 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:36 UTC to 2016-11-04 08:36 UTC: 1 buckets
INFO:elastalert:Queried rule Example rule from 2016-11-04 08:36 UTC to 2016-11-04 08:36 UTC: 0 buckets
INFO:elastalert:Alert sent to Slack
INFO:elastalert:Alert sent to Slack
INFO:elastalert:Alert sent to Slack
INFO:elastalert:Alert sent to Slack
INFO:elastalert:Alert sent to Slack
INFO:elastalert:Alert sent to Slack
INFO:elastalert:Alert sent to Slack
INFO:elastalert:Alert sent to Slack

**Comment by mza97** [comment]
I tried with --start NOW et got:

Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/tech/cloud/elastalert/elastalert-master/elastalert/elastalert.py", line 1409, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/tech/cloud/elastalert/elastalert-master/elastalert/elastalert.py", line 1404, in main
    client = ElastAlerter(args)
  File "/tech/cloud/elastalert/elastalert-master/elastalert/elastalert.py", line 92, in __init__
    self.conf = load_rules(self.args)
  File "elastalert/config.py", line 429, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file example_rules/example_new_term.yaml: Error initializing rule Example rule: Error searching for existing terms: ValueError(u'Unknown string format',)

**Comment by q2dg** [comment]
Well, I think issues like this, after more than two years, could be closed. It's necessary a cleanup.
