### ISSUE TITLE
Installation error on OEL 6

### ISSUE THREAD

**Issue by oazabir** [Yelp/elastalert#837]
During installation I am getting this error:

```
Installed /tmp/easy_install-V7APwZ/mock-2.0.0/pbr-1.10.0-py2.6.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/tmp/easy_install-V7APwZ/mock-2.0.0/pbr-1.10.0-py2.6.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/tmp/easy_install-V7APwZ/mock-2.0.0/pbr-1.10.0-py2.6.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/tmp/easy_install-V7APwZ/mock-2.0.0/pbr-1.10.0-py2.6.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
AttributeError: 'module' object has no attribute 'evaluate_marker'
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-V7APwZ/mock-2.0.0/setup.cfg: AttributeError: 'module' object has no attribute 'evaluate_marker'
```

Could you help me solve this problem?

I have tried on Python 2.6.6

**Comment by oazabir** [comment]
I was able to get it installed using:

pip install -r requirements.txt && python setup.py install

**Comment by Lushali** [comment]
For requirements.txt, do you mean we need to replace it with a specific file?  In this question, is it /tmp/easy_install-V7APwZ/mock-2.0.0/pbr-1.10.0-py2.6.egg?

**Comment by Qmando** [comment]
I don't understand your question @Lushali. Clone the repo, install pip if you don't have it, then run ``pip install -r requirements.txt``. There may be some development libraries you need to build packages like cryptography requires libssl-dev. If you hit errors, search for the libraries installation instructions on google.

Please note that I've recently removed official support for Python2.6. It should still work, but may not in the future.

**Comment by Lushali** [comment]
@Qmando Thanks, I got it.
