### ISSUE TITLE
Error in using elastalert  "nextchar = self.instream.read(1)"

### ISSUE THREAD

**Issue by Tyoshi14** [Yelp/elastalert#864]
I am the beginner of elastalert and when I begin to test the most simple rule I write to get some basic info, I  get the following error。 Is there something wrong with elastalert ? 

**Error:**
INFO:elastalert:Queried rule IES crash rate Alert from 2017-01-12 02:29 CST to 2017-01-12 02:44 CST: 10000 / 10000 hits (scrolling..)
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.4', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.4-py2.7.egg/elastalert/test_rule.py", line 322, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.4-py2.7.egg/elastalert/test_rule.py", line 317, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.4-py2.7.egg/elastalert/test_rule.py", line 236, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.4-py2.7.egg/elastalert/elastalert.py", line 528, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.4-py2.7.egg/elastalert/elastalert.py", line 380, in run_query
    data = self.get_hits(rule, start, end, index, scroll)
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.4-py2.7.egg/elastalert/elastalert.py", line 271, in get_hits
    hits = self.process_hits(rule, hits)
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.4-py2.7.egg/elastalert/elastalert.py", line 211, in process_hits
    set_es_key(hit['_source'], rule['timestamp_field'], rule['ts_to_dt'](ts))
  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.4-py2.7.egg/elastalert/util.py", line 108, in ts_to_dt
    dt = dateutil.parser.parse(timestamp)
  File "/usr/local/lib/python2.7/site-packages/dateutil/parser.py", line 743, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/dateutil/parser.py", line 300, in parse
    res = self._parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/dateutil/parser.py", line 358, in _parse
    l = _timelex.split(timestr)
  File "/usr/local/lib/python2.7/site-packages/dateutil/parser.py", line 139, in split
    return list(cls(s))
  File "/usr/local/lib/python2.7/site-packages/dateutil/parser.py", line 136, in next
    return self.__next__()  # Python 2.x support
  File "/usr/local/lib/python2.7/site-packages/dateutil/parser.py", line 130, in __next__
    token = self.get_token()
  File "/usr/local/lib/python2.7/site-packages/dateutil/parser.py", line 61, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'int' object has no attribute 'read'

And here is my filter
 filter:
- term:
    service: "hotsoon"

How should I solve the problem ?

**Comment by Qmando** [comment]
It seems you've got a unix (integer) timestamp. Try adding
```
timestamp_format: unix
```

**Comment by rlamarche** [comment]
The config key is `timestamp_type` and not `timestamp_format`.
See https://elastalert.readthedocs.io/en/latest/ruletypes.html#timestamp-type

**Comment by Qmando** [comment]
@rlamarche Oops, Thank you!
