### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by limelias** [Yelp/elastalert#879]
Hello,

When i run elastalert-test-rule rules/error.yaml, i get:

```
Successfully loaded Error Notifications

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): es
WARNING:elasticsearch:GET http://es:14900/ [status:N/A request:0.008s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 68, in perform_request
    response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-5, 'No address associated with hostname'))
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (2): es
WARNING:elasticsearch:GET http://es:14900/ [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 68, in perform_request
    response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-5, 'No address associated with hostname'))
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (3): es
WARNING:elasticsearch:GET http://es:14900/ [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 68, in perform_request
    response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-5, 'No address associated with hostname'))
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (4): es
WARNING:elasticsearch:GET http://es:14900/ [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 68, in perform_request
    response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-5, 'No address associated with hostname'))
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.4', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.4-py2.7.egg/elastalert/test_rule.py", line 324, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.4-py2.7.egg/elastalert/test_rule.py", line 319, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.4-py2.7.egg/elastalert/test_rule.py", line 232, in run_elastalert
    client = ElastAlerter(['--debug'])
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.4-py2.7.egg/elastalert/elastalert.py", line 116, in __init__
    self.five = self.is_five()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.4-py2.7.egg/elastalert/elastalert.py", line 125, in is_five
    info = self.writeback_es.info()
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 220, in info
    return self.transport.perform_request('GET', '/', params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 79, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', gaierror(-5, 'No address associated with hostname'))) caused by: ConnectionError(('Connection aborted.', gaierror(-5, 'No address associated with hostname')))
```

Im running elasticsearch v5 on localhost, port 9201. I'm on the support_es5 branch.

This is my config.yaml:

```
rules_folder: rules

run_every:
  minutes: 1

buffer_time:
  minutes: 15

es_host: localhost

es_port: 9201

alert_time_limit:
  days: 2

```

Where am I going wrong? 
Thankyou!

**Comment by limelias** [comment]
Update: I found where i went wrong, I forgot to add my --config in command line
