### ISSUE TITLE
Installation broken after latest commits (Failing with error pkg_resources.DistributionNotFound)

### ISSUE THREAD

**Issue by darshandzend** [Yelp/elastalert#928]
Judging by the error message and latest commit messages, I pointed my `HEAD` to `c663da20331695e9ac8a34fde79141dd00c9a2fe`. It works with this, so I'm guessing some succeeding commit broke it.

# Installation
I started out with a fresh Ubuntu 16.04 docker container with python 2.7.12. Here's the steps I followed as a root:

1. Clone the project `git clone https://github.com/Yelp/elastalert.git`
2. Make sure pip is up-to-date
```
# pip install --upgrade pip
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 912kB/s
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-9.0.1
```
3. Run 
```
# python setup.py  install
      <Successful (zero return value) execution, will post output on request>
```
4. Run `pip install -r requirements.txt`, this fails with the following error:
```
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/stomp.py-4.1.17-py2.7.egg'
```
I'd seen this yesterday too. This seems a benign error since I could run `elastalert` commands yesterday despite it.
5. Run `pip install elasticsearch>=5.0.0` (Produces no output)
6. Create config.yaml

# The problem
Running any `elastalert*` command results in the following:
```
# elastalert --help
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests-oauthlib==0.5.0' distribution was not found and is required by exotel
```

**Comment by andreyp1986** [comment]
To install version 5 of elasticsearch, you have to run:
pip install elasticsearch\>=5.0.0

If you run pip install elasticsearch>=5.0.0, latest version will be installed (5.2.0 currently), and the output of installation process will be thrown to file =5.0.0

**Comment by stillclimbing2** [comment]
I ran this and still get same error when executing any elastic* command
pip install elasticsearch\>=5.0.0

**Comment by Qmando** [comment]
I've got invalid Bash in the documentation, sorry about that. You need to add quotes.
``pip install "elasticsearch>=5.0.0"``

You probably have a file named =5.0.0 with pip output in it now. I'll fix that.

**Comment by Qmando** [comment]
Did you try ``pip install "requests-oauthlib==0.5.0"``?

If the exotel library has broken dependencies, I can remove it. I added it to master but have not released it yet. You can also just ``pip install elastalert`` instead of installing it from master.

**Comment by oarevalo** [comment]
I'm running into the same `exotel` error. This is from a fresh clone from Master.
I tried doing a `pip install elastalert` but when running `elastalert` from the shell, on the same directory as my project (where my config and rules are), I get the following error
```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 9, in <module>
    load_entry_point('elastalert==0.1.8', 'console_scripts', 'elastalert')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2362, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group,name),))
ImportError: Entry point ('console_scripts', 'elastalert') not found
```
Any ideas?

**Comment by Qmando** [comment]
I think that generally means you have a mismatch version between the pip and python binaries. I recommend using a virtualenv which gives you some better control over these things. 

From a relatively blank Linux install, you should be able to get everything working with 

```
root@6382cd528f33:/# apt-get install python2.7 python2.7-dev python-virtualenv python-pip
....
root@6382cd528f33:/# virtualenv --python=python2.7 venv
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in venv/bin/python2.7
Also creating executable in venv/bin/python
Installing setuptools, pip...done.
root@6382cd528f33:/# source venv/bin/activate
(venv)root@6382cd528f33:/# pip install elastalert
....
(venv)root@6382cd528f33:/# elastalert --help
usage: elastalert [-h] [--config CONFIG] [--debug] [--rule RULE]
                  [--silence SILENCE] [--start START] [--end END] [--verbose]
                  [--pin_rules] [--es_debug] [--es_debug_trace ES_DEBUG_TRACE]
```

**Comment by Qmando** [comment]
If you get
```
Traceback (most recent call last):
   ...
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests-oauthlib==0.5.0
```
You need to run ``pip install "requests-oauthlib==0.5.0"`` to fix it.


I'll add ``requests-oauthlib`` to requirements.txt. It seems that something (exotel maybe) requires it but does not list it as a requirement.

**Comment by oarevalo** [comment]
@Qmando Thanks, installing elastalert inside a virtualenv worked. I can get it running, although now it complains about a different error:
```
RequestError: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on')
```
This shows up every few seconds.

On the other error, my problem was not with requests-oauthlib, it was with `'requests==2.2.1'`, but using the same idea (`pip install "requests==2.2.1") allowed it to work. So I got the git version working too, but it shows now the same error as with the `elastalert` package.

```
ERROR:root:Error finding recent pending alerts: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on') {'sort': {'alert_time': {'order': 'asc'}}, 'query': {'bool': {'filter': {'range': {'alert_time': {'to': '2017-03-20T23:07:12.874146Z', 'from': '2017-03-18T23:07:12.874080Z'}}}, 'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}}}}
Traceback (most recent call last):
  File "/home/jenkins_local/elastalert/env/local/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 1214, in find_recent_pending_alerts
    size=1000)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 569, in search
    doc_type, '_search'), params=params, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 89, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 122, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on')
```

**Comment by Qmando** [comment]
You must run ``elastalert-create-index`` as per http://elastalert.readthedocs.io/en/latest/running_elastalert.html#setting-up-elasticsearch

**Comment by Qmando** [comment]
Or, check out this experimental branch 😄 
https://github.com/Yelp/elastalert/pull/945

**Comment by oarevalo** [comment]
@Qmando yup, that did it... with a twist. I *think* that the first time I ran `elastalert-create-index` with the broken config/dependencies somehow it created a bad index since I was able to confirm its existence in elasticsearch directly. 

However, this index may have been corrupt in some way. So I manually deleted the index and ran `elastalert-create-index` again, and now it works without errors!

**Comment by darshandzend** [comment]
@Qmando Hi, sorry for being late to respond. 

I added `pip install "requests-oauthlib==0.5.0"` to my installation procedure (and quoted "elasticsearch>=5.0.0") as you suggested. I then got the following error:
```
pkg_resources.DistributionNotFound: The 'requests==2.2.1' distribution was not found and is required by exotel
```

I finally got everything working by installing `requests==2.2.1` as well. Here's the portion of my new Dockerfile ATM:

```
RUN git clone https://github.com/Yelp/elastalert.git
WORKDIR /elastalert
RUN python setup.py install && \
    pip install -r requirements.txt || true && \
    pip install "elasticsearch>=5.0.0"

RUN pip install "requests==2.2.1"
RUN pip install "requests-oauthlib==0.5.0"
```

**Comment by wirecutter313** [comment]
Having a similer issue..  when I install requests = 2.2.1 I get this now

elastalert --help
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 9, in <module>
    load_entry_point('elastalert==0.1.8', 'console_scripts', 'elastalert')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 18, in <module>
    import kibana
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/kibana.py", line 4, in <module>
    from util import EAException
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/util.py", line 7, in <module>
    from auth import Auth
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/auth.py", line 5, in <module>
    from aws_requests_auth.aws_auth import AWSRequestsAuth
  File "/usr/local/lib/python2.7/dist-packages/aws_requests_auth/aws_auth.py", line 7, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,

**Comment by Qmando** [comment]
http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

Exotel claims it needs 2.2.1 but likely it will work with any version of requests.

**Comment by wirecutter313** [comment]
Yup, tried that too.. and I get an error around exotel if I try to run elastalert 

**root@server1:/etc/elastalert# pip install requests==2.6.0**
Collecting requests==2.6.0
  Using cached requests-2.6.0-py2.py3-none-any.whl
Installing collected packages: requests
  Found existing installation: requests 2.2.1
    Uninstalling requests-2.2.1:
      Successfully uninstalled requests-2.2.1
Successfully installed requests-2.6.0
**root@server1:/etc/elastalert# elastalert-test-rule --help**
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
_pkg_resources.DistributionNotFound: The 'requests==2.2.1' distribution was not found and is required by exotel_
root@server1:/etc/elastalert#

**Comment by Qmando** [comment]
You can get around the pkg_resources/dist-packages crap by just calling the python directly.

``python -m elastalert.test_rule`` is exactly the same as ``elastalert-test-rule``.
``python -m elastalert.elastalert`` is the same as ``elastalert``
etc, etc

**Comment by wirecutter313** [comment]
Ya it works fine like that. Thanks

**Comment by prayagupd** [comment]
I'm getting similar issue, 

```bash
ubuntu@ip-172-21-3-9:~$ elastalert-create-index
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests-oauthlib==0.5.0' distribution was not found and is required by exotel

```

installing requests-oauthlib

```bash
ubuntu@ip-172-21-3-9:~$ pip install "requests-oauthlib==0.5.0"
Collecting requests-oauthlib==0.5.0
  Downloading requests_oauthlib-0.5.0-py2.py3-none-any.whl
Collecting requests>=2.0.0 (from requests-oauthlib==0.5.0)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 1.9MB/s 
Collecting oauthlib>=0.6.2 (from requests-oauthlib==0.5.0)
  Downloading oauthlib-2.0.2.tar.gz (125kB)
    100% |████████████████████████████████| 133kB 5.3MB/s 
Building wheels for collected packages: oauthlib
  Running setup.py bdist_wheel for oauthlib ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/84/98/7a/fba7268f61097bea6081cbe5480bc439b38975748ea7684fd5
Successfully built oauthlib
Installing collected packages: requests, oauthlib, requests-oauthlib
Successfully installed oauthlib-0.7.2 requests-2.5.1 requests-oauthlib-0.4.2
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

#
ubuntu@ip-172-21-3-9:~$ elastalert-create-index
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.13.0 (/home/ubuntu/.local/lib/python2.7/site-packages), Requirement.parse('requests==2.2.1'), set(['exotel']))
```

installing requests==2.2.1

```
ubuntu@ip-172-21-3-9:~$ pip install "requests==2.2.1"
Collecting requests==2.2.1
  Downloading requests-2.2.1-py2.py3-none-any.whl (625kB)
    100% |████████████████████████████████| 634kB 1.7MB/s 
Installing collected packages: requests
Successfully installed requests-2.13.0
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

#still same error
ubuntu@ip-172-21-3-9:~$ elastalert-create-index
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.13.0 (/home/ubuntu/.local/lib/python2.7/site-packages), Requirement.parse('requests==2.2.1'), set(['exotel']))
```

**Comment by Qmando** [comment]
If you use ``python -m elastalert.create index`` instead of elastalert-create-index and ``python -m elastalert.elastalert`` instead of elastalert, it should work.

**Comment by prayagupd** [comment]
@Qmando 
`python -m elastalert.create index` does not work.

```bash
ubuntu@ip-172-21-3-9:~/workspace/tellher$ python -m elastalert.create index
/usr/bin/python: No module named elastalert.create
```

all I have is 

```bash
ubuntu@ip-172-21-3-9:~/workspace/tellher$ elastalert
elastalert                   elastalert-create-index      elastalert-rule-from-kibana  elastalert-test-rule        
```

**Comment by prayagupd** [comment]
Well, it worked for once I cleaned up the pip installations and reinstalled eveything.

```bash
pip freeze > requirement.txt
pip -r uninstall requirement.txt
```

```
elastalert-create-index 
Enter Elasticsearch host: 172.21.3.9
Enter Elasticsearch port: 9200
Use SSL? t/f: f
Enter optional basic-auth username (or leave blank): 
Enter optional basic-auth password (or leave blank): 
Enter optional Elasticsearch URL prefix (prepends a string to the URL of every request): 
New index name? (Default elastalert_status) alerting_metadata
Name of existing index to copy? (Default None) 
[2017-04-15T08:26:42,632][INFO ][o.e.c.m.MetaDataCreateIndexService] [sclogevents1] [alerting_metadata] creating index, cause [api], templates [], shards [5]/[1], mappings []
[2017-04-15T08:26:44,724][INFO ][o.e.c.m.MetaDataMappingService] [sclogevents1] [alerting_metadata/aOm8JSweR8-Us2iCE7yv-A] create_mapping [elastalert]
[2017-04-15T08:26:44,741][INFO ][o.e.c.m.MetaDataMappingService] [sclogevents1] [alerting_metadata/aOm8JSweR8-Us2iCE7yv-A] create_mapping [elastalert_status]
[2017-04-15T08:26:44,755][INFO ][o.e.c.m.MetaDataMappingService] [sclogevents1] [alerting_metadata/aOm8JSweR8-Us2iCE7yv-A] create_mapping [silence]
[2017-04-15T08:26:44,767][INFO ][o.e.c.m.MetaDataMappingService] [sclogevents1] [alerting_metadata/aOm8JSweR8-Us2iCE7yv-A] create_mapping [elastalert_error]
[2017-04-15T08:26:44,786][INFO ][o.e.c.m.MetaDataMappingService] [sclogevents1] [alerting_metadata/aOm8JSweR8-Us2iCE7yv-A] create_mapping [past_elastalert]
New index alerting_metadata created
Done!
```

**Comment by darshandzend** [comment]
There's no need for doing manual installation anymore. Just doing 
```
pip install elastalert
```
solves the problem.

Closing the issue.

**Comment by anjan-cele** [comment]
Hi @Qmando 

Whenever I am running my test example i.e example_frequency. I am getting following error :


Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'blist>=1.3.6' distribution was not found and is required by elastalert



However

When I check for 'blist>=1.3.6' installation. It is telling as : 

Requirement already satisfied: blist>=1.3.6 in /usr/local/lib/python3.5/dist-packages


What could be the problem?

Thanks
