### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by andreyp1986** [Yelp/elastalert#933]
When trying to install latest version of EA (0.1.8), I get this error:

> Installed /usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg
Processing dependencies for elastalert==0.1.8
Searching for requests==2.2.1
Reading https://pypi.python.org/simple/requests/
Best match: requests 2.2.1
Downloading https://pypi.python.org/packages/d1/0c/2dc2996268bc64b531a5a2dc6f4ec04552f3a8a2a86e88aeedcb92987741/requests-2.2.1.tar.gz#md5=ac27081135f58d1a43e4fb38258d6f4e
Processing requests-2.2.1.tar.gz
Writing /tmp/easy_install-OR0w1y/requests-2.2.1/setup.cfg
Running requests-2.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-OR0w1y/requests-2.2.1/egg-dist-tmp-isp4Tf
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    'stomp.py'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 740, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-OR0w1y/requests-2.2.1/setup.py", line 6, in <module>

  File "/tmp/easy_install-OR0w1y/requests-2.2.1/requests/__init__.py", line 53, in <module>
  File "/tmp/easy_install-OR0w1y/requests-2.2.1/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

Here is the dependency tree for EA:
elastalert==0.1.8
  - argparse [required: Any, installed: 1.1]
  - aws-requests-auth [required: Any, installed: 0.3.0]
    - requests [required: >=0.14.0, installed: 2.13.0]
  - blist [required: Any, installed: 1.3.6]
  - boto [required: Any, installed: 2.46.1]
  - botocore [required: Any, installed: 1.5.19]
    - docutils [required: >=0.10, installed: 0.13.1]
    - jmespath [required: <1.0.0,>=0.7.1, installed: 0.9.1]
    - python-dateutil [required: <3.0.0,>=2.1, installed: 2.2]
      - six [required: Any, installed: 1.9.0]
  - configparser [required: Any, installed: 3.5.0]
  - croniter [required: Any, installed: 0.3.15]
    - python-dateutil [required: Any, installed: 2.2]
      - six [required: Any, installed: 1.9.0]
  - elasticsearch [required: Any, installed: 5.2.0]
    - urllib3 [required: >=1.8,<2.0, installed: 1.20]
  - exotel [required: Any, installed: 0.1.1]
    - requests [required: ==2.2.1, installed: 2.13.0]
    - requests-oauthlib [required: ==0.5.0, installed: 0.5.0]
      - oauthlib [required: >=0.6.2, installed: 2.0.1]
      - requests [required: >=2.0.0, installed: 2.13.0]
  - jira [required: ==0.32, installed: 0.32]
    - requests [required: >=1.2.3, installed: 2.13.0]
    - requests-oauthlib [required: >=0.3.3, installed: 0.5.0]
      - oauthlib [required: >=0.6.2, installed: 2.0.1]
      - requests [required: >=2.0.0, installed: 2.13.0]
    - six [required: >=1.5.2, installed: 1.9.0]
    - tlslite [required: >=0.4.4, installed: 0.4.9]
  - jsonschema [required: Any, installed: 2.6.0]
    - functools32 [required: Any, installed: 3.2.3.post2]
  - mock [required: Any, installed: 2.0.0]
    - funcsigs [required: >=1, installed: 1.0.2]
    - pbr [required: >=0.11, installed: 2.0.0]
    - six [required: >=1.9, installed: 1.9.0]
  - PyStaticConfiguration [required: Any, installed: 0.10.3]
    - six [required: Any, installed: 1.9.0]
  - python-dateutil [required: Any, installed: 2.2]
    - six [required: Any, installed: 1.9.0]
  - pyyaml [required: Any, installed: 3.12]
  - simplejson [required: Any, installed: 3.10.0]
  - stomp.py [required: Any, installed: 4.1.17]
  - texttable [required: Any, installed: 0.8.7]
  - twilio [required: Any, installed: 5.7.0]
    - httplib2 [required: >=0.7, installed: 0.10.3]
    - pytz [required: Any, installed: 2012rc0]
    - six [required: Any, installed: 1.9.0]

As I understand, currently the requirement tree for elastalert==0.1.8 is:
elastalert==0.1.8 >>> exotel==0.1.1 >>> requests==2.2.1
requests==2.2.1 in its turn uses old version of urllib3, which uses PROTOCOL_SSLv3.
This protocol was disabled in new versions of Debian, so elastalert can't be installed properly in new versions of Debian.

Some system info:
Description:    Debian GNU/Linux 8.5 (jessie)
Release:        8.5

pip -V
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

pip show requests
Version: 2.13.0

pip show urllib3
Version: 1.20

Further investigation: http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

**Comment by andreyp1986** [comment]
Seems that the problem comes from exotel dependency.
I opened issue in the project: https://github.com/sarathsp06/exotel-py/issues

**Comment by sarathsp06** [comment]
@andreyp1986 project exotel upgraded to v0.1.3 with fix for this.Need to test on more machines

**Comment by andreyp1986** [comment]
@sarathsp06 Your fix works well and solves the issue. Thanks!
