### ISSUE TITLE
Elastalert doesn't send all her data

### ISSUE THREAD

**Issue by Alexwii** [Yelp/elastalert#948]
Hello everyone !

I have created some modules for Elastalert, and sometimes Elastalert will doesn't send correctly the table of data, and Python say to me KeyError: 'keyfind'.

I don't know why and sometimes it's works and sometimes it doesn't works. And I will know if i'm the only one have this bug or somebody already has had this bug ?

Thank you for your answer.

**Comment by Qmando** [comment]
"keyfind" doesn't appear in the code anywhere, so you probably have bugs in your own code. I can't help you unless you either post your code or maybe a traceback.

**Comment by Alexwii** [comment]
Of course, this is it:
```
# -*- coding: utf-8 -*-
import json

from elastalert.util import elastalert_logger
from elastalert.enhancements import BaseEnhancement
from elasticsearch import Elasticsearch
from datetime import datetime, timedelta, time

class VerifInterface(BaseEnhancement):
        def process(self, match):

                # On renseigne les informatons de connexion de la base de donnée Elasticsearch
                es = Elasticsearch([{'host': 'localhost', 'port': 9200}], timeout=120)

                # On va convertir l'heure python par défaut en Epoch Milis sinon Elasticsearch n'envoie pas les bonnes infos
                lte = datetime.now() # On donne la date d'aujourd'hui
                onehour = timedelta(hours=1) # on donne la valeur d'une heure à une variable
                gte = lte - onehour # on enlève une heure pour chercher dans l'intervalle

                mlte = int(lte.strftime("%s")) * 1000 # on converti en mili
                mgte = int(gte.strftime("%s")) * 1000

                # On renseigne le query
                interface = match['interface']
                source = match['source']

                # La query est différente selon la facility
                query = '{"query":{"bool":{"must":[{"match":{"interface":{"query":"%s","type":"phrase"}}},{"match":{"source":{"query":"%s","type":"phrase"}}},{"range":{"@timestamp":{"gte":"%s","lte":"%s","format":"epoch_millis"}}}],"must_not":[{"match":{"status":{"query":"down","type":"phrase"}}}]}}}'

                # On envoie une requête Elasticsearch qui va compter le nombre de requête
                es_count = es.count(index='logstash-*', body=query % (interface,source,str(mgte),str(mlte)))
                count = es_count['count']

                while count >= 10:
                        # On change les valeurs de -1h des variables de temps
                        lte = gte
                        gte = lte - onehour

                        # On convertie en mili
                        mlte = int(lte.strftime("%s")) * 1000
                        mgte = int(gte.strftime("%s")) * 1000

                        # On relance une recherche
                        es_count = es.count(index='logstash-*', body=query % (interface,source,str(mgte),str(mlte)))
                        count = es_count['count']

```

**Comment by Qmando** [comment]
Traceback?

**Comment by Alexwii** [comment]
```
ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elastalert-0.1.8-py2.6.egg/elastalert/elastalert.py", line 952, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
  File "/usr/lib/python2.6/site-packages/elastalert-0.1.8-py2.6.egg/elastalert/elastalert.py", line 1004, in send_alert
    enhancement.process(match)
  File "/usr/lib/python2.6/site-packages/elastalert-0.1.8-py2.6.egg/elastalert/elastalert_modules/verifinterface.py", line 24, in process
    interface = match['interface']
KeyError: 'interface'
```

Thank you so much for your help

**Comment by mza97** [comment]
```interface``` has to be a key in each of your event dict that match the pattern

**Comment by Alexwii** [comment]
Yes, the key is in all event matched by the query

**Comment by Qmando** [comment]
You should probably add 
```
- query:
     query_string:
       query: "_exists_: interface"
```
to make sure that you are getting documents with that field.

The contents of match will also vary depending on the rule type.

To avoid the keyerror, you could add
```
if 'interface' not in match:
    return
```
