### ISSUE TITLE
Load filters  from a Kibana 5 dashboard

### ISSUE THREAD

**Issue by locvx1234** [Yelp/elastalert#949]
I configure a rule  following: 

    filter:
      download_dashboard: "Beat dashboard"

to send dashboard in Kibana 5 to my mail box. But I received a error 

> WARNING:elasticsearch:GET http://192.168.169.223:9200/kibana-int/dashboard/_search?_source_include=dashboard [status:404 request:0.040s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/elastalert/elastalert/elastalert.py", line 1477, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/root/elastalert/elastalert/elastalert.py", line 1472, in main
    client = ElastAlerter(args)
  File "/root/elastalert/elastalert/elastalert.py", line 129, in __init__
    self.init_rule(rule)
  File "/root/elastalert/elastalert/elastalert.py", line 644, in init_rule
    raise EAException("Could not download filters from %s" % (new_rule['filter']['download_dashboard']))
elastalert.util.EAException: Could not download filters from Beat dashboard

Please help me solve this problem. Thanks.

**Comment by kureus** [comment]
The section of the docs that references this config suggests that this feature is just for kibana 3 dashboards?

http://elastalert.readthedocs.io/en/latest/recipes/writing_filters.html#loading-filters-directly-from-kibana-3

You could submit a pull request if you need to get it working for v5.
