### ISSUE TITLE
Compound aggregation keys cause an error

### ISSUE THREAD

**Issue by Qmando** [Yelp/elastalert#954]
```
Traceback (most recent call last):
 File "/opt/elastalert_test/virtualenv_run/bin/elastalert-test-rule", line 11, in <module>
   load_entry_point('elastalert==0.1.8', 'console_scripts', 'elastalert-test-rule')()
 File "/opt/elastalert_test/virtualenv_run/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/test_rule.py", line 333, in main
   test_instance.run_rule_test()
 File "/opt/elastalert_test/virtualenv_run/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/test_rule.py", line 328, in run_rule_test
   self.run_elastalert(rule_yaml, conf, args)
 File "/opt/elastalert_test/virtualenv_run/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/test_rule.py", line 247, in run_elastalert
   client.run_rule(rule, endtime, starttime)
 File "/opt/elastalert_test/virtualenv_run/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 618, in run_rule
   self.add_aggregated_alert(match, rule)
 File "/opt/elastalert_test/virtualenv_run/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 1219, in add_aggregated_alert
   aggregation_key_value = self.get_aggregation_key_value(rule, match)
 File "/opt/elastalert_test/virtualenv_run/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 515, in get_aggregation_key_value
   return self.get_named_key_value(rule, match, 'aggregation_key')
 File "/opt/elastalert_test/virtualenv_run/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 521, in get_named_key_value
   key_value = lookup_es_key(match, rule[key_name])
 File "/opt/elastalert_test/virtualenv_run/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/util.py", line 101, in lookup_es_key
   value_dict, value_key = _find_es_dict_by_key(lookup_dict, term)
 File "/opt/elastalert_test/virtualenv_run/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/util.py", line 46, in _find_es_dict_by_key
   if term in lookup_dict:
TypeError: unhashable type: 'list'
```

**Comment by Qmando** [comment]
Fixed by https://github.com/Yelp/elastalert/commit/41cb84ee0790fce6e7bc6d17c41d85c8e519e610
