### ISSUE TITLE
metric_aggregation error

### ISSUE THREAD

**Issue by bsteph** [Yelp/elastalert#961]
I'm trying out the new metric_aggregation feature. I'm receiving the error below:
ERROR:root:Uncaught exception running rule Apache_Thread: ElastAlerter instance has no attribute 'rule'
^C[zsssc5z@lsdnecsseot bin]$ vi ~/elastalert_rules/apachethreads.yaml 
[zsssc5z@lsdnecsseot bin]$ ./elastalert
ERROR:root:Traceback (most recent call last):
  File "/home/zsssc5z/.local/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 904, in run_all_rules
    num_matches = self.run_rule(rule, endtime, self.starttime)
  File "/home/zsssc5z/.local/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 669, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/home/zsssc5z/.local/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 476, in run_query
    data = self.get_hits_aggregation(rule, start, end, index, rule.get('query_key', None))
  File "/home/zsssc5z/.local/lib/python2.7/site-packages/elastalert-0.1.8-py2.7.egg/elastalert/elastalert.py", line 411, in get_hits_aggregation
    query = self.get_aggregation_query(base_query, rule, query_key, term_size, self.rule['timestamp_field'])
AttributeError: ElastAlerter instance has no attribute 'rule'

My rule is:
name: Apache_Thread
type: metric_aggregation

es_host: localhost
es_port: 9200

index: logstash-%Y.%m.%d
use_strftime_index: true

buffer_time:
  hours: 1

metric_agg_key: apache_threads
metric_agg_type: avg
#query_key: _source
doc_type: newssi_monitoring
bucket_interval:
  minutes: 5
  
sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true

min_threshold: 1
max_threshold: 5

#filter:
#- term:
#    metricset.name: cpu

# (Required)
# The alert is use when a match is found
alert:
- "debug"

Any ideas?

**Comment by Qmando** [comment]
This was fixed earlier today. https://github.com/Yelp/elastalert/commit/bf631b80a3e4db3414cacec5c1823f4a8abf4be5
Please pull master and try again.
