### ISSUE TITLE
Flatline receives hits but no matches

### ISSUE THREAD

**Issue by JC1738** [Yelp/elastalert#972]
```
# (Required)
# Type of alert.
# the flatline rule type alerts when num_events events occur with timeframe time
type: flatline

# (Required)
# Index to search, wildcard supported
index: logstash-*

# (Required, flatline specific)
# Alert when this many documents matching the query occur within a timeframe
threshold: 2000

# (Required, flatline specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  minutes: 2

use_count_query: true
doc_type: XXXX
```

When running get the following output:

```
11:24 PDT to 2017-03-29 11:29 PDT: 1465 query hits, 0 matches, 0 alerts sent
```

Would have expected 1 match (and 1 alert) since 2000 < 1465, not sure what else doing wrong.

Thanks

**Comment by Qmando** [comment]
One slight oddity is that with ``use_count_query`` (or ``use_terms_query``) is that it takes at least two queries to generate an alert. If you wait a minute, it will send an alert.

The reasoning is because of how the rule type get's data from elastalert. Those 1465 events are reported as having occurred at a single point in time and therefore don't cover the 2 minute timeframe.

This is something I should fix.

**Comment by JC1738** [comment]
Yes @Qmando, I saw that from other peoples comments.  I do wait, the rules are running every 5 minutes.  The second run still doesn't appear to alert.

```
2017-03-29 11:41:18,957 DEBG 'elastalert' stderr output:
INFO:elastalert:Ran XXXXX from 2017-03-29 11:36 PDT to 2017-03-29 11:41 PDT: 1631 query hits, 0 matches, 0 alerts sent

2017-03-29 11:41:18,957 DEBG 'elastalert' stderr output:
INFO:elastalert:Sleeping for 299.576026 seconds
```

Then it wakes up and this gets printed

```
2017-03-29 11:46:19,302 DEBG 'elastalert' stderr output:
INFO:elastalert:Ran XXXXX from 2017-03-29 11:41 PDT to 2017-03-29 11:46 PDT: 1516 query hits, 0 matches, 0 alerts sent
```

So it ran twice, both under 2000 without any matches/alerts.

Thanks

**Comment by JC1738** [comment]
I do notice this error message between execution runs when it wakes up, which might be related?

```
ERROR:root:Error finding recent pending alerts: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on') {'filter': {'range': {'alert_time': {'to': '2017-03-29T18:46:18.598757Z', 'from': '2017-03-27T18:46:18.598701Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 1214, in find_recent_pending_alerts
    size=1000)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 569, in search
    doc_type, '_search'), params=params, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 89, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 122, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'search_phase_execution_exception', u'No mapping found for [alert_time] in order to sort on')
```

**Comment by Qmando** [comment]
I guess you have encountered a bug. When using ``use_count_query`` and a ``timeframe`` that is less than ``run_every``, it won't send an alert.

You can work around this by either setting ``run_every`` to 1 minute, or setting ``timeframe`` to greater than 5 minutes (and change threshold accordingly), or by removing ``use_count_query``.

**Comment by Qmando** [comment]
For the search_phase_execution_exception, you need to run ``elastalert-create-index``. It will keep spitting out errors like that, but the basic functionality will still work.

**Comment by JC1738** [comment]
@Qmando Ok, tried making the timeframe 6 minutes, kept run_every at 5 minutes.

First execution run:
```
2017-03-29 12:54:19,078 DEBG 'elastalert' stderr output:
INFO:elastalert:Queried rule XXXXX from 2017-03-29 12:49 PDT to 2017-03-29 12:54 PDT: 1340 hits

2017-03-29 12:54:19,089 DEBG 'elastalert' stderr output:
INFO:elastalert:Ran XXXXX from 2017-03-29 12:49 PDT to 2017-03-29 12:54 PDT: 1340 query hits, 0 matches, 0 alerts sent
```
Second Run

```
2017-03-29 12:59:19,270 DEBG 'elastalert' stderr output:
INFO:elastalert:Queried rule XXXXX from 2017-03-29 12:54 PDT to 2017-03-29 12:59 PDT: 1294 hits

2017-03-29 12:59:19,355 DEBG 'elastalert' stderr output:
INFO:elastalert:Queried rule XXXXX from 2017-03-29 12:59 PDT to 2017-03-29 12:59 PDT: 0 hits

2017-03-29 12:59:19,368 DEBG 'elastalert' stderr output:
INFO:elastalert:Ran XXXXX from 2017-03-29 12:54 PDT to 2017-03-29 12:59 PDT: 1294 query hits, 0 matches, 0 alerts sent

INFO:elastalert:Sleeping for 299.385528 seconds
```

It's weird that the second run had a second entry for hits that has 0 right after a count of 1294, but still doesn't work.  Any other ideas?

Thanks,

**Comment by Qmando** [comment]
Did you increase the threshold as well? Because now the 6 minute timeframe will include 1340+1294 events.

You can also remove ``use_count_query`` or change ``run_every`` to a lower value like 1 minute.

**Comment by JC1738** [comment]
Yes, I had up'd the threshold.  It still doesn't match.  I also tried without use_count_query, it behaves some, no match/alert.  The reason I don't run_every quicker, don't want to tax our ES.   Any other ideas?

**Comment by Qmando** [comment]
I'm not quite sure what is going on at this point. I haven't experience issues with flatline like this before. If it's possible, I can give you some print statements to throw in to try and get some further information.

```
--- a/elastalert/ruletypes.py
+++ b/elastalert/ruletypes.py
@@ -190,6 +190,7 @@ class FrequencyRule(RuleType):

         event = ({self.ts_field: ts}, count)
         self.occurrences.setdefault('all', EventWindow(self.rules['timeframe'], getTimestamp=self.get_ts)).append(event)
+        print "Eventwindow:", self.occurences['all'].data
         self.check_for_match('all')

     def add_terms_data(self, terms):
@@ -480,10 +481,12 @@ class FlatlineRule(FrequencyRule):

         # Don't check for matches until timeframe has elapsed
         if most_recent_ts - self.first_event[key] < self.rules['timeframe']:
+            print "Exiting check because", most_recent_ts, self.first_event[key], self.rules['timeframe']
             return

         # Match if, after removing old events, we hit num_events
         count = self.occurrences[key].count()
+        print "Current count", count
         if count < self.rules['threshold']:
             # Do a deep-copy, otherwise we lose the datetime type in the timestamp field of the last event
             event = copy.deepcopy(self.occurrences[key].data[-1][0])
```

For this, you would need to continue using use_count_query.
To find the proper file, you can run ``python -c 'import elastalert.ruletypes;print elastalert.ruletypes.__file__'``

**Comment by JC1738** [comment]
Thanks, I let it run longer and I got it to actually fire.  So not sure why it didn't right away, but I think it's working, might be something to look at closer when having runevery longer then timeframe.  Especially with the count_query option.

**Comment by Qmando** [comment]
Phew! Good to hear.

There definitely is a bug, but it's only in that one specific scenario. I'll try to fix it but it's not top priority.
