### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'access_key' and Starting new HTTP connection (1): 169.254.169.254

### ISSUE THREAD

**Issue by ardentisys-rajshekhar** [Yelp/elastalert#989]
I have setup elastalert on my VMs. today's setup is asking for access_key

```
ubuntu@elast-alert:~/elastalert$ sudo elastalert-create-index 
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 9, in <module>
    load_entry_point('elastalert==0.1.8', 'console_scripts', 'elastalert-create-index')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/create_index.py", line 83, in main
    profile_name=args.profile)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/auth.py", line 24, in __call__
    aws_access_key=credentials.access_key,
AttributeError: 'NoneType' object has no attribute 'access_key'
```
the same installation was working on yesterday's VM. Also facing following issue.. this one is trying to connect to predefined ip address 169.254.169.254 even after specifying the elasticsearch's server's ip address.  The API is accessible from this machine when checked for network issue..

```
ubuntu@elast-alert:~/elastalert$ elastalert-test-rule example_rules/example_single_metric_agg.yaml 
Successfully loaded Metricbeat CPU Spike Rule

INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 9, in <module>
    load_entry_point('elastalert==0.1.8', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/test_rule.py", line 333, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/test_rule.py", line 320, in run_rule_test
    hits = self.test_file(copy.deepcopy(rule_yaml), args)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/test_rule.py", line 54, in test_file
    es_client = elasticsearch_client(conf)
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/util.py", line 282, in elasticsearch_client
    profile_name=es_conn_conf['profile'])
  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.8-py2.7.egg/elastalert/auth.py", line 24, in __call__
    aws_access_key=credentials.access_key,
AttributeError: 'NoneType' object has no attribute 'access_key
```

**Comment by micahhausler** [comment]
@ardentisys-rajshekhar are you using a username/password authenticat or AWS elasticsearch?

**Comment by micahhausler** [comment]
@theneb you're right. I'll make a patch for that.
