### ISSUE TITLE
Error when running elastalert -h

### ISSUE THREAD

**Issue by ZillaG** [Yelp/elastalert#994]
I installed the latest elastalert on a CentOS 7.2 box with Python 2.7 using "pip install elastalert" method. "which elastalert" shows /bin/elastalert, but when I run "elastalert -h" I get the following stack trace.

$ elastalert -h
```
Traceback (most recent call last):
  File "/bin/elastalert", line 11, in <module>
    load_entry_point('elastalert==0.1.8', 'console_scripts', 'elastalert')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 20, in <module>
    from alerts import DebugAlerter
  File "/usr/lib/python2.7/site-packages/elastalert/alerts.py", line 26, in <module>
    from twilio import TwilioRestException
ImportError: cannot import name TwilioRestException

```
Any clues? Thanks!

**Comment by Qmando** [comment]
pip install twilio==5.6.0

**Comment by ZillaG** [comment]
Thanks!
